### ISSUE TITLE
Change first heading in tutorial section

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1009]
Each tutorial header starts with: _Tutorial: ###_ (example below)
As I am already in the tutorial section this may not be necessary and we can display only the title of the tutorial itself. 

![grafik](https://user-images.githubusercontent.com/36844029/176148651-d56eb7d0-abac-4968-baa1-91922d85834c.png)

**Comment by han-f** [comment]
and some of the tutorials have permalinks (like the one above) and some do not. Should we harmonise this? Is it only the jupyter notebook tutorials that have this permalink?

cc @jh-RLI

**Comment by jh-RLI** [comment]
Yes, we should harmonize this. Also, your guess is correct, this was implemented only for the Jupyter-based tutorials.

**Comment by wingechr** [comment]
fixed on most of the jupyter tutorials
