### ISSUE TITLE
Add "capacity building module" to drop-down menu in tutorials

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1010]
We want to add this specific category to the drop-down menu in the tutorial editor, so all capacity building modules can be displayed on a separate section on the tutorial page (#826). 

cc @jh-RLI

**Comment by wingechr** [comment]
@han-f Maybe we should not call them "capacity building" on the OPE, but instead maybe "Introduction" or "Overview"?
Seems like the term "capacity building" might need more explanation or could be confusing on it's own.

**Comment by han-f** [comment]
@wingechr  - I am also fine with another term. I think this drop-down would only be visible in the tutorial editor, to guide the choice and be indicator that tutorials with this category will be shown on top of the page.
How about "Training Course"? If we do not want to use the term "capacity building", we would also need to consider a new header title for that separate section, as the use of the term is currently envisaged: #826
