### ISSUE TITLE
Update to bootstrap 5 

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1027]
It would be nice to update from bootstrap 4 to 5. 

We would have to upgrade the PyPi package `django-bootstrap4` to https://pypi.org/project/django-bootstrap5/
and also review all bootstrap related code and files: https://github.com/OpenEnergyPlatform/oeplatform/search?q=bootstrap

**Comment by wingechr** [comment]
I would be careful with that. there is a lot of breaking changes between 4 and 5, so that would mean a lot of changes in the templates

**Comment by jh-RLI** [comment]
Okay good to know. @bmlancien asked if this would be possible.

**Comment by bmlancien** [comment]
If it is too difficult to update to the new version, we can also leave it that way, no problem. I will work with that version.

**Comment by wingechr** [comment]
I mean I am not against it (and having the latest version is a good idea).
If we check with https://getbootstrap.com/docs/5.0/migration/ and go through all the items marked *breaking* and then look for all occurrances in the templates, do you guys think it's worth it?

**Comment by bmlancien** [comment]
I think it is always worth migrating to the newest version because that helps keeping it up-to-date with the current state of Bootstrap. It will be some work to do but also I don't think it's something impossible. I can open a new branch and start working on that. Obviously, something important would be to check and test everything at the end of the migration.

**Comment by wingechr** [comment]
ok, then let's do it.

**Comment by jh-RLI** [comment]
@bmlancien have you started working on this yet? I think I saw some commits, could you create a PR and put it as a draft? It's better to make the work visible for everyone :)

**Comment by bmlancien** [comment]
Alright, I'll put it as a PR draft.

And I will try to add the issue number to the commits! :)
