### ISSUE TITLE
test permission setting

### ISSUE THREAD

**Issue by wingechr** [OpenEnergyPlatform/oeplatform#1051]

**Comment by jh-RLI** [comment]
@wingechr is this about testing permissions in general? I just noticed that granting admin permissions to a user actually (sometimes/always ??) does not grant permissions. I have been granted permissions to a table and tried to enter a new record into the table, but I get a 403 back. Also the response.text tells me that I do not have permission to perform this action. Did you also noticed something similar?

**Comment by wingechr** [comment]
no,this was about the permissions page for the tables.

* i need to add checks if this is actually doing what it claims
* currently, you can accidentally remove yourself from the permissions, and then no one can edit them
