### ISSUE TITLE
Migration of existing metadata after new metadata storage (JSONB column) has been implemented and oemetadata is stable.

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1066]
After the implementation of the metadata jsonb field and once the metadata standard is stable, we should do a review of all the existing metadata and update them all as best as possible to the latest standard.

By re-writing all the metadata, all the search fields and tags would be automatically updated as well

**Comment by Ludee** [comment]
I just found that the search bar is not finding tables in _model_draft_ with no metadata:
see https://openenergy-platform.org/dataedit/view/model_draft?query=TYNDP
and https://openenergy-platform.org/dataedit/view/model_draft CTRL+F TYNDP

Please add the list of existing table names to the search function!

**Comment by jh-RLI** [comment]
Moved the off topic comments to new issue. This issue is solved with https://github.com/OpenEnergyPlatform/oeplatform/pull/1183
