### ISSUE TITLE
adding tags to tables (which are not in model_draft) triggers http 403 forbidden

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1069]
When adding a tag (via the sidebar menu) to a table, e.g. [this one](https://openenergy-platform.org/dataedit/view/boundaries/bkg_gn250_b), an htttp 403 error is thrown. This was only reproducible for tables that are not in model_draft schema/topic. It seems that the permission check is too strict. We don't want to allow the user to upload data to a table in a specific schema (that is not model_draft), but we do want them to be able to edit the metadata and tags. 

Edit: Adding tags via the metaEdit (keywords) will also update the table tags.

@Ludee, do you agree? or do we need to check that we are all on the same page about where what permission should apply?

**Comment by Ludee** [comment]
We do not have a proper definition of all permissions and rules yet. This is always done case-by-case until now. This must be discussed in a larger group. Let's try to find a good place to document this and start with the current rules as a base for discussion and implementation.
I use the workaround to add the tags using the keys of the metadata for now.

**Comment by jh-RLI** [comment]
I will provide a list with the current permissions.
