### ISSUE TITLE
Bugs when editing metadata of existing table using MetaBuilder

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/oeplatform#1087]
I'm unsure whether this are known issues or if they have been already addressed. 

1. When updating the metadata of existing tables (by pressing edit) the information from the `isAbout` and `valueReference` key get lost - potentially more keys.

Example table with  `isAbout` and `valueReference` annotations: https://openenergy-platform.org/dataedit/view/model_draft/wind_turbine_domestic_lod_geoss_tp_oeo 
(EDIT: this now shows the already broken status; see [here ](https://openenergy-platform.org/dataedit/view/model_draft/wind_turbine_nearshore_lod_geoss_tp_oeo)for a so far untouched and still annotated metadata string)

Original metadata json which I had luckily saved locally. [ORIGINAL_wind_turbine_domestic_LOD_GEOSS_tp_OEO.txt](https://github.com/OpenEnergyPlatform/oeplatform/files/9862759/ORIGINAL_wind_turbine_domestic_LOD_GEOSS_tp_OEO.txt)
Metadata shown in MetaBuilder. [SHOWN_in_medabuilder.txt](https://github.com/OpenEnergyPlatform/oeplatform/files/9862752/SHOWN_in_medabuilder.txt)

- [x] bug fixed

2. After inserting the correct and updated metadata and when submitting I get an error message `Bad request` and can't update the metadata.

- [x] bug fixed

**Comment by jh-RLI** [comment]
Yes sorry for this! - the data isn't actually lost, but the key name got renamed by a bug in omi. I already fixed this and I am aware that this will cause some harm - hope not to much. Definitely try to back up metadata for some of your uploads you already did. With the newest version of omi installed on the oep production, this is fixed.

**Comment by jh-RLI** [comment]
I will do some more tests locally to reproduce the second bug.

**Comment by jh-RLI** [comment]
is fully fixed with omi v0.0.8 - locally confirmed with latest dev
