### ISSUE TITLE
Study factsheet page broken

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1093]
This page is broken: https://openenergy-platform.org/factsheets/rdf/study/  
and we link to it via the text on this page: https://openenergy-platform.org/factsheets/overview/

So we either need to fix the first page to show the (currently not working) study factsheets alpha, or remove the link from the second page.

**Comment by jh-RLI** [comment]
This is actually expected - we removed the link to the studie factseht (aplha) with version 0.10.1 - I think @adelmemariani got more info on why we removed it. 

->see changelogs [0_10_1.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/master/versions/changelogs/0_10_1.md)
Remove link to Study Factsheets (alpha) in navigation bar (PR #987)

**Comment by jh-RLI** [comment]
Also the links in the overview page are "hardcoded" this should also be fixed while removing the studie factsheet link.

**Comment by jh-RLI** [comment]
@han-f do you agree that we can close this issue? I will correct the technical comment I made.
