### ISSUE TITLE
Multiple definitions of primary key error when defining PK on table column

### ISSUE THREAD

**Issue by henhuy** [OpenEnergyPlatform/oeplatform#1110]
See https://github.com/OpenEnergyPlatform/oedialect/issues/43 for reference

I will add a small PR to address this.

**Comment by wingechr** [comment]
hi @henhuy. sorry to be late to the party. 

Unfortunately, the fix does not quite work. `if ccolumns in primary_key_col_names` is not ok, because both of the vars are lists.

I will create a new fix including a unittest

**Comment by henhuy** [comment]
Ah you are right! Thanks for finding and fixing!
