### ISSUE TITLE
OEP Page Content - Startpage (Index) needs update

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#1126]
Link: https://openenergy-platform.org/
Code: https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/base/templates/base/index.html

---

**Open Energy Platform**
Make your energy system modelling process transparent!

**Database** 

`original`
Are you interested in data? Visualize the database to explore it. All contributors publish datasets under an open license, so you can securely download and work with it. Are you interested in sharing your own data? This is the place to upload it.
`edited`
Are you looking for data? Then, here you can explore what's on the platform. All contributors publish datasets under open licenses, so you can securely download and work with it. Do you want to share your own data? This is the place to upload it.

**Factsheets** `edited`
Do you want to learn more about scenarios and models related to the data? Then, this is the right place to look. Also if you contributed data and want to provide more context, ~Create~ _create_ [2] your own factsheet here.

**Ontology** `edited`
Ontology ~referes~ _refers_ [1] to a collection of domain specific terminology and their relationships. Come here to learn more about the Open Energy Ontology (OEO), which helps with data annotation and management.

**Tutorials**
There is something you'd like to do on the platform, but you don't know how? Check out the tutorials! They are available for all levels, and in the form of texts, videos and markdowns.

**Comment by u-mueller** [comment]
Thanks for the template! If you have more than a few corrections, this is a not too comfortable way.

1) Would it make sense to create a PR as I did (inadvertently) here: https://github.com/OpenEnergyPlatform/oeplatform/compare/develop...u-mueller-patch-1?quick_pull=1

2) What should we deal with larger tasks as for example structural issues, names/appearence/placement of buttons and other elements, text, that's missing right away, etc.?

**Comment by u-mueller** [comment]
But I should say that for smaller issues, your suggestion seems to work for me (see my above changes). Who is implementing the changes then?

**Comment by Ludee** [comment]
Looking at your changes I realised that it makes no sense to keep the changelog in the text. This makes it harder to included the changes efficiently in the end.
Having `original` and `edited` section is more efficient and increases readability.

Let's not use PR for this. This will be used for implementation when all text updates are done.

If you need to show something. Use a screenshot and some paint like this:
![grafik](https://user-images.githubusercontent.com/14353512/206483335-017ee776-c2f9-44a4-bbee-6bdfeec33fb3.png)

**Comment by han-f** [comment]
I have to admit that here I feel rather old school. I think it is easier to edit a text collaboratively in Word as this provides the possibility to track changes and adding comments that can be discussed together with a quick turnaround. I wonder whether we could combine both: We post the original text here, the editing team then takes it into  word and once the editing team thinks the text is in a new version we post it here again. Like this it follows the suggested approach above, but allows for intermediate steps that may be complicated to do here, as it may involve a flurry of comments and be complicated to visually follow compared to track changes. 

For the structural issues I think working with screenshots is ok, but may need some spoken feedback loop to make sure suggestions are understood as meant by the initiator.

**Comment by u-mueller** [comment]
Thanks Hannah, I would feel better with your solution. It would be good, if we had the possibility to edit texts seperately.

**Comment by u-mueller** [comment]
@Ludee, @han-f, maybe we can define the process as follows:    

1. seperate project on Github --> @Ludee, still to be created?
2. issue for every subpage
3. extended workflow: 
- each subpage with text
- one of editing team copies text to word-dokument (named after issue name) on SIROP Teams: [[WP5 > Textedits_OEP_main_pages]]((https://fraunhofer.sharepoint.com/:f:/r/sites/SIROP/Freigegebene%20Dokumente/General/WP5%20OE%20Platform/Textedits_OEP_main_pages?csf=1&web=1&e=EupdHb)https://fraunhofer.sharepoint.com/:f:/r/sites/SIROP/Freigegebene%20Dokumente/General/WP5%20OE%20Platform/[Textedits_OEP_main_pages](https://fraunhofer.sharepoint.com/:f:/r/sites/SIROP/Freigegebene%20Dokumente/General/WP5%20OE%20Platform/Textedits_OEP_main_pages?csf=1&web=1&e=EupdHb)?csf=1&web=1&e=EupdHb)
- start editing process in modus "Änderungen nachverfolgen"
- after editing or reading (that is, even without changes), everyone adds his/her initials to document name (Startpage_Index_UM.docx etc.) 
- when complete, last one editing uploads revised text to original github issue
- for structural issues add screenshots to issue
- in case of unsolved questions concerning e.g. OEO, OEKG etc. request review by expert 
- implement

**Comment by jh-RLI** [comment]
We updated the text suggested in this issue some time ago and added the scenario bundles. We should continue to expand the homepage and also give the user an understanding of our services, such as what they can expect from the oep - data transfer, ..... possibly also references to our service chains that ‘form’ the product we want to offer. At the moment we only show each part individually. There are other topics and it would be desirable to address this issue in the future. I will close this one.
