### ISSUE TITLE
OEP Page Content - About Overview needs update

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#1143]
As suggested in #1126 this is a single issue for updating the content of the About Overview Page. The current content reads as follows:

General Introduction

The Open Energy Family aims to ensure quality, transparency and reproducibility in energy system research. It is a collection of [various tools and information](https://github.com/OpenEnergyPlatform/organisation) and that help working with energy related data. It is a collaborative community effort, everything is openly developed and therefore constantly evolving.

The main module is the Open Energy Platform (OEP), a web interface to access most of the modules, especially the community database. It provides a way to publish data with proper documentation (metadata), and link it to source code and underlying assumptions.

The address the problem of different name and data(base) formats, the [Open Energy Ontology (OEO)](https://openenergy-platform.org/ontology) was developed. The ontology provides a controlled vocabulary with clear definitions of terms and relationships between those terms. Data annotation adds the possibility of enhanced searching functions and logical querying across data sets.
What? Energy System Modelling and Data

Openly licensed data relevant in the field of climate and energy research can be published and accessed here. Especially energy system modelling data and scenarios can be found, along with further information on the underlying models, frameworks and studies.

Energy system models are used to explore the current and future energy systems and are often applied to questions involving the expansion of renewables and energy storages as well as energy and climate policy. The models themselves vary widely in terms of their type, design, programming, application, scope, level of detail, sophistication, and shortcomings.

The OEP considers the entire modelling process from the preprocessing of the raw data, the simulations, the postprocessing of the result data. The heart of the OEP is the underlying [Open Energy Database (OEDB)](https://openenergy-platform.org/dataedit/schemas), which can be used by everyone and is maintained by a team of developers from different institutes.
OEP circle simple
How? Open Science

We follow and promote the principles of [Open Science](https://en.wikipedia.org/wiki/Open_science) and offer an open infrastructure for energy system research. The focus is on Open Data and the provision of modelling results under open licenses. The OEP uses an extensive metadata set, the [OEMetadata](https://github.com/OpenEnergyPlatform/oemetadata). It is based on the [Tabular Data Package](https://frictionlessdata.io/specs/tabular-data-package/) specifications and the [FAIR principles](https://www.go-fair.org/fair-principles/) to improve the Findability, Accessibility, Interoperability, and Reuse of digital assets.
OEP circle simple
Who? OEP-Community

The Open Energy Family is a cross-project research project that is continuously being developed by various universities and institutes. The source code of all members of the family is open source and accessible on [GitHub](https://github.com/OpenEnergyPlatform/). Get involved and contribute!
Research Projects ...

![Screenshot_About](https://user-images.githubusercontent.com/42000429/211028385-0573463b-bcfb-4a11-afdf-fe127fabb10e.png)

**Comment by jh-RLI** [comment]
The associated PR is already merged ... I'm closing it now, please open it again if necessary.
