### ISSUE TITLE
New Student Task: Setup OEP

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#1160]
Setup the OEP. Follow the instructions on the project's [GitHub page](https://github.com/OpenEnergyPlatform/oeplatform). You can skip the database setup and run it with a docker, as explained on the [developers page](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/docker/USAGE.md). Once you can run the OEP locally, using git, checkout to a new branch 'feature/student_button'. Insert a button on the OEP frontpage that just alerts "i clicked this button". Create a Screenshot of this and leave it in the issue. Commit your changes to the new branch. Write a commit message that reads "Added a button" and references this issue. Push your new branch to the repository. Thank you.

**Comment by mdvcode** [comment]
Okey, I will make it today🚀

Ср, 8 февр. 2023 г. в 11:46, christian-rli ***@***.***>:

**Comment by mdvcode** [comment]
<img width="1341" alt="Screenshot 2023-02-08 at 13 25 29" src="https://user-images.githubusercontent.com/94698585/217530998-2ffdd8e7-0484-4815-9d3e-3d368604de4c.png">

i made it

**Comment by mdvcode** [comment]
i already made it

ср, 8 лют. 2023 р. о 11:48 Daryna Martymianova ***@***.***> пише:
