### ISSUE TITLE
search function for power plants does not work

### ISSUE THREAD

**Issue by tillmo** [OpenEnergyPlatform/oeplatform#117]
In the power plant list, if I enter e.g. "Magdeburg" in the search field and press "Go", nothing happens.

**Comment by christian-rli** [comment]
Similarly when you attempt to use the filter function nothing happens. When trying to update a created filter an error message appears ("Request failed: error") and a loading animation spins endlessly.

**Comment by christian-rli** [comment]
I just tested this and the filter function works now. The column for the search has to be selected and since it's a very large data set the query takes a little while to process.
