### ISSUE TITLE
Rework OEP Profile page

### ISSUE THREAD

**Issue by Darynarli** [OpenEnergyPlatform/oeplatform#1170]
**Question:**

1. What kind of Mockups do you need?
2. What is the size limit for a profile photo?
3. Who does the front development (design)?
4. What is the logic of getting stars? Is there a logic already or can I offer ideas?
5. There are restrictions on how often you can change your name/email/password
6. Is the function to delete a profile available or just log out of a profile?
7. What do you want it to be in settings?
8. What is a pending review?
9. Is it possible for other users to be able to view someone's profile (if, for example, they saw the author of an article or table, will the author be visible there?)

**What I want to do:**
_Profile description_

1. profile photo can be added
2. account lifetime
3. mail
4. Social media links (optional)
5. achievement stars

_Actions:_

1. table button: when the button is pressed, all tables created by the user, which are links to the table itself, are displayed; what is the topic of the table; when it was uploaded, filtered by date in descending order ; who has been reviewed
2. reviews button: when you click on the button, all reviews created by the user are displayed, which are a link to the review itself; review creation date, filtered by date in descending order
3. settings: when the button is pressed, a link to the token is displayed; Name; email; affiliation; description; the edit button, by clicking on which you can change the name/email/affiliation/description; change password button, by clicking on which you can change the password
4. for those who come to see someone else's profile, there will be all functions except settings

**Comment by jh-RLI** [comment]
Hey, looks great so far @Darynarli 👍 
The final version will come from the result of your work and you are good to go (it is on the to-do list). You create the concept for the functionalities and create the basic concept of the page. You can also create a basic layout, but that already exists in this case. As @bmlancien said he will support you and do the design part and implement it later and you will implement the Backend (django stuff). 
As a result we will work out the final solution together but you are the main developer for this feature :) . 

PS: I will create a GitHubb-Project and add this Issue. You can create more issues and add them to the Project. There is a Kanban-Board that you can use. You can move the issues you are currently working on to the in-progress column:
https://github.com/OpenEnergyPlatform/oeplatform/projects/25

**Comment by jh-RLI** [comment]
> 2. When will the gamification feature be decided?
It would be good if you could start working this out. You can start with a very basic idea that is easy to implement. We want to incentivize users, so we want to have features like this. Once you have something we can dicuss it and improve it together.

**Comment by jh-RLI** [comment]
> 5. There are restrictions on how often you can change your name/email/password

I think there are no restictions so far and i think we can keep it this way if there are no reasons against it :) 

> 6. Is the function to delete a profile available or just log out of a profile?

I think we miss such a functionality, users will have to write a e-mail and ask us to delete at the moment.

> 7. What do you want it to be in settings?

Thats something we should discuss together with @christian-rli @Ludee and others maybe in the developer meeting

> 8. What is a pending review?

As far as i remember this means the table is uploaded but was not reviewed so far. A reviewer can pick up this table and review it.

> 9. Is it possible for other users to be able to view someone's profile (if, for example, they saw the author of an article or table, will the author be visible there?)

I like the idea but thas also something we should discuss with the others :)

**Comment by Darynarli** [comment]
I took a profile photo now. Do I need to commit and pull every step or every part of profile page, what I make?

**Comment by jh-RLI** [comment]
You mean you have started the development? Or did you actually take a picture? Regarding the commit, you should aim for atomic commits (my interpretation is that you want to make small commits without hurting yourself - my practical approach is to never commit a whole file, but commit small parts of the code no bigger than a single function (a function should not be that big)

**Comment by jh-RLI** [comment]
And use the issue ID #1170 at the end of your commit message, this will show the commit here.

**Comment by Darynarli** [comment]
And what branch?

**Comment by jh-RLI** [comment]
@Darynarli Please also implement tests if needed. Currently, there should be at least tests for your python code.

- https://docs.djangoproject.com/en/4.1/topics/testing/overview/
 
Here is a complex example of some tests related to "create table" RESTapi functionality:
setup test classes
- https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/api/tests/__init__.py
test
- https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/api/tests/test_table.py
(sorry, i will provide some simpler example soon)

(Just for your information)
We do not have a JavaScript test system setup yet, if you want you can also look into this and try to run tests for possible java script code, that you might not even need for your proposed functionality:
- https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/javascript/#javascript-tests

**Comment by Darynarli** [comment]
Hi. I have a question about reviews. Where can I found all the reviews? I can't quite figure out what is it?

**Comment by jh-RLI** [comment]
This is something that is still in developement https://github.com/OpenEnergyPlatform/oeplatform/pull/1033 
You can check out the mockups in Figma to get a better idea.
@christian-rli is working on them, but it is currently postponed due to too many other tasks.

**Comment by Darynarli** [comment]
Then wait for it to be implemented and then implement it in the profile page, do I understand correctly?

**Comment by jh-RLI** [comment]
Yes you can add the page but keep it empty or hide it for now :)

**Comment by Darynarli** [comment]
okey)

**Comment by Darynarli** [comment]
I made all Profile  page except review

**Comment by jh-RLI** [comment]
The backend functionality is okay now. Frontend will be added soon.

**Comment by jh-RLI** [comment]
The UI will be implemented by #1218
