### ISSUE TITLE
Profilepage settings options

### ISSUE THREAD

**Issue by bmlancien** [OpenEnergyPlatform/oeplatform#1175]
Hi @Darynarli, could you help us by making a list of the things we could have under "Settings" in the profile page? Things like a "Delete account" button, personal data, privacy, notifications, etc. We won't be able to implement all of it, at least not at first, but it could be good to have an idea of the options we want to give to the users. To help you, you could have a look at your settings section on Github to see what they have to inspire you you.

**Comment by bmlancien** [comment]
As discussed today, I'll also make a few suggestions:

Visible to public:

- Name (mandatory)
- Role (mandatory)
- Pronouns
- Work title or Company
- Location
- Public email address
- Bio
- URL (e.g. website)
- Social media account(s)

Private:

- Change email
- Change password
- Delete account
- Receive notifications (e.g. table review complete)

**Comment by Darynarli** [comment]
Do we need Affiliation and description ?

**Comment by bmlancien** [comment]
The description (or bio in my comment) could be an idea, but as said today, we'll have to decide with the other dev members first. What do you mean by affiliation? The company or role?

**Comment by Darynarli** [comment]
I think company, and what do you think?

**Comment by bmlancien** [comment]
From my side, I would say yes, especially if it's an easy feature to implement. 

I would also like to have the role as a feature (like moderator) but this would require more work probably. I'm not sure if the roles are defined yet @jh-RLI ?

**Comment by jh-RLI** [comment]
There is a role system, but it needs to be improved and extended with new roles like the _Moderator_ role. So more work is definitely needed here.

Also, I changed my mind about the email being publicly visible by default. I think it is better to show only the username.

**Comment by bmlancien** [comment]
> There is a role system, but it needs to be improved and extended with new roles like the Moderator role. So more work is definitely needed here.

Alright.

> Also, I changed my mind about the email being publicly visible by default. I think it is better to show only the username.

We could make the email public as an option. Maybe some users want to be contacted this way?

**Comment by jh-RLI** [comment]
Yes would be nice to have it as an option.

**Comment by jh-RLI** [comment]
Lets discuss this in he oep-dev meeting next week. I think a button would be good.

**Comment by Darynarli** [comment]
okey, can I now make a button and next week we will discuss?

**Comment by jh-RLI** [comment]
token reset button is missing
