### ISSUE TITLE
Rename repository to OEAcademy

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#1176]
- [x] Rename repo and GitHub-page 

https://github.com/OpenEnergyPlatform/academy

**Comment by han-f** [comment]
we need to fix the link on OEP main page now on the "Tutorial" tile, which we should also rename :-) :
[#1174](https://github.com/OpenEnergyPlatform/oeplatform/issues/1174)

**Comment by Ludee** [comment]
All links are fixed and the new Family member is released 🎉

**Comment by han-f** [comment]
Welcome to the Family OEA.
