### ISSUE TITLE
The search bar is not finding tables in _model_draft_ with no metadata:

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1195]
I just found that the search bar is not finding tables in _model_draft_ with no metadata:
see https://openenergy-platform.org/dataedit/view/model_draft?query=TYNDP
and https://openenergy-platform.org/dataedit/view/model_draft CTRL+F TYNDP

Please add the list of existing table names to the search function!

_Originally posted by @Ludee in https://github.com/OpenEnergyPlatform/oeplatform/issues/1066#issuecomment-1260679012_

**Comment by jh-RLI** [comment]
the search vector only uses only complete words,no partial or fuzzy matches.
if it was as a keyword in the metadata. it would work.

OR

when updating the search vector, split the table names on the "_" and add each token

**Comment by wingechr** [comment]
After some more consideration: let's not fix it. people need to fill out meta data for that reason.

**Comment by jh-RLI** [comment]
Yes i like that. I think we will need a more powerful search in the future. For now this is good as it is.
