### ISSUE TITLE
[Topics Page] Implement reworked UI

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1201]
We created a prototype of the OEP-Topics page (forma schma page).
- [x] implement mockup
- [ ] connect with backend
-  [ ] gather feedback
- [ ] release
- [ ] Check if consistent with https://wiki.openmod-initiative.org/wiki/Database_schema

**Comment by u-mueller** [comment]
I like the design! One small remark: the model-draft bar is quite eye catching for the topics page, wouldn't it be better that way in the review section?

@jh-RLI: How do you link the tables to the topics? Shall this also be discussed in connection with our scenario factsheets?

**Comment by jh-RLI** [comment]
model_draft is bigger because we want to make it more understandable that the user can only upload data on this topic. It is also to show that the data is not officially published. But maybe you are right and it is a bit too catchy. The reviews section is not fully fleshed out yet. There will be a list of ongoing and completed reviews on the profile page and a review can be started when looking at a single table.

Currently, the new user role of reviewer is being introduced to assign reviews to a profile, but it is not yet clear where the complete list of all open reviews will be displayed. In this sense, a separate review section that looks like this topics page is not yet planned.
