### ISSUE TITLE
[OPR] Notify the user on certain review process events

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1216]
## Description of the issue

The PeerReview once initiated requires active user interaction between at least two users. 

One thing is to show the review state on the table data page.

There are edge cases and regularly occurring events that are eligible for special notification to users to raise awareness of OPR progress. 

## Ideas of solution

First listen for a specific event:

send a notification to the user if:

- The review is about to be stale
- is stale
- will be deleted
- a reviewer submitted the review (can be enabled/disabled)
- a contributor submitted the review (can be enabled/disabled)

Implement the notification:

- Decide what types of notifications are to be considered (e-mail, next login or page visit) ... start with display notification on the profile page
- Use the PeerReviewManager to get the reviewer and contributor users.
- Send one or multiple notifications

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by Darynarli** [comment]
It would be nice to notify by email (for example 3 times) and if there was no answer, to do something (for example, deleting an unfinished review or automatic acceptance if the author did not give a return answer). When there will be a rating system, take points for it
