### ISSUE TITLE
Not possible to decrease the width of database columns

### ISSUE THREAD

**Issue by tillmo** [OpenEnergyPlatform/oeplatform#122]
The column width can be changed, but I would like to decrease e.g. the width of id column such that there is no extra space. This is not possible, because there appears to be a (too large) minimum width. (Also, the default width of some columns could be decreased.)

**Comment by EdithaK** [comment]
@gnn : It is an old one. Maybe the problem is already solved?

**Comment by christian-rli** [comment]
"Decrease minimum width of column" - User Feedback and part of the requirement specification.

RequirementSpecificationID=48

**Comment by Dhruvin14** [comment]
@Bachibouzouk  Is it not possible to decrease the width of database columns?

**Comment by Bachibouzouk** [comment]
> @Bachibouzouk Is it not possible to decrease the width of database columns?

One would have to look in the recline.js options in [dataview.html](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/dataedit/templates/dataedit/dataview.html).

Are you confortable in `javascript` @Dhruvin14 ?

**Comment by Dhruvin14** [comment]
@Bachibouzouk  I am new with javascript, but I tried to look into recline.js options in dataview.html.

There is a may possibilities to change the width of columns in dataview.html in line no. 72.  

<script type="text/javascript" src="https://rawgit.com/okfn/recline/master/vendor/slickgrid/2.2/slick.grid.js"></script> 

In this script, variable is defined as a defaultColumnWidth = 80,

I do not know after how should I change it? Could you please look into it.

**Comment by Bachibouzouk** [comment]
> I do not know after how should I change it? Could you please look into it.

If you don't know javascript maybe it is better that you tackle other issues :)

Our dependence on recline.js might be modified as well if we update to Bootstrap 4 so I would wait a bit before tackling this issue

**Comment by klarareder** [comment]
This is already implemented and released
