### ISSUE TITLE
Clickable elements lack hand pointer on mouseover

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#1241]
## Description of the issue

On the database page the current schemas are clickable, but there's not hand pointer on mouseover to signify this. This is confusing to users and seems broken.

## Steps to Reproduce
1. Observe this page: https://openenergy-platform.org/dataedit/schemas
2. Mouseover on schemas looks not clickable, but is
3. The cursor should be a hand pointer
![database-page](https://github.com/OpenEnergyPlatform/oeplatform/assets/42000429/88a576bc-0a2f-4f40-89dd-2b28946f927d)

## Ideas of solution

- make cursor change appearance to hand pointer on clickable elements on page i.e. the schemas
- to be specific: change arrow to hand https://upload.wikimedia.org/wikipedia/commons/8/83/Mouse-cursor-hand-pointer.svg
- if i'm not mistaken a css change `cursor: pointer;` at the right location should suffice
- While touching the page, fix the typo: under openstreetmap it reads **OMS** while it should read -> **OSM**.

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by wingechr** [comment]
already resolved with https://github.com/OpenEnergyPlatform/oeplatform/pull/1236
