### ISSUE TITLE
List of all registered OEP is scrapable

### ISSUE THREAD

**Issue by l-emele** [OpenEnergyPlatform/oeplatform#1244]
## Description of the issue

With the current pattern of the URLs of the profile pages it is very easy to scrape a full list of all people that are registered to the OEP.

## Steps to Reproduce
1. Produce a list by simply incrementing the number at the end of the URL. For example, this is my profile: https://openenergy-platform.org/user/profile/120

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
We have just updated the OEP with a hotfix that hides sensitive information like e-mail from other users (registered/public). Users are still scrapable, but this doesn't seem to be a problem as long as no private data is affected. Wht do yu think?

**Comment by l-emele** [comment]
Even the fact that you are registered is private data. We mention nowhere in the [privacy policy statement](https://openenergy-platform.org/legal/privacy_policy/) that the fact that you are registered will be publicly available. The statement not even mentions a profile page. Therefore I still regard this as a major issue of privacy.

**Comment by jh-RLI** [comment]
Great :) I'll close this issue now and we'll continue the discussion once we've agreed on the next steps.
