### ISSUE TITLE
The map view is not enhanced RSID44

### ISSUE THREAD

**Issue by tillmo** [OpenEnergyPlatform/oeplatform#125]
The map view should display the n (default n=100) most important data entries within the current bounding box. Importance could be defined in several ways. One way is to single out one column (i.e. capacity, for power plants) in each table, and define "more important" to be "higher value in this column". Alternatively, the column could be selected by the user, and select between higher value and lower value.

RequirementSpecificationID = 44

**Comment by EdithaK** [comment]
@gnn  : It is an old one. Maybe the problem is already solved?

**Comment by MGlauer** [comment]
Users can select and filter data in custom views now. The corresponding results are displayed in the map view. This solves this issue.
