### ISSUE TITLE
[OPR] Enable submit button in review page if all fields are reviewed

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1257]
## Description of the issue
Currently the submit button can be clicked at any time. This is not the desired state. The submit button for both (reviewer and contributor) should remain disabled unital all fields are reviewed.

On the reviewer page, the field state must either be:
- accepted
- suggestion
- rejected

On contributor page, the state must be:
- accepted
- rejected

## Ideas of solution

- implement check review complete JavaScript function

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
@Darynarli 
this works if there are field that have to be clicked. But if all fields are already reviewer (green) and the reviewer was the last one to submit the data contributor is stuck on the review page.



![Image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/1310a46b-ee4d-42d4-a580-c54aa7e9bc0c)

**Comment by jh-RLI** [comment]
This would be no problem if the award badge field would pop up if the reviewer accepts all field on first review. There would be no need to send the review to the contributor. The reviewer can just award a badge and finish the review.

**Comment by Darynarli** [comment]
> 

Yes, now it works like this: if the state_dict on the reviewer page is empty, then the button is activated only after all fields have been evaluated. But if the state_dict is not empty on the reviewer page, then the button is activated after the first field is evaluated. Does it need to be fixed?

**Comment by Darynarli** [comment]
> This would be no problem if the award badge field would pop up if the reviewer accepts all field on first review. There would be no need to send the review to the contributor. The reviewer can just award a badge and finish the review.

Yes, now it works like this: if the state_dict on the reviewer page is empty, then the button is activated only after all fields have been evaluated. But if the state_dict is not empty on the reviewer page, then the button is activated after the first field is evaluated. Does it need to be fixed?
