### ISSUE TITLE
[OPR] Begin feature rollout phase - Communicate to the use

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1263]
## Description of the issue

The open peer review process is about to be rolled out to the open energy plaform. As we first release the feature into the wild, we must communicate that we start the first step of the rollout phase. This phase is expected to be error prone and the users must be guided to a github discussion where they can share thier experiences openly. 

## Ideas of solution

Display information on the rollout pahse in the reviewer and contpributor pages. 
Draft:
"This feature is in early rollout phase now. We do expect you to experience some errors. Please share your experience in this [discussion]() on github (login required)."

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
@bmlancien I'd like to add a very small but visible "banner" to the review pages indicating that the open peer review functionality is still under development and linking to a Github discussion (I'll create one and provide the link).

Can you provide a placeholder for this?
The text I suggested in the issue description, inside a div with visible background color and a placeholder for the link would be perfect.

**Comment by bmlancien** [comment]
Here is a first idea on how to do it. We could make look like an alert on top of the main content, although without the possibility to close it. That way we are sure the users will see it.

I would also move the "Open Peer Review process" info button to the box to the right because it is taking a lot of space and I think it's still visible enough there.

What do you think?

![db__model-draft_banner](https://github.com/OpenEnergyPlatform/oeplatform/assets/33999424/d43d6fce-9a72-4615-adfe-02c047be777e)

**Comment by jh-RLI** [comment]
very nice!!

**Comment by jh-RLI** [comment]
I also like the idea to move the info button.

**Comment by jh-RLI** [comment]
I get a wired behavior:
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/fcb42f62-7c87-44f4-b1b6-07490156a95d)

**Comment by bmlancien** [comment]
Ah! I didn't see that. Let me check it.

**Comment by jh-RLI** [comment]
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/67f98e4f-84bb-4097-8a44-29bc2503561f)
its because of the missing Per Review info button :)

**Comment by bmlancien** [comment]
Ah ok, do we want to add the button?

**Comment by jh-RLI** [comment]
Yes :) it is still a placeholder but thats okay

**Comment by jh-RLI** [comment]
btw here is the link to the discussion. Could you add this to the banner ?
https://github.com/OpenEnergyPlatform/oeplatform/discussions/1268

**Comment by bmlancien** [comment]
It should work now.

**Comment by jh-RLI** [comment]
Works!

**Comment by jh-RLI** [comment]
I will merge the branch now.

**Comment by jh-RLI** [comment]
Thanks for also increasing the size of the modal window :)
