### ISSUE TITLE
[OPR] The review datamodel does not store a suggested/denied value that is accepted

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1270]
## Description of the issue

The review datamodel stores all field reviews. Once a field review is accepted there are three possibility what the new value for this metadata field is.

- The field was accepted immediately without the reviewer saying anything about it. In this case, the new value is the old value
- The reviewer suggested a new value and the contributor accepted it. In this case, the new value is the reviewer's suggestion.
- The reviewer proposed a new value, and the contributor rejected it. Then the reviewer either proposes another value or accepts the contributor's proposal. In this case, the new value is the value that was accepted. Theoretically, this discussion loop can go on forever, but this is unlikely because the reviewer and the contributor are assumed to have an incentive to complete the review.

## Ideas of solution

Set the new value according to the description above.

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by Darynarli** [comment]
I can't fully understand what needs to be changed?
Can you explain in more detail, please?

**Comment by jh-RLI** [comment]
@Darynarli after you are done with the code reviews, this is your next task (as we discussed in our meeting today).
I will add a better explanation now :) .

**Comment by jh-RLI** [comment]
The issue describes **two bugs** in the OPR.

## 1. The new value metadata value (result of the review) is not updated in the metadata field box (UI):

- For example, if a suggestion/deny is part of the review:

![Image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/4ec6c0dd-b61b-41b8-a258-ddaf9f6f1094)

- After submit, the contributor can Accept or Deny. If accept is used, the new value should be the suggested value from the reviewer:


![Image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/8ecb2a0d-5486-4327-9171-e901fba7bcba)

- Currently, the suggested value is just ignored. Once the contributor presses accept, the initial value from the metadata is visible as the accepted value.


![Image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/ce75d888-7aa5-490d-a61b-e57a82f9d126)

- The same happens if the contributor now denies a field review, suggest another value and submits. In this case, the reviewer can accept the review and the same bug is triggered. The new value is lost again, and the initial value from the metadata is visible as the accepted value.



## 2. The root cause is in the data model

If a field review is accepted, the new value from the review suggestion is not stored as an accepted value in the data model.
For Example, assume there is a reviewer suggestion for the "ID" field of the metadata. The contributor accepts it. The data model stores the field review like this:

```` json

{
            "key": "id",
            "category": "general",
            "fieldReview": [
                {
                    "role": "contributor",
                    "user": "oep_contributor",
                    "state": "ok",
                    "comment": "",
                    "timestamp": 1690186996055,
                    "contributorValue": "http://127.0.0.1:8000/dataedit/view/model_draft/test2",
                    "reviewerSuggestion": ""
                },
                {
                    "role": "reviewer",
                    "user": "oep_reviewer",
                    "state": "suggestion",
                    "comment": "diese url passt besser",
                    "timestamp": 1690186794361,
                    "contributorValue": "http://127.0.0.1:8000/dataedit/view/model_draft/test2",
                    "reviewerSuggestion": "better_url"
                }
            ]
        },
```

**Comment by Darynarli** [comment]
I have several questions:

1. After the contributor has accepted the reviewer's suggestion, should the information be updated automatically on the contributor's page or after clicking the submit button on the reviewer's page?

2. As far as I understand, if the contributor accepted the reviewer's suggestion, the reviewerSuggestion should be recorded in the ContributorValue?
For example like this:
`
{
            "key": "id",
            "category": "general",
            "fieldReview": [
                {
                    "role": "contributor",
                    "user": "oep_contributor",
                    "state": "ok",
                    "comment": "",
                    "timestamp": 1690186996055,
                    "contributorValue": "better_url",
                    "reviewerSuggestion": ""
                },
                {
                    "role": "reviewer",
                    "user": "oep_reviewer",
                    "state": "suggestion",
                    "comment": "diese url passt besser",
                    "timestamp": 1690186794361,
                    "contributorValue": "http://127.0.0.1:8000/dataedit/view/model_draft/test2",
                    "reviewerSuggestion": "better_url"
                }
            ]
        }
`


Exactly the same questions for the review page

**Comment by jh-RLI** [comment]
> * After the contributor has accepted the reviewer's suggestion, should the information be updated automatically on the contributor's page or after clicking the submit button on the reviewer's page?

I am not sure what the background is for this idea. I think it doesn't make sense to automatically update the field, since the contributor shouldn't be able to open the review while the reviewer is reviewing and resubmitting. Therefore, it should be fine to update the field when submitting.

> * As far as I understand, if the contributor accepted the reviewer's suggestion, the reviewerSuggestion should be recorded in the ContributorValue?

Yes, you can implement it like this. Also once the review is accepted the new contributorValue must be visible on the page.

I'm not 100% happy with this, we might have to extend the review datamodel by a new field that also stores the initial value from the metadata. But we can do this later.

**Comment by jh-RLI** [comment]
Ideally, we would also introduce a new key in the review datamodel. Something like "newValue". This would make things more clear. What do you think?
