### ISSUE TITLE
Inconvenience of client cache update upon releasing/deploy new versions

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1281]
## Description of the issue

When deploying a new version of an application, users are inconvenienced as they need to manually refresh the client cache to see the latest changes.

## Ideas of solution

ChatGPT suggested to introduce a Cache Busting Mechanism. We could use this existing lib [django-compressor](https://github.com/django-compressor/django-compressor).

> To set up a cache-busting mechanism in your Django application, you can use the Django extension module "django-compressor". Django Compressor allows you to compress static resources such as CSS and JavaScript files and assign them a unique hash value based on their content. This automatically changes the URL of the resources whenever they are modified.

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Suggested implementation:

Hier ist eine Schritt-für-Schritt-Anleitung, wie Sie Django Compressor einrichten können:

Installieren Sie django-compressor mit pip:

`pip install django-compressor`

Fügen Sie 'compressor' zu Ihrer INSTALLED_APPS-Liste in den Einstellungen Ihrer Django-Anwendung hinzu.

Konfigurieren Sie die Einstellungen für django-compressor in den Einstellungen Ihrer Django-Anwendung. Fügen Sie Folgendes hinzu:

```python
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True
```

Führen Sie den Befehl django manage.py collectstatic aus, um Ihre statischen Dateien zu sammeln und in den angegebenen STATIC_ROOT-Ordner zu kopieren.

Verwenden Sie den {% compress %}-Template-Tag in Ihren HTML-Templates, um die komprimierten Versionen Ihrer CSS- und JavaScript-Dateien einzufügen. Zum Beispiel:

```django
{% load compress %}

{% compress css %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endcompress %}

{% compress js %}
<script src="{% static 'js/script.js' %}"></script>
{% endcompress %}
```

**Comment by jh-RLI** [comment]
@wingechr what do you think?

**Comment by wingechr** [comment]
i think that's a very good solution.
