### ISSUE TITLE
create EDIT page for study and scenario factsheets

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/oeplatform#1282]
## Description of the issue
Goal is to create a page for adding and editing factsheets on studies and scenarios.
On the edit page, users should be able to enter all information about a study and related scenarios in a structured manner, based on the OEKG.
@adelmemariani created most of the backend functionalities. Now the frontend has to be aligned with oep design and implemented on the oep.
## Ideas of solution

![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/38690039/dc876efb-d7ab-4695-a435-8e1529f48767)

Some feedback on the existing functionalities were provided in the [oekg repo](https://github.com/OpenEnergyPlatform/oekg/).

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Aligning the design with the open energy platform theme seems to be more complicated than we initially thought. 

The study-factsheet/bundles are developed using React along with material design components. The rest of the OEP was developed using Bootstrap5. Moving the components from Material Design to Bootstrap would mean that we would have to completely rework the current implementation of all components. 

My conclusion is that we don't want this extra effort, but we will try to adapt the Material Design components to look similar to what Bootstrap provides. 

In future React-based developments, we should use Bootstrap components. 

We will not spend too much effort on customizing the design, but rather focus on usability, as we have very limited resources in terms of UI/UX expert. 

@adelmemariani @bmlancien

**Comment by jh-RLI** [comment]
We already implemented the new layout and oep style. I will close this issue :)
