### ISSUE TITLE
create VIEW page for study and scenario factsheets

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/oeplatform#1283]
## Description of the issue
Goal is to create a page for viewing and exploring a study and scenario factsheet, which all the related content (linked). 
The page should contain all information that is added on the factsheet edit page #1282 in a nice and structured way.
- show basic information about a study, expandable
- basic information about each scneario that is related to the study, expandable
- list / links to the model factsheets
- list of linked datasets
- maybe external links like reports

The concept for this page was called "[scenario bundle](http://openenergy-platform.org/ontology/oeo/OEO_00020227)". 

## Ideas of solution

![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/38690039/bbae325f-0746-4f63-8650-e1d60a9e31d3)

This is an old draft for how a scenario bundle could look like. @bmlancien a more elaborate design is welcome...

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
We already agreed on a mockup and @bmlancien implemented it. The updated page will be available within the next OEP release.


![Image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/50b0b0f0-dcce-48e2-b444-88a523f75e83)

We still need to improve details like this one:
https://github.com/OpenEnergyPlatform/oeplatform/issues/1419

**Comment by jh-RLI** [comment]
I will close this issue as we have implemented the general style already. Thanks @bmlancien !
