### ISSUE TITLE
create OVERVIEW page for study and scenario factsheet / bundles

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/oeplatform#1284]
## Description of the issue
The goal is to have an overview page, where all study factsheets are listed.

## Ideas of solution
@adelmemariani provided a nice draft that already contains required functionalities. The design has to be aligned with oep design and the implemented on the OEP.
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/38690039/321fefbf-afaa-4b08-b3b8-e31604921bde)

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
I will close this issue as we have implemented the general layout and oep style already. https://github.com/OpenEnergyPlatform/oeplatform/pull/1479 also provides more improvements to the cards view option.
