### ISSUE TITLE
Password reset form is not captcha protected

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#1286]
## Description of the issue

Every form that cause communications between the platform and the outside world should be captcha protected. Otherwise, the OEP may be used for DDOS attacks on other servers.

## Ideas of solution

Add captcha protection or similar to the password reset form

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
@MGlauer Do you think we should be very strict about this and include a captcha in the forms used to create tables, factsheets, etc.?

**Comment by MGlauer** [comment]
I think the critical criterion is whether
a) The for triggers any communication with the outside (emails, hooks etc)
b) Whether the form can be accessed without being logged in

If both are the case, a Captcha is mandatory.
