### ISSUE TITLE
access control for factsheet editing

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/oeplatform#1299]
## Description of the issue

In the OEKG it should be noted who is editing a factsheet and stored in a history. 
Question TBD: (How) should the history ba accessible for users?

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
@adelmemariani Good that you have already worked on access control to restrict access to logged in users. This issue also targets other aspects of access control, I think. 

It would be great if you could add the issue ID to your commit message to link the commit to the issue, making the code traceable to the requirement (issue). Just add the issue ID to your commit massage :) 
`git commit -m "commit message #1299" ....`

I add the commit here:
[64c56d8](https://github.com/OpenEnergyPlatform/oeplatform/commit/64c56d87bc0105d6b212250b7c7e31ebf8603edd)

**Comment by jh-RLI** [comment]
After some discussion, we have determined that we need a link between the user (id) and a factsheet (id) to implement access control. 
We assume that the best solution is to implement a new table in the oep_django database that stores this data. It should be updated every time a factsheet is created.

The access control will be implemented in a similar pattern as we currently use for the data tables that a user can create. 

@adelmemariani  is there any progress on the table that stores this relationship?

**Comment by adelmemariani** [comment]
> @adelmemariani is there any progress on the table that stores this relationship?

Yes. The following is an example of the history of OEKG:

http://toep.iks.cs.ovgu.de/sirop/oekg_history

**Comment by jh-RLI** [comment]
Thanks for the update :)

The page looks empty for me (even if I'm logged in), also showing some JS errors:
![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/db2a2aa4-0eb4-4bac-82d1-d9cd1bb324ea)

**Comment by jh-RLI** [comment]
@adelmemariani 
As we created this complete list of features, we can also use it to determine the access control. 
The table is perhaps a little too detailed, but I think it's a good starting point for a deeper look. 

We should add one or more access permissions to each feature (depending on how fine granular we want the access control to be, it may be sufficient to add the access permissions to only one feature at a higher level)

In General, I see a need for the following levels of permissions. Do you agree?
**Access permissions**: PublicUser, AllLoggedInUsers, CreatorUser, PermissinGroup, MaintainerUser

| Feature Name (Part of Factsheet/Bundle) | Sub-Feature                 | Access permissions | Comment                                                           |
|----------------------------------------|-----------------------------|----------------------|-------------------------------------------------------------------|
| Factsheet-Overview                    |                             |                      |                                                                   |
|                                        | List-Factsheets             |                      |                                                                   |
|                                        | Access-Scenario-Compare     |                      | Make this feature more visible.                                  |
|                                        | Access-Create               |                      |                                                                   |
|                                        | Access-Filter               |                      |                                                                   |
|                                        | Reset-Filter                |                      |                                                                   |
|                                        | Access-Detailpage           |                      |                                                                   |
|                                        | ?? Switch-View              |                      |                                                                   |
| Factsheet-Detailpage                  |                             |                      |                                                                   |
|                                        | View-Mode                   |                      |                                                                   |
|                                        | Edit-Mode                   |                      |                                                                   |
|                                        | Delete                      |                      |                                                                   |
|                                        | Share                       |                      |                                                                   |
|                                        | Access-Linked-Entities      |                      |                                                                   |
|                                        | Category-Timeline           |                      | The timeline UI is not suitable                                  |
|                                        | !! Tooltips                 |                      |                                                                   |
|                                        | Show Title                  |                      |                                                                   |
|                                        | ?? Compare-similar-FS       |                      | Not implemented                                                  |
|                                        | ?? FS Category Badges       |                      |                                                                   |
| Factsheet-Edit/Create                 |                             |                      |                                                                   |
|                                        | Categories                  |                      |                                                                   |
|                                        | Expanding-Stepper           |                      |                                                                   |
|                                        | Progressbar                 |                      |                                                                   |
|                                        | Save                        |                      |                                                                   |
|                                        | Share                       |                      |                                                                   |
|                                        | Delete                      |                      |                                                                   |
|                                        | Tooltips                    |                      |                                                                   |
|                                        | Compare-similar-FS          |                      |                                                                   |
|                                        | ?? Compare-similar-FS       |                      | Do we need this on the Edit page???                               |
|                                        | ?? FS Category Badges       |                      |                                                                   |
| Scenario-Comparison                   |                             |                      |                                                                   |
|                                        | Select-Element-Modal        |                      | The element term might change.                                    |
|                                        | comparison-detail           |                      | Make similar badges more visible (focus on similar things).       |
|                                        | Back-button                 |                      |                                                                   |
|                                        | ?? comparison-extra-metric  |                      |                                                                   |
| History-List                          |                             |                      | [http://toep.iks.cs.ovgu.de/sirop/oekg_history](http://toep.iks.cs.ovgu.de/sirop/oekg_history) |
| Filter-Modal                          |                             |                      |                                                                   |
|                                        | Input-Text-Autoselect       |                      |                                                                   |
|                                        | Input-Date                 |                      |                                                                   |
|                                        | Input-Checkbox             |                      |                                                                   |
|                                        | Input-Date-Range-Silder    |                      | Implemented as an example.                                        |
|                                        | Confirm                    |                      |                                                                   |
|                                        | Cancel                     |                      |                                                                   |


?? - Use if this feature might not be necessary
--
!! - Use if feature is missing and should be implemented

**Comment by jh-RLI** [comment]
I started implementing this yesterday and submitted a draft to @adelmemariani and @wingechr. 
We have found that this task is not as trivial as I initially thought. Implementing a full access control that defines the access rights for each of the nodes in the OEKG is a task that is not done quickly.

My idea for a simple solution that can be implemented now is to implement two types of permissions. 
1. creator: the creator of a scenario bundle gets the permission "admin" for the bundle. The connection is made using the oep user ID and the UID of the scenario bundle. 
2. PermissionGroup: we want to use the groups that can already be created on the OEP and connect them to the ScnearioBundle access control. The creating user can add groups to the ScnearioBundle he/she owns.
3. users with permissions can edit the Scneario bundle, the creator can always delete a bundle and if he/she defines the group as admin, all users in the group can also delete a bundle.

My general understanding is that the UID of a scenario bundle "knows" all associated nodes. To implement my suggestion, it is required that we can simply delete the specific scenario bundle (maybe just the UID)  by disconnecting it from the connected nodes. The nodes that were connected remain in the oekg. In this way, we can delete scenario bundles and also remove them from the UI on the OEP without having to implement full, fine-grained access control for the oekg. The downside is that over time there may be many stale or incorrect nodes in the Oekg, as they cannot be deleted by the user.

To improve this, we can:
1. create a function/script that removes nodes created by a user when creating a scenario bundle that were later deleted and not used over a period of time. 
2. we can also implement a moderator view that allows manual node cleanup (which I don't like).
3. and more ....

**Comment by stap-m** [comment]
> My idea for a simple solution that can be implemented now is to implement two types of permissions.
> 
>     1. creator: the creator of a scenario bundle gets the permission "admin" for the bundle. The connection is made using the oep user ID and the UID of the scenario bundle.
> 
>     2. PermissionGroup: we want to use the groups that can already be created on the OEP and connect them to the ScnearioBundle access control. The creating user can add groups to the ScnearioBundle he/she owns.
> 
>     3. users with permissions can edit the Scneario bundle, the creator can always delete a bundle and if he/she defines the group as admin, all users in the group can also delete a bundle.

This sound very good to me.

**Comment by jh-RLI** [comment]
@adelmemariani FYI the following is only in my branch so far but once it is merged it will apply to all post requests (using react axios) to the django backend.

There is a new component called csrfToken.js. It will read out django csrf cookie. This must be present in all post requests headers. In a axios request make sure to add the header like this
