### ISSUE TITLE
User groups in model schema

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#130]
Model data is more volatile than result date. Thus, we need a different editing scheme that features groups. Only group members can edit or add data sets.

**Comment by MGlauer** [comment]
Most of the datasets in the OEDB are (read: will be) versioned. This implies a rather slow and burdensome workflow if you want to change data, which is not viable for projects that are still in development. There are one ore more  specific schema(s) that will not follow this versioning scheme. 
In order to prevent vandalism the each dataset will belong to a user group that has write-access to these datasets.
1. Extend the login app: Implement these user groups using the Django ORM (maybe we can inherit the pre-implemented [group handling](https://docs.djangoproject.com/en/1.10/ref/contrib/auth/#group-model))
2. Link datasets (identified by schema and table name) to groups 
3. Implement a methods like has_write_permission(user, schema, table)  or get_writeable_tables() as an interface to this group management.

**Comment by EdithaK** [comment]
Hello @MFinkendei, is this still on your list?

**Comment by christian-rli** [comment]
user groups and handling  permissions on the website are implemented. Allowing editing options in schemas other than model_draft should be dealt with in a separate issue.

**Comment by christian-rli** [comment]
Rereading this issue. It seems the original issue has been solved. Handling permissions in different schemas will become an issue after dissolving schemas. This should be newly phrased in a new issue.
