### ISSUE TITLE
Link from data table to scenario bundle

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1305]
## Description of the issue

Introduce info alongside data tables which factsheets refer to the data a user currently sees. 

## Ideas of solution
Implement another info box on the right to a data table. Infobox should contain links to factsheets. Ideally the link opens in a new tab, so factsheet and data table can be viewed alongside one another. 

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
@adelmemariani if you have figured out how to store the factsheet ID in a table, then we can use those patterns here as well. 
We can implement something like an observer that provides a list of and links to factsheets/bundles that contain a table. The observer should always be up to date and able to provide the list for all tables to be presented on the data view page.

**Comment by stap-m** [comment]
I think, this is an important feature for a stable bundle version!

**Comment by jh-RLI** [comment]
There is now a new tab on the tables-detailpage with that provides a list of all scenarios that list the current tables as input / output dataset. It looks very basic and currently it is not possible to link to the scenario. 

![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/1a8db3d5-738c-4f1c-8d0a-fc75d1541054)

**Comment by jh-RLI** [comment]
@han-f @stap-m @adelmemariani @l-emele  The link to the scenario bundle or the scenario factsheet will take place in a further step. 
At the moment it would be good to know whether we should link to a scenario or whether we should list all scenario bundles that contain the scenario and then link to each one. 
If we link to a scenario, then we would need another page in the scenario bundle that lists all available scenario factsheets, independently of the scenario bundles.

**Comment by jh-RLI** [comment]
For tables that are in the "Scenario" topic, there is now the "Scenario bundle" section, which is visible in the updated sidebar. 

![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/ef5d911b-021e-4d57-ba22-fc664be9f32a)

Clicking on one of the bundle acronyms will open the bundle page.

This is currently only in the develop branch not yet on TOEP / OEP.

**Comment by jh-RLI** [comment]
I'm closing this issue for now. We may publish it again if problems are discovered during testing.
