### ISSUE TITLE
Django compressor seems to produce unexpected cache behavior.

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1337]
## Description of the issue

@Darynarli and myself experienced unexpected behavior that is triggered by the new package `django-compression`. This behavior prevents updating the compressed sources like js or css files entirely. This also happens somewhat silent, because the compressed files (e.g. `static/CACHE/js/....`) are created as expected (Using the management command `manage.py compress`). The first error can be found if the template that imports the source script (html-template) code is inspected using the dev-tool (e.g. chrome).

It was observed in the local dev-environments, production might also be affected by the next release. 

If you want to know what is part of the compression search in templates for this templatetag:
``` jinja2
{% compress js %}
  <script src="update source name here "></script>
{% endcompress %}
```

To avoid this behavior in development, you can deactivate the compressor in the settings.py 

COMPRESS_ENABLED = False

## Steps to Reproduce
We noticed this during the development of the open peer review. We have updated the source code of a JS source that is part of the compression. I noticed that the script import of the compressed file (name like output18471749.js) is not updated in the html-template after a new compressed file was created.

## Ideas of solution

- Fix django-compressor settings 
- or Report bug
- or Fix template inheritance
- other???

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by wingechr** [comment]
```bash
python manage.py compress
```
this updates the files now (at least for me), but in order for the server to detect the (offline) changes, it has to be reloaded.
so i also run this 

```bash
touch oeplatform/wsgi.py
```
touching and python file causes the dev server to reload, touching `oeplatform/wsgi.py` causes the productive wsgi server to reload, so it works both in productuin and dev
