### ISSUE TITLE
Data view: design suggestion to increase the understanding

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#134]
- order of the elements on the page: Name of Table, Tags, explanation/help (hide symbols +/-), "Show also unconfirmed data" (0), Data,  "Data is displayed using recline.js", comments (1), "Commit your changes" box (2), meta data, Revision (3)

0) Rename and add explanation. See also #147

1) Make the text ">>Commments" more clear: "Show the table explaining the comments on the rows". Can we open it in another tab?

2) put "upload csv" into the grey "commit your changes" box under the explanatory text (+ "You can make change in the table above and / or upload additional rows from a csv file.") See also #147.

3) Make the text more clear: "You can download THE CURRENT OR AN older revisioN of the data stored On the platform. Each revision has a unique id which can be used for citations. In order to save memory ON THE SERVER THE RELEASES ARE NOT DIRECTLY are available. You can request a dump of the current table OR A FORMER VERSION by..."
What about the check box to order related tables, too?

A) Bug: displaying: source on top of the meta data instead of in the table

B) Lastest revision mark it as "lastest / current revision/ release"  See also #143.

C) Will untested data be displayed in another font colour? See also #147.

**Comment by christian-rli** [comment]
"Redesign the data view: Display the column descriptions from metadata." - User Feedback and part of the requirement specification. 

https://github.com/OpenEnergyPlatform/oeplatform/issues/226 and https://github.com/OpenEnergyPlatform/oeplatform/issues/167 are connected to this issue.

RequirementSpecificationID=49

**Comment by wingechr** [comment]
finished with #167 and #226
