### ISSUE TITLE
Link to api tutorial on oep homepage is broken.

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1350]
## Description of the issue

This button leads to a 404 page on the academy page.
![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/876abc57-593d-4625-a58d-3cfc1fae57a1)

## Ideas of solution
- [x] Find updated tutorial URI and update link.

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by Ludee** [comment]
The tutorials on the Academy have been restructured and updated.
It should be this link: 
https://openenergyplatform.github.io/academy/tutorials/01_api/01_api_download/
