### ISSUE TITLE
notes for schema dissolve

### ISSUE THREAD

**Issue by wingechr** [OpenEnergyPlatform/oeplatform#1356]
# README

## current state

* only allowed to create / insert into sandbox and model_draft
* in code: usually checked with UNVERSIONED_SCHEMAS | PLAYGROUNDS
* finalized data: move from model_draft to TARGET (only via API)
* Table model references Schema model instance
* in security settings
    * DEFAULT_SCHEMA = 'sandbox'
    * PLAYGROUNDS = (DEFAULT_SCHEMA, 'test')
    * UNVERSIONED_SCHEMAS = ("model_draft", )
* in dataedit/views.py: 
    * schema_whitelist, schema_sandbox

## desired state
* ~newly created tables all in database schema dataset~
* ~is_draft is an attribute~
* newly created tables in model_draft
* tables can be identified by their name alone
* there is a api + UI function to mark table as no longer draft
  * this moves the table into (versioned?) schema dataset
* should there also be a reverse?
* you can delete all
* you can only edit in draft
* we have now "topics" that replace the schemas
* table can be in multiple topics
* tables not in draft are always in `dataset` topic
* in platform:
  * if model_draft: do not show in tocics

## problems
* lots of potentially dangerous migrations, and we dont have a (good) access to backend
* what are the security settings on the server (DEFAULT_SCHEMA, ...)
* how excactly does the versioning work (and also, what about the tables like `_edit_base`and so on`?

**Comment by wingechr** [comment]
# IMPORTANT NOTES for productive release

* make sure security settings are updated (schema names, see default file)
* run `python manage.py migrate` BEFORE `python manage.py alembic upgrade head`, because topics have to be created first

**Comment by jh-RLI** [comment]
Because this was a question - this is what is currently in the settings on the production OEP:
```
DEFAULT_SCHEMA = "sandbox"
PLAYGROUNDS = ('sandbox', 'model_draft')
UNVERSIONED_SCHEMAS = ('model_draft', )
```

**Comment by jh-RLI** [comment]
Btw. the publish functionality is already implemented. Once your table was reviewed the user sees a publish button when is visits the profile page.

**Comment by wingechr** [comment]
closing this for now, continue in #1000

**Comment by han-f** [comment]
> 
>     * Question: Do we really want to display this data all the time?
>       Perhaps it should only be publicly visible when metadata is available and open peer review has been requested? Otherwise we could show data without licence information.  We could potentially be sued for publishing this data. In this way, the user could also decide when the data is ready for review.
I think this is a good idea to not make data in model_draft visible to the public by default. I'd support this approach you suggest. And data would then only be ready for review once it does have a proper open license attached.
