### ISSUE TITLE
[Factsheets] Linking Frameworks, Models, Scenarios, Data

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#138]
Set links (both directions) between the different elements, not just names.

Suggestion:
If a model based on oemof is added, add it to the oemof fact sheet automatically.

**Comment by beritRLI** [comment]
in the scenario FS a place is missing where to put the links to the used data (best case: to the oedb)
that should be possible in both categories: empirical data and assumptions.

**Comment by stap-m** [comment]
This is going to be adressed in the new FS generation, see [here](https://github.com/orgs/OpenEnergyPlatform/projects/25)
