### ISSUE TITLE
Scenario Bundles: Cannot add more than one publication 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1397]
## Description of the issue
I added a new scenario bundle and would like to add more than one publication under the heading "Publication**s**.
I cannot find a button to add further publications etc. 

Please add this, as I think it is a use case that several publications are available. 

## Steps to Reproduce
1. Click on "Publications"
2. Add your first publication, save
3. Then no possibility available to add another publication

## Ideas of solution

Add a button to add further publications, similar to adding more than one scenario

## Context and Environment
* Version used: 
* Operating system: windows 10
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
We will add a similiar view like what we have in the scenari tab. this will not be part of the upcomming release.

**Comment by han-f** [comment]
It would be great if this could be included in the now coming release, as we already have a use case to which we would like to add multiple publications.

**Comment by jh-RLI** [comment]
It will be. i started to work on it but need some react tips from @adelmemariani ;) .
