### ISSUE TITLE
Scenario Bundle: Updates to the title won't show up on overview page. 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1401]
When I change the "study" name while editing a scenario bundle factsheet, that change is not reflected on the main page. See screenshots below for an example:
Main page: 
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/7d6f4a20-ac61-47f5-ac21-77e24778afa2)
Overview:
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/a61900d8-49d1-43d0-8362-d8e7bcf8f047)
Editing interface:
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/91262346-a4b5-497c-a73a-991130d7a4c5)

**Comment by han-f** [comment]
I just checked whether this also is the case for "acronym" - here it works. Maybe it is good to test for other fields, too.

**Comment by han-f** [comment]
This issue still persists even after the hotfix release

**Comment by jh-RLI** [comment]
Okay, this seems a bit more complicated:
Creating a new bundle and then reopening it and editing the title and acronym works as expected. But this doesn't seem to work for existing scenario bundles. You can see the difference in the title in this bundle, for example:
https://openenergy-platform.org/sirop/factsheet/6ddf7ede-c3a5-93c8-4385-b975c628d610

The title on the overview page is different from the tile seen on the details page. Can you please check this @adelmemariani

**Comment by jh-RLI** [comment]
For me this works now. Please reopen if the error persists.
