### ISSUE TITLE
[models] View does not update when editing a model and selecting a tag like "Openness"

### ISSUE THREAD

**Issue by maurerle** [OpenEnergyPlatform/oeplatform#1403]
## Description of the issue

When editing a model, the general Information tab stays visible, even when clicking one of the other tabs.
The selected tab is rendered below, which is more than one screen view below, so it feels like nothing happens at all.

This is very bad, as it is quite unintuitive that nothing happens.
When adding a new model, it works as expected.

![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/25026204/d981cfb4-2abc-407f-8bbe-b2451cf99838)

## Steps to Reproduce
1. Edit a model
2. Click one of the Tabs like "Openness"
3. View does not change, looks like nothing happened, but view is actually rendered below

## Ideas of solution

Either set the focus to the section which should be edited (scroll down the view on click of the tags)

or remove the general information tab when a different one is selected (this is the current behavior when **adding** a new model)

## Context and Environment

Website

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Reagrding the described bug i also noticed that the view is actually updating but the first tab stays open and the content of the clicked tab is appended to the end of the page. That is unexpected.

**Comment by jh-RLI** [comment]
Fixed in #1407 and will be available with the next oep release (latest in the next two months, but probably much sooner :) )

**Comment by han-f** [comment]
I was able to get this to work, but realised that the moment I add information to a further area, the previously input information seems gone, even after refreshing. I guess we will wait a bit until we add further model information. In view of the scenario bundle factsheet it would be great to get this to work, as we will then be able to link the models to the bundle factsheets. 

The ENUSEM model was already included in the model factsheets, but it does not seem to be in the OEKG, and I was not able to add this to one of our scenario bundle factsheets. This may be related to #1414

cc @l-emele
