### ISSUE TITLE
Scenario Bundles: Citation field is not available not in editing interface

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1410]
In the overview we can see a field "Citation" under "Publication", but this field is not available in the editing interface.
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/ba9c1185-3db4-47a3-a89d-68828d91d030)
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/0aa2b111-a5c7-463f-8f3f-63645dd1086e)

**Comment by jh-RLI** [comment]
This field was a suggestion by me i think the implementation is missing so far. It should be gray or removed until it is implemented @adelmemariani

**Comment by han-f** [comment]
I like the idea of the field and look forward to implementation. I agree it would be good to remove it until then.
