### ISSUE TITLE
Scenario Bundles: Publication date gives day -1

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1412]
When I add a publication date e.g. as 2019-05-15 it provides as output 2019-05-14, tried it with a few times, seems a consistent issue.

**Comment by han-f** [comment]
may this be a problem that there is a date time field in the backend which does not fit with the time zone and thus it slips one day?

**Comment by adelmemariani** [comment]
> may this be a problem that there is a date time field in the backend which does not fit with the time zone and thus it slips one day?

Yes, the main cause seems to be the time zone as explained [here](https://stackoverflow.com/questions/7556591/is-the-javascript-date-object-always-one-day-off). I will fix this issue in the next hotfix release.

**Comment by jh-RLI** [comment]
Was working for developers, please confirm and reopen if bug persists.
