### ISSUE TITLE
Scenario Bundles: some IRIs not in OEKG?

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1414]
For this scenario bundle we have a lot of tables to add under "Inputs" and "Outputs". But it is not possible to add the most recent ones.

- https://openenergy-platform.org/dataedit/view/scenario/eu_leg_data_2022_rep_table_1
- https://openenergy-platform.org/dataedit/view/scenario/eu_leg_data_2022_rep_table_3

Are they not yet in the OEKG?
Can the OEKG be updated accordingly?

**Comment by jh-RLI** [comment]
@adelmemariani 
Is there any automated update of the table list in place? Do we have to update the list of tables manually?

**Comment by jh-RLI** [comment]
When updating this list, it would be nice if you could add documentation on how to update the list :) 

I see the current list here:
https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/factsheet/frontend/src/data/datasets_names.json#L5

We need to specify:
- How to update this list (add documentation to oep-documentation).
- When will we trigger the update manually? Can we automate this?
