### ISSUE TITLE
Scenario Bundles: Regions turn into "None"

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1415]
I added region information to several factsheets and while they showed up in the latest days, they all of a sudden turned into "None"

"None" is not available in the region drop-down menu and it is a pity, as for one factsheet I have to click 27 countries to show up.
https://openenergy-platform.org/sirop/factsheet/6ddf7ede-c3a5-93c8-4385-b975c628d610

![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/15954896-6669-4ba5-b44f-c16e813b899e)

**Comment by jh-RLI** [comment]
@adelmemariani 
Please check :)

**Comment by adelmemariani** [comment]
Thank you @han-f for reporting this bug. This will be fixed soon in the next hotfix release.
