### ISSUE TITLE
Scenario bundles: country drop-down not in (english) alphabetical order

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1424]
## Description of the issue

The country drop-down menu holds the countries in another than english alphabetical order. This makes it a bit counter-intuitive to find the country(ies) you are looking for. 
## Ideas of solution

 I think it would be helpful if this list could appear sorted from A-Z. 

## Workflow checklist
- [x ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

FYI @stap-m @l-emele @wingechr

**Comment by l-emele** [comment]
In that context: Which country list/ontology are we using in the OEKG? I am aware that we had discussions about this, but I don't recall the decision.

**Comment by adelmemariani** [comment]
[LLC, Languages, Countries And Codes](https://www.omg.org/spec/LCC/)
