### ISSUE TITLE
Scenario bundles: Scenario Abstract reads "Abstract" 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1434]
## Description of the issue

The scenario abstract reads "abstract" as a title, and I think it should better read "scenario abstract", specifically when a user views this during a scenario comparison alongside the study title and abstract. I think that would add clarity, compared to  screenshot below:
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/26352685-4ca3-4444-aacc-bfeba68549c0)

## Ideas of solution

Rename "abstract" field for scenario into either "scenario abstract" or "about this scenario". 

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [x ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

FYI @stap-m @l-emele @wingechr

**Comment by han-f** [comment]
Not sure whether this is targeted at the next release or not, but on toep it still reads "abstract". While no one made a thumbs up here, I think it wouldn't hurt to change the title to either or of the suggestions above, if even temporarily - it will make the understanding easier.

**Comment by jh-RLI** [comment]
We agreed on the naming "scenario abstract". We also want to enable the user to hide the scenario abstract.
