### ISSUE TITLE
data in model_draft should not be editable by anyone

### ISSUE THREAD

**Issue by tillmo** [OpenEnergyPlatform/oeplatform#145]

**Comment by MGlauer** [comment]
We decided to implement a group management which is tracked in #130. Data in this schema will be editable by group members only. This will be implemented as soon as #130 is closed.

**Comment by EdithaK** [comment]
@MFinkendei I assigned you because you are also doing the #130 . Hope that is right.

**Comment by christian-rli** [comment]
group permissions are implemented already
