### ISSUE TITLE
Model Factsheets: Intro text suggestion 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1450]
In #1418 we have a suggested intro text for scenario bundles. Here, I would like to draft an intro text for the model factsheet page.
The first draft goes like this:

The [model](https://openenergy-platform.org/ontology/oeo/OEO_00020353) [factsheets](https://openenergy-platform.org/ontology/oeo/OEO_00000162) characterise models used in energy system analysis in a structured way regarding important characteristics, such as their scope and [licence](https://openenergy-platform.org/ontology/oeo/OEO_00020015) and their developing [institutions](https://openenergy-platform.org/ontology/oeo/OEO_00000238). You are developing a model? Then you can inform about its characteristics here. The models available as a factsheet can be integrated as an element into a [scenario bundle](https://openenergy-platform.org/sirop/) which weave together important information about [scenarios](http://openenergy-platform.org/ontology/oeo/OEO_00000364), such as the model used for conducting a [scenario projection,](https://openenergy-platform.org/ontology/oeo/OEO_00010262) [data](https://openenergy-platform.org/ontology/oeo/IAO_0000027) provided on the OEP and [publications](https://openenergy-platform.org/ontology/oeo/OEO_00020012). 

FYI @stap-m @l-emele @wingechr

**Comment by han-f** [comment]
A thought just came to my mind: Do I recall correctly that @Ludee created many of the model factsheets, also for models that are not developed by RLI? How would a person that actually develops a model that had already been put in here take ownership of it and be able to edit it?

**Comment by jh-RLI** [comment]
Good question currently there is no functionality to change ownership, we would have to change the owner of a factsheet manually in the database or we can add the permission group feature.

**Comment by jh-RLI** [comment]
I think this is a browser cache issue again. On Chrome, press Strg+F5 together when you are on the scenario bundle page.
![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/9047c1e7-0df9-4ebc-b8c8-eeef7f31ac24)

**Comment by stap-m** [comment]
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/38690039/0674f516-1a22-4bec-8cec-fa2d19bae113)
For the database page, there is this header. I'd like to have a header for the scenario bundles, too (or harmonised for all menu topics. Ontology has no header, either).

**Comment by han-f** [comment]
> I think this is a browser cache issue again. In your browser, press Strg+F5 together when you are on the scenario bundle page. (make sure your Fn key is not in the way so you can press the F5 key)

I see it on the scenario bundle page, but I was talking about the intro text for the model factsheets. I cant see it there even when refreshing.

**Comment by jh-RLI** [comment]
Sorry, you're right, I got them mixed up because I didn't realize we had agreed on the text. I will add it, it will be in the next release.

**Comment by jh-RLI** [comment]
> ![grafik](https://user-images.githubusercontent.com/38690039/281329562-0674f516-1a22-4bec-8cec-fa2d19bae113.png) For the database page, there is this header. I'd like to have a header on top of the description for the scenario bundles, too (or harmonised for all menu topics. Ontology has no header, either).

It will be added, but I'm not sure if it will be there by this release. Maybe @adelmemariani you could add this as bryan wasnt albe to do this?

**Comment by l-emele** [comment]
> The [model](https://openenergy-platform.org/ontology/oeo/OEO_00020353) [factsheets](https://openenergy-platform.org/ontology/oeo/OEO_00000162) characterise models used in energy system analysis in a structured way regarding important characteristics, such as their scope and [licence](https://openenergy-platform.org/ontology/oeo/OEO_00020015) and their developing [institutions](https://openenergy-platform.org/ontology/oeo/OEO_00000238).

Instead of linking to the separate classes [model](https://openenergy-platform.org/ontology/oeo/OEO_00020353) and [factsheets](https://openenergy-platform.org/ontology/oeo/OEO_00000162), I suggest to link to the class [model factsheet](http://openenergy-platform.org/ontology/oeo/OEO_00000277) instead.

**Comment by jh-RLI** [comment]
I added the intro text to the model factsheet page and also added the suggestion from @l-emele :
![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/70e05221-04f8-48a0-bd85-ac0eef78cbb7)
