### ISSUE TITLE
toep: scenario bundle overview does not load

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1462]
## Description of the issue

Yay, for the scenario bundle button and corrected link. 
When I click the button, the page leads now to: https://toep.iks.cs.ovgu.de/scenario-bundles/main
but it does not load (I am not logged in, but shouldn't need to be)
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/29da0348-6652-49b7-ba8d-5145e91842a6)

## Steps to Reproduce
1. Click scenario bundle button
2. wait
3.

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment
* Version used: NA
* Operating system: Windows 10
* Environment setup and (python) version: NA
* Browser: Firefox

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)
FYI @wingechr

**Comment by han-f** [comment]
It also does not load when I am logged in.

**Comment by jh-RLI** [comment]
on the TOEP we currently do not support the https:// URL please try this one http://toep.iks.cs.ovgu.de/scenario-bundles/main .

**Comment by han-f** [comment]
thanks this worked. will test.

**Comment by jh-RLI** [comment]
> thanks this worked. will test.

spoiler ... we already found some new bugs like it is not possible to update a scenario bundle currently.
