### ISSUE TITLE
Database: Changes in tables

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#147]
a) It is risky that users, that are not logged-in, get the impression that they could change the data or upload a csv file. They might undertake changes, that will not be stored, without noticing. Then all efforts will be lost. Therefore, please, disable the change function and the "csv upload button" for users that are not logged-in.

b) Make commit messages mandatory for changes in the data table AND the upload of new rows. Make that clear in the box where the user clicks "save". For the design see also #134. 

c) Changed data (being changes of the existing data in the existing rows and columns) are shown in the table ("Data (unchecked / unconfirmed)") underneath the "Data" table, when the checkbox "Show unchecked /unconfirmed rows" is ticked. In this case the first table also shows new, unconfirmed rows. That is also true for new tables that are not part of the latest release.
That it not very self-explaining. Therefore, I suggest the following:
Rename the check box: "Show also unconfirmed data". Write the following text next to it: "Please, find new, untested / unconfirmed rows in the data table and a list of changes suggested since the latest release in the table underneath."

d) Please, mark cells in the data view, for which changes have been suggested being not approved yet. It would be great to have a mouseover text field  “userxy proposed to change this field to yyzz”.

e) Please, also mark new, unconfirmed rows: "userxxx uploaded this row".

f) New tables: A lot of information are also displayed, when the unconfirmed data check box is not ticked. Can we a add a text like "no confirmed data available" underneath the column names? In this way we avoid that it looks incomplete or people assume an error.

**Comment by EvaWie** [comment]
Should we implement an edit mode, in which users can see the latest version (and the already suggested changes) and can make change.? In this way the difference between viewing the latest release and editing the data would become more obvious and the commit messages could refer to a series of changes.

**Comment by nesnoj** [comment]
Related:
Data (e.g. in supply schema) can be edited using the edit box even if you're not logged in. I guess this is not supposed to be allowed?

**Comment by MGlauer** [comment]
@nesnoj Those changes are not stored in the database, but just in the current display. If you reload the original data should be present again.

**Comment by nesnoj** [comment]
Confirmed.
But why does the box show up if it's not permitted to edit data?

**Comment by christian-rli** [comment]
'Hide „edit“ button when not allowed to edit.' - User Feedback and part of the requirement specification.

RequirementSpecificationID=47

**Comment by Bachibouzouk** [comment]
@MGlauer - can I take up this issue?

**Comment by christian-rli** [comment]
@Bachibouzouk feel free to take up all the issues that you think you can handle :)

**Comment by MGlauer** [comment]
There is no edit button

**Comment by christian-rli** [comment]
Is this still active? Uploads work with the new csv upload function. There is no edit button other than the one for the metadata. Therefore closing this issue. We should however consider reintroducing the functionality of editing in table.
