### ISSUE TITLE
Database: Table of changes

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#148]
A) Rename this table if you can: "Changes of the data suggested after the last release"

B) Bug: The table does not display all changes
6 changes, 3 are displayed. see http://193.175.187.164/dataedit/view/workshop/workshop_martinglauer

**Comment by christian-rli** [comment]
The Link that's supposed to show the incomplete changes, opens with "Request failed: parsererror".

**Comment by christian-rli** [comment]
Issue no longer relevant.
