### ISSUE TITLE
Database: manual changes in the data table are not stored in the database

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#149]
... even when one is locked in.

**Comment by EvaWie** [comment]
Is it correct, that one or more change(s) will be stored in the table of changes, only when a commit message is sent afterwards? In principal is that great, but the user needs to be informed and asked to write a commit message (see also #147).

**Comment by MGlauer** [comment]
The manual addition/update of values in the database does not seem to be a frequent use-case. Most tables contain large datasets that can not be maintained manually. All changes in those tables are done via the API anyway. Therefore, we dropped the manual data editing during the redesign.

**Comment by jh-RLI** [comment]
@Ludee @wingechr I just found out that manual editing of table fields has been discontinued in favor of existing api functionality. Now it's also clear why the feature is no longer available :)
