### ISSUE TITLE
Enhance ontology / oeo page

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1496]
## Description of the issue

The ontology/oeos page is not well structured and not user friendly as the buttons to download the publication files and other buttons to browse the oeos are grouped together. It is not explained where and how users can use and find these functions.

## Ideas of solution

Introduce section that guide the user better:

1. Download
2. View

Group the available buttons and add better icons/styles.

Figure out what content should be displayed and what not
- [ ] Should all modules be available? 
  - [x] Only to view them?
  - [ ] or also to download them?

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
@stap-m @l-emele 

I had some time last week to improve the ontology pages in the OEP. If we have time, we will install this update on the TOEP today and you can test it there. Finally, all modules and imports also reflect the descriptions that are available in the oeo files. I have also regrouped the buttons to make them easier to understand The page now looks like this:

![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/08518a06-14ea-4257-9174-bcb499154c42)

**Comment by stap-m** [comment]
@jh-RLI thanks for updating the page. It looks much better now. 
Anyway, I'd like to reopen the issue to further improve the site. This might need some more discussion with @l-emele @han-f @christian-rli and maybe others. My first thoughts are:

- I don't think it is necessary to offer the extracts of imported ontologies for download. If at all, we could mention, from which ontologies we import. In case, the list should be updated automatically with each release.
- For the modules, I think it may be sufficient to describe the main content-related modules: oeo-physical, oeo-model, oeo-social, oeo-sector. The other modules are useless without the rest and its existence is more of a internal oeo structuring question. We might link to the modules description of the oeo wiki.
- The "download the oeo" part should mention that the download from oep under the given link contains the latest version. Further, I'd like it to be conform to the OBO requirements, see https://github.com/OpenEnergyPlatform/ontology/issues/1790
- We might want to update the header text. It is kind of redundant with the module descriptions.
- Should we make the download of older versions explicit on the oep? The domains are there.

**Comment by jh-RLI** [comment]
I think it would be good to create a new issue as we reference these issues in the commits / Pull Requests and i dont want to blow single issues up more then necessary. But this is just a side node i like the idea of reworking it further as all what i did was the asolute bear minimun as things where not working properly like the description in modules and so on. 

I also have one more PR ready that will improve the loading time of the page a bit and visually marks editor notes apart from definition / description text. 



> I don't think it is necessary to offer the extracts of imported ontologies for download. If at all, we could mention, from which ontologies we import. In case, the list should be updated automatically with each release.

Thats true i overlooked the buttons and only removed the other module once. 

> The "download the oeo" part should mention that the download from oep under the given link contains the latest version. Further, I'd like it to be conform to the OBO requirements, see https://github.com/OpenEnergyPlatform/ontology/issues/1790

Good hint reagrding the OBO principles. I will add the version first. 

> We might want to update the header text. It is kind of redundant with the module descriptions.

Almost all of the text you see comes from the oeo release files. But of course we can also add text that was created specifically for this page. I think the idea was that we can theoretically list multiple ontologies and the pages will be populated from the ontology files. At least that's what the implementation suggests to me.  Not sure if we still plan to do something like this.

> Should we make the download of older versions explicit on the oep? The domains are there.

We could do this, currently we only store the latest version on the oep server.

**Comment by jh-RLI** [comment]
I updated the page so it only lists the "relevant" modules:

![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/ac42578f-5aa4-4816-b607-9d7b41514b8c)

**Comment by stap-m** [comment]
My suggestion is to merge the "Overview" page and the "Modules" page: 

- the overview page already contain descriptions. We could add a "modules" section there and only show the oeo-description text there (the specific module descriptions are kind of redundant to it). 
- Remove the "modules" page completely
- We could add a sentence like "The separate modules can be downloaded from github directly."
- Further, we should explain in a sentence there, what oeo-full-owl and oeo-closure are.

![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/38690039/075d9b8e-8bd0-46bb-97c2-4dc995c9611c)

What do you think @l-emele @han-f ?

**Comment by jh-RLI** [comment]
This is also related https://github.com/OpenEnergyPlatform/oeplatform/issues/1142

**Comment by stap-m** [comment]
We are being approached by users because of this page, see https://github.com/OpenEnergyPlatform/ontology/issues/1847 I think it is partially related to this issue. If it is not a time consuming issue, I'd be happy to fix this rather soon. We could also do it in a (bilateral) session together.
