### ISSUE TITLE
[SFS] The dark blue links on black background in tool tips

### ISSUE THREAD

**Issue by l-emele** [OpenEnergyPlatform/oeplatform#1510]
## Description of the issue

The tool tips of the OEKG fact sheets contain dark blue links on black background.
![grafik](https://user-images.githubusercontent.com/36884905/231712796-f121dec2-72d1-4dce-96c8-e23476d66eb9.png)

At first, I did not notice at all that there are links...

## Steps to Reproduce
1. Hover over the question mark icon and then the tool tip shows up

## Ideas of solution
Different link colour or tool tip background colour

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment
* Browser version used: Firefox 102.10.0esr (64-Bit)
* Operating system: Win 10
* Environment setup and (python) version: irrelevant

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
This is solved IMO:
![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/fa17d2f0-5114-46bc-9791-d0d3e3cd71bd)
