### ISSUE TITLE
[SFS] Show only sectors form selected sector division

### ISSUE THREAD

**Issue by u-mueller** [OpenEnergyPlatform/oeplatform#1524]
## Description of the issue

If you choose a predifined sector division, say KSG, then only KSG sectors should show up und field: "Which sectors are considered in the study?". This function has been before, but seems to have vanished.

## Steps to Reproduce
1. Choose predifined sector division
2. Check list of sectors
3.

## Ideas of solution

1) Only allow subclasses/individuals from predifined sector divisions
2) Only show the general sectors below, when non of the listed sector divisions is chosen (?):
- Agriculture, forestry and land use sector
- Energy demand sector
- Building sector
- Commercial sector
- Heating and cooling sector
- Household sector
- Transport sector
- Energy transformation sector
- Electricity sector
- Industry sector

## Context and Environment
* Version used: latest
* Operating system: Windows 10, Firefox 102.10.0esr, MS Edge Version 112.0.1722.48
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](CONTRIBUTING.md)

**Comment by stap-m** [comment]
This is similar to #1523, therfore I close this issue and comment in the other one respectively.
