### ISSUE TITLE
Tooltips for sectors, sector divisions and technologies to refer to the corresponding OEO classes

### ISSUE THREAD

**Issue by adelmemariani** [OpenEnergyPlatform/oeplatform#1525]
## Description of the issue

Currently, in the scenario bundles page, there is no information about the sectors, sector divisions, and technologies.

## Ideas of solution

A tooltip displaying the OEO definition and a link to the corresponding ontology page will assist the user in choosing sectors, sector divisions, and technologies.

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by stap-m** [comment]
> 2024/01/22 working meeting:
> 
> * make models and frameworks clickable and bring users to factsheets
> * sector divisions, sectors and technologies: tooltips including a link
> * EDIT by @stap-m : in the "scenario" tab: descriptors (should be relabelled as scenario descriptors) also should get tooltips

https://github.com/OpenEnergyPlatform/oeplatform/issues/1537#issuecomment-1903639170
