### ISSUE TITLE
Scenario bundles: make models and frameworks clickable

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1537]
## Description of the issue

Not sure whether there may be a related issue, did not find one. I think it would be super if the model and framework information provided in a scenario bundle would also be clickable as the info on input and output data already is. 

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

fiy @stap-m @l-emele @wingechr

**Comment by han-f** [comment]
The same would be great for sectors and technologies, but here I would suggest to link to the corresponding class/individual in the textual oeo-viewer, so users can learn more about the definitions.

what do you think @l-emele @stap-m  -> should we create a separate issue for this?

**Comment by stap-m** [comment]
> The same would be great for sectors and technologies, but here I would suggest to link to the corresponding class/individual in the textual oeo-viewer, so users can learn more about the definitions.
> 
> what do you think @l-emele @stap-m -> should we create a separate issue for this?

@han-f  There is this issue: https://github.com/OpenEnergyPlatform/oeplatform/issues/1525 Is this what you mean?

**Comment by han-f** [comment]
yes, this seems related. But I cannot click descripors for sectors and technologies, while I can for input and output data that also appear like a "button"
Sectors and technologies: 
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/b7651714-a9f8-4368-b4ce-29b50705633e)

**Comment by han-f** [comment]
2024/01/22 working meeting: 

- make models and frameworks clickable and bring users to factsheets  
- sector divisions, sectors and technologies: tooltips including a link

**Comment by jh-RLI** [comment]
This is also somewhat related to this issue https://github.com/OpenEnergyPlatform/oeplatform/issues/1545
