### ISSUE TITLE
Scenario Bundles: Display scenario years in ascending order

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/oeplatform#1538]
## Description of the issue

Scenario years are not displayed in ascending order. 
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/54852694/82c7fff1-0848-4bf6-9ba1-2e5e74db39e5)

## Ideas of solution

It would be great to sort them in ascending order.

Solution could be similar to the alphabetical sorting here https://github.com/OpenEnergyPlatform/oeplatform/issues/1423

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Yes we should introduce ascending order.
