### ISSUE TITLE
Scenario Bundles: DOI seems to be repeated

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/oeplatform#1539]
## Description of the issue

When inserting a DOI in the publications it seems to be repeated.
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/54852694/a8ae5354-61ce-4e8b-925c-14b6797cafbd)

## Steps to Reproduce
1. insert DOI in field 
2. save

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Good catch! Seems like no one ever used the DOI :)
