### ISSUE TITLE
revisits tooltips for 1st column of scenario tab

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/oeplatform#1543]
## Description of the issue
In the scenario section, some of the names and tooltips of the first coulumns are unintuitive or unfitting. E.g. "name" links to "study".
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/38690039/bf289b1b-101e-4f21-853b-1dbc771d0790)

## Ideas of solution

- Name
    - relabel "Scenario name"
    - tooltip to "scenario" [OEO_00000364](http://openenergy-platform.org/ontology/oeo/OEO_00000364)
- Descriptors
    - relabel "Scenario descriptors"
    - tooltip to "data descriptor" [OEO_00000119](http://openenergy-platform.org/ontology/oeo/OEO_00000119) --> maybe there is a better idea??

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by l-emele** [comment]
> Descriptors
> 
>     * relabel "Scenario descriptors"
> 
>     * tooltip to "data descriptor" [OEO_00000119](http://openenergy-platform.org/ontology/oeo/OEO_00000119) --> maybe there is a better idea??

Sorry, I saw this issue too late. "data descriptor" is in my view wrong here. You select here one or more scenario types a.k.a. subclasses. So I suggest "scenario type" as label instead.

**Comment by stap-m** [comment]
Ok, "scenario type" as label sounds good to me. 
What about the tooltip instead of "data descriptor" @l-emele ?

**Comment by jh-RLI** [comment]
I added the name "Scenario type" and added the tooltip from OEO_00000364 (like it was before).
