### ISSUE TITLE
Scenario Bundle: Filter option on overview page results in error

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1544]
## Description of the issue

![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/1e6f6189-1e87-449f-ad6b-d9a7b7e7f250)
## Steps to Reproduce
1. Scenario Bundles -> Overview aka main page
2. Open Filter dialog
3. Submit

## Ideas of solution

??? Possibly related to permissions

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by adelmemariani** [comment]
The error was related to CSRFToken. I added the following to the API call.

`{
        headers: { 'X-CSRFToken': CSRFToken() }
      }`
