### ISSUE TITLE
toep: scenario bundles do not load 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1558]
## Description of the issue
scenario bundles do not load neither when not logged in nor when logged in

## Steps to Reproduce
1. open: https://toep.iks.cs.ovgu.de/scenario-bundles/main
2.
3.

## Context and Environment
* Version used: Firefox 115.6.0esr
* Operating system: Windows 10
* Environment setup and (python) version: NA

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)
FYI: @wingechr

**Comment by jh-RLI** [comment]
Please use the `http `url instead of `https `for toep

http://toep.iks.cs.ovgu.de/scenario-bundles/main
