### ISSUE TITLE
Scenario bundles: Access denied error for edit mode in create new

### ISSUE THREAD

**Issue by adelmemariani** [OpenEnergyPlatform/oeplatform#1576]
When we use the "create new" button to make a new bundle, we are in edit mode, but if we click the view button, we can not go back to the edit mode again. An error with "Access denied! You cannot edit scenario bundles that you do not own!" message  prevents editing the new un-saved bundle 

## Solution

Disable the save and edit button until the bundle is saved!

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
I noticed that too, thanks for pointing it out. This is because there is no entry in the database because the scenario bundle has not yet been created. We need a different status that indicates that the current scenario bundle is being created and avoids the access rights check.

**Comment by adelmemariani** [comment]
fixed!
