### ISSUE TITLE
Licences

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#158]
Workshop Feedback:
Let's explain in the openmod wiki, how dataset licenses can / should be handled.

Do we need to do more?

**Comment by EvaWie** [comment]
Do we want to provide an extendable list of licenses (Drop-down menu)?

**Comment by Ludee** [comment]
Here is a nice overview of some licenses:
http://licenses.opendefinition.org/

**Comment by Ludee** [comment]
Make a collection of the relevant open data licenses in the OEDB.

**Comment by christian-rli** [comment]
@Ludee : also see this related issue: https://github.com/OpenEnergyPlatform/tutorial/issues/87

**Comment by christian-rli** [comment]
This was closed with OpenEnergyPlatform/tutorial#87
