### ISSUE TITLE
Do not allow the user to edit oekg entries for now (like scenario year ...)

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1582]
## Description of the issue

The function for editing entries from the oekg is not yet stable. Every registered user can edit oekg entries such as "Scenario year" or "Author" and possibly also change other scenario bundles.

## Steps to Reproduce
1. Open two scneario bundles
2. Add a scneario/scenario year like "3000" for testing to both
3. Modify the entry on one of the bundles
4. Bot bundles now contain the modified entry

## Ideas of solution

 Until we implemented a more robust solution this feature sould not be available. 

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by adelmemariani** [comment]
I disabled all entity edits: #1599
