### ISSUE TITLE
Either an error in the API or in some tables: The "geom" field is null when the table is queried via the http api

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1584]
## Description of the issue

This behavior was observed on one table (user reported):

https://openenergy-platform.org/dataedit/view/grid/ego_grid_ding0_line

-> api
https://openenergy-platform.org/api/v0/schema/grid/tables/ego_grid_ding0_line/rows

## Steps to Reproduce
1. Open the tables [api/rows page ](https://openenergy-platform.org/api/v0/schema/grid/tables/ego_grid_ding0_line/rows)
2. Search for "geom"
3. Everything is null

## Ideas of solution

As other tables that include a "geom" field don't show this behavior, this error might not be related to the api. We need to find the reason first to be able to find a solution.

Other table:
https://openenergy-platform.org/dataedit/view/grid/bnetza_vorhaben_enlag

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by wingechr** [comment]
Actually not a bug.

The table ego_grid_ding0_line is just really big (i tried to download it completely but stopped after 5 minutes) and for some reason known only to postgres, it starts returning rows with empty geom.

you can check that there are rows with by using filters or selecting specific rows:

* https://openenergy-platform.org/api/v0/schema/grid/tables/ego_grid_ding0_line/rows/?where=geom!=null
* https://openenergy-platform.org/api/v0/schema/grid/tables/ego_grid_ding0_line/rows/1

vice versa, you can select the ids that have no geometry in the web interface filter and show that they indeed have no geom:

![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/4265368/5f74d981-ac04-46d3-b881-77a6fd274f12)
