### ISSUE TITLE
Loading of the ontology page takes too long

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#1585]
## Description of the issue

Loading of the ontology [page](https://openenergy-platform.org/ontology/oeo/) takes more than a minute. This is quite a bad first impression for first-time users and will likely drive them away.

## Steps to Reproduce
1. Visit https://openenergy-platform.org/ontology/oeo/ with an empty cache
2. Wait

## Ideas of solution

I do not know what is taking so long. Once loaded, the page shows an overview of the modules. The slowdown seems to not occur on the client-side (I stopped the JS execution and the loading finished immediately upon resuming), but on the server side. So, I guess the server is loading something from somewhere that is just cached on the client-side, but not on the server side. As the request does not have any parameters, it is not immediately apparent, why this is necessary.

## Context and Environment
* Version used: The one in production at the moment of writing this issue
* Operating system: Firefox Version 119.0 
* Environment setup and (python) version: Does not apply

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
I assume we can enhance this by using the cpython implementation of the owl parser. I assume python is just slow. We will try this soon. 

`* Owlready2 * Warning: optimized Cython parser module 'owlready2_optimized' is not available, defaulting to slower Python implementation`
