### ISSUE TITLE
Scenario bundles: a never-ending progress loop, when creating a bundle if the use is not logged in

### ISSUE THREAD

**Issue by adelmemariani** [OpenEnergyPlatform/oeplatform#1586]
Currently, if the user is not logged in, a never-ending progress appears when the save button is clicked.

## Ideas of solution
Disable the "create new" button if the user is not logged in. Guide the user to the login page.

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Fixed. We still shoud prevent users from opening the "Create New" page completely.
