### ISSUE TITLE
Scenario bundles: blank page when clicking on scenario tab, if the user is not logged in

### ISSUE THREAD

**Issue by adelmemariani** [OpenEnergyPlatform/oeplatform#1587]
When creating a new scenario bundle, if the user is not logged in, clicking the scenario tab leads to a black page which is confusing in the absence of any error message. Scenario tab is prevented because the user is not logged in.
## Ideas of solution

Disable the "create new" button if the user is not logged in. Guide the user to the login page.

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Hm, the title of the problem suggests a different issue than the description. Can you be more specific about what you mean? I don't see the behaviour described in the title, but I see what you describe in the description :)

**Comment by jh-RLI** [comment]
Duplicated with  https://github.com/OpenEnergyPlatform/oeplatform/issues/1586 ?

**Comment by adelmemariani** [comment]
You are right, I changed the description. Thank you for mentioning it.

**Comment by jh-RLI** [comment]
We should disable the "Create new" button if the user is not logged in. I just tried to do that, but it's a bit more effort than expected - I won't do that now. But as soon as the non-logged in user tries to create a bundle, he/she will be redirected to the login page.

**Comment by adelmemariani** [comment]
I did it with a tooltip for now. 

![Screenshot 2024-02-19 at 10 50 52](https://github.com/OpenEnergyPlatform/oeplatform/assets/7637364/aa82e1dd-77ac-4c97-8004-9084c991c2be)

**Comment by jh-RLI** [comment]
I implemented a redirect in the save factsheet button. Maybe I can move this functionality to the create new button.
