### ISSUE TITLE
Implement 'Coming Soon' Page for NFDI4Energy

### ISSUE THREAD

**Issue by SMutyala18** [OpenEnergyPlatform/oeplatform#1591]
## Description of the issue

Implementing "Coming Soon" page for NFDI4Energy along with the addition of the logo to the Partners section.

## Ideas of solution

1. **Logo Integration:**
   - Add the NFDI4Energy logo to the Partners section on the homepage.

2. **Coming Soon Page:**
   - Implement a "Coming Soon" page that visitors are redirected to when clicking on the NFDI4Energy logo in the Partners section.

**In the [organization](https://github.com/OpenEnergyPlatform/organisation):**

This issue is related to a corresponding NFDI4Energy Introduction in compendium page. For more details, please refer to [Add NFDI4Energy to Compendium #87](https://github.com/OpenEnergyPlatform/organisation/issues/87) in the organization repository.

---

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by SMutyala18** [comment]
@jh-RLI, could you please approve this request? Thank you.

**Comment by jh-RLI** [comment]
Hi @SMutyala18, this looks good :). I am glad that we are slowly starting to include the NFDI in the OEP.
