### ISSUE TITLE
Database: Tag tables

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#160]
Tag information are not part of the json string.
(How) can I tag tables using the API / SQLAlchemy?

**Comment by Ludee** [comment]
One discussed idea is to add the tags to the metadata string.
This will be added to the metadata development for v.1.4

**Comment by christian-rli** [comment]
Version 1.4 of the string includes a „keyword“ element. We need to discuss if this should be used to attach labels in oep or whether a special oep-key should be used. In any case parsing of the string to create labels in OEP will need to be implemented.

**Comment by Bachibouzouk** [comment]
@christian-rli - any updates?

**Comment by christian-rli** [comment]
We didn't discuss this again, but I recall that keyword should indeed be used to assign labels (tell me if I'm wrong @Ludee ). It makes sense in any case. Labels can be added manually via the website as well. I don't think there are functions to synchronize the two though. I would keep this issue open until that's the case, but it did not make it to the requirement_specification, so unless it's very easy to implement, it's pretty low priority.

**Comment by jh-RLI** [comment]
As @christian-rli mentioned tags are represented as keywords in the OEMetadata JSON string. The metadata can be added via the API to the table. If the user appends metadata to a table using the API the keywords are not automatically added as tags. The tags from the metadata keywords will be added as soon as the user is adding any tag via the OEP website. It might be worth updating the API function to automatically set the tags as soon as the  metadata is added to the Table.

**Comment by jh-RLI** [comment]
I will close this issue since a basic functionality is given. Further issues can be added as new issues.
