### ISSUE TITLE
Missing help for Metadata web inferface

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#161]
Please, add small (blue ) question marks, which provide info texts, next to the input boxes,

**Comment by EdithaK** [comment]
@ludde define the info text, pls

**Comment by christian-rli** [comment]
Before closing this issue, make sure https://github.com/OpenEnergyPlatform/oeplatform/issues/298 and https://github.com/OpenEnergyPlatform/oeplatform/issues/168 are also resolved.

RequirementSpecificationID=29

**Comment by MGlauer** [comment]
After our metadata tool is ready:
@MGlauer Implement help_text -> field mapping
@klarareder Use mapping to add help text, display help texts in dataview

**Comment by Bachibouzouk** [comment]
> After our metadata tool is ready

@MGlauer - is there a PR / branch linked to this metadata tool?

**Comment by christian-rli** [comment]
> @MGlauer - is there a PR / branch linked to this metadata tool?

The tool is called omi and developed in separate repository: https://github.com/OpenEnergyPlatform/omi

**Comment by Bachibouzouk** [comment]
@EvaWie 

Do you mean next to the left-handside labels (like Title, Description, etc.) ?
![Metadaten](https://user-images.githubusercontent.com/4399407/63859623-02318800-c9a8-11e9-9096-6c8e09112b18.png)

To reach this view one has to [choose a schema](https://openenergy-platform.org/dataedit/schemas), then choose a dataset, then scroll down the page and click on Edit, under the Metadata blue title

**Comment by Bachibouzouk** [comment]
> The tool is called omi and developed in separate repository: https://github.com/OpenEnergyPlatform/omi

References across repositories are possible :)

**Comment by klarareder** [comment]
This is part of the new metadata editor

**Comment by wingechr** [comment]
implemented in [feature/new_meta_editor](https://github.com/OpenEnergyPlatform/oeplatform/tree/feature/new_meta_editor) using "description" from meta data schema
