### ISSUE TITLE
Scenario Bundles: Publication date should allow for year only 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1615]
## Description of the issue

The publication date currently requires month, day and year information. Some publications only have a year (or year and month) publication listed, see for example: https://www.umweltbundesamt.de/sites/default/files/medien/11850/publikationen/39_2023_cc_projektionsbericht_12_23.pdf

It does feel uncomfortable to add more detailed information than available. 

If I only add the year but no month and day for example, the date shows up as:
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/f32bde1a-1f5e-44b0-adda-a07ea0c620d1)

## Ideas of solution

Also allow for less detailed dates of publication 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

cc @wingechr @l-emele @stap-m

**Comment by l-emele** [comment]
I am fine with having only the publication year.

**Comment by han-f** [comment]
I also think this is sufficient

**Comment by jh-RLI** [comment]
#1723 implements the selection of only the year as the publication date.
