### ISSUE TITLE
OfflineGenerationError after starting docker image

### ISSUE THREAD

**Issue by ebroda** [OpenEnergyPlatform/oeplatform#1626]
## Description of the issue
As I build the docker image myself and started it, I get a Django error.

```
OfflineGenerationError at /

You have offline compression enabled but key "788ef1...4ed" is missing from offline manifest. You may need to run "python manage.py compress". Here is the original content:
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/jquery-ui.min.css"><!-- //cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.css -->
    <link rel="stylesheet" type="text/css" href="/static/css/base-style.css?md5=d4e024ac45daad057d0191a8f6266156">
```
## Steps to Reproduce
1. Create docker image
2. docker-compose up
3. Visit localhost:8080 in Browser

## Fix
```bash
$ sudo docker ps --format '{{.Names}}'
docker-oep_oeplatform_1
docker-oep_postgres_1
$ sudo docker exec -ti docker-oep_oeplatform_1 bash
root@ba4bea24f8b9:/app# python manage.py compress
Compressing... done
Compressed 10 block(s) from 131 template(s) for 1 context(s).
root@ba4bea24f8b9:/app# 
```
Restart docker-container (probably only the Django would be enough, but I don't know how)
Then it works.

## Ideas of solution
Include python mange.py compress in docker-entrypoint.sh.

## Context and Environment
* Version used: develop
* Operating system: Docker
* Environment setup and (python) version: 

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by ebroda** [comment]
As I'm not part of the repo, I can't ask for Review (step 9). So please have a look :wink: 
https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md?plain=1#L42

**Comment by jh-RLI** [comment]
Very good tip, didn't realise this wasn't possible via the GitHub UI. Posting a comment like you did is also a good option :)
