### ISSUE TITLE
Wrong api docs link on homepage

### ISSUE THREAD

**Issue by ebroda** [OpenEnergyPlatform/oeplatform#1628]
## Description of the issue
When I visit https://openenergy-platform.org/  
And I click on "Learn more" below API  
I get a "404 - Not found"  
But expect to see the API docs.

These are the links:
```
https://openenergyplatform.github.io/academy/tutorials/01_api/01_api_download/
https://openenergyplatform.github.io/academy/tutorials/01%20API/01_api_download/
```

Second one is the right one; even though the first one looks better (with _ instead space in url)

Changes have been introduced in https://github.com/OpenEnergyPlatform/academy/commit/878d30048a4728cf7365ce0bac875be498c215f9

## Steps to Reproduce
see above

## Ideas of solution
a) Update link
For now probably the easiest solution, as it also doesn't break other links and there probably have been discussions about changing the dir name.

b) Rollback uris
This will be in OpenEnergyPlatform/academy; dir is here 
https://github.com/OpenEnergyPlatform/academy/tree/production/docs/tutorials/01%20API

## Context and Environment
* Version used: current
* Operating system:  -
* Environment setup and (python) version:  -

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
@wingechr we've already talked about this. But I haven't yet questioned why you actually removed the "_" from the url? I also think it looks better when it's gone. I also think this could potentially break the links for some tutorial lists we've sent out in the past.

**Comment by wingechr** [comment]
I (hope I ) just fixed this.

I originally changed it because the underscores in the subfolders did not look nice on the page navigation.

I found a better solution to rename it in the `mkdocs.yml` and changed the paths back to the old ones.

**Comment by ebroda** [comment]
For me then this one could be closed, as the base issue is resolved?

**Comment by jh-RLI** [comment]
Great, works again.
