### ISSUE TITLE
Data view: Searching and Filtering

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#163]
Is the search and the filter working for unconfirmed data?

**Comment by EdithaK** [comment]
@pkassing : I dont realy know what Eva wants. I cant ask her because she is not in the project any more. Could you test the filter function in the database (http://oep.iks.cs.ovgu.de/dataedit/schemas) at several datasets, please? Close the ticket if you can not find any problems.

**Comment by MGlauer** [comment]
I talked to her. The question was the following: Will you be able to search for specific data entries inside the database and will the unverified data be included in this search. 
**Answer:** No. There is no feasible way to search inside of datasets as big as the oedb (several TB). There are approaches to implement something similar (e.g. datatype-sensitive splay trees) - but this is out of scope for open_eGo.

I will leave the ticket open, as this may be future work.

**Comment by EdithaK** [comment]
@MGlauer Thank you. 
@pkassing No testing required anymore.

**Comment by christian-rli** [comment]
See also #117

**Comment by christian-rli** [comment]
"As a user I want to filter data in order to find them." - user feedback 
Implement filter functions for Data view.

**Comment by christian-rli** [comment]
RequirementSpecificationID=11

**Comment by MGlauer** [comment]
@christian-rli Could you specify the difference between this issue and #321 ?

**Comment by christian-rli** [comment]
#321 originally asked for a filter across **all** data, which we deemed unfeasible and decided that (at least for the time being) filtering by _tags_ are the only filters that allow searching across data sets. 

This issue concerns filtering data in the data view of single tables.

**Comment by MGlauer** [comment]
There are functionalities for custom filters for every table
