### ISSUE TITLE
Display python access example not as one liner

### ISSUE THREAD

**Issue by ebroda** [OpenEnergyPlatform/oeplatform#1646]
## Description of the issue
Currently the Python example for using the data is shown as a one liner, even though the source has line breaks.

![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/5451330/61dc0bdb-607c-41cd-b351-8f15ba5aaeee)

Or is this wanted? Else you should consider decrease the amount of rows.

If you want to have everything marked at one, consider include [onclick="this.select()"](https://stackoverflow.com/a/7313795)

## Steps to Reproduce
1. Open any database item, e.g. https://openenergy-platform.org/dataedit/view/boundaries/bkg_gn250_b

## Ideas of solution
Increase rows by one, remove white-space: nowrap;

Consider removing also resize: none; cause if necessary people should be able to increase the field size

see code in referenced commit. If you agree, you might directly merge or I'll create a pull request out of it.

## Context and Environment
* Version used: current online one
* Operating system: -
* Environment setup and (python) version: -

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Good idea. We are currently in the process of implementing an updated sidebar for the detail page of the tables. 

it will look similar to this mockup:
![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/516a5035-ae18-486c-9ec7-dae02f261e82)

As you can see, we will hide this field by default and I also assume @bmlancien will update the associated styles and possibly avoid the inline CSS. We haven't really talked about how the code in the api window should look when "view" is clicked, so your comment here is perfect timing.

**Comment by jh-RLI** [comment]
This is now implemented in develop branch, expect for the URL part. 
![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/04e35a68-13ce-44d6-acf2-89cdf79590e7)

**Comment by ebroda** [comment]
> This is now implemented in develop branch, expect for the URL part.
While it looks basically nice, the code is still wrong on Firefox for me:
![grafik](https://github.com/user-attachments/assets/41526fd8-5142-4fa4-9bca-40f700b5ef67)

As possible fix could be changing 

```
.table-sidebar__collapse textarea {
	white-space: nowrap;
}
```

to
```
	white-space: pre;
```.
