### ISSUE TITLE
Show/hide topics sidebar

### ISSUE THREAD

**Issue by bmlancien** [OpenEnergyPlatform/oeplatform#1681]
## Description of the issue

There should be an option for the topics view sidebar to be shown/hidden in order to expand the table width to 100% so that users can see more content from the table without scrolling.

## Ideas of solution

![sidebar_1](https://github.com/OpenEnergyPlatform/oeplatform/assets/33999424/311955c9-6cea-4ec2-aefd-6bf22748202e)
![sidebar_1 (1)](https://github.com/OpenEnergyPlatform/oeplatform/assets/33999424/a3390a35-169d-4200-a422-4bd687bd358b)

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
@l-emele @han-f @stap-m @christian-rli @wingechr @adelmemariani 
Above is the mockup of how we plan to implement the collabsable sidebar on the dataview page for each table. 

Currently there is still the open peer review button visible, it will most likely be moved to the "Open Peer Review" tab. The Scenario Bundle field is new and links to the bundle (by id) that lists this table as output or input dataset in any of the included scenario factsheets. The tags are harmonized in color. .... and a few other updates from our discussions during the last project meeting.

Most of this has already been implemented in several pull requests, which means that it is likely to be included in the next release (planned for the first half of June).

**Comment by stap-m** [comment]
I like it. 
What happens to the bundle field, if there is no bundle related? Is it invisible or is there a button which allows a link, or something else?
