### ISSUE TITLE
[Factsheets] Export Functionality

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#169]
Can offer a csv export of the fact sheet structure (meaning the question) so that the users can prepare the answer offline or use the structure for other use cases?

Can we offer the download of fact sheets (PDF)?

**Comment by stap-m** [comment]
Is this still a requirement? I add this issue to [project 25](https://github.com/orgs/OpenEnergyPlatform/projects/25)

**Comment by stap-m** [comment]
discussed in SIROP project meeting to close issue
