### ISSUE TITLE
OEO pages not found 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1692]
## Description of the issue
I receive some 503  errors on oeo related pages on the OEP.
Due to the maintenance?

## Steps to Reproduce

1. Visit: https://openenergyplatform.org/ontology/
2. Visit: https://openenergyplatform.org/viewer/oeo/
3. Visit https://openenergyplatform.org/ontology/oeo/

## Ideas of solution

???

## Context and Environment

- Version used:
- Operating system:
- Environment setup and (python) version:

## Workflow checklist

- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

fyi @stap-m @wingechr @l-emele

**Comment by han-f** [comment]
Also the bundles do not load: 
https://openenergyplatform.org/scenario-bundles/main

**Comment by jh-RLI** [comment]
At the moment the Oep is down ... I'm waiting for someone with more permissions to restart the server.

There is an unexpected error.

**Comment by jh-RLI** [comment]
The server restart fixed this for now. I will monitor if this happens again.
