### ISSUE TITLE
Unnecessary Login requirement for OEMetaBuilder

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#1693]
## Description of the issue

The [OEMetaBuilder page](https://openenergyplatform.org/dataedit/oemetabuilder/) requires users to be logged in to the OEP.  This is unnecessary. Simply remove the login requirement for the current metadata creation site.

Also see https://github.com/OpenEnergyPlatform/omi/issues/99

**Comment by jh-RLI** [comment]
This is now fixed.
