### ISSUE TITLE
Suggestions for improved text: Ontology overview page

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1707]
## Description of the issue
https://openenergyplatform.org/ontology/
The text could be improved for readability. 
Below are some suggestions, derived with chatgpt with further editing by me.
I could do this from a users perspective for any page on the oep that has a certain amount of floating text. 

## Ideas of solution

The Open Energy Ontology (OEO) is a dynamic domain ontology for energy system modeling, updated regularly following a to a release cycle. Access the latest version 2.3.0 [here](https://openenergyplatform.org/ontology/oeo/).

An ontology is a structured collection of terms and their relationships, providing clear definitions and logical interpretation. The OEO aims to create a common language for energy system modeling, bridging various disciplines.

**Ontologies have diverse applications:**

- Standardising Terminology: Provides a controlled vocabulary with clear definitions, disambiguating terms.
- Data Annotation and Integration: Enhances data integration, aggregation, and search functions
- Templates for Data Capture: Ensures uniform and detailed reporting structures
- Visualisation: Makes complex knowledge comprehensible through various visual formats
- Text and Data Mining: Automates searches across resources, aiding discovery, data synthesis, and meta-analysis.

The OEO is developed within the scope of the Open Energy Family, but aims to serve the entire energy system modeling community. We encourage its use in various contexts and use cases beyond its initial scope.

**Where and how can I contribute?**

We welcome everyone to contribute to OEO development, a community-driven project hosted on GitHub. Explore our [guidelines](https://github.com/OpenEnergyPlatform/ontology/blob/dev/CONTRIBUTING.md) and [wiki](https://github.com/OpenEnergyPlatform/ontology/wiki) for detailed instructions. If you have questions, reach out via the OEP [contact form](https://openenergyplatform.org/contact/), and we’ll connect you with the right person.

**Further information**

OEO development began with the "SzenarienDB" project and is enhanced by "LOD_GEOSS" and "SIROP". The OEO was introduced in an open access peer-reviewed paper: [Introducing the Open Energy Ontology: Enhancing data interpretation and interfacing in energy systems analysis](https://doi.org/10.1016/j.egyai.2021.100074). 

The [OEO steering committee](https://openenergyplatform.org/ontology/oeo-steering-committee/) was established in autumn 2019.

## Workflow checklist

- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
There is also a related issue https://github.com/OpenEnergyPlatform/oeplatform/issues/1496. 

This issue here is not duplicated, but offers a great ‘concrete’ suggestion on how to improve the oeo pages content.

Especially this https://github.com/OpenEnergyPlatform/oeplatform/issues/1496#issuecomment-1916338211 is related here because it would be good to combine the overview and module pages.
-> Further, we should explain in a sentence there, what oeo-full-owl and oeo-closure are.

**Comment by jh-RLI** [comment]
In general, I think it's a good idea to do this moderation work for any site with a lot of text. 

A bit offtopic, but related: I would also suggest that we add a few bullet points to the front page of the OEP. There we should explain the main features/services we offer https://github.com/OpenEnergyPlatform/oeplatform/issues/1708

**Comment by stap-m** [comment]
TODO: Add oeox to overview page, too. I'll provide a short description here...

**Comment by stap-m** [comment]
> **Where and how can I contribute?**
> 
> We welcome everyone to contribute to OEO development, a community-driven project hosted on GitHub. Explore our [guidelines](https://github.com/OpenEnergyPlatform/ontology/blob/dev/CONTRIBUTING.md) and [wiki](https://github.com/OpenEnergyPlatform/ontology/wiki) for detailed instructions. If you have questions, reach out via the OEP [contact form](https://openenergyplatform.org/contact/), and we’ll connect you with the right person.

About this part, I think we should first link to the [ontology course](https://openenergyplatform.github.io/academy/courses/05_ontology/) on OEA and then to the "guidelines", not the wiki. The wiki and the contributing file are also linked in the course.

**Comment by stap-m** [comment]
> **Further information**
> 
> OEO development began with the "SzenarienDB" project and is enhanced by "LOD_GEOSS" and "SIROP". The OEO was introduced in an open access peer-reviewed paper: [Introducing the Open Energy Ontology: Enhancing data interpretation and interfacing in energy systems analysis](https://doi.org/10.1016/j.egyai.2021.100074).

The projects SEDOS and Stadt-Land-Energie should also be mentioned.

**Comment by jh-RLI** [comment]
Do you happen to have links to the project pages?

> > **Further information**
> > OEO development began with the "SzenarienDB" project and is enhanced by "LOD_GEOSS" and "SIROP". The OEO was introduced in an open access peer-reviewed paper: [Introducing the Open Energy Ontology: Enhancing data interpretation and interfacing in energy systems analysis](https://doi.org/10.1016/j.egyai.2021.100074).
> 
> The projects SEDOS and Stadt-Land-Energie should also be mentioned.

**Comment by jh-RLI** [comment]
We might have links on the RLI´s website.

**Comment by stap-m** [comment]
> TODO: Add oeox to overview page, too. I'll provide a short description here...

**OEO Extended (OEOX)**
To increase the usability of OEO and react to user requirements, we introduced a post-coordination extension to
OEO, the Open Energy Ontology Extended (OEOX). We created OEOX as an ontology for specific energy-
related terms with a high complexity that go beyond the level of detail of the standard OEO class hierarchy.

_Once the JOWO paper is finally published, we should cite it here._

**Comment by jh-RLI** [comment]
This is how it currently looks. I will now add the glossary also and try to add the oeox in the sidebar ontology list. 

![image](https://github.com/user-attachments/assets/939d58ff-4e09-461f-b959-2af15198edd6)

**Comment by stap-m** [comment]
> This is how it currently looks. I will now add the glossary also and try to add the oeox in the sidebar ontology list.

Looks good already, thanks! Please consider my comment on the **Where and how can I contribute?** section.



> URLs:
> `http://127.0.0.1:8000/ontology/oeo/`
> or `http://127.0.0.1:8000/ontology/oeo/releases/oeo-full.owl` to get this file.

The URLs should be updated to `https://openenergyplatform.org/ontology/......` 😄

**Comment by jh-RLI** [comment]
:D sure i have update it ... I think soon i can put this on the TOEP.

**Comment by jh-RLI** [comment]
regaridng the Where and how can I contribute? it reads now:

![image](https://github.com/user-attachments/assets/7dead642-4289-47da-a5db-68f497fcc2f1)

We welcome everyone to contribute to OEO development, a community-driven project hosted on [GitHub](https://github.com/OpenEnergyPlatform/ontology). Explore our [ontology course](https://openenergyplatform.github.io/academy/courses/05_ontology/) and have a look at our [contribution guidelines](https://github.com/OpenEnergyPlatform/ontology/blob/dev/CONTRIBUTING.md) If you have questions, reach out via the OEP [contact form](https://openenergyplatform.org/contact/), and we'll connect you with the right person.

**Comment by stap-m** [comment]
Perfect!
