### ISSUE TITLE
Suggestions for improved text: About page

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1715]
## Description of the issue

https://openenergyplatform.org/about/
The text could be improved for readability.
Below are some suggestions, derived with chatgpt with further editing by me.

## Ideas of solution

**General Introduction**

The Open Energy Family promotes quality, transparency, and reproducibility in energy system research through a [collection of tools](https://github.com/OpenEnergyPlatform/organisation), all developed openly. The primary module, the Open Energy Platform (OEP), offers a web interface for accessing various tools and the community database, allowing users to publish data with proper documentation.

To address the recurring issue of varying names and data(base) formats, the [Open Energy Ontology (OEO)](https://openenergy-platform.org/ontology) was developed. This ontology offers a controlled vocabulary with clear definitions of terms and the relationships between them. By annotating data with the OEO, enhanced search functions and logical queries across data sets are possible.

**What? Energy System Modelling and Data**

The platform provides openly licensed data relevant to climate and energy research, including scenario projection data, qualitative information about scenarios, and information about the models used to calculate projection data based on scenarios. 

**How? Open Science**

The OEP adheres to [Open Science principles](https://en.wikipedia.org/wiki/Open_science) by offering an open research data infrastructure for climate and energy system research, emphasising the publishing of data and information under open licenses. The platform uses an extensive metadata set - [OEMetadata](https://github.com/OpenEnergyPlatform/oemetadata)- to adhere to the [FAIR principles](https://www.go-fair.org/fair-principles/):  the findability, accessibility, interoperability, and reuse of digital assets.

**Who? OEP-Community**

The Open Energy Family is a collaborative project involving various universities and institutes, with all source code available on [GitHub](https://github.com/OpenEnergyPlatform/). The project encourages community involvement and contributions.

## Workflow checklist

- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Perhaps we should mention the scenario bundles or the practice of bundling information and making it openly available. I also think a link to the compendium would make a lot of sense here. The compendium is the complete description of the Open Energy family. The link to the "collection of tools" in the first paragraph could point to several pages in the compendium. Perhaps we could link to the introduction page to the architecture https://openenergyplatform.github.io/organisation/family_members/software-architecture/

I will add the suggestion to the page already, we can update it again any time.

**Comment by jh-RLI** [comment]
Do we already agree on the updated text?
