### ISSUE TITLE
On comparison page, only the scenario descriptors are visible

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#1719]
And another one: 
In the bundles there are two kinds of descriptors, i.e. for studies and for sceanrios.
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/38690039/c3481143-6e53-4ecc-8207-e3630440bb0f)
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/38690039/fc0b739f-8c58-46c4-aac4-e5cb4ab36d5c)

In the comparison, only the scenario descriptors seem to be a selectable criteria, but I think both should be shown. However, I am not sure if we should distinguish between them or just show them all as descriptors. @han-f any opinion?

_Originally posted by @stap-m in https://github.com/OpenEnergyPlatform/oeplatform/issues/1486#issuecomment-1859784748_

**Comment by jh-RLI** [comment]
@stap-m @han-f we still have to decide whether we want to display both descriptor types (study and scenario) in a list or as two individual options on the comparison page. There is also an inconsistency in the naming. The "Scenario descriptors" are labelled as "Scenario type" (when creating a scenario).

**Comment by stap-m** [comment]
I just checked the OEP for this. 
- Naming: We decided to use the scenario types as scenario descriptors. I think it is ok to call them "types" in the bundles. This might also aviod mixing them up.
However, the naming is not yet consistent! They should be called the same on the creation page and on the comparison page, which is not yet the case.
- Can you make the descriptors clickable also on the comparison page?

**Comment by jh-RLI** [comment]
Sure i will implement it this way.
