### ISSUE TITLE
toep: scenario bundles: publication year only is not possible 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1727]
## Description of the issue
Some publications do not have an exact publication date (see discussion in #1723).  But I cannot yet just select a publication year, albeit it seems this issue was worked on. Is it possible to include this solution in the upcoming release?

This is how it displays when I only supply a year in the date field: 
![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/801d8880-48c8-4d6e-a2d5-f90f23f261d6)

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Workflow checklist

- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
This is now possible with https://github.com/OpenEnergyPlatform/oeplatform/pull/1723
