### ISSUE TITLE
Scenario bundles: Selection of models in backend and frontend  displays empty 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1756]
## Description of the issue
If i select a model in the backend of the factsheet the box does not display a tick when I select it. Therafter the model display is empty, This also holds for the frontend view, 
see below: 

![grafik](https://github.com/user-attachments/assets/d7b16ec0-700b-427e-97cc-553e27f95996)

![grafik](https://github.com/user-attachments/assets/a78493f9-fc8f-46ad-8c4d-11fba3881347)

## Steps to Reproduce

1. Select model from dropdown, try to select it
2. Exit dropdown
3. Check how it is displayed

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment

- Version used:
- Operating system:
- Environment setup and (python) version:

## Workflow checklist

- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

cc @stap-m  @l-emele @wingechr

**Comment by han-f** [comment]
Also, the frontend view of bundles that already had models attached displays empty:
![grafik](https://github.com/user-attachments/assets/87160fdc-347d-4fa3-8e7b-31add7b89b45)

**Comment by jh-RLI** [comment]
I will install some more minor updates on the TOEP/OEP today. This is fixed after that.

**Comment by jh-RLI** [comment]
Ah okay, I thought I had already implemented it ... The ‘Acronym’ field in the model/framework factsheets is not a mandatory field. So it can be empty. I wanted to implement it so that I try to display the acronym first, and if it's empty, it should display the name.

**Comment by han-f** [comment]
this still happens to me today after the update.
