### ISSUE TITLE
Docker images does not start

### ISSUE THREAD

**Issue by ebroda** [OpenEnergyPlatform/oeplatform#1787]
## Description of the issue
I wanted to start oeplatform using the provided GitHub image and it fails with the following exception:

FileNotFoundError: [Errno 2] No such file or directory: '/app/ontologies/oeo/2.4.0/modules'

Shortened stack trace:
```
oeplatform-1                    | Migrating Django database...
oeplatform-1                    | Traceback (most recent call last):
oeplatform-1                    |   File "/app/manage.py", line 10, in <module>
...
oeplatform-1                    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
oeplatform-1                    |   File "/app/ontology/urls.py", line 4, in <module>
oeplatform-1                    |     from ontology import views
oeplatform-1                    |   File "/app/ontology/views.py", line 19, in <module>
oeplatform-1                    |     OEO_MODULES_SUBMODULES = collect_modules(OEO_PATH / "modules")
oeplatform-1                    |   File "/app/ontology/utils.py", line 29, in collect_modules
oeplatform-1                    |     for file in os.listdir(path):
oeplatform-1                    | FileNotFoundError: [Errno 2] No such file or directory: '/app/ontologies/oeo/2.4.0/modules'
oeplatform-1 exited with code 1
```

## Steps to Reproduce
1. Clone repository.
2. docker compose -f docker/docker-compose.yaml up

## Ideas of solution
As the structure of the oeo release has changed, the loading of the oeo was updated, but it seems as if the image was not tested afterwards. 
https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/docker/Dockerfile#L17

The following commands builds a valid image:
```
RUN mkdir -p /app/ontologies/oeo && cd /app/ontologies/oeo && wget https://github.com/OpenEnergyPlatform/ontology/releases/download/v2.4.0/build-files.zip && unzip build-files.zip && mv build-files 2.4.0 && rm -r __MACOSX && rm build-files.zip
```
I'll add a PR for that.

## Context and Environment
- Version used: current
- Operating system: Linux / Ubuntu 22.04
- Environment setup and (python) version:

## Workflow checklist

- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Thanks a lot!
