### ISSUE TITLE
open_ego tutorials planing and integration

### ISSUE THREAD

**Issue by wolfbunke** [OpenEnergyPlatform/oeplatform#181]
I already spoke with @MGlauer about an integration of tutorials of our oep and the ego tool.

In my idea it would be great to have an tutorial at the oep. The goal would be an interactive tutorial run  as a blog. It should / could include single task or question, example, plots and maybe tutorial video. For example an article could be how get a data table via API and plot the data on our PC.

**Example of tutorial pages:**  
* https://www.datacamp.com/community/tutorials/15-easy-solutions-data-frame-problems-r#gs.5ykL=UY ( in R)
* https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-1-python-basics?ex=5 (Python)
* https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-1-python-basics?ex=1 (Video)

OR
*  https://blog.quandl.com/

The integration should be done step by step. Users of oep or admin user should only be able to write and edit blog articles / items.

**What is our idea and opinion?**
* @beritRLI 
* @ulfmueller 
* @lukasol 
* @EdithaK 
* @Ludee 
* @gplssm 
* @IlkaCu 

The integration of interactive consoles is also part of ticket: _IPython on OEP #177_

References: 
* https://www.psd-tutorials.de/tutorials/web/python
* https://cdn.datacamp.com/dcl/standalone-example.html
* http://oep.iks.cs.ovgu.de/

**Comment by wolfbunke** [comment]
Another maybe more easy example can be found here: https://github.com/barbagroup/AeroPython/blob/master/lessons/04_Lesson04_vortex.ipynb

**Comment by wolfbunke** [comment]
Source Code of datacamp light: https://github.com/datacamp/datacamp-light  (GPL-3)

**Comment by beritRLI** [comment]
Thanks for starting the issue. For when is the release planned?
Could we make a list of suggestions in a google sheet, then prioritize and work out the first priorities (methodology, content, timeline); I like your suggestions for GitHub tutorials and would add youtube-tutorials.
We were already discussing to address different kind of users in different tutorials to avoid an overload in one tutorial.

**Comment by EdithaK** [comment]
@Ludee please link the tutorials you did for reeem here.

**Comment by Bachibouzouk** [comment]
As this issue is now references in https://github.com/OpenEnergyPlatform/examples/issues/8 and because the tutorials will not be stored in the current repository after #422, I close this issue now.
