### ISSUE TITLE
Certificate error when querying OEP API

### ISSUE THREAD

**Issue by henhuy** [OpenEnergyPlatform/oeplatform#1813]
## Description of the issue

I get following error when trying to query OEP API:
`requests.exceptions.SSLError: HTTPSConnectionPool(host='openenergyplatform.org', port=443): Max retries exceeded with url: /api/v0/advanced/search (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))`

## Steps to Reproduce

Minimal python example:
```
data = {
    "query": {
        "fields": "version",
        "from": {"type": "table", "table": "sedos_results", "schema": "model_draft"},
    }
}
response = requests.post(f"https://openenergyplatform.org/api/v0/advanced/search", json=data)
data = response.json()
```

## Ideas of solution

As someone pointed out that OEP certificate has been renewed on 28th August (not checked by myself):
Maybe certificate has expired? Or cert chain is corrupt?

**Comment by jh-RLI** [comment]
I have informed the system administrator. I assume that it is a problem in the SLL certificate chain, as we had a similar problem 1-2 months ago.

**Comment by jh-RLI** [comment]
For me this is now resolved. Thanks to sysadmin who fixed the ssl chain :) Please reopen if it persists.
