### ISSUE TITLE
API authorization not working in docker container

### ISSUE THREAD

**Issue by ebroda** [OpenEnergyPlatform/oeplatform#1829]
## Description of the issue
I was trying to use the API to add a table, but both ways (REST and cli.create_table()) fail with an unspecific PermissionDenied. It work's without problems at openenergyplatform.org.

## Steps to Reproduce
1. Start up oep from the docker image.
2. Try to submit a new table via API.
3. Receive a Permission Denied / 403 error.

## Ideas of solution
After like two hours checking why the auth is not applied correctly, I found the following hint in the django-rest-framework docs:
> Note that if deploying to [Apache using mod_wsgi](https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIPassAuthorization.html), the authorization header is not passed through to a WSGI application by default, as it is assumed that authentication will be handled by Apache, rather than at an application level.  

https://www.django-rest-framework.org/api-guide/authentication/#apache-mod_wsgi-specific-configuration

So a small change; I'll provide a PR for that.

## Context and Environment

- Version used: current
- Operating system: Ubuntu
- Environment setup and (python) version: current

## Workflow checklist

- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Sorry for the trouble :/ this will help a lot as most developers (except me) will use the docker image I think.  Currently you are actually the main reason why it is being propperly reviewed and used. This will probably change towards the end of the year / next year as more developers are expected to join.  Thanks a lot again!
