### ISSUE TITLE
toep: names of tables render differently

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1846]
## Description of the issue
For some tables, there is not the table name, but a title displayed which makes it not possible to identify which dataset this is. 

![grafik](https://github.com/user-attachments/assets/faee7f68-3f8b-4d73-af81-770826e60e29)

## Steps to Reproduce

1. similar to #1845 
2.
3.

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment

- Version used:
- Operating system:
- Environment setup and (python) version:

## Workflow checklist

- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by han-f** [comment]
Additionally, I think the drop down does not show all tables (but maybe this is because it is on toep?)
E.g. I can find WEM: eu_leg_2023(...)  but not WAM: eu_leg_2023(...)

**Comment by jh-RLI** [comment]
> Additionally, I think the drop down does not show all tables (but maybe this is because it is on toep?) E.g. I can find WEM: eu_leg_2023(...) but not WAM: eu_leg_2023(...)

While the comparison uses the data form OEP the bundles on toep are not up to date and therefor the listed tables are not complete. On Monday we can check this on the OEP with the complete scenario bundles.

**Comment by jh-RLI** [comment]
The bug you describe is no longer part of the OEP as you updated the input / ouput tables there. It will also not be the issue again as it was some artifact from before when it was not possible to select the tables correctly.
