### ISSUE TITLE
Restructure the data view RSID46

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#185]
The dataview of [some visualisations](http://oep.iks.cs.ovgu.de/dataedit/view/supply/ego_renewable_power_plants_germany) on the OEP takes unnecessarily long to load. This is because the map is built whenever the page is loaded.

Instead, the Map should be only visible, if
1. There is actual geographical infomation inside the table to render
2. The user states explicitly that he wants to see the map
(same goes for the graph)

Implement tabs for the specific [views](http://okfnlabs.org/recline/docs/tutorial-views.html) in the recline framework by splitting the currently used MultiView. 
Users should be able to create views for a specific dataset (i.e. a map using the coordinates in column x, a graph plotting column x vs column y, etc), name them. These Views should be visible by anybody, so that we get a collection of useful dataviews for everybody.

Users should still be able to filter data w.r.t specific criteria.

The structure of the views should be stored in the django-internal database.

RequirementSpecificationID = 46

**Comment by wolfbunke** [comment]
Hi @MGlauer and @tom-heimbrodt,
at the moment there are no Geoviews visible. Is it a bug or are still changes going on?

**Comment by christian-rli** [comment]
In a project meeting, it was said that the map does only load when necessary. Are the other remaining tasks still pending or can this issue be closed?

RequirementSpecificationID=46

**Comment by Bachibouzouk** [comment]
@MGlauer - can this issue be closed ?

**Comment by christian-rli** [comment]
According to @MGlauer in a project meeting this was already done. Therefore closing this issue.
