### ISSUE TITLE
OEO URL is striped by last char

### ISSUE THREAD

**Issue by ebroda** [OpenEnergyPlatform/oeplatform#1865]
## Description of the issue
This is really a detail, but the last char at download URLs is stripped.

## Steps to Reproduce
1. Visit https://openenergyplatform.org/ontology/
2. Check URLs for Glossary and Download 2.4.0 in right card.
3. URLs are ``https://openenergyplatform.org/ontology/oeo/releases/latest/glossar``and ``https://openenergyplatform.org/ontology/oeo/releases/lates``

Expectation would be (and these URLs also work):
```
https://openenergyplatform.org/ontology/oeo/releases/latest/glossary
https://openenergyplatform.org/ontology/oeo/releases/latest
```

## Ideas of solution
https://github.com/OpenEnergyPlatform/oeplatform/blob/7dfcda4d42f14a0fdbc8562e65819ed6495e59f4/ontology/urls.py#L32-L38
The ? at the end of the urls is, as of regex, an optional param (0 or 1). Seems like django is evaluating them, and this way getting to removing the last character. 

I'm not sure, why the ? is there - but probably can simply be removed.

## Context and Environment

- Version used: current OEP
- Operating system: independent
- Environment setup and (python) version: -

## Workflow checklist

- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Oh, good catch! I will add this to the hotfix as we found other things like this. Thanks :)

**Comment by jh-RLI** [comment]
I agree we can remove the "?" from the urls.
