### ISSUE TITLE
Error: Show data from tables does not work

### ISSUE THREAD

**Issue by johannwagner** [OpenEnergyPlatform/oeplatform#188]
There is an error in current "feature/api" branch. 
If you want to show the data of a table, you will get an error, because old api functionalities was removed.

**Comment by johannwagner** [comment]
Seems working now. I did not change anything.

**Comment by EdithaK** [comment]
@johannwagner : is the problem solved with the new API ? If yes, please close the ticket

**Comment by Bachibouzouk** [comment]
Because no one complained about it anymore, nor referenced it in a PR for 2 years, I will close this issue.
