### ISSUE TITLE
Missing (license) tags in oedb

### ISSUE THREAD

**Issue by EdithaK** [OpenEnergyPlatform/oeplatform#199]
We want to have a representative status of tagging within the oedb for the release in April. What is missing ...

**Comment by EdithaK** [comment]
Thank you @Ludee for filling up the data tables with tags. Dont know if i hab the right version. But if so, could you please spend some thoughts on additional tags? Some suggestions:

- [ ] add the tag demand (for http://oep.iks.cs.ovgu.de/dataedit/view/demand)
- [ ] add the tag something like "social" ... economics ....
- [ ]
- [ ]

**Comment by Ludee** [comment]
There was a discussion on a Breakout group in Milano:
https://docs.google.com/document/d/1PPGyXr8Z0MUWNJajWwwwfSmORZv6z9iWTAnWh-4bmRY/edit#heading=h.lii4i3j7uy1s

**Comment by Ludee** [comment]
consider: #158

**Comment by Ludee** [comment]
- [ ] implement tags for licenses

**Comment by Ludee** [comment]
Alle tags sind vorhanden und können genutzt werden. Einmal alle schemas durchgehen und alles taggen.

**Comment by Bachibouzouk** [comment]
@Ludee, @christian-rli - can this be closed then?

**Comment by christian-rli** [comment]
> Alle tags sind vorhanden und können genutzt werden. Einmal alle schemas durchgehen und alles taggen.

This is not what this issue's headline suggests and should go into a new issue rather than keeping this two year old issue alive - if it's not already obsolete by now.
