### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#2]
We need a user management for our platform. For starters each user
should be able to login and manage a profile that consists of his
name, mail-address (per default hidden) and his affiliation. Maybe we
will extend this profiles later.

Django seems to come with a package for user management:
`django.contrib.auth.forms`

**Comment by MGlauer** [comment]
There is a chapter in the django doc on authentication:
https://docs.djangoproject.com/en/1.9/topics/auth/
and a section on how to customise it: 
https://docs.djangoproject.com/en/1.9/topics/auth/customizing/

This should be useful.

**Comment by Ludee** [comment]
I want to have a profile picture and see other profiles. It should be linked to the openmod wiki profile and get data.

**Comment by beritRLI** [comment]
I thought it is linked to the wiki profile. Can it use the  wiki picture (if one is there)?

**Comment by Ludee** [comment]
User management works but could need some nice feature. Low prio

**Comment by christian-rli** [comment]
When working on this we should rethink the entire concept: registration, activation (yes/no), password security (ssh-implementation). Making user profiles nice is a nice to have.

**Comment by Bachibouzouk** [comment]
@MGlauer - can this issue be linked to a PR/branch ?

**Comment by stefaneidelloth** [comment]
I just registered as a new user and I see some buttons "Manage Profile" and "Manage Group". If that is not yet implemented, in my opinion the buttons should not be shown. 
![image](https://user-images.githubusercontent.com/12675339/77657839-22451c00-6f76-11ea-85f6-592e871d189a.png)

**Comment by MGlauer** [comment]
These buttons are functional, but only for authenticated users. They should be hidden for anonymous users.

**Comment by MGlauer** [comment]
Should be fixed now

**Comment by christian-rli** [comment]
What is needed to close this issue? Could someone post a list with check boxes that we can tick off one by one?

**Comment by christian-rli** [comment]
The things asked for in this issue originally have been implemented. Therefore closing this now.
