### ISSUE TITLE
Bump Postgres/PostGIS versions

### ISSUE THREAD

**Issue by eosram** [OpenEnergyPlatform/oeplatform#204]
I recently discovered a nice extension, [postgresql-unit](https://github.com/ChristophBerg/postgresql-unit), for PostgreSQL implementing a data type for using SI units, which is available for PostgreSQL 9.5. Just to explain how I came up with this out-of-the-blue question : ). Besides from that, newer PostgreSQL versions have a nice feature when [unnesting arrays](http://stackoverflow.com/questions/8760419/postgresql-unnest-with-element-number) and you want to keep the order. And PostGIS 2.3 ships with a [voronoi function](http://postgis.net/docs/ST_VoronoiPolygons.html). Most likely there are other features we or other projects could benefit from, but, of course, these are nice-to-have features, which are not necessarily needed atm and besides from that I am not sure how much work upgrading would actually mean. Nevertheless, are there ambitions to upgrade the oep in the future?

Status quo
"PostgreSQL 9.3.10"
"POSTGIS="2.1.2 r12389" GEOS="3.4.2-CAPI-1.8.2 r3921" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 1.10.1, released 2013/08/26" LIBXML="2.9.1" LIBJSON="UNKNOWN" TOPOLOGY RASTER"

**Comment by s3pp** [comment]
I keep this issue open for collecting useful new features : ). PostgreSQL 9.5 introduces also an [assert](https://www.postgresql.org/docs/9.5/static/plpgsql-errors-and-messages.html) statement. This could be handy for error checking in the dataprocessing.

**Comment by christian-rli** [comment]
It was previously unclear how to close this issue. Check the current version of postgres and postgis installed. If an update is advisable, go ahead with it. If not, close this issue.

**Comment by jh-RLI** [comment]
We could consider upgrading Postgresql as we are only using version 9.XX But this may be a more complex task as there might be some limitations due to the hosting provider... not 100% sure.

**Comment by jh-RLI** [comment]
We updated everything and now have version 14 installed.
