### ISSUE TITLE
Enhance factsheet explanation

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#213]
It is unclear how to distinguish models and frameworks. Additionally, enhance the overall descriptions regarding

* What is a model/framework/scenario/study
* How do I classify my tool as a model/framework/scenario/study

**Comment by beritRLI** [comment]
Ich würde den Einführungstext dazu nochmal klarer fassen (=> issue an mich)

**Comment by EdithaK** [comment]
@beritRLI 
I foude a long dicribtion on http://oep.iks.cs.ovgu.de/factsheets/overview/
Is something missing? Can we close the Issue?

**Comment by EdithaK** [comment]
@pkassing please 
1. read the text on the here: http://oep.iks.cs.ovgu.de/factsheets/overview/ 
If you understand it:
2. rewrite it in the way you would have liked it to be
3. Post it here
If not:
2. leave a comment and talk to Berit

**Comment by EdithaK** [comment]
@Ludee please provide all listed tutorials. Please organise help from students and Jnnr where possible.

**Comment by beritRLI** [comment]
There should be an explication in the right side bar (replacing the current note about "highly volatile development...") when you are at the model- or framework FS:
The Fact Sheets are made to reach three main objectives: 
1. Find models/frameworks for your needs or just get an overview about the existing ones
2. Compare a selection of models for different purposes - e.g. to develop a strategy to link them
3. Store your model/framework information to provide transparency 

You find more information about the Fact Sheets on the "Overview Site" (link to Overview: https://oep.iks.cs.ovgu.de/factsheets/overview/)

Improve overview:
* Add the above points as paragraph 3 (=> The Fact Sheets are made to reach three main objectives: 
1. Find models/frameworks for your needs or just get an overview about the existing ones
2. Compare a selection of models for different purposes - e.g. to develop a strategy to link them
3. Store your model/framework information to provide transparency )

replace the (current) paragraph 3 and 4 with the following text:
When publishing a study, there is a full set of linked Factsheets (and datasets) to improve transparency and to avoid repeated and long explications of the used tools as well as senseless printing of assumptions which the users need in exportable formats.  The model on which the study is based can be described in a model Fact Sheet. This will link to a framework Fact Sheet (if based on one) and it will be linked from the scenario Fact Sheets that describe the various scenarios of the study. Usually different scenarios with modified input data and assumptions are calculated and compared. As input data is one of the most important information of the scenario, the scenario factsheet will include links to the datasets in a publicly available database (the concept of the OpenEnergy Database is to provide a place to store and publish this data).

The current Factsheets are a result of bringing together existing characterizations and improving it in two workshops and in an online discussion. This discussion is reopened with the growing interest to use the factsheets. The release of Dec. 2017 will include functions to filter the Fact Sheets and to compare them regarding specified characteristics. In 2018 we will broaden the view of energy system models and provide the possibility to specify health, social and other aspects.

**Comment by beritRLI** [comment]
@EdithaK and @pkassing : please profread text
@MGlauer : please include text

**Comment by beritRLI** [comment]
@MGlauer the version you updated is not the one I see online, right?
Could you please add a heading over the filter possibilities
"Filter" with help text: "you can filter the attributes to compare the models by clicking the categories below and chosing up to 8 attributes. If you only want to compare a selection of models you can filter them by using the coloured tags below."

und dann noch ein help text für "Select tag filter": "You can select models by chosing one or more tags. If you want to tag models you can set tags by editing the model. You can also define a new tag and add that to the group of models that you want to compare."
