### ISSUE TITLE
Write a press release

### ISSUE THREAD

**Issue by EdithaK** [OpenEnergyPlatform/oeplatform#219]
Find the draft on the Server at /open_eGo/Veroeffentlichungen/Pressemitteilungen
revision loop:
- [x] RLI (draft)
- [x] Next
- [x] ZNES
- [ ] IKS
- [ ] ...

**Comment by lukasol** [comment]
just uploaded a reviewed version.

**Comment by EdithaK** [comment]
@ulfmueller: Could you pass the new version to the right person at ZNES/UniFL

**Comment by ulfmueller** [comment]
I can do that and pass it to the right person at the Flensburg University of Applied Sciences

**Comment by wolfbunke** [comment]
I take a look into it on Monday, if it's ok for you?

**Comment by EdithaK** [comment]
Great! Thanks

**Comment by ulfmueller** [comment]
I just checked the document and it seems like it is rather a  working version which we - as the one involved in the project - have to clarify before I/we give it to public affair people. Also (and in context with the previous sentence) I would appreciate a version without or fewer comments before I hand in on to public affair people.
I personally can give comments until monday.
By the way, I think this is / would have been a perfect issue for the redmine.

**Comment by lukasol** [comment]
@EdithaK what's the status here?

**Comment by wolfbunke** [comment]
It is on my table and I am late. I will work Tuesday on it. We have still time or?

**Comment by wolfbunke** [comment]
An update of the document can be found on the sftp server

**Comment by Ludee** [comment]
Was this released yet?

**Comment by EdithaK** [comment]
No, we did not do it at the last release

**Comment by christian-rli** [comment]
Closing issue since it is no longer relevant.
