### ISSUE TITLE
Linked open data conformant API

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#220]
As requested during the first meeting of the german research network energy the API of the OEP should conform to state of the art [linked open data](http://linkeddata.org/). The general idea is that one should be able to reference data via an URL. 
For starters, it should be sufficient to return the plain value of a cell. From my understanding this conforms to RDF Turtle close enough.
(Later, we will add a more rigorous (ontological) knowledge presentation.)

**Comment by johannwagner** [comment]
I implemented the functionality with the schmema we discussed.
Should I check, if the column name exists and provide a hint to the user ?

**Comment by MGlauer** [comment]
If the column is not there, a 404 should be issued. This is done automatically and i guess the most intuitive behavior.

**Comment by johannwagner** [comment]
Fixed to 404.

**Comment by Bachibouzouk** [comment]
Based on the discussion, commits and the fact that the issue is 2 years old, I conclude this issue can be closed
