### ISSUE TITLE
Dokumentation durch Q&A verbessern

### ISSUE THREAD

**Issue by beritRLI** [OpenEnergyPlatform/oeplatform#221]
regelmäßig Q und A ansehen um Dokumentation zu verbessern
wo verorten wir Q&A? => openmod Forum Q&A
Für release 14.08 erstmal nur festlegen wie wir diesen Verbesserungsprozess verankern/auf dem Schirm behalten

**Comment by EdithaK** [comment]
Please note that we collect them in the Wiki: [](https://github.com/openego/oeplatform/wiki)

**Comment by Bachibouzouk** [comment]
Now that the Q&A is in the wiki, I conclude this issue can be closed
