### ISSUE TITLE
wrong locations in map view for some tables

### ISSUE THREAD

**Issue by nesnoj** [OpenEnergyPlatform/oeplatform#222]
I tried to draw some data on the map.
It works pretty well with `supply.ego_conventional_powerplant` but fails on some tables, e.g. `demand.ego_dp_loadarea` or `demand.ego_demand_federalstate` - all geoms seem to be located at the north pole. Could this be caused by the CRS? (some use WGS84 and some ETRS89)
To my mind the CRS should be set for the table or column and therefore read by your JS script - or does the script use one standard CRS? @Ludee

**Comment by MGlauer** [comment]
This is known. The CRS should be consistent in a single column. This should be something we can handle and is currently implemented in #185

**Comment by nesnoj** [comment]
Ok, thanks

**Comment by MGlauer** [comment]
@tom-heimbrodt : See https://github.com/openego/oeplatform/blob/develop/dataedit/static/dataedit/editors.js#L321

**Comment by Bachibouzouk** [comment]
@MGlauer - According to the commit, the issue is closed
