### ISSUE TITLE
[Factsheets] check of fact-sheet categories with existing publications

### ISSUE THREAD

**Issue by beritRLI** [OpenEnergyPlatform/oeplatform#229]
Through to the review we are writing for the EMP-E special issue about model categorisation we have a bigger collection of papers who suggest/work with various categories to compare energy system models.
We should go through and check what ist covered, what is not covered and we don't see the need to do so and what is not covered but would be good to include.
result: suggestions to improve the Factsheets concerning categories and views

**Comment by stap-m** [comment]
Outdated
