### ISSUE TITLE
Comments via OEP api

### ISSUE THREAD

**Issue by eosram** [OpenEnergyPlatform/oeplatform#245]
It would be nice if one could set comments as an essential part of data documentation via api calls - especially on tables.

**Comment by jh-RLI** [comment]
functions to add metadata as comment on table are implemented in [oem2orm ](https://pypi.org/project/oem2orm/) and [oep-client](https://pypi.org/project/oep-client/). The api accepts valid oemetadata as HTTP POST at: /api/v0/schema/{schema}/tables/{table}/meta/

You can also add metadata using the metadata form on the oep when viewing a table. Keep in mind you need permission on that table.
