### ISSUE TITLE
Trying to set ForeignKey constraint

### ISSUE THREAD

**Issue by eosram** [OpenEnergyPlatform/oeplatform#249]
In order to set a ForeignKey constraint I wish to set a unique constraint on a text column called region_key, because this is a prerequisite as far as I understand it. Setting up the table is working as expected looking at the table definition of http://oep.iks.cs.ovgu.de/api/v0/schema/model_draft/tables/buergen_test_unique/ . But unfortunately I'm not able to insert data in this table by:

<pre>
curl -X POST -H 'Content-Type: application/json' -H 'Authorization: Token ...' -d '{"query": {"region_key": "1"}}' oep.iks.cs.ovgu.de/api/v0/schema/model_draft/tables/buergen_test_unique/rows/new
</pre>

The same table just without the unique constraint is set up in http://oep.iks.cs.ovgu.de/api/v0/schema/model_draft/tables/buergen_test/. Here the insert statement succeeds. Did I get something wrong?

**Comment by MGlauer** [comment]
It seems that this is caused by a faulty type cast. The `region_key` is interpreted as integer for some reason. I will fix as soon I am back in office.
