### ISSUE TITLE
Http response 504

### ISSUE THREAD

**Issue by eosram** [OpenEnergyPlatform/oeplatform#251]
Trying to insert a larger dataset I receive the following response:

<pre>
DEBUG: http://oep.iks.cs.ovgu.de:80 "POST /api/v0/schema/model_draft/tables/buergen_geo_municipality/rows/new HTTP/1.1" 504 330
DEBUG: Response [504]
</pre>

Got this response recently at around Wed Sep 27 19:29:.. CEST 2017. How can I handle this?

**Comment by EdithaK** [comment]
Could you solve the problem? Maybe this is an often appearing problem and something for the FAQ?

**Comment by MGlauer** [comment]
No, this is something I have to fix. But it requires some internal restructuring that is not done easily. But I am working on it.

**Comment by Bachibouzouk** [comment]
@MGlauer - is there a commit number / PR linked to this old issue ?
