### ISSUE TITLE
Link to glossary on discussion is missing

### ISSUE THREAD

**Issue by wolfbunke** [OpenEnergyPlatform/oeplatform#257]
On http://oep.iks.cs.ovgu.de/discussion/
the link on glossary points to an empty` http://href=/` url.

See 3rd enumeration :

> > Transparency of energy system modelling and fruitful debates about it are very much depending on a common understanding of expressions. Therefore we started a **glossary**. You can watch up; debate and add expressions.

**Comment by MGlauer** [comment]
@EdithaK This seems to be your text. Where should the link actually point to?

**Comment by christian-rli** [comment]
In case you mean the glossary of the openmod-initiative the link is this: https://wiki.openmod-initiative.org/wiki/Category:Glossary

**Comment by han-f** [comment]
We will work on this issue now.
