### ISSUE TITLE
Database / Dataview, Links zu Tutorials funktionieren nicht 

### ISSUE THREAD

**Issue by pkassing** [OpenEnergyPlatform/oeplatform#259]
Unter den Datensätzen gibt es einen Erklärungstext, dessen zweite Hälfte auf Tags eingeht.
Darunter soll es in Stichworten Links zu verschiedenen Tutorials rund um die OEP geben.
Die Stichpunkte sind jedoch noch keine Hyperlinks

**Comment by EdithaK** [comment]
@pkassing : I did not find the link you meantioned. Can you concretize?

**Comment by pkassing** [comment]
https://oep.iks.cs.ovgu.de/dataedit/schemas
This is the link to the page that I mentioned. At the bottom you find "links to tutorials". However, the links are missing

**Comment by EdithaK** [comment]
True.
@Ludee please provide all listed tutorials. Please organise help from students and Jnnr where possible.

**Comment by jh-RLI** [comment]
@Ludee @christian-rli all the available turotials are listed [here](https://github.com/OpenEnergyPlatform/examples), aren't they?

**Comment by christian-rli** [comment]
> @Ludee @christian-rli all the available turotials are listed [here](https://github.com/OpenEnergyPlatform/examples), aren't they?

They are not really listed, but they are in the subdirectories of your linked location :) A dedicated page, linking to all tutorials in an orderly fashion still needs to be created. With the redesign of the OEP on its way, it's now a good time to do so, so it's high up on my list.
