### ISSUE TITLE
Add explanations on where to put which kind of data

### ISSUE THREAD

**Issue by EdithaK** [OpenEnergyPlatform/oeplatform#260]
Please explain with graphic and text where to upload data the oedb on the first page of oedb:
Case 1:  fast--> model draft
Case 2: finished data --> shema

bei den Rückmeldungen vom FFE zu der oedb gab es u.a die Anmerkung, dass es unklar ist, wo Daten hochgeladen werden können => verschiedene Stufen: ich will schnell damit arbeiten; in Projekten (=> model-draft schema); Feste Datensätze => ins entsprechende Schema; außerdem wäre der Hinweis gut, dass in allen Schemata auch die noch nicht revieten Datensätze angezeigt werden können, wenn man den roten Button drückt….

und dazu den Verbesserungsvorschlag, dass es helfen würde, wenn es ein Schaubild dazu geben würde, wo welche Daten abzulegen sind (und was dann mit ihnen passiert) => Wenn ich die und die Daten habe, dann in das Schema x bei einem anderen Fall in das Schema y....

Erstellung Schaubild und Aufnahme in oedb Doku und ich denke das wäre auch sehr gut auf der ersten oedb-Seite platziert.

**Comment by nesnoj** [comment]
:+1: 
+ bitte Vorgaben/Muster zur Tabellen- und Spaltenbenennung (best practice)

**Comment by klarareder** [comment]
model draft is not versioned

**Comment by klarareder** [comment]
e.g. include factsheets

**Comment by klarareder** [comment]
![overview_OEP](https://user-images.githubusercontent.com/42575569/55480862-79453900-5621-11e9-8578-1d1008c7a9ef.png)

**Comment by c-moeller** [comment]
As discussed in the last OEP workshop an open issue for me is to comment on the graphic designed by @klarareder 

I really like it! It makes things much clearer now :+1: 

I have some little remarks:
- the symbols on the top of the boxes within the data box might need a legend
- the factsheets box might get some additional explanation since there are framework, model and scenario factsheets (or is data upload only the case for scenarios?)
- Is metadata and data review only necessary for the final data?
- I think an additional text explaining the graphic might be necessary (e.g. explain what "topic" means in the last data publication step). I could help with the text (but I will not be available until the mid of July)

**Comment by stap-m** [comment]
I added a legend to the graphic. Is it understandable?
![legend](https://user-images.githubusercontent.com/38690039/63762071-81e52700-c8c2-11e9-8a51-e8f6c6854902.png)

**Comment by han-f** [comment]
Currently users cannot write to the sandbox schema, or am I mistaken?

**Comment by stap-m** [comment]
How can we include the graphic in the new design? I think it would make sense to place it at the tutorials for beginners, BUT then it wouldn't be visible on the start page.

**Comment by han-f** [comment]
Couldn't we place it on to the startpage as a thumbnail that can be clicked to be viewed in large, and then repeat it at the tutorials for beginners site? We would still need to figure out whether the sandbox will be writable for users or not.

**Comment by bmlancien** [comment]
I would put it in the tutorial section as well as in the documentation section, since some users will probably have the idea to look for this topic in the documentation, and not necessarily in the tutorial section. But I would not put it on the home page because the goal of the page is to give the visitor a short overview of the platform and not deeper informations.

**Comment by han-f** [comment]
Re: sandbox:
See also this issue about potentially misleading documentation on the wiki: https://github.com/OpenEnergyPlatform/data-preprocessing/issues/32

**Comment by Ludee** [comment]
I have one small comment on the last icon.
It should be "Under version control", "Version controlled", "With revisions" not "GitHub".
I think it means, that the data history can be tracked.

**Comment by stap-m** [comment]
Good point @Ludee, "version controlled" or else would be better. The first eyecon refers to the "review process"

**Comment by klarareder** [comment]
> 
> 
> I added a legend to the graphic. Is it understandable?
> ![legend](https://user-images.githubusercontent.com/38690039/63762071-81e52700-c8c2-11e9-8a51-e8f6c6854902.png)

Acutally the eye meant that the table is visible or not. The sandbox can not be seen, while the other can.

**Comment by klarareder** [comment]
I wrote this text to accompany the figure: please correct it for spelling or content:

The OEP has multiple functionalities. Any user can upload data. For first tests, the **sandbox** may be used. The sandbox is not visible, but the upload process is very fast but beware, the sandbox is deleted regularly.  Once accustomed to the sandbox the user may use the **model draft** and upload its real data within a project. The data is visible, the upload process is fast and the model draft connects to GitHub. As soon as the **final data** is available and the user makes no further changes, the data can be permanently stored at the corresponding **topic**. The stored data is than visible, the upload process takes some time and the data is stored in GitHub. **Metadata**, that fulfil the FAIR principles, accompanies the data. Additionally, data **reviews** by other uses highlight datasets of exceptional high quality. Furthermore, the **model factsheets** give background on the model, which produced the data. Hence, the OEP gives the user a platform to publish her or his data **transparently** and **comparably**.

**Comment by bmlancien** [comment]
![OEP_Data_Process_v3](https://user-images.githubusercontent.com/33999424/98265139-06ccd580-1f89-11eb-9241-05948ae02301.png)

**Comment by klarareder** [comment]
This is much clearer than the last version. I have the following remarks:
1.) I want to upload data can also be part of A -> I use an API to upload or download data
2.) B should include the upload wizard, I will search for the icon Christian used for the implementation
3.) The arrow from Sandbox to model draft is only for the type of connection not the data itself, hence a different color of arrow or just a line might be better.

@bmlancien I added a rough grafik of the content (it must not all be on the final grafic, it is for you to see the relations)

![grafik](https://user-images.githubusercontent.com/42575569/98344219-3a544200-2013-11eb-9d6b-4566b10bb834.png)

**Comment by klarareder** [comment]
Here the icon with the wizard:

![grafik](https://user-images.githubusercontent.com/42575569/98344892-32e16880-2014-11eb-9518-167943ce18a1.png)

**Comment by bmlancien** [comment]
![OEP_Data_Process_v4](https://user-images.githubusercontent.com/33999424/100612364-28fd0d80-3313-11eb-8a82-34efc19524b5.png)

**Comment by klarareder** [comment]
I like this! I will discuss it on thursday in our Jour Fixe.

**Comment by bmlancien** [comment]
![OEP_Data_Process_v5](https://user-images.githubusercontent.com/33999424/100993664-f98a1300-3555-11eb-8ec1-5efec8dbf9b5.png)

**Comment by klarareder** [comment]
I created the turorial:
https://openenergy-platform.org/tutorials/8/
