### ISSUE TITLE
Enable SQL-A dialect in API

### ISSUE THREAD

**Issue by EdithaK** [OpenEnergyPlatform/oeplatform#261]
Enable SQL-A dialect in API.
 
Thus enable geo query.

**Comment by MGlauer** [comment]
Geo-queries are rather independent from the dialect. This is part of the [Advanced API](http://oep-data-interface.readthedocs.io/en/latest/api/advanced.html#functions)

**Comment by nesnoj** [comment]
I tested some geo stuff with the advanced API and it is working...
The only thing we're waiting for is the dialect which, according to @MGlauer, will be finished by around end of this year.
Can we close this one or do you want to keep it as reminder @MGlauer?

**Comment by christian-rli** [comment]
Dialect is up and running. closing ticket.
