### ISSUE TITLE
OEP Text on open_eGo website

### ISSUE THREAD

**Issue by EdithaK** [OpenEnergyPlatform/oeplatform#262]
@wolfbunke 
what do you think about this to add some text here: [https://openegoproject.wordpress.com/participate/](url)

The OpenEnergy Platform was developed within the open_ego Project. It is a place providing great tools to make energy system modelling process transparent! 

It addresses everybody in the field of energy modelling and analytics. It includes the OpenEnergy Database to give, get document open data and work with them via the visual interface or a REST-full HTTP-interface. It also includes Fact Sheets to describe, find, and compare energy system models. 

You are invited to explore and use this and many more functions.

**Comment by christian-rli** [comment]
This seems either outdated or out of scope, because the corresponding project is long over.
