### ISSUE TITLE
Search Engine Optimization 

### ISSUE THREAD

**Issue by pkassing** [OpenEnergyPlatform/oeplatform#267]
It would be great if somebody could do some search engine optimization. Our Open Energy Platform should be the first thing to show up when somebody searches for it. Now, other companies and organizations show up first and I didn't find the website fast enough. 
![screenshot google search database](https://user-images.githubusercontent.com/32895915/32094370-d18d0962-baff-11e7-8acc-783710858752.png)
![screenshot google search platform](https://user-images.githubusercontent.com/32895915/32094371-d1accd6a-baff-11e7-8f34-78496f4ef570.png)

**Comment by EdithaK** [comment]
Thanks, I do not know who has the right skills for that. I´ll ask Miriam from RLI

**Comment by christian-rli** [comment]
I think search engine optimization shouldn't be regarded as good practice for a website. In any case https://oep.iks.cs.ovgu.de is now the first result when searching "Open Energy Platform" or "OpenEnergyPlatform" on Google. 
![2018-10-23](https://user-images.githubusercontent.com/42000429/47346996-9bb84b00-d6ae-11e8-8930-d524e4fe02d8.png)
