### ISSUE TITLE
Tag colours

### ISSUE THREAD

**Issue by beritRLI** [OpenEnergyPlatform/oeplatform#279]
Two improvements for Tags
1) when creating a new Tag there should be a colour help: suggested colour for project tag, spatial tag,  renewable technology, fossile technology, laws and licence tag,...
it is hard to find the right colour and it is not obvious that one should choose the fitting one.
If that is not easily possible it would be good for the quick solution if default is the project colour.
I suggest: instead of the field where one can choose the colour, there is a multiple choice field to choose the "field of tag" where one can choose one of the above tag-fields (project tag, country tag, technology tag (renewable), technology tag (fossile), technology tag (infrastructure), technology tag (storage), laws and licence tag, year tag, sector tag, 

2) the tags should be displayed in order  a) by colour and b) by alphabeth

**Comment by christian-rli** [comment]
"Only show relevant tags, develop a tag color scheme and enable tagging tables via API." User Feedback and part of the requirement specification.

Before closing this Issue, make sure https://github.com/OpenEnergyPlatform/oeplatform/issues/301 is resolved as well.

RequirementSpecificationID=40

**Comment by klarareder** [comment]
At the moment the tags have to many colours. We need to group colours in categories. The categoires I see straigt away are:
1 year
2 region/continent/country...
3 project name
4 technology (e.g. biogas, PV, Wind)
5 Licence
6 Institute/University/data provider in general
7 topics (e.g. climate, envrionment)
8 other

I think if we limit the choice of colours to 10, I think we get around quite nicely. I will look for a nice colour bar.

**Comment by klarareder** [comment]
How about this colour palette:

![grafik](https://user-images.githubusercontent.com/42575569/52481327-82c89c80-2bae-11e9-9f59-ec9762fb4b11.png)

#8dd3c7
#ffffb3
#bebada
#fb8072
#80b1d3
#fdb462
#b3de69
#fccde5
#d9d9d9
#bc80bd

Maybe we could group it like this:

#8dd3c7 - year
#ffffb3 - region
#bebada - topic
#fb8072 
#80b1d3 - project name
#fdb462 - institute/universtity/data provider
#b3de69 - licence
#fccde5
#d9d9d9 - technology
#bc80bd - other

**Comment by christian-rli** [comment]
Is this plaette red-green colour blind compatible? I think #d9d9d9 (light gray) might be a little bit difficult to differentiate from #fccde5 (rose) and #bebada (purple). Probably none of those points are really an issue for tags, though. So no objections.

**Comment by klarareder** [comment]
Tags have new colors,

but it would be nice to have a limited choice of colours with the topic to choose from

**Comment by MGlauer** [comment]
The tag categories are not yet stored anywhere. This has to be the next step (see #390)
