### ISSUE TITLE
API: 403 on inserting data

### ISSUE THREAD

**Issue by nesnoj** [OpenEnergyPlatform/oeplatform#280]
I tried to insert some data:
```
data = {'query': {'subst_id0': '1', 'subst_id1': '2', 'capacity': '100'}}
result = requests.post(url='http://oep.iks.cs.ovgu.de/api/v0/schema/model_draft/tables/wn_abw_region_transport/rows/new',
                       json=data,
                       headers={'Authorization': 'Token %s'%token})
```
I granted all rights on this table to oeuser and oep and used the token from my OEP profile.
But I always get a 403 response - I'd appreciate a hint on what's wrong here..

**Comment by MGlauer** [comment]
This is intended behaviour. The API has an internal permission handling as the postgres internal is not versatile enough. You did not have write permissions on this table. I granted write permissions to you.

**Comment by nesnoj** [comment]
Thx!
1. Does this mean I got rights on this specific table only? (hence a drop and recreation will reset the permissions?)
2. Sorry for bothering you with details but now I get a 400: `column \\"id\\" does not exist` - why?

**Comment by nesnoj** [comment]
I do not have a column `id` and I do not try to insert data into this column. Is it mandatory?

For debugging, I added this column and tried
1. to add the dataset as before (same error message)
2. to add it including a value for `id` (in this case I get a 400: `CompileError(\'Unconsumed column names: id\'`

**Comment by Bachibouzouk** [comment]
@nesnoj - the 403 error at the origin of the issue was addressed, can we close this issue?

I think it should belong to the oedialect anyway...

**Comment by nesnoj** [comment]
Yepp
