### ISSUE TITLE
Lift column restrictions for API

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#283]
Currently all tables are required to have a column id of type bigserial. This is of course not a practical assumption. And should be fixed.

**Comment by MGlauer** [comment]
This was done to ensure two major functionalities:

1. Rows are accessible via `rows/{id}` 
2. Rows could be autoincremented via `rows/new`

We can drop 2. and return the normal "not null"-DBAPI-error when a POST is sent to "/row". Currently, there is no sequence handling in order to implement auto-increments for the api (see #282).

Accessing the tables could be done as before - assuming there is a primary key and proper url-encoding. If there is none raise a corresponding error. Yet, I do not like the resulting urls. Maybe we should use the `?where=<pk1>=value1+<pk2>=value2` and deprecate `rows/{id}`. 

For now simple primary keys should be sufficient for now, but we should come up with a concept for compound keys.

**Comment by henhuy** [comment]
Any progress here?
Stumbled upon it yesterday. 
As there was no error/warning while creating the table (something like "you must have column "id" with type "bigserial" as primary key), I was very confused when I could not insert data...
I think it would be okay if the _rows/{id}_, _rows/new/_ thing would be working for my custom primary key as well (like autodetect)?!

**Comment by jh-RLI** [comment]
We now check in the api if the id column is available. Please reopen of error persists.
