### ISSUE TITLE
[Factsheets] Reformat Factsheets

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#284]
The Factsheets in modelview need some love. For starters it would be good if the column selection in `/factsheets/models/` would have a structure is not as atrocious as the current collapsing panels.

**Comment by beritRLI** [comment]
what you mean with collapsing panels?

**Comment by MGlauer** [comment]
Those divs with class `panel-collapse` ;)

**Comment by christian-rli** [comment]
`panel-collapse` is no longer there. There are still collapse-able items on the page, but after the redesign, it doesn't look atrocious anymore (in my opinion). Not sure about opintions, but the headline of the issue has been addressed :)
