### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by johannwagner** [OpenEnergyPlatform/oeplatform#285]
Is it possible to serve the site with a docker container right now ? 

Thanks In Advance,  
    Johann

**Comment by MGlauer** [comment]
Not yet. But it sure would lower the hurdle for external developers. We should create one soon.

**Comment by johannwagner** [comment]
@MGlauer 

https://github.com/johannwagner/openeGo-docker

I started to implement a docker-compose.yml to launch a development instance on a local machine, because I wasn't able to create a development environment on my machine due to different issues:

- Django published a major version update on Dec 2, which breaks egoio on install. Why ? No clue. I set it with `django == 1.11` to a LTS version and it fixed the problem.
- There were multiple missing requirements: `shapely, svn` 
- There is a [syntax error](https://github.com/openego/ego.io/blob/dev/egoio/db_tables/reference.py#L167) in egoio master, which need to be fixed. There are too many double quotes.
- I don't have a working database dump for the current version. Is there a public place to get a fresh one ?

I would contribute the docker-compose.yml to the project and maintain it, if it is nesseary. Right now, I just built it for myself to have a reproduceable and usable development environment, that does not crash every time.

Should I create seperate issues for ego.io ?

Thanks, 
  Johann

**Comment by MGlauer** [comment]
Great! 

> Django published a major version update on Dec 2, which breaks egoio on install. Why ? No clue. I set it with django == 1.11 to a LTS version and it fixed the problem.

I will take a look at it.

> There is a syntax error in egoio master, which need to be fixed. There are too many double quotes.

Fixed and issued a pull request: https://github.com/openego/ego.io/pull/42

> I don't have a working database dump for the current version. Is there a public place to get a fresh one ? 

For a public docker image, we should create only the schemas displayed by the oep and the required metatables. We are currently developing an alembic integration ([`feature/alembic`](https://github.com/openego/oeplatform/tree/feature/alembic) for the oep. Maybe this should be used in your docker image as soon as we are done.

**Comment by johannwagner** [comment]
Okay, could you send me a working database dump for the current development until alembic integration is done ? I just want to use the container to work on my other issue.

**Comment by christian-rli** [comment]
appears to be solved in #771
