### ISSUE TITLE
improve texts on oep

### ISSUE THREAD

**Issue by beritRLI** [OpenEnergyPlatform/oeplatform#289]
all suggestions for improvement of texts for the oep can be gathered here

1. site: https://oep.iks.cs.ovgu.de/dataedit/  ; last point "Tutorial - How to exprot my results" => change to "Tutorial - How to export my results"
2. main page, near the end: "The oedb is structured through predefined schemas in order to organize the heterogeneous data sets contained in the database into defined groups of." - end of sentence missing.
3. main page: "REST-full" -> "RESTful", see also https://en.wikipedia.org/wiki/Representational_state_transfer
4. at http://oep.iks.cs.ovgu.de/dataedit/view/reference : "You if you are logged in, you can add tags to this schema to improve the searchability of this dataset." -> "If you are logged in, you can add tags to this schema to improve the searchability of this dataset."

**Comment by christian-rli** [comment]
"As a user it is important for me that if the DB is not accessible I get a nice text displayed explaining why I can't access it (e.g. we continuously develop the DB to improve it and in this process it can fail)." -user feedback

Improve texts (especially in errormessages) on oep.

**Comment by klarareder** [comment]
Does anyone know how the end of the scentence in 2. is supposed to be. I want to fix this issue, but dont't know the correct wording. How about: 'of similar content'

**Comment by christian-rli** [comment]
I'm not sure either. I would have just removed 'of' to fix the sentence, but 'of similar content' sounds good, as well. I'd say, just go ahead with any solution that leaves us with a complete sentence :)

**Comment by christian-rli** [comment]
(only tagging and commenting for completeness sake)

"Improve texts (e.g. in errormessages) on oep." - User Feedback and part of requirement specification.

RequirementSpecificationID=41

**Comment by klarareder** [comment]
@MGlauer I changed the text of the 500 error message. I wanted to trigger the error to see the new message, but I did not know how. For the 404 I changed the securitysetting `DEBUG=False` and `ALLOWED_HOSTS =[*]` and than I entered in my local WebApp a wrong path like: `http://127.0.0.1:8000/jkdfjk`. That worked fine, but I did not know how to trigger the 500.

**Comment by nesnoj** [comment]
You can add a view which returns a [`HttpResponse`](https://docs.djangoproject.com/en/2.2/ref/request-response/) with arg status=500, e.g.
```
from django.views.generic import TemplateView
from django.shortcuts import HttpResponse
...
class TestView(TemplateView):
    return HttpResponse(status=500)
```
should work.
(of course, view must be added to urls.py)

**Comment by klarareder** [comment]
@nesnoj unfortunatly I did not get your example working. Finally, I just added the html as as new page for testing and deleted it afterwords...

**Comment by klarareder** [comment]
branch is merged into develop
