### ISSUE TITLE
Feedback TB3: License information

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#293]
I just filled it out a model factsheet for this MODEX thing. It was mostly a good experience, but a few bits of feedback:

iii) Some of the information on the other models is wrong, e.g. calliope and Balmorel are listed as "not open source".

**Comment by christian-rli** [comment]
Feedback is noted. what is needed to close this issue?

**Comment by christian-rli** [comment]
Not sure when this was done, both currently have the status "open source: ✓". Therefore closing this issue.
