### ISSUE TITLE
in database table view, provide link to metadata

### ISSUE THREAD

**Issue by tillmo** [OpenEnergyPlatform/oeplatform#297]
at the top of the page, provide a link that jumps to the metadata section

**Comment by christian-rli** [comment]
"As a user, I would like to have a metadata entry displayed for each column, so that I know which of my data correspond to which column." - user feedback

**Comment by christian-rli** [comment]
RequirementSpecificationID=22

**Comment by jh-RLI** [comment]
@christian-rli To make sure I understand that correctly. The requirement is to display the metadata entry for each column e.g. as a popup by moving the mouse over each column name in the data view? 

Or is this already done by displaying the metadata string at the bottom of the page?

**Comment by MGlauer** [comment]
I think this has been done in #382.

**Comment by christian-rli** [comment]
I can confirm that this is done in #382 . A mouseover over a table column header displays its description from the metadata.

**Comment by Bachibouzouk** [comment]
@MGlauer - this issue is addressed in #382. However #382 has conflicts and cannot be merged into develop. @wingechr - could you solve the conflicts ?

**Comment by christian-rli** [comment]
addressed in #430 (see #382 ).
