### ISSUE TITLE
In database views, the metadata is not prominently displayed

### ISSUE THREAD

**Issue by tillmo** [OpenEnergyPlatform/oeplatform#298]
* the title of a database table (obtained from the metadata) is often more informative than the table name: display it in the database table overview (if the title is too long, it could be truncated) as well as on the top of the page for the table
* on the page table, display the column descriptions as mouseover for the column names

**Comment by christian-rli** [comment]
Currently both options are displayed, so while it's not exactly the solution described here, I think the spirit of the issue has been addressed.
