### ISSUE TITLE
Lat and lon fields are not automatically detected in map data view RSID44

### ISSUE THREAD

**Issue by tillmo** [OpenEnergyPlatform/oeplatform#299]
in the map data view, the user has to select the fields for latitude and longitude manually. Try to guess these fields automatically. If "lat" is recognised as latitude, and "lon" as longitude, this would already greatly help. Also the metadata could be considered.

RequirementSpecificationID = 44

**Comment by christian-rli** [comment]
This was implemented with the last release :)
