### ISSUE TITLE
Table not shown

### ISSUE THREAD

**Issue by stefansc1** [OpenEnergyPlatform/oeplatform#302]
New tables not part of oeuser are not shown in dataview. They can be accessed through SQL statements, but not through the API.

To reproduce, create a new table by a user not part of the oeuser group (or change ownership). The old oep displayed those tables, the new one doesn't.

Solution: change ownership of table to oeuser.

**Comment by christian-rli** [comment]
I'm not sure if this is a bug or a feature. In future data should only be visible after a review (if I understand correctly), so there will need to be a state where data is in the database, but not visible publicly. I don't know if that is the reason for this particular issue. There should exist a comprehensive explanation on the data-input process somewhere. Not sure if it already does or still needs to be created.

**Comment by christian-rli** [comment]
This is no longer an issue. All table creations are done via the api and are visible in dataview (unless they are created in the sandbox schema, which is left invisible on purpose). The reference from the tutorial repository meant to reference https://github.com/OpenEnergyPlatform/tutorial/issues/84
