### ISSUE TITLE
EnvI 2017 Feedback: Dataset Maintainer

### ISSUE THREAD

**Issue by gnn** [OpenEnergyPlatform/oeplatform#309]
While presenting the OEP at the EnvironInfo 2017, one feature potential data users requested was having a maintainer for a dataset, i.e. someone who can be contacted should a user have questions about or issues with a dataset. This might already be covered by dataset metadata, but I'm not entirely sure.

**Comment by Bachibouzouk** [comment]
@gnn - could you find out?

**Comment by MGlauer** [comment]
@Ludee Is this part of metadata version 1.4?

**Comment by Ludee** [comment]
Good question. This is not part of the new version 1.4.0.
We decided against it because we don't yet have a concept of what a "dataset maintainer" has to do.
We will put that on the list for the next metadata version.

**Comment by christian-rli** [comment]
On the OEP we now have dataset owners and user management to allow editing for other users. This can be seen as a dataset maintainer. I am therefore closing this issue. If a new, different or clearer definition of a role comes up, it can be discussed in a new issue.
