### ISSUE TITLE
Moving the OEP to its own GitHub group

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#310]
There was a discussion about moving the **oeplatform** repo to its own GitHub organisation to better manage and display the development in different project besides _open_eGo_.
There was some additional development in the project _open_FRED_ (with its own repo) and there will be more development from the new project _SzenarienDB_. To avoid redundancy and reduce confusion with different organisations and repos I suggest to move the OEP (code, tickets etc.).

We can use this reboot to reorganise the organisational structures and implement for example a **steering committee**. The new home is reserved and ready to get furnished:
https://github.com/orgs/OpenEnergyPlatform/

Of course all participants of the OEP should agree.

**Comment by beritRLI** [comment]
Agree absolutely! Thanx for organising it Ludwig!

**Comment by wolfbunke** [comment]
Hi together, 

I think for the further development a moving of the source-code to an own Github organisation could be a good idea. But past and ongoing projects and work should be visible written into the the new Organisation (readme, wiki). Maybe a Project history would be nice or?
 
Technical following issues and questions should be minded:
* Note in old repository where we moved to 
* How to move the existing issues and conversation?
** Copy all open issues and link to old issues?
** How to deal with closed issues?
*...

**Comment by gplssm** [comment]
Makes sense from my far-away-perspective! :rocket:

**Comment by Ludee** [comment]
New link:
https://github.com/OpenEnergyPlatform/oeplatform
