### ISSUE TITLE
API for adding meta data

### ISSUE THREAD

**Issue by wingechr** [OpenEnergyPlatform/oeplatform#314]
Can we also upload meta data via the api? Currently, it only seems to be possible on the platform via forms.

**Comment by christian-rli** [comment]
API and dialect don't support uploading metadata yet, unfortunately. Implementation is high priority.

**Comment by christian-rli** [comment]
"Implement API-support for metadata" - User Feedback
RequirementSpecificationID=17

**Comment by wingechr** [comment]
first draft (without validation of metadata) implemented in 21b72eb93f5fa232d

**Comment by Bachibouzouk** [comment]
@wingechr, @MGlauer if you are working on this, could you push the branch containing your work and link it to this issue?

**Comment by MGlauer** [comment]
This was delayed due to #484 and #502. Now I can go back to testing this

**Comment by MGlauer** [comment]
Closed in #477
