### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by Christian-Winzer** [OpenEnergyPlatform/oeplatform#316]
Hi there,
it seems the links pointing from the following page: 
https://github.com/OpenEnergyPlatform/oeplatform/wiki
to  "requirement_oep-api.yml" and "Jupyter Notebooks" are broken!
many greetings, Christian

**Comment by klarareder** [comment]
I think the list item nr. "7 Download the Jupyter Notebooks" can be removed entrirely. On the homepage they say that with installing Anaconda3 you automatically have Jupyter Notebooks, see: https://jupyter.org/install

**Comment by klarareder** [comment]
I fixed the link to the requirement_oep-api.yml, that is woking now

**Comment by christian-rli** [comment]
I think 7 referred to our tutorials for the API, at least the broken link seemed to point to the old location of those tutorials. I updated the link.

**Comment by Christian-Winzer** [comment]
yep, I meant the tutorial. Both links now work fine - many thanks :-)!

**Comment by mstappel** [comment]
My collegue found that the link to the OEP login (nr 6) is broken now. So I reopen this issue.
Thanks for help!

**Comment by christian-rli** [comment]
I fixed the broken link, checked all other links on that page and fixed another dead one.
