### ISSUE TITLE
Error message im dataviewer

### ISSUE THREAD

**Issue by wingechr** [OpenEnergyPlatform/oeplatform#317]
## Error: 
beim Aufrufen bestimmter Seiten im dataviewer kommt es zur Fehlermeldung (javascript alert): `Request failed: parsererror`

## Steps to reproduce
Im Browser (Firefox) die url aufrufen: `https://openenergy-platform.org/dataedit/view/model_draft/example_dialect_table`

**Comment by wingechr** [comment]
Es **scheint** wohl dann aufzutreten, wenn noch keine Daten hochgeladen wurden.

**Comment by nesnoj** [comment]
JS message `Request failed: rerror` also pops up when you try to filter datasets, e.g.
https://openenergy-platform.org/dataedit/view/grid/ego_dp_mv_griddistrict
Reproduce: Filters -> Add filter -> Field `version`, Filter type `value` -> any value, e.g. `0.4.5`
