### ISSUE TITLE
Filtering Data

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#321]
As a   user I want to filter data (across all data) to find data.

**Comment by christian-rli** [comment]
RequirementSpecificationID=7

**Comment by jh-RLI** [comment]
@MGlauer @christian-rli The "2019-01-15_Pflichtenheft_Arbeitsaufteilung_Fazit" indicates that this has already been done. Can this be closed?

**Comment by christian-rli** [comment]
I don't see how the file indicates that @jh-RLI . In any case I tried the filter and search functions and they were not functional in with my tests.

**Comment by jh-RLI** [comment]
@christian-rli in the file in tab "Bearbeitungsvorschlag" there is the column "Anmerkung" in the row for RequirementSpecificationID=7 there is a checkmark.  I thought that meant this issue was solved.

**Comment by christian-rli** [comment]
Sorry @jh-RLI . That column was ambiguous. Checkmarks in there only meant that a person in charge was selected.

**Comment by christian-rli** [comment]
A free filter across all data was considered unfeasible, filtering by tags is possible to implement and being worked on. Details of work with the tags are in issue #614 . This issue will be resolved with #600
