### ISSUE TITLE
[Specification Sheet] Search Scenarios with keywords

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#322]
As a user, I would like to search for keywords in the metadata in order to get suitable scenarios displayed.

(This is a meta-issue, developed at a specification sheet workshop. The following issues contributed to it's creation. This issue can be closed when all sub-issues get closed and vice versa)

https://github.com/OpenEnergyPlatform/oeplatform/issues/166
https://github.com/OpenEnergyPlatform/oeplatform/issues/294
https://github.com/OpenEnergyPlatform/oeplatform/issues/117

**Comment by christian-rli** [comment]
RequirementSpecificationID=56

**Comment by MGlauer** [comment]
Metadata has been includes in the platform-wide search
