### ISSUE TITLE
filter row/ column

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#323]
As a   user, I want to filter columns/rows to display only parts of a data set.

**Comment by christian-rli** [comment]
RequirementSpecificationID=8

**Comment by jh-RLI** [comment]
@MGlauer @christian-rli The "2019-01-15_Pflichtenheft_Arbeitsaufteilung_Fazit" indicates that this has already been done. Can this be closed?

**Comment by MGlauer** [comment]
Has been solved in dccd6cf4e
