### ISSUE TITLE
download filtered dataset

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#324]
As a user, I would like to be able to download a filtered dataset.

**Comment by christian-rli** [comment]
RequirementSpecificationID=14

**Comment by jh-RLI** [comment]
@MGlauer @christian-rli The "2019-01-15_Pflichtenheft_Arbeitsaufteilung_Fazit" indicates that this has already been done. Can this be closed?

**Comment by MGlauer** [comment]
Yes, the API has such functionality, but there is no web interface
