### ISSUE TITLE
generate tables

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#326]
As a   user, I would like to generate tables myself to store my own data.

**Comment by christian-rli** [comment]
RequirementSpecificationID=9

**Comment by jh-RLI** [comment]
@MGlauer @christian-rli The "2019-01-15_Pflichtenheft_Arbeitsaufteilung_Fazit" indicates that this has already been done. Can this be closed?

**Comment by Dhruvin14** [comment]
@christian-rli I stored the new table on OEplatform in my test of this issue.  Could you please look into it?

**Comment by christian-rli** [comment]
Thank you for looking into this @Dhruvin14 . I can confirm :)
