### ISSUE TITLE
view multiple scenarios at the same time

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#330]
As a   user, I would like to view different scenarios at the same time in order to   be able to compare scenarios.

**Comment by christian-rli** [comment]
Project meeting Feedback: "check pyam".

RequirementSpecificationID=64

**Comment by MGlauer** [comment]
Scenarios are too heterogeneous to implement this. Scenario factsheets are implemented in #618. Two scenarios would need alignment which exceed the current scope.
