### ISSUE TITLE
search text in a dataset

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#332]
As a   user I want to search for texts to find single entries in a dataset.

**Comment by christian-rli** [comment]
In order to make the scope feasible, search functionality is limited to one table at a time. 
RequirementSpecificationID=52

**Comment by klarareder** [comment]
Here the sql query to search text thoughout a whole table:

`SELECT * FROM schema.table_name
WHERE to_tsvector(table_name::text) @@ to_tsquery('search text');`

I tested it on a table with 26658 rows and it worked fine, but on a table with 19278808 rows it did not terminate in a reasonable time. I see two options:

1.    I guess it would be good to have first a count of rows:

`SELECT count(*) FROM schema.table_name;`

And if the count is larger than X a popup that no search can be performed.
Not so nice if that happens to someone looking for something...

2.    Different sql query which is faster. - But in the table with 19278808 rows I can not even perform a simple select in a decent time, so I think that would only be possible if we would know the column the value should be in.

**Comment by MGlauer** [comment]
Long request times must be expected in this regard. But I guess we could go with an asynchonous approach (AJAX). So, as soon as a matching row is found, we plot it (I'm not sure, whether this is already the case).
Another approach is to index large tables - which makes things faster, but requires *a lot* of physical storage (O(n*log(n))) for an uncommon usecase.
It might be that the long request times stem from the calculation of text search vectors. We could [add new meta-columns that contain the pre-vectorised text](https://blog.lateral.io/2015/05/full-text-search-in-milliseconds-with-postgresql/). This might yield the benefit of faster queries without non-linear increase in disk consumption.

**Comment by klarareder** [comment]
The second options sounds nice, but on envery update one has to call the function that triggers the optimized search. I think as in our case users are able to update the tables it might very easily be forgotten to do this and makes the update more complicated. Hence, I would prefer option 1. I don't know if a matching row is directly displayed. When we incorportate the SQL query we can check how it is done, and maybe it already is the way we want it.

**Comment by Dhruvin14** [comment]
@MGlauer  
Which approach is appropriate for the large database?

**Comment by MGlauer** [comment]
*IF* we limit the indexing to Columns that contain just text (`TEXT`, `VARCHAR`, etc) solution 2 would be the best. BUT: As @klarareder pointed out, this has to be updated after every change and updating the whole index might take long - depending on how it is implemented. 

Indexes spanning multiple tables are not possible in any current SQL-Dialect that I know. Therefore we have following possibilities:

1. Materialized View: A view that collects the ts_vectors for all tables in the OEP. Easy to implement but updating this might take an eternity.
2. A table that does the same as 1.: We have a table that keeps track of all the ts_vectors. After updating a table, we just have to update the table containing the data of this table.
3. Something else: If we want to add NLP-functionalities like synonym-search and so on, we should look for third-party solutions like ElasticSearch etc.

**Comment by Dhruvin14** [comment]
As of 1st and 2nd, both approaches take lot processing time while updating a table using ts_vectors so; we could have an only 3rd possibility for searching a text in large dataset!

**Comment by christian-rli** [comment]
It is already possible to search for text using the filter options below any given table. The column will have to be specified. However, having free search over all columns is not mentioned in the requirement. Can this issue be closed or is a search across all columns needed first?
