### ISSUE TITLE
Cells should only allow one value

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#333]
As a   user, I would like to enter exactly one value for each cell so that the   assignment is unique.

**Comment by christian-rli** [comment]
RequirementSpecificationID=3

**Comment by Bachibouzouk** [comment]
@klarareder - Could the issue be described a little bit further? (with snap shots if possible?)

@christian-rli - What do you mean by "RequirementSpecificationID=3" ?

**Comment by christian-rli** [comment]
> @christian-rli - What do you mean by "RequirementSpecificationID=3" ?

See #394 for a full list of all RequirementSpecificationIDs and descriptions.

**Comment by MGlauer** [comment]
The platform allows only single values per column, unless someone uploads a string or JSON data.
