### ISSUE TITLE
convert units in db

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#334]
As a   user, I would like to convert units in the database to suit my preferred   format.

**Comment by christian-rli** [comment]
RequirementSpecificationID=70

**Comment by l-emele** [comment]
See also issue #408.

**Comment by MGlauer** [comment]
Unit conversions are not supported by the OEP, as units are to heterogeneous - especially different metrics for monetary values.

**Comment by MGlauer** [comment]
A [paper on unit conversion](https://zenodo.org/record/3957445#.X3MYp3ZfjLI) ha been created

**Comment by MGlauer** [comment]
And a [table for unit conversions](https://openenergy-platform.org/dataedit/view/reference/szenariendb_conversion) has been published
