### ISSUE TITLE
error in case of wrong format at upload

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#335]
As a   user, I want an error to be reported to me when I upload a wrong format.

**Comment by wingechr** [comment]
Can someone please clarify this: 

* What is the `wrong` format?
    * data types
    * number of columns
    * json data structure?

**Comment by stap-m** [comment]
I found this comment in Redmine: 
"Beim Hochladen von Float in eine Integer Spalte kommt keine Fehlermeldung -> hierfür muss ein parser erstellt werden, der überprüft, ob der Datentyp passt"

**Comment by Dhruvin14** [comment]
so that means when a user adds float data an integer datatype column then it converts into the integer value, but we want an error and it should not happens.

**Comment by stap-m** [comment]
Yes. When a user adds float data into an integer column, no error message occurs. But there should be an error message. 
A parser is needed to check if the datatype is matching.

**Comment by MGlauer** [comment]
The API emulates a SQL-interface as implemented by SQLAlchemy. There are no error messages because there are none in these cases. All error messages that occur are passed to the user or caught and handled by the OEP (i.e. HTTP 400).

**Comment by MGlauer** [comment]
Possible HTTP 400 errors should be documented (Tutorials?)

**Comment by MGlauer** [comment]
A paper on unit conversions has been created

**Comment by christian-rli** [comment]
I added a section on http status codes to the API documentation. Once merged this closes the issue.
