### ISSUE TITLE
only allow complete scenarios

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#336]
As a   user, it is important for me that scenarios can only be imported if they are   complete (according to OEP definition), so that I have transparency and   comparability of assumptions and results.

**Comment by christian-rli** [comment]
Still requires a definition of completeness.

RequirementSpecificationID=45

**Comment by MGlauer** [comment]
There is no such thing as a "complete scenario"

**Comment by MGlauer** [comment]
We will implement Bundles that cover a complete scenario and tie all the elements of a scenario together. A minimalist version of bundles will be implemented as part of #618
