### ISSUE TITLE
Not possible to upload data as datapackages

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#338]
As a   user, I would like to upload my data as a datapackage, as I manage metadata   and data together.

**Comment by christian-rli** [comment]
RequirementSpecificationID=34

**Comment by MGlauer** [comment]
Metadata tool is in development and will be integrated into the OEP. The oem2orm tool allows the creation of tables from an existing metadata string. Data packages are not supported by the *OEP frontend* as they conflict with the existing metadata review process.

**Comment by christian-rli** [comment]
There are instructions on how to upload a datapackage (i.e. a csv table plus oemetadata file) here: https://github.com/OpenEnergyPlatform/tutorial/blob/develop/upload/OEP_Upload_Process_Data_and_Metadata_oem2orm.ipynb . A frontend implementation will have to wait for an overhaul of the review process. However it _is_ possible and documented how to upload a datapackage. Therefore closing this issue
