### ISSUE TITLE
[Specification Sheet] There is no Store of Access Statistics

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#340]
Implement anonymous OEP Access statistics.

**Comment by christian-rli** [comment]
"Store access statistics." 
RequirementSpecificationID=31

**Comment by Bachibouzouk** [comment]
@christian-rli is this still an issue, or would it be closed by closing #182 ?

**Comment by christian-rli** [comment]
This is a separate issue from #182 . This issue is to implement statistics and not the traffic light system. In 182 I quoted directly from a user's feedback which resulted in the creation of several issues. Sorry if that was confusing in the mass of issues. 

Have a look at #394 for a full list of all requirement specification descriptions.

**Comment by MGlauer** [comment]
This is done by the webserver and should not be part of the platform code.
