### ISSUE TITLE
[Specification Sheet] Enhance Metadata View

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#341]
Enhance metadata view by implementing descriptive „?“-buttons and a retractable view.

(This is a meta-issue, developed at a specification sheet workshop. The following issues contributed to it's creation. This issue can be closed when all sub-issues get closed and vice versa)

- [x] https://github.com/OpenEnergyPlatform/oeplatform/issues/298

- [x] https://github.com/OpenEnergyPlatform/oeplatform/issues/161

- [ ] https://github.com/OpenEnergyPlatform/oeplatform/issues/168

**Comment by 4lm** [comment]
I'm improving the metadata edit view and this issue seems the right issue for it. Work is done on this branch: https://github.com/OpenEnergyPlatform/oeplatform/tree/feature/improve-meta-edit-view-ux

**Comment by jh-RLI** [comment]
We don't need the meta theme anymore. There will be a restructuring of the Databse/Dataedit pages, which is currently in the design phase. Related topics will be collected and managed via GitHub projects.
