### ISSUE TITLE
[Specification Sheet] Fix all dead Links

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#342]
"As a user I always want to click on working hyperlinks to avoid getting into 404." - user feedback

Create, or repair broken Links to tutorials, glossary, papers, references.

(This is a meta-issue, developed at a specification sheet workshop. The following issues contributed to it's creation. This issue can be closed when all sub-issues get closed and vice versa)

https://github.com/OpenEnergyPlatform/organisation/issues/7
https://github.com/OpenEnergyPlatform/oeplatform/issues/257
https://github.com/OpenEnergyPlatform/oeplatform/issues/316
https://github.com/OpenEnergyPlatform/oeplatform/issues/316
https://github.com/OpenEnergyPlatform/oeplatform/issues/259

**Comment by jh-RLI** [comment]
I'm gonna work on #259. Is the topic list uptodate @christian-rli? Otherwise this would be the last except the continuous update for tutorial links.

**Comment by christian-rli** [comment]
Thank you @jh-RLI . The list should be up to date and this issue can be closed, once completed.

**Comment by jh-RLI** [comment]
this can be closed after #418 is approved
