### ISSUE TITLE
bulk download

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#344]
As a   user, I would like to be able to download data via bulk so that I don't have   to execute the same click routine over and over again.

**Comment by christian-rli** [comment]
RequirementSpecificationID=66

**Comment by christian-rli** [comment]
Bulk downloads are possible using the API. Several helper tools are available for this now, for example the [oep-client](https://github.com/wingechr/oep-client), [saio](https://github.com/coroa/saio) and [oem2orm](https://github.com/OpenEnergyPlatform/data-preprocessing/tree/feature/oep-upload-oem2orm/data-import/oep-upload). Download tutorials are collected in the [tutorial repository](https://github.com/OpenEnergyPlatform/tutorial/blob/master/download ).

@wingechr what additional steps are needed to close this issue?

**Comment by han-f** [comment]
Bulk means several tables at once? I.e. a user selects several tables at once and can then download these together at once?
If this does not explicitly need a web-interface, then I assume this issue can be closed as @christian-rli mentions the availability of the tools. 
So the main question from my side would be: does the initial comment refer explicitly to a possibility to use the frontend to select multiple tables for download?

E.g. having selection buttons to select all of these tables at once?  https://openenergy-platform.org/dataedit/view/scenario?query=&tags=185

**Comment by wingechr** [comment]
I don't think we should have a download button for all tables of a specific tag. That would create a lot of workload (probably accidentally) for very generic tags

**Comment by christian-rli** [comment]
My interpretation of the initial comment is that the question clearly arose in the front end. Whether or not the solution needs to live in the front end as well, appears to be open, at least the way I read it. There is a technical solution, so I believe you can decide if you want to build a front-end solution that allows table selection, or if you're happy with the status quo. A compromise solution could be an info at an appropriate location that references to one of the api/download descriptions.

**Comment by wingechr** [comment]
* front end solution: we decided against it (too much data, not compliant with REST api specification)
* client side: with the API or the oep-client, multiple tables can easily be downloaded
