### ISSUE TITLE
bulk upload

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#345]
As a   user, I would like to be able to upload data via bulk so that I don't have to   repeat the same click routine over and over again.

**Comment by christian-rli** [comment]
RequirementSpecificationID=67

**Comment by wingechr** [comment]
I think with the latest speedup, the API upload qualifies as "bulk", and with help of additional tools like the "oep-client", this can be simplified even further to a single CLI command.

So I think we can close this.
