### ISSUE TITLE
csv wizard to upload data

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#346]
As a   user I would like to use a wizard to upload csv files in order to use the   scenariosDB without any technical precognition.

**Comment by christian-rli** [comment]
RequirementSpecificationID=10

**Comment by MGlauer** [comment]
The API supports csv-upload since 5822f1b12 but there is no web-interface, yet.

**Comment by han-f** [comment]
@wingechr will look into making a prototype for the webinterface if this helpful as a next step.

**Comment by wingechr** [comment]
* Step 1: allow api POST for new rows to accept raw csv text: `?form=csv` 
* Step 2: Upload form in web interface
* Step 3: More customization options ?

**Comment by wingechr** [comment]
A simple version of Step 1 is implemented  in https://github.com/OpenEnergyPlatform/oeplatform/tree/feature/csv-upload-346

**Comment by wingechr** [comment]
I committed the first working version in the branch.

It works completely in the users browser and submits the parsed data via the API, authenticated by the current CSRF-Token.

## FEATURES
* text encoding and separator selection
* basic column value parsing
* column name change
* preview

## TODOS
* disable/hide button if user has no writing permissions on table (this is not a security issue)
* check column names match with table structure
* provide example csv based on table structure

**Comment by han-f** [comment]
We will need to add explanatory text as mouse overs. I also assign myself.

**Comment by han-f** [comment]
We will need to translate the current version to english.

**Comment by wingechr** [comment]
finished with https://github.com/OpenEnergyPlatform/oeplatform/pull/632
