### ISSUE TITLE
default schema in csv upload wizard

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#348]
As a   user, I want to be able to display a default profile for a table schema in   the upload wizard so I don't have to recreate them each time.

**Comment by christian-rli** [comment]
RequirementSpecificationID=68

**Comment by han-f** [comment]
We would interpret this as providing in the CSV webinterface a link to an empty CSV file that holds as inspiration a "proper" structure (database friendly)  that users could then use to build their upload file.

**Comment by han-f** [comment]
Related to 
https://github.com/OpenEnergyPlatform/tutorial/issues/21
and to #346

**Comment by christian-rli** [comment]
I'm not sure if it's significantly more work, but I do believe, it would be quite a bit more user-friendly to build something like a file drop-off point, where users can upload their csv-files. If the structure is database compatible, it just uploads to the oedb. A fancy version could let the user select a data format for specific columns, if they can be interpreted in more than one way. If the structure is not datbase-compatible, a helpful error message can return a possible reason why that might be so. 

That's how I would interpret an upload wizard. But you might decide that this is not feasible.

**Comment by wingechr** [comment]
I am currently working on the simple version: https://github.com/OpenEnergyPlatform/oeplatform/issues/346

**Comment by wingechr** [comment]
fisnihed with https://github.com/OpenEnergyPlatform/oeplatform/pull/632
