### ISSUE TITLE
tool to convert poorly formatted data into stacked data

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#350]
As a   user, I would like a tool to be made available to me in the case of numbers   as column names, so that stacked data can be created from my data so that I   do not have to do this manually.

**Comment by christian-rli** [comment]
@Ludee already developed a tool for this. It would only need a nice tutorial to go with it. See https://github.com/OpenEnergyPlatform/examples/issues/8 for the other tutorial tasks. 

RequirementSpecificationID=59

**Comment by Ludee** [comment]
https://github.com/OpenEnergyPlatform/examples/blob/master/api/df_normalize_denormalize.ipynb

**Comment by klarareder** [comment]
@Ludee in denormalizing you commented: ```
# in some cases pivot_table() is problematic. 
# So unstack() can be also used for denormalizing via:
```
could you add what are those cases?

**Comment by oakca** [comment]
@klarareder I was the one who commented that. So the case:

You have a table in excel, where you have no values under a column (basically empty), the value of it changes in pandas to `NaN`:

```
df
    Site Storage Commodity  inst-cap-c  ...  depreciation  init  discharge  ep-ratio
0    Mid    Pump      Elec           0  ...            50     1   0.000003       NaN
1  South    Pump      Elec           0  ...            50     1   0.000003       NaN
2  North    Pump      Elec           0  ...            50     1   0.000003       NaN
```

After normalizing it looks like following:

```
df_normalized
     Site Storage Commodity     parameter         value
0     Mid    Pump      Elec    inst-cap-c  0.000000e+00
...
18    Mid    Pump      Elec      ep-ratio           NaN
```

So in this case `ep-ratio` value is `NaN`, and if you use `pivot_table()` on `df_normalized`, basically the parameter `ep-ratio` is removed. In the end you get something like following:

```
df_denormalized
    Site Storage Commodity  inst-cap-c  ...  depreciation  init  discharge
0    Mid    Pump      Elec           0  ...            50     1   0.000003
1  South    Pump      Elec           0  ...            50     1   0.000003
2  North    Pump      Elec           0  ...            50     1   0.000003
```

That is why I commented `in some cases pivot_table() is problematic`. There are following ways to approach this:

1. I can change the string `in some cases pivot_table() is problematic` to `as an alternative`
2. I can remove the `pivot_table()` part, but maybe in some cases `unstack()` won't work so...

Which one would you prefer? **Keep in mind there are also other cases which I did not experience before, and can broke both of the `pivot_table()` and `unstack()` sadly.** Writing a generalized function for every df is kinda impossible. So maybe keeping the `pivot_table()` part would make sense.

**Comment by klarareder** [comment]
@oakca thank you for the very nice explanation. I would keep both options and write: 

> In case of columns containing only NaN values, pivot_table will omit these columns in the denormalized table. Hence, in this case another option is to use unstack().

Maybe it would be good to also enter in the end something like:

> Please check your final table, depending on your data it might not always work as expected.

**Comment by oakca** [comment]
@klarareder I pushed it. The sad thing is I thought this issue was opened in `OEP/examples`, I gave the issue number as #350 in the commit.

Here is the commit https://github.com/OpenEnergyPlatform/examples/commit/2e42c5740aa14d3489b28ec25360e0e59ef35e19

**Comment by klarareder** [comment]
@SzenarioDB Team: I made a first test tutorial for this issue. It can be found in the Filr.

**Comment by christian-rli** [comment]
tool and description are available. closing this issue
