### ISSUE TITLE
Urgent issues to publish data in the project oemof_heat and general feedback to OEP

### ISSUE THREAD

**Issue by c-moeller** [OpenEnergyPlatform/oeplatform#358]
Hello OEP-Team, the project oemof_heat needs to publish example data sets for their scenarios till December/January and we had an intense workshop this week where we discussed the necessary steps. There are some open issues we urgently have to discuss with you to make sure the example data sets will find their way to the OEP. I've already talked to @Ludee and will setup a meeting with him. We also gatherd some general feedback. I guess, most of the stuff is already open issues, but still might be interesting.

The following is the urgent issues (general feedback is below):

---------------------------------------------------------------------------------------------
Vor der Veröffentlichung des Beispieldatensatzes sind in Zusammenarbeit mit den Entwicklern der OEP/Projektmitarbeitern von SzenarienDB sind noch einige Fragen zu klären:
- in welches Schema der OEP werden unsere Datensätze geladen (scenarios?)? Beeinflusst das die von uns definierten Schemata und Kategorien?
Zunächst in model_draft (oder Sandbox). Zielschema wird im Dateinamen angegeben. Im Laufe des Reviews werden die Daten in das zugehörige Schema sortiert, siehe hier (orientiert an ISO-Norm):
https://wiki.openmod-initiative.org/wiki/Database_schema#v0.2_.28current_version.29
Review: https://github.com/OpenEnergyPlatform/data-preprocessing/wiki

- Welche Lizenz wird für die Veröffentlichung empfohlen?
siehe License-Matrix. Am besten geeignet ist CC BY 4.0.

- Der Beispieldatensatz enthält eine Zeitreihe von AGFW. Wir fragen bei AGFW an, ob Daten (Zeitreihe) unter Lizenz veröffentlicht werden darf. Dabei AGFW einen Vorschlag zu Art der Lizenz unterbreiten (welche wird empfohlen?)
AGFW muss nachweisen, dass sie die Urheber sind.
Wir machen einen Vorschlag zur Lizensierung (Metadaten in Form von TASL).
AGFW muss Einverständnis zur Lizensierung geben.

- Wir benötigen einen Textbaustein für die Veröffentlichung, der auf die Daten verweist und auf Open Source/Open Science thematisiert. --> Gibt es hier bereits Veröffentlichungen, die ähnliches gemacht haben und an denen wir uns orientieren können?
EGO-Paper (Hülk 2017 Allocation). https://journals.aau.dk/index.php/sepm/article/download/1833/1531/
http://iopscience.iop.org/article/10.1088/1742-6596/977/1/012007
Im Text kann auf das Tag verwiesen werden (Beispiel siehe hier: https://reiner-lemoine-institut.de/wp-content/publications/20170306_Gruene_Studie_BB/Untersuchungen_zur_Energiestrategie_2030.pdf)

- Wer hat Schreibrechte auf der OEP? Ist Factsheet von allen editierbar? Können Schreibrechte festgelegt werden? Es gibt noch Vorbehalte bei Projektpartnern hinsichtlich der Veröffentlichung unserer Daten bei globalen Schreibrechten. --> Gibt es hier bereits Veröffentlichungen, die ähnliches gemacht haben und an denen wir uns orientieren können?
Ja. Das ist der Sinn einer gemeinschafltich genutzen Platform. Man muss eingeloggt sein. Änderungen werden getrackt.

Unterscheidung zwischen Factsheets und Daten:
- Daten können nach abgeschlossenem Review nur mittels eines PR von den Datenownern genehmigt verändert werden.
- Factsheets können von allen verändert werden (wie Wikipedia).

- Bleibt die URL eines Factsheets dauerhaft konstant? Wenn ja, könnte bis zur Veröffentlichung am 15.12. dieser Link feststehen und ins Paper einfließen. Die Daten selbst könnten dann auch noch bis Februar hochgeladen werden.
Ja. 
---------------------------------------------------------------------------------------------
Allgmeines Feedback an OEP:
- Es ist grundsätzlich toll, Daten einfach runterladen zu können (unter anderem über Code-Zeilen, die ich auch direkt in mein Skript einbinden kann)
- [x] Links zu den Tutorials auf der Startseite funktionieren nicht. Resolved.
- [x] unter Database, Dataview sind Links zu Tutorials angegeben (zB find data). funktioniert nicht
- grundsätzlich ist für den Nutzer keine Struktur zu erkennen, wo Daten gefunden werden können.
- Unter Data-Views ist die Struktur unintuitiv, der Zusammenhang zwischen Database und Factsheet auch (Dort könnte erklärt werden, wie der Zusammenhang zwischen Database und Factsheet ist (über Tags)).
- Aktueller Stand ist gut nutzbar, um Daten hochzuladen. Jedoch nicht gut genug nutzbar, um es in Papern etc. zu verbreiten als Projektteam.
- Factsheet kann jeder bearbeiten. Ist es möglich, das zu sperren? Nein, das ist so vorgesehen, s.o.

**Comment by jnnr** [comment]
> Hello OEP-Team, the project oemof_heat needs to publish example data sets for their scenarios till December/January and we had an intense workshop this week where we discussed the necessary steps. There are some open issues we urgently have to discuss with you to make sure the example data sets will find their way to the OEP. I've already talked to @Ludee and will setup a meeting with him. We also gatherd some general feedback. I guess, most of the stuff is already open issues, but still might be interesting.
> 
> The following is the urgent issues (general feedback is below):
> 
> Vor der Veröffentlichung des Beispieldatensatzes sind in Zusammenarbeit mit den Entwicklern der OEP/Projektmitarbeitern von SzenarienDB sind noch einige Fragen zu klären:
> 
>     * in welches Schema der OEP werden unsere Datensätze geladen (scenarios?)? Beeinflusst das die von uns definierten Schemata und Kategorien?
> 
>     * Welche Lizenz wird für die Veröffentlichung empfohlen?
> 
>     * Der Beispieldatensatz enthält eine Zeitreihe von AGFW. Wir fragen bei AGFW an, ob Daten (Zeitreihe) unter Lizenz veröffentlicht werden darf. Dabei AGFW einen Vorschlag zu Art der Lizenz unterbreiten (welche wird empfohlen?)
> 
>     * Wir benötigen einen Textbaustein für die Veröffentlichung, der auf die Daten verweist und auf Open Source/Open Science thematisiert. --> Gibt es hier bereits Veröffentlichungen, die ähnliches gemacht haben und an denen wir uns orientieren können?
> 
>     * Wer hat Schreibrechte auf der OEP? Ist Factsheet von allen editierbar? Können Schreibrechte festgelegt werden? Es gibt noch Vorbehalte bei Projektpartnern hinsichtlich der Veröffentlichung unserer Daten bei globalen Schreibrechten. --> Gibt es hier bereits Veröffentlichungen, die ähnliches gemacht haben und an denen wir uns orientieren können?
> 
>     * Bleibt die URL eines Factsheets dauerhaft konstant? Wenn ja, könnte bis zur Veröffentlichung am 15.12. dieser Link feststehen und ins Paper einfließen. Die Daten selbst könnten dann auch noch bis Februar hochgeladen werden.
> 
> 
> Allgmeines Feedback an OEP:
> 
>     * Es ist grundsätzlich toll, Daten einfach runterladen zu können (unter anderem über Code-Zeilen, die ich auch direkt in mein Skript einbinden kann)
> 
>     * Links zu den Tutorials auf der Startseite funktionieren nicht
> 
>     * unter Database, Dataview sind Links zu Tutorials angegeben (zB find data). funktioniert nicht
> 
>     * grundsätzlich ist für den Nutzer keine Struktur zu erkennen, wo Daten gefunden werden können.
> 
>     * Unter Data-Views ist die Struktur unintuitiv, der Zusammenhang zwischen Database und Factsheet auch (Dort könnte erklärt werden, wie der Zusammenhang zwischen Database und Factsheet ist (über Tags)).
> 
>     * Aktueller Stand ist gut nutzbar, um Daten hochzuladen. Jedoch nicht gut genug nutzbar, um es in Papern etc. zu verbreiten als Projektteam.
> 
>     * Factsheet kann jeder bearbeiten. Ist es möglich, das zu sperren?

**Comment by Ludee** [comment]
At the current version this is not possible. The information for each factsheet is not stored in the OEP. It is part of the internal OEP-Django-Database which is not under version control ATM. But of course there are regular backups.
It is a collaborative work and the model factsheets describe the current version of the model. I'm not sure what the additional benefit of a version control is. Until now we didn't experience any vandalism or trolls.

**Comment by jnnr** [comment]
Most of the questions have been answered (see initial posting). Therefore I close the issue.
