### ISSUE TITLE
Factsheet edits are not stored

### ISSUE THREAD

**Issue by jnnr** [OpenEnergyPlatform/oeplatform#361]
When editing an existing factsheet (in this case this one: https://openenergy-platform.org/factsheets/models/158/) and finally clicking "submit all", the changes are not applied. This seems to be a bug.

**Comment by Ludee** [comment]
This is quite urgent. Some partners are using the fs already:
e.g. http://openenergy-platform.org/factsheets/models/158/

Please fix ASAP. @MGlauer

**Comment by MGlauer** [comment]
Unfortunately, I can not reproduce this error :(
I edited the factsheet several times and no error occured. **But:** The server logs *do* tell me that something went wrong. I will look into this...

**Comment by MGlauer** [comment]
Oh, no. Could reproduce - working on it

**Comment by jakob-wo** [comment]
Is there any progress with that issue or any work-around? It happend to me again with a model fact sheet that I just created and now I cannot edit it (http://openenergy-platform.org/factsheets/models/160/). The model fact sheet neither appears when searching for it by the name or the acronym. I can only access it if I enter die URL (see above) directly. Is that behavior connected to "not saving edits"?

**Comment by Bachibouzouk** [comment]
@MGlauer - Is the branch [hotfix/save_factsheets_i361](https://github.com/OpenEnergyPlatform/oeplatform/tree/hotfix/save_factsheets_i361) the one related to this issue? Are you currently working on it or could I try on this issue?

Also, does the branch [feature/factsheet](https://github.com/OpenEnergyPlatform/oeplatform/tree/feature/factsheet) has anything to do with the issue? Can it be deleted?

Thanks :)

**Comment by MGlauer** [comment]
It seems that this error does not occur anymore.
