### ISSUE TITLE
Homepage: first page: Scenario log has no text

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#362]
Please include the appropriate text at the caption Scenario log

**Comment by Dhruvin14** [comment]
@stap-m, Which text need to be added here or is there documentation for that?

**Comment by stap-m** [comment]
'Scenario log' doesn't seem to be part of the front page anymore. 
This issue has to wait until the redesign is completed.

**Comment by Dhruvin14** [comment]
Can we close this issue? 
Is it needed to implement scenario log in the new design? @stap-m

**Comment by christian-rli** [comment]
This issue seems outdated and no longer relevant.
