### ISSUE TITLE
+ Button leads to page not found

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#363]
When navigation through the site, the + button does not work. How to reproduce:
1.) https://openenergy-platform.org/
2.) click on any of the links in the graphic, e.g. Framework Factsheet
3.) click on the green + behind the captionFramework Factsheet -> Error: Not Found The requested URL /accounts/login/ was not found on this server.

**Comment by MGlauer** [comment]
Can be reproduced. This happens only if the user is not logged in.

**Comment by MGlauer** [comment]
Has been closed in ca2e63d53
