### ISSUE TITLE
Define and implement Factsheets

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#368]
This is a meta level issue. Finalizing the definition and implementation of factsheets is a requirement for a range of other issues. "Define and implement Factsheets" is user feedback and part of the requirement specification. All issues that deal with Factsheets can be viewed here: https://github.com/OpenEnergyPlatform/oeplatform/issues?q=is%3Aopen+is%3Aissue+label%3Aspecification_sheet+label%3AFactsheets

RequirementSpecificationID=18

**Comment by jh-RLI** [comment]
WE implemented scneario bundles already.
