### ISSUE TITLE
Improve Preview Functionality

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#369]
"Enhance the map view. Enable preview of large numbers of polygons and automatically guess lat/lon columns." -User Feedback and part of the requirement specification. 

This is a meta Issue. Close it once https://github.com/OpenEnergyPlatform/oeplatform/issues/248, https://github.com/OpenEnergyPlatform/oeplatform/issues/125 and https://github.com/OpenEnergyPlatform/oeplatform/issues/299 are resolved.

RequirementSpecificationID=44

**Comment by klarareder** [comment]
@MGlauer reminder

**Comment by Dhruvin14** [comment]
@Bachibouzouk  Are these issues #248, #125, #299  related with new updates of Bootstrap 4?

**Comment by Bachibouzouk** [comment]
@Dhruvin14 - I am not sure, @MGlauer or @johannwagner might know better

**Comment by MGlauer** [comment]
This has been implemented during the redesign
