### ISSUE TITLE
Redesign of OEP-Layout

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#370]
"As a user, I would like to use an intuitive and attractive Interface to support my workflow." - User Feedback and part of the requirement specification.

See i.e: https://github.com/OpenEnergyPlatform/oeplatform/issues/134, https://github.com/OpenEnergyPlatform/oeplatform/issues/226 and https://github.com/OpenEnergyPlatform/oeplatform/issues/167. 

RequirementSpecificationID=71

**Comment by wingechr** [comment]
finished with #134, #226 and #167.
