### ISSUE TITLE
User blocked after reaching a connection limit

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#372]
After a while of using the API on and off for a few months, i.e. not excessively, the API seized to accept new connections, returning: "ConnectionException: This user exceeded the connection limit."

At first the problem resolved itself after a few hours and connections were accepted again. After another few connections the problem now appears to be permanent. There might have been a few unclosed connections initially, but in general I took care to close all connections that I opened, especially after the problem first occured.

I used the following type of code to create and close connections:

![bildschirmfoto zu 2019-02-04 10-34-46](https://user-images.githubusercontent.com/42000429/52200294-b632c080-2868-11e9-8d4f-85a3b14d00c6.png)

**Comment by henhuy** [comment]
Right now I'm using `transaction` package (https://transaction.readthedocs.io/en/latest/) to establish connection to OEP via oedialect. This includes a `transaction.manager` - a python context manager which automatically closes the connection at exiting the with clause. Maybe this is a safer way? See also: https://www.programcreek.com/python/example/62277/transaction.manager for more examples.

**Example:**

    import transaction

    with transaction.manager:
        session.add(series_1)
        session.add(series_2)

**Comment by christian-rli** [comment]
The problem was that open cursors accumulated, because calling sql-alchemy's close() method did not properly close connections to the OEDB. @MGlauer updated the oedialect so that this is no longer an issue. Thank you. Closing issue.
