### ISSUE TITLE
Create a sympathetic mascot for the OEP

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#385]
We decided for the [Platypus](https://en.wikipedia.org/wiki/Platypus). Because it is super sweet and the names match.

Images that could be used:

1. https://da.wikipedia.org/wiki/Fil:Malene.png
1. https://de.wikipedia.org/wiki/Datei:Platypus.jpg
1. https://pixabay.com/de/vectors/schnabeltier-tier-aussie-australien-153496/

**Comment by christian-rli** [comment]
Full name would of course be the OpenEnergyPlatypus... and it might go well with a super hero dress and a lightning logo. But I guess we should make do with any sketch we can get.

**Comment by nesnoj** [comment]
Although you already came to a decision: I like the matching name, but does a platypus represent the character of freedom and openness of the OEP? Compared to, let's say, a dove?

**Comment by christian-rli** [comment]
I agree with the idea that a dove represents freedom, but personally I associate it with peace - which is all well, but maybe not the focus of the OEP. Also, as far as banner animals go, it's a bit overused. Another kind of bird might have been good, but to speak out in favour of the platypus again: why not? It's peculiar and it's true to itself. Everybody can be cool and choose an eagle, not everybody has the character to pull off a platypus. I don't think we want to be normal. We want to be different (in a very specific way) and so is the platypus. A platypus might not really represent anything yet, so that's our chance to characterize it.

**Comment by bmlancien** [comment]
![20190704_151419](https://user-images.githubusercontent.com/33999424/60670651-7f8dc000-9e71-11e9-83a3-862df7a871a1.jpg)

First idea and mockup. The platypus in its natural habitat: the OEP :)

**Comment by bmlancien** [comment]
![2019_07_09_Platypus_Mascot](https://user-images.githubusercontent.com/33999424/60879418-dd3f5500-a241-11e9-87fc-c009307e86a1.png)

**Comment by bmlancien** [comment]
![2019_07_09_Platypus_Mascot_v2](https://user-images.githubusercontent.com/33999424/60890242-35368580-a25b-11e9-841d-9b354995cba9.png)

Without glasses this time, but with fur!

**Comment by bmlancien** [comment]
Should we stick to the Platypus with the fur + glasses? This is personally my favorite.

![404-Platypus](https://user-images.githubusercontent.com/33999424/61297098-c5387a00-a7db-11e9-88f9-8cb7b87487ff.png)

**Comment by Bachibouzouk** [comment]
@Ludee , @bmlancien - This issue can be closed I presume?

**Comment by christian-rli** [comment]
No strong feelings for or against glasses from me. A majority seems to like the glasses (so far). Any arguments that support a case against glasses @han-f ? 
@MGlauer @l-emele @wingechr @klarareder would you like to leave an emoji-vote?

**Comment by MGlauer** [comment]
Shall we use the `.png` versions or are there some other formats?

**Comment by bmlancien** [comment]
There is a `.svg` version but it's not ready to use, I would have to work on that. I would use the `.png` version for now, if possible:

![Platypus_Mascot](https://user-images.githubusercontent.com/33999424/97461011-99dc8e80-193d-11eb-8624-7cbab5d6ac68.png)

**Comment by christian-rli** [comment]
I think we successfully created a mascot. Can this issue be closed or should some files be moved to the repository?

**Comment by Ludee** [comment]
Also implement it in the error page (500.)
