### ISSUE TITLE
Activation mail not received, issues logging out when not activated

### ISSUE THREAD

**Issue by boltbeard** [OpenEnergyPlatform/oeplatform#389]
There seems to be a problem with the receipt of the activation E-mail. So far I have tried getting the activation e-mail sent to two different E-mails without success. I've waited for the activation link for about 14 hours till now, and nothing has come yet.

Somehow, I am also not able to log out of the account at all. The logout button doesn't seem to work as advertised :). I had to use two different [firefox containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) to log into two different accounts but now both of them won't log out.

Do let me know if you need more information.

**Comment by MGlauer** [comment]
Oh, you are right. There was a misconfiguration in the mail settings. It should be fixed now. 
I will also fix the login button issue

**Comment by Bachibouzouk** [comment]
- [ ] Email (fixed in 1173c517c605759d4fbcda5c77fa5bbaa13b6139)

- [ ] Login button

**Comment by Bachibouzouk** [comment]
@MGlauer - did you fix the login in another commit?

**Comment by MGlauer** [comment]
Yes, fixed in 0a6098e52
