### ISSUE TITLE
Error in serialization in api/search (on oeplatform clone)

### ISSUE THREAD

**Issue by wingechr** [OpenEnergyPlatform/oeplatform#397]
This error occurs on a clone of the platform.

**Error**: on the dataedit view, data that has been uploaded does not show up (it can be retrieved via the api though). 

**Origin**: the dataedit view uses a REST api call to api/search to retrieve the data, which fails. Internally it throws a serialization error:

```
 Traceback (most recent call last):
File "/var/www/oeplatform/api/encode.py", line 214, in _iterencode
  yield from _iterencode_dict(o, _current_indent_level)
File "/var/www/oeplatform/api/encode.py", line 188, in _iterencode_dict
  yield from chunks
File "/var/www/oeplatform/api/encode.py", line 109, in _iterencode_list
  yield from chunks
File "/var/www/oeplatform/api/encode.py", line 221, in _iterencode
  o = _default(o)
File "/var/www/oeplatform/env/lib/python3.5/site-packages/django/core/serializers/json.py",
  return super(DjangoJSONEncoder, self).default(o)
File "/usr/lib/python3.5/json/encoder.py", line 179, in default
  raise TypeError(repr(o) + " is not JSON serializable")
```

The problem can be fixed by replacing line 221 in `api/encode.py`
with 
```python
if isinstance(o, psycopg2.extensions.Column):
    o = o.name
else:
    o = _default(o)
```

However, it does not seem to be a problem on the main site http://openenergy-platform.org/

Information about the clone:

* Debian GNU/Linux 9
* PostgreSQL 9
* Virtualenv:
   * Python 3.5
   * alembic==1.0.11
   * Django==1.11.22
   * djangorestframework==3.9.4
   * GeoAlchemy2==0.4.1
   * psycopg2==2.8.3
   * SQLAlchemy==1.2.0
* oeplatform version:
   * tried with HEAD of `master` branch and `develop` branch as well as `tag/0.4.0` release version, all have the same issue
* DEGBUG=False

**Comment by MGlauer** [comment]
Interesting. I was not able to reproduce it. Now reinstalled each package manually and after reinstalling pyscopg2 I **am** able to reproduce. Hooray, I guess!?

Anyway, it seems the DBAPI of pyscopg changed. It works fine with psycopg==2.7.5

**Comment by wingechr** [comment]
Awesome! I can confirm, changing the `requirements.txt` to `psycopg2==2.7.5` works.
