### ISSUE TITLE
Cannot create scenario factsheet

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#400]
After having created a study and adding some scenario information the saving fails. The study is not listed, while it is available in the drop down menu when selecting "create new Study".  Selecting it from the drop down menu, however, does not result in
a) the previous data I had added to be shown
b) anything happening when clicking the "submit all" button. 

Where are the contents I had previously added and which I would like to continue working on?

**Comment by han-f** [comment]
If I open a private tab and log in again (so this seems to have been a local error) I can see the scenario I have created, but I cannot modify either the study or the scenario . 
* When I click modify study, the page throws an error
* When I click submit all after having modified scenario data, the page throws an error. 

![grafik](https://user-images.githubusercontent.com/36844029/61203386-81197c80-a6ea-11e9-80e4-bd2266506376.png)

**Comment by jh-RLI** [comment]
#457 is already solved and should be included in the next oep release
#519 is the same as your second comment on this issue, am I right? @han-f 
To avoid duplicate tissue, I would like to close this issue.

**Comment by han-f** [comment]
> #519 is the same as your second comment on this issue, am I right? @han-f
> To avoid duplicate tissue, I would like to close this issue.

Yes it is. Thanks!
