### ISSUE TITLE
Scenario factsheets in the future: fixed form or via ontology?

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#402]
Currently the factsheets follow a very fixed form that relates to a very specific modelling approach and do not allow for scenarios which follow other definitions as given. 

To discuss: 
Will the factsheet form be updated to allow for more generality and variety in the scenario data submitted, or will the factsheets be linked to the ontology in some way?

**Comment by han-f** [comment]
The scenario factsheets ideally follow the format we have used to record information about the scenarios we upload(ed) to the database. It lies in Filr under AP 5. Not sure whether we have another ticket on this or where we made this explicit. We had discussed it a few times during project meetings.

**Comment by christian-rli** [comment]
Seems like we're jointly working on an answer to this in the following weeks. I'm adding you @adelmemariani because you're likely to be in charge for the implementation.

**Comment by stap-m** [comment]
Via OEKG.
