### ISSUE TITLE
Dead link to opsd_power_plants_germany 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#403]
https://openenergy-platform.org/dataedit/view/orig_geo_opsd/opsd_power_plants_germany  leads to nowhere 

![grafik](https://user-images.githubusercontent.com/36844029/61632728-daa31d80-ac8d-11e9-8218-55bfe7d933ac.png)
 
![grafik](https://user-images.githubusercontent.com/36844029/61632696-c828e400-ac8d-11e9-9e4d-c3a43e3692e5.png)

**Comment by Ludee** [comment]
OPSD is not open data (has no open license). The table exists in the back-end but is not granted for public view! The "Not found" should be redirected to the metadata without data.

**Comment by Dhruvin14** [comment]
@Ludee and @han-f  It would be nice if you can describe the location of OPSD metadata so, I can fix the issue.

**Comment by jh-RLI** [comment]
@Ludee @han-f still relevant? Has the table perhaps been deleted?

**Comment by jh-RLI** [comment]
@Ludee In that case we use an empty table and add metadata (for now at least). Can you link the metadata?

**Comment by wingechr** [comment]
if it's not open data, it should not be on the oep, right?
