### ISSUE TITLE
Misleading heading in /dataedit/

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#404]
The heading in the tab of https://openenergy-platform.org/dataedit/  reads
"How to access our data". 
"our data" seems not the correct term for the data that the OEP provides access to; this may suggest that the OEP owns the data. 

It may be sufficient to write "Access data" or "How to access data" or simply "How to access the database" 

![grafik](https://user-images.githubusercontent.com/36844029/61699752-c7e72200-ad3b-11e9-8994-0faaa7642d8d.png)

**Comment by Dhruvin14** [comment]
Can I change it with "How to access the database"? @han-f

**Comment by han-f** [comment]
Yes, this sounds ok to me.
