### ISSUE TITLE
Create document for guidance

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#405]
Create one document that describes the whole process of how to contribute scenario data to the OpenEnergy Platform from the perspective of a new user.

**Comment by christian-rli** [comment]
Will it be a pdf? If it's not decided yet: it could just be another jupyter tutorial for which a [template](https://github.com/OpenEnergyPlatform/tutorial/tree/develop/template) exists. Maybe it helps.

**Comment by wingechr** [comment]
Chapter 1 and 2 of the document are still valid, but chapter 3 (factsheets) needs rework after the chanegs on the platform has been implemented. Currently, his is a little broken.

**Comment by han-f** [comment]
We have updated the document based on @Richard-Schmitz comments - many thanks for these. Apart from chapter 3 this should be thus ready for being added to the tutorials section. @christian-rli - could you please advise what to do? Could you also have a look at chapter 3 (its short) and see whether it is ok to upload it? Many thanks.

**Comment by christian-rli** [comment]
I had a look at chapter 3 and it looks good to me @han-f . As we discussed in our call the pdf is based on a word file that can easily be converted to mark-up. It can be copied into the tutorial creator on the OEP once the image upload works (again). So, unfortunately there is no easy publish button for pdfs and there will have to be some manual attention. Hopefully it's not too much of a bother.

**Comment by han-f** [comment]
We have added this to tutorials now, but still need to work a bit on formatting issues (e.g. python code displays correctly in preview, but not in final view).

https://openenergy-platform.org/tutorials/11/

**Comment by christian-rli** [comment]
Formatting should be a separate issue. The topic of this one has been addressed in my opinion :)
