### ISSUE TITLE
Interaction with tables not working

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#406]
Interacting with tables does not work (except the search function). Clicking _Filters_ or _Fields_ trying to filter the table for graphical representation leads to infinite loading.

![grafik](https://user-images.githubusercontent.com/36844029/61779138-6937ac00-ae00-11e9-801b-ebf1a7af740c.png)

**Comment by Dhruvin14** [comment]
This issue is related to #321 and #323 @christian-rli

**Comment by christian-rli** [comment]
Cannot reproduce the original error, probably due to the redesign. At any rate, filtering does currently work
![Bildschirmfoto zu 2021-12-01 13-54-08](https://user-images.githubusercontent.com/42000429/144238121-4d52d55f-2b54-4d63-abb1-aafd26508777.png)
.

**Comment by christian-rli** [comment]
Geometry view is functional as wel
![Bildschirmfoto zu 2021-12-01 13-56-05](https://user-images.githubusercontent.com/42000429/144238318-ef014d46-a00c-4c16-aca7-fadfd14a38b0.png)
l:
