### ISSUE TITLE
Missing reference to metadata standard

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#411]
Create a short description and reference to OEP metadata version 1.4.0 at an appropriate location. Link to the [description](https://github.com/OpenEnergyPlatform/examples/wiki/Metadata-Description).

**Comment by jh-RLI** [comment]
@christian-rli Would [this](https://openenergy-platform.org/dataedit/) be an appropriate location? I could add another Tutorial section and list the metadata tutorial/description there.

**Comment by christian-rli** [comment]
A redesign / restructuring of the website is on its way @jh-RLI . @bmlancien is working on a sketch. Once the new structure implemented we can link the description at a prominent location. We can also link it at the beginning of the metadata view below every table, but that'll have to wait until version 1.4.0 is actually supported on the platform. There is an [active issue for the latter](https://github.com/OpenEnergyPlatform/oeplatform/issues/427), though. So I guess this issue has to wait for a little while :)

**Comment by Bachibouzouk** [comment]
@4lm is working on the metadata here : https://github.com/OpenEnergyPlatform/metadata
