### ISSUE TITLE
There are too many open issues that could be closed

### ISSUE THREAD

**Issue by Bachibouzouk** [OpenEnergyPlatform/oeplatform#413]
Many issues could potentially be closed.
Closing them would bring more peace of mind and a clearer view of what's left to do.

I started using the label "?Can be closed?" on those issues so that the dev with more experience can decide on the closing.

**Comment by Bachibouzouk** [comment]
@MGlauer - we labelled quite a few issues with the '? Can be closed ?' label. I think only you have the knowledge whether those can effectively be closed or not. The best would be to link the issues with the commit which solved them, but if it is too time consuming, just closing the issue will already help :)

**Comment by Bachibouzouk** [comment]
@MGlauer - thanks for closing many issues !!! \o/

**Comment by christian-rli** [comment]
I looked through all issues with the tag and closed a few and marked them `is_active` on other occasions. No `?can be closed?` remain :)
