### ISSUE TITLE
There are too many branches not linked to a pull request

### ISSUE THREAD

**Issue by Bachibouzouk** [OpenEnergyPlatform/oeplatform#414]
It would be good to delete some of the branches (for example the ones that have been updated more than a year ago and only contain 1-2 commits).

The remaining branches should have a PR open and refer to an issue in the PR description. Or deleted if they are not relevant anymore. 

It is a bit difficult for a newcomer to make such decision, I would suggest that each creator of branches sorts up theirs? What do you think @MGlauer, @wingechr, @klarareder ?

This would be helpful for me and @jh-RLI to tackle issues :)

**Comment by jh-RLI** [comment]
[This](https://help.github.com/en/articles/closing-issues-using-keywords) helps to establish the connection between PR and issue.

**Comment by Bachibouzouk** [comment]
@MGlauer - can I proceed deleting branches that are more than a year old and are only 1-2 commits ahead?

**Comment by Bachibouzouk** [comment]
Thanks for deleting some of the branches @MGlauer :)

**Comment by klarareder** [comment]
I assume this issue is closed, please reopen if I am mistaken.
