### ISSUE TITLE
Rework Framework Factsheets

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#419]
The Framework Factsheets need a havy rework.
open_MODEX will contribute the content. 

List all existing FFS issues here:

Provide new structure: @srhbrnds

**Comment by srhbrnds** [comment]
> 
> 
> The Framework Factsheets need a havy rework.
> open_MODEX will contribute the content.
> 
> List all existing FFS issues here:
> 
> Provide new structure: @srhbrnds

Please, find the suggested FFS structure here https://next.rl-institut.de/s/6ZXwQkXFSSxMQAf . Feel free to review and comment on the proposed FFS.

**Comment by Ludee** [comment]
After the latest OEP-Release we have some additional feedback from @srhbrnds.

**Comment by jh-RLI** [comment]
@Ludee I have an overview of the tasks from the review. Most of them are rather small tasks. I will implement them in the next few days.
