### ISSUE TITLE
"About OEP" site needs a rework

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#424]
## Main page
1.  ESA
1. Open Science
1. OEP-Community

## About OEP

**General Introduction**

The OEP aims to ensure quality, transparency and reproducibility in energy system research. It provides a way to publish proper documentation of data, code and underlying assumptions. 
The OEP is a community effort, it is developped openly and therefore is constantly evolving. 

**1. What? Energy System Modelling**
* Image ->   OEP circle simple

Energy system models are used to explore the current and future energy systems and are often applied to questions involving the expansion of renewables and energy storages as well as energy and climate policy. The models themselves vary widely in terms of their type, design, programming, application, scope, level of detail, sophistication, and shortcomings.

The OEP considers the entire modelling process from the preprocessing of the raw data, the simulations, the postprocessing of the result data. The heart of the OEP is the underlying open energy database, which can be used by everyone and is maintained by a team of developers from different institutes.

**2. How? Open Science**
* Image ->   Open Science (closed, transparent, open)

The OEP follows the principles of Open Science and offers an open infrastructure for energy system research. The focus is on Open Data and the provision of modelling results under open licenses. The OEP uses an [extensive metadata set](https://github.com/OpenEnergyPlatform/examples/blob/master/metadata/oep_metadata_template.json) based on the [tabular data package](https://frictionlessdata.io/specs/tabular-data-package/) specifications and the [FAIR principles](https://www.go-fair.org/fair-principles/) to improve the findability, accessibility, interoperability, and reuse of digital assets.

**3. Who? OEP-Community**

The OEP is a cross-research project that is continuously being developed by various universities and institutes. The entire source code of the OEP is open source and is located on GitHub. Get involved and contribute!

Logos:
* open_eGo
* open_FRED
* SzenarienDB
* open_MODEX
* LOD-GEOSS

Institutes:
* OvGU
* ZNES
* Uni Flensburg
* RLI
* HZG
* IEE
* ÖI

**Comment by bmlancien** [comment]
![OEP-Processing](https://user-images.githubusercontent.com/33999424/65038816-1b977580-d951-11e9-9d9d-a9c58e629ce5.png)
![Closed_Transparent_Open_Science_Diagram](https://user-images.githubusercontent.com/33999424/65038827-1e926600-d951-11e9-896c-06e5a411eefb.png)

**Comment by Ludee** [comment]
I have some minor feedback about the two images:

- The circle could be a little thicker
- add a colour code (black: not published or published withou open license; grey: published without open licenses; blue: published with suitable open licenses)

**Comment by bmlancien** [comment]
![OEP-Processing](https://user-images.githubusercontent.com/33999424/65225634-c3ce4b00-dac5-11e9-8f3a-a66cd6efac09.png)

![Closed_Transparent_Open_Science_Diagram](https://user-images.githubusercontent.com/33999424/65225641-cb8def80-dac5-11e9-954e-cf03517565e0.png)

**Comment by Ludee** [comment]
Thank you! @bmlancien 
Of course, I have additional minor changes:

- color code: Black: Not published
- 1 row: data->model->data in black; plots in grey

Can you please provide high res files with transparent background?
I will directly use them on a poster I have to finish today ;)

**Comment by stap-m** [comment]
After our meeting yesterday I just took a look on this issue. It already looks quite good to me! I just have some minor comments:
* This sentence "The OEP is a community effort and is constantly evolving." from the general Intro needs to be marked or placed prominently. Maybe we could extend it to something like: "The OEP is a community effort, it is developped openly and therefore is constantly evolving."
* To keep the pattern, what about: **1. What? Energy System Modelling** (and I'd delete the arrow between 'Who?' and 'OEP-Community')
* Question: Is it too much input if we actually wrote down the 4 FAIR principles here, additionally to the Link?

**Comment by han-f** [comment]
> Is it too much input if we actually wrote down the 4 FAIR principles here, additionally to the Link?
I think it would be good to name the principles.

**Comment by stap-m** [comment]
I just edited the text above based on my comments.

**Comment by Ludee** [comment]
Thanks for updating.
The FAIR principles are more than just 4. I would recommend to not repeat them but rather set a link to this page: https://www.go-fair.org/fair-principles/

**Comment by han-f** [comment]
> The FAIR principles are more than just 4.
Aren't there 4 headings that are then specified in more detail? I think we could name the four headings and provide a link. Like this some main information is visibly provided and further details behind the link..

**Comment by stap-m** [comment]
> ...the FAIR principles to improve the findability, accessibility, interoperability, and reuse of digital assets.

This is how I added those 4 to the text.

**Comment by han-f** [comment]
> 
> 
> > ...the FAIR principles to improve the findability, accessibility, interoperability, and reuse of digital assets.
> 
> This is how I added those 4 to the text.

Yes, I saw this and think this with the link is sufficient. @Ludee what do you think?

**Comment by MGlauer** [comment]
I created a branch for the changes on the "About OEP"-page: https://github.com/OpenEnergyPlatform/oeplatform/blob/features/about-oep-424/base/templates/base/about.html

**Comment by Ludee** [comment]
I added text to the three points and fixed all links on the landing page.
Your commit fcd3d52 is not on the test page yet, but looks good in html ;) @MGlauer

**Comment by stap-m** [comment]
Some institutes, e.g. from LOD_GEOSS, are not included in the list above @Ludee

**Comment by Ludee** [comment]
I will add the projects (LOD-GEOSS, open_MODEX) and missing institutes.

**Comment by beritRLI** [comment]
O Mann, Sorry – heute war (ist noch) so ein Chaostag, dass ich das Treffen total verpeilt habe!!
Ich wollte wirklich dabei sein, weil ich auch neugierig bin, wie sich iiasa da jetzt einbringt…

Hatte letzte Woche ein Gespräch mit Patrick von IZES, (da hatte ich auch eine Frage an euch weitergeleitet). Er ist mit Karsten (DLR) in einem Projekt, der den Vorschlag gemacht hat in dem Projekt die OEO zu verwenden. Er hat aber gleich nach dem Versuch abgebrochen und meinte, dass Karsten das bearbeiten soll, da er sich ja damit auskennt. Jetzt meine Frage: wie weit ist Karsten inhaltlich mit der OEO  befasst? Kennt er sich genug aus, um das in einem anderen Projekt zu verwenden? Es wäre schade, wenn das deshalb nicht zustande käme…

Viele Grüße
Berit

Von: Ludwig Hülk <notifications@github.com>
Gesendet: Montag, 17. August 2020 15:55
An: OpenEnergyPlatform/oeplatform <oeplatform@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [OpenEnergyPlatform/oeplatform] "About OEP" site needs a rework (#424)


I will add the projects (LOD-GEOSS, open_MODEX) and missing institutes.

**Comment by beritRLI** [comment]
Ups, ging aus Versehen an den Verteiler – also an alle ein großes Sorry von mir für die Verpeilte Sitzung heute!!!
@Karsten: bist du auch in dem Verteiler?
Wäre super, wenn du es schaffst das in dem Projekt zu verorten!!!!

Von: Berit Müller
Gesendet: Montag, 17. August 2020 17:00
An: OpenEnergyPlatform/oeplatform <reply@reply.github.com>
Betreff: AW: [OpenEnergyPlatform/oeplatform] "About OEP" site needs a rework (#424)

O Mann, Sorry – heute war (ist noch) so ein Chaostag, dass ich das Treffen total verpeilt habe!!
Ich wollte wirklich dabei sein, weil ich auch neugierig bin, wie sich iiasa da jetzt einbringt…

Hatte letzte Woche ein Gespräch mit Patrick von IZES, (da hatte ich auch eine Frage an euch weitergeleitet). Er ist mit Karsten (DLR) in einem Projekt, der den Vorschlag gemacht hat in dem Projekt die OEO zu verwenden. Er hat aber gleich nach dem Versuch abgebrochen und meinte, dass Karsten das bearbeiten soll, da er sich ja damit auskennt. Jetzt meine Frage: wie weit ist Karsten inhaltlich mit der OEO  befasst? Kennt er sich genug aus, um das in einem anderen Projekt zu verwenden? Es wäre schade, wenn das deshalb nicht zustande käme…

Viele Grüße
Berit

Von: Ludwig Hülk <notifications@github.com<mailto:notifications@github.com>>
Gesendet: Montag, 17. August 2020 15:55
An: OpenEnergyPlatform/oeplatform <oeplatform@noreply.github.com<mailto:oeplatform@noreply.github.com>>
Cc: Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Betreff: Re: [OpenEnergyPlatform/oeplatform] "About OEP" site needs a rework (#424)


I will add the projects (LOD-GEOSS, open_MODEX) and missing institutes.
