### ISSUE TITLE
Tags get lost when tables are moved from model_draft to another schema

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#426]
We had tagged each of our KSz2050 tables in the  model _draft schema. Now that tables have been moved to the scenario schema all tags are gone. 
However, they are still visible under the most popular tags list. 
Is there a way this can be fixed ex-post? It would involve quite some work to tag all of the tables individually again.

**Comment by christian-rli** [comment]
Sorry about the (hopefully temporarily) lost work @han-f . I'm not sure how tags are stored. There are a couple issues revolving around tag-storing / tag-setting: #160 #390 

I believe the information was lost, because I used sql to move the tables. Is it possible to move tables to schemas (other than model_draft) via api or dialect now @MGlauer ?

**Comment by MGlauer** [comment]
The registers the table inside the meta_table `public.tables`. Tags are attached to those registers. Thus it should be sufficient, if you update the table registers's schema foreign key. **BUT**: It might be that the OEP already registered this new table. in this case you have to delete this register.

**Comment by l-emele** [comment]
So it is best to currently not assign new tags until issues #160 and #390 are resolved?

**Comment by christian-rli** [comment]
Thanks for the advice @MGlauer . I updated the register and now the tags are displayed correctly for the table in the new schema.

**Comment by han-f** [comment]
Many thanks @christian-rli. @MGlauer: do you know what leads to the tags being displayed under popular tags, but when clicking them none of the tables with the corresponding tag shows up? Seems to hold true for all tags related to the tables in this issue.

**Comment by han-f** [comment]
yes, can be closed - I have created issue #435 for the partial problem of popular tags leading to empty results.

**Comment by Ludee** [comment]
This issue is nor solved yet.
