### ISSUE TITLE
Popular tag links lead to empty or partial listing of tables 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#435]
The tags being displayed under _popular tags_ that relate to tables  with the prefix _ksz2050_r2__ lead to either "no matches found" or results that do not include the tables with mentioned prefix

"No matches found" for these tags: 
BMU
Climate Protection Scenario 2050
KSz2050

Results show, but do  NOT include _ksz2050_r2__  tables for these tags:
Datenlizenz Deutschland - Namensnennung
Germany 
2050
Öko-Institut

**Comment by christian-rli** [comment]
The search for `ksz2050_r2_` yields 31 tables in the scenario schema. BMU finds a lot of tables in scenario and model_draft.

... I checked and all of the searches above return reasonable results now. This was either fixed, a temporary bug or there are several tags with the same name - for which a separate issue exists. At any rate, this seems to no longer be an issue.
