### ISSUE TITLE
Implementing reworked OEP-Layout

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#436]
Please implement new design before Tu 8.10.2019!

**Comment by Bachibouzouk** [comment]
@Ludee Link to new design guidelines and/or PR?

**Comment by Ludee** [comment]
@johannwagner and @MGlauer need to roll out a new release.
I guess this is the branch with the reworked layout designed by @bmlancien 
https://github.com/OpenEnergyPlatform/oeplatform/tree/fix/design-rework-welcome-page

**Comment by Bachibouzouk** [comment]
@MGlauer : according to https://openenergy-platform.org/, this can be closed. However, it would be good to have a link to a pull request or the name of a branch listed in this issue so we can see what was done to tackle the issue.

**Comment by Ludee** [comment]
@johannwagner What's the status of the redesign? Is it done with https://github.com/OpenEnergyPlatform/oeplatform/pull/458 and https://github.com/OpenEnergyPlatform/oeplatform/commit/58c05403eb9057822c374628e6fce4c9cee55b6f?
This issue is behind deadline, please communicate if you need any help.
Are you coming to the working session tomorrow 14.11?

**Comment by johannwagner** [comment]
I implemented the Welcome page. I won’t be at the Hackaton. @MGlauer does have all information.

**Comment by MGlauer** [comment]
@Ludee I do not get how this relates to the text missing from the mock-up. Descriptions for the following categories are missing alongside the corresponding links:

* Process Modelling
* Open Science
* OEP-Community

The text above seems to be to a temporary "About OEP" category that we included for the intermediate release.
