### ISSUE TITLE
Can't run tests without errors locally

### ISSUE THREAD

**Issue by 4lm** [OpenEnergyPlatform/oeplatform#439]
Hi all,

pytest seems to work with travis/tox on GitHub, but I can't get pytest locally to run without errors.

First I did run (venv enabled) `pytest`, but it was nagging that

> `[...] settings are not configured [...] define the environment variable DJANGO_SETTINGS_MODULE [...]`

so I did run it with `DJANGO_SETTINGS_MODULE="oeplatform.settings" python -m pytest`, but I still get (different errors), now its complaining that 

> `[...] E   django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.`

For complete error output see this [gist](https://gist.github.com/4lm/cb69d423991c601a02b6b92d168fcc45).

Any ideas?

**Comment by 4lm** [comment]
Mhh, pytest seems not to be the right choice for testing in this case, in the tox file I could see that. It uses the django test command for executing the tests. So I did `python manage.py test --no-input` (venv enabled). But I still get errors. For complete error output see this [gist](https://gist.github.com/4lm/9b76ea736c9cf2d9440c4122bed7cc2b). Thx!

**Comment by Bachibouzouk** [comment]
I think you can do `tox -v`

**Comment by 4lm** [comment]
> I think you can do `tox -v`

:thinking: This also does fail (this time on JS):
```
  py3: commands succeeded
  check: commands succeeded
  docs: commands succeeded
ERROR:   javascript: commands failed
```

**Comment by Bachibouzouk** [comment]
The solution was to install `npm` locally
