### ISSUE TITLE
Links to scenario factsheets lead nowhere

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#445]
Clicking any scenario name on https://openenergy-platform.org/factsheets/scenarios/   leads to "nowhere", see screenshot:

![grafik](https://user-images.githubusercontent.com/36844029/66626186-96be1580-ebf7-11e9-9179-faf1dfdc36c3.png)

**Comment by Bachibouzouk** [comment]
@solar-c - once your PR #440 is merged, can you look at it ?

**Comment by Ludee** [comment]
Looks like a problem of the responsive functions. when zooming it seems to work at some point.

**Comment by Bachibouzouk** [comment]
The problem seems to come from the class 'navbar' `position` attribute which is set to relative

**Comment by bmlancien** [comment]
I can see that the problem is resolved if I remove the Bootstrap CSS grid classes:

`col-lg-8 col-lg-offset-1 col-md-9`
`col-md-3`

But I don't know how these classes work and there must be a reason why they were included into that template.

**Comment by MGlauer** [comment]
Maybe @johannwagner can help

**Comment by johannwagner** [comment]
I will take a look, will report back.

**Comment by johannwagner** [comment]
Okay, I would like to debug this and tried to create a scenario factsheet.

![Screenshot from 2019-11-15 10-07-24](https://user-images.githubusercontent.com/12380026/68930995-e1e7bd00-078f-11ea-80fe-3494f0714cc3.png)

@MGlauer

**Comment by Bachibouzouk** [comment]
@johannwagner You should pull the newest version of `develop`

**Comment by Bachibouzouk** [comment]
@johannwagner, any news on this one?

**Comment by han-f** [comment]
This still applies, even with the new release.

**Comment by MGlauer** [comment]
The arrangement of the buttons indicates that this is also a caching issue.

**Comment by han-f** [comment]
Yes, thank you. I will remember to hit F5 on any single page.
