### ISSUE TITLE
Python version described in readme is not the same as inside the tests

### ISSUE THREAD

**Issue by Bachibouzouk** [OpenEnergyPlatform/oeplatform#446]
The readme says the version is 3.4, however the tests are performed with 3.5 and I could successfully deploy the website locally with 3.6.
We should address which version is the correct one and explain why we don't use version 3.6 or 3.7.

**Comment by Bachibouzouk** [comment]
@MGlauer - what do you think?

**Comment by Bachibouzouk** [comment]
@MGlauer can we change this to python 3.6 and 3.7 ?

**Comment by christian-rli** [comment]
The readme now states: "The installation steps have been proofed on linux and windows for python 3.6 and 3.7. Be aware that some of the required packages present installation's difficulties on windows." I believe the issue has been addressed.
