### ISSUE TITLE
Where is the branch of the design that is hosted on https://openenergy-platform.org/ ? #447 #434

### ISSUE THREAD

**Issue by 4lm** [OpenEnergyPlatform/oeplatform#448]
Hi all,

please help! Right now I'm working on the modularization of the template block tags usage #447. Which also effects the revamp of the design #434. But the design on #434 doesn't seem to be version on https://openenergy-platform.org/ (which seems more up-to-date). So my question is, where is the branch/release etc. of the version on https://openenergy-platform.org/?

**Comment by 4lm** [comment]
Just found the issue, 

instead of using the static tag for loading some resources hard coded paths where used: [Link to code](https://github.com/OpenEnergyPlatform/oeplatform/blob/master/base/templates/base/base.html#L11-L15).

That's why a hand full of JS files where not found, because their relative path to static was hard coded instead. Which resulted in a different looking design. I had to collect the static files to get all des JS files for rendering (`python manage.py collectstatic`), which should not be necessary during local development.

So the correct way would be IMO to load the resources via the static tag. Will fix this tomorrow in a PR on master.

**Comment by 4lm** [comment]
:thinking: Blame shows that the static files are 3 years old on `master`, they are not in the `develop` branch. So the redesign seems to be based on `master` and not `develop` and is using this (outdated?) JS files, which are not present in the `develop` branch ... interesting! Or am I missing something?

**Comment by johannwagner** [comment]
I am not sure, where I branched from. 
I did not use “static” from Django, but used absolute paths, will fix this later.

**Comment by MGlauer** [comment]
>  Blame shows that the static files are 3 years old on `master`, they are not in the `develop` branch. So the redesign seems to be based on `master` and not `develop` and is using this (outdated?) JS files, which are not present in the `develop` branch ... interesting! Or am I missing something?

No, it is the other way round. The files were removed from dev but are still present on master. `git bisect`shows that this happened in d5436e04f1.

The redesign was based on dev, but due to a `git cherry-pick` it appears on master as if it was not. In fact, there are now two redesigns in the git history due to that. The original redesign can be found in fix/design-rework-welcome-page. It has not been merged into dev yet due to the missing subpages `/tutorial`?  and `/documentation`.

**Comment by 4lm** [comment]
OK, perfect, now I understand! I had tried `master` and `v0.0.5`, but not `fix/design-rework-welcome-page`. Just tried it, looks good!

@johannwagner, no fix needed!

Will close this issue.
