### ISSUE TITLE
Scenario factsheets cannot be created

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#457]
`GET /factsheets/scenarios/add/` results in the following exception.

`django.db.utils.ProgrammingError: column modelview_energymodel.generation_renewables_bio does not exist
LINE 1: ...view_energymodel"."generation_renewables_biogas", "modelview...`

According to a git-bisect, this was introduced in 0929d4828f4c

**Comment by MGlauer** [comment]
Looks like there is a migration missing. @solar-c could you commit and push this migration?

**Comment by Bachibouzouk** [comment]
The migrations are located on #440 apparently, I will merge current `develop` in this branch and merge it back to `develop`

**Comment by han-f** [comment]
Related to #400 and #519

**Comment by jh-RLI** [comment]
@Bachibouzouk ?Can be closed? since you merged #440?
