### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by l-emele** [OpenEnergyPlatform/oeplatform#459]
My browser warns me that the SSL certificate of https://openenergy-platform.org/ expired yesterday.
![grafik](https://user-images.githubusercontent.com/36884905/68582587-6201e000-047b-11ea-8acf-cfde0abfd0ef.png)

**Comment by MGlauer** [comment]
I informed the administrator

**Comment by MGlauer** [comment]
Should be updated now

**Comment by l-emele** [comment]
Warning disappeared.
