### ISSUE TITLE
Add subpages for Tutorials

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#462]
Implement the subpage for tutorials including pages for the three defined tutorial types: 

- [x] Jupyter Notebooks
- [x] Text-based Tutorials
- [x] Video-based tutorials

**Comment by MGlauer** [comment]
@Ludee: Can you add the mock-up

**Comment by MGlauer** [comment]
Tutorial overview
![2019_09_26_OEP_Tutorials](https://user-images.githubusercontent.com/7835111/68846472-6faea400-06cd-11ea-953f-1910490b47fb.png)

**Comment by MGlauer** [comment]
Video tutorial:
![2019_09_26_OEP_Tutorials (1)](https://user-images.githubusercontent.com/7835111/68846515-85bc6480-06cd-11ea-9f42-668d2db743ac.png)
Text-tutorial
![2019_09_26_OEP_Tutorials (2)](https://user-images.githubusercontent.com/7835111/68846554-91a82680-06cd-11ea-8217-4d51105693f5.png)

**Comment by Bachibouzouk** [comment]
What about the work done in #391 ?

**Comment by johannwagner** [comment]
I do not really have a clue regarding #391. It seems, that @klarareder started to write down some tutorial, but I think, this is not relevant anymore due to the possibility to create tutorials in the backend. 

@MGlauer

**Comment by MGlauer** [comment]
Yes, @klarareder created a tutorial page. We will transfer this page to the new format implemented by @jh-RLI in #478. The problem is, that the approach we used there is not flexible enough to support the community-approach we plan for the OEP.

**Comment by MGlauer** [comment]
@johannwagner The list of tutorials needs to be improved according to the [mockup](https://github.com/OpenEnergyPlatform/oeplatform/issues/462#issuecomment-553813460)

**Comment by johannwagner** [comment]
@christian-rli I assigned you this ticket in order to find a good point in time for fixing up the designs.
