### ISSUE TITLE
An experienced python user could not deploy the website locally

### ISSUE THREAD

**Issue by Bachibouzouk** [OpenEnergyPlatform/oeplatform#464]
We should go through the first install steps one more time for

- [x] on linux

- [ ] on windows

**Comment by jh-RLI** [comment]
On windows after creating the environment one needs to run this:
`conda install -c conda-forge shapely`

and also remove from requirements.txt:
* shapely>=1.5.17

before installing the dependencies in requirements.txt.

**Comment by jh-RLI** [comment]
To set the environment variable on windows via cmd one need to input:
 `cmd/v`
and then input: 
`set varname=var`

**Comment by jh-RLI** [comment]
It´s better to use the GUI -> Explorer -> right click "computer" -> select property -> select "Erweiterte Systemeinstellung" -> select "environment variable" -> Systemvariable click "new..."
