### ISSUE TITLE
There is no automated way to check the links of the website work

### ISSUE THREAD

**Issue by Bachibouzouk** [OpenEnergyPlatform/oeplatform#476]
## Problem
When doing release we have to manually check every pages to see if it works

## Proposed Solution

- [ ] Check the links with https://github.com/bartdag/pylinkvalidator

- [ ] Have mocks for POST requests

**Comment by jh-RLI** [comment]
There is now a management command available https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/base/management/commands/check_links.py
