### ISSUE TITLE
There is no backend for tutorials

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#478]
We need a backend that handles the tutorials. @johannwagner will do the design. Therefore in this issue we need a new django app `tutorials` that contains a new model that stores text in a markdown format.
The data in this modeld will be managed by a view that handles `GET`, `POST` requests for templates that receive text in markdown, validate them (look out for injections!) and saves them in said model - or return them, depending on the request type. The rendering of this markdown is not part of this issue.

**Comment by johannwagner** [comment]
Please use https://github.com/OpenEnergyPlatform/oeplatform/tree/feature/tutorials to implement model and custom logic. I will work on the same branch while implementing view and some other logic to add content of https://github.com/OpenEnergyPlatform/examples to the platform.
