### ISSUE TITLE
There is no structure documentation of the website

### ISSUE THREAD

**Issue by Bachibouzouk** [OpenEnergyPlatform/oeplatform#479]
It would be good to know what is meant to be in each of these folders. So that people making improvement know where to store them according to the given structure. Or people know in which folder to look to make modifications

- [x] api
- [ ] base
- [x] dataedit
- [ ] docs
- [ ] literature
- [x] login
- [x] modelview
- [ ] oedb_datamodels
- [ ] oeplatform
- [ ] tests
- [ ] version

**Comment by MGlauer** [comment]
Some of this is [already documented](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/docs/source/index.rst). I will extend this.

**Comment by MGlauer** [comment]
I realised that this documentation is not currently linked in the README.md. I added a badge in #480

**Comment by Bachibouzouk** [comment]
> Some of this is [already documented](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/docs/source/index.rst). I will extend this.

I transformed the items into check boxes :)

**Comment by Bachibouzouk** [comment]
There is a structure now, it is only not complete and will be tracked by #506
