### ISSUE TITLE
[Factsheets] Several changes

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#49]
- Model / Framework / scenario fact sheet; general information: Rename "Institution(s)" as "Partner(s)"; info text: "Which organisations develop(ed) the model / framework / scenario?"
- Model; model integration; "Input/output data file format": Please, separate Input and Output into two drop-down menus. Veto? They should not be mandatory.
- (Move the "Primary Outputs" to the integration section, right before the "Output data file format".)
  **Sorry, we changed our mind. Please, do not move it.**
- Model fact sheet: documentation quality stays a mandatory field, because it is a drop-down menu. The option "not available" needs to be added. Can the field be next to link to documentation.
- "Additional software" will no longer be a mandatory field. Please, remember to delete the "*".
- option to say when approximately it may become open source under the item 'planned to open up in the future' in the openness section (please, make a text field) **Sorry, we changed our mind: Please, put it into mathematical properties.**
- There needs be added a check box: "Multi-regional model" in the coverage section . Info text: "Allows the model multi-regional modelling?"
- Geographic (spatial) resolution info text: "What is the typical geographic resolution, the model works with?"

**Comment by MGlauer** [comment]
Primary Outputs occurs in Frameworks and Models. We should keep consistency regarding the place, where this place occurs. I.e. If we move it in models we should move it in frameworks, too. But the corresponding tab is not part of the framework factsheet. This should be discussed.

**Comment by MGlauer** [comment]
The approximation of "opening up" should not be a text field, but a drop down with ranges, i.e. <1 month , < 1 year, < 2 years, >= 2 years

**Comment by MGlauer** [comment]
@EvaWie : Which category does "Multi-regional model" belong to?

**Comment by EvaWie** [comment]
"Multi-regional model" belongs to coverage.
"primary outputs" will stay in the general information section, until we decided, whether frameworks have outputs or not. If the answer is yes, the text field should stay in the general information section of the model- and framework fact sheets, because the framework fact sheet does not have an integration section.

**Comment by EvaWie** [comment]
Change: The "Multi-regional model" check box belongs to mathematical properties.

**Comment by stap-m** [comment]
This is outdated.
