### ISSUE TITLE
There is no graph library for bootstrap4 

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#491]
As described in #486 map and table functionalities have been replaced by more modern libraries. The old graph functionality is not yet implemented, though.

**Comment by Bachibouzouk** [comment]
The new functionality should to to `backend.js`. It should retrieve the data via AJAX and create a plot in a div in dataedit/templates/dataedit/dataview.html.

**Comment by MGlauer** [comment]
Below is how the old plot function looked like. The new one should follow a simiar scheme but usability improvements are always welcome. Maybe we should also integrate a filter functionality as in #498. 

![image](https://user-images.githubusercontent.com/7835111/69734443-45c69a00-112f-11ea-9647-a489245c547b.png)

**Comment by Bachibouzouk** [comment]
I am trying to figure out where is the code which generates this view you show in the comment above @MGlauer. This was done in `dataedit/templates/dataedit/dataedit_overview.html` which you seem to delete and replace by `dataedit/templates/dataedit/dataview.html` in #498

**Comment by MGlauer** [comment]
This was a recline view. Recline took a dataset and created multiple views. This functionality is not there anymore - as we are replacing recline. Therefore you will not be able to find it. The creation of the graphs was handled by recline internally.

**Comment by MGlauer** [comment]
The data retrieval should not be too problematic. I can support you here if you want. From my perspective the real issue is that time series is heterogeneous. They can be stored horizontally or vertically (recline supported vertical data only). What we need is a form that allows users to select those series and trigger them to be plotted in the graph. I am not really sure how to design such a form, unfortunately.

**Comment by Bachibouzouk** [comment]
It is not clear to me how I should retrieve the data using AJAX, are you suggesting to use the function `request_data` from `backend.js` @MGlauer ?

The code structure in `backend.js` should be discussed before I implement further functions (it could also have some comments for better reusability...). You seem to have an idea in mind, could you draw it schematically on a piece of paper (i.e. which functions could be reused for map, datatable and graph)?

**Comment by MGlauer** [comment]
![_20191127_170007](https://user-images.githubusercontent.com/7835111/69739361-df924500-1137-11ea-9127-7f34c27afb9e.JPG)

**Comment by Bachibouzouk** [comment]
Thanks for your schema @MGlauer :)

I think @Ludee wanted to be able to create several graphs resulting in a view like this :+1: 
![photo5402148022130945170](https://user-images.githubusercontent.com/4399407/69739981-e5d4f100-1138-11ea-865c-33fe0ea28db0.jpg)

**Comment by Bachibouzouk** [comment]
In case of very large datatables, wouldn't it be too much data for the HTTP call to the server? Should we restrict them by default to 100 values ?

**Comment by MGlauer** [comment]
> In case of very large datatables, wouldn't it be too much data for the HTTP call to the server? Should we restrict them by default to 100 values ?

Yes, but a limit of 100 random values would not be very usable. This is why I would argue that we include the filter function to give the user some control over which fragment of the database they receive.

**Comment by Bachibouzouk** [comment]
I included a plotly graph in #499, how would you make such that we don't duplicate the call to the server for the data which we need for the datatable, the graphs and the map?

**Comment by MGlauer** [comment]
I think this depends in what we want to implement. If we want to cover cover vertical horizontal representations only then we can reuse the data interface. If we want to support vertical series, too, we might need to implement appropriate requests.

**Comment by Ludee** [comment]
I think we should implement a light version of the graphs now. It is more important to have a small feature that works for all the tables than some specials that will crash sometimes.
From my perspektive, the prio is:

1. Display of the data in a table
1. Plat the data on a map (points, lines, polygons)
1. Plot some value

**Comment by MGlauer** [comment]
Has been addressed in #499
