### ISSUE TITLE
Few things to change in the Welcome page of the website

### ISSUE THREAD

**Issue by Bachibouzouk** [OpenEnergyPlatform/oeplatform#503]
@johannwagner thanks for this PR, 50 changed files, a lot of work I assume! I have a few remarks, if they are solved we are IMO good to go:

1. In the console I get 3 errors that 3 icon fonts are not found.
2. Undefined by mockup: All buttons have a flat design, but the login button has not, should be IMO flat as well.
3. Undefined by mockup: The login button in desktop view is on the left side of the link list in the navbar. Should IMO on the right side of the link list (more common this way).
4. In mobile view the spacing of the login button is not vertically aligned to the hamburger button. Also the spacing towards navbar bottom and between hamburger button and login button is a little off.
5. The OEP logo is not vertically aligned in the navbar (desktop view).
6. In comparision to the mockup, headings in body ("Open Energy Platform", "Tutorials") must be in a darker blue.
7. Heading "Tutorials" is missing the hat icon to its left.
8. All buttons in the mockup are more rounded.
9. The vertical alignment of the "Tutorial" section in the body is compared to the mockup a little off.
10. The button "See Tutorials" is dark grey, but should be dark blue. Undefined by mockup: the hover state should IMO also be blue, either dark blue background with white font or light blue background.
11. In the mobile view the tutorial section is stacked too close to the next section. The "See Tutorials" button leans right against the next section, not a single pixel padding or margin.
12. Footer in the mobile view should not be vertically stacked, please compare with mockup.
13. In the mobile view the app has horizontal overflow with horizontal scrolling. This should not be the case.
14. Undefined by mockup: IMO at least in the mobile view the navbar should be sticky.

_Originally posted by @4lm in https://github.com/OpenEnergyPlatform/oeplatform/pull/458#issuecomment-561292035_

**Comment by wingechr** [comment]
i hope with the planned changes to the main pages, we can fix most problems for small screens/mobile. but this issue can be closed IMO.
