### ISSUE TITLE
The documentation of the website structure could be improved further

### ISSUE THREAD

**Issue by Bachibouzouk** [OpenEnergyPlatform/oeplatform#506]
The structure is available [here](https://oep-data-interface.readthedocs.io/en/latest/index.html) and the source code for the documentation is available [here](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/docs/source/index.rst)

- [x] api
- [ ] base
- [x] dataedit
- [ ] docs
- [ ] literature
- [x] login
- [x] modelview
- [ ] oedb_datamodels
- [ ] oeplatform
- [ ] tests
- [ ] version
- [x] tutorials

**Comment by jh-RLI** [comment]
Obsolete ... The documentation is maintained and constantly expanded here https://openenergyplatform.github.io/oeplatform/
