### ISSUE TITLE
Lack of standalone metadata "generator"

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#513]
As a   user, I want to be able to create metadata records quickly (with a metadata   generator).

**Comment by christian-rli** [comment]
A good way of doing this is to build upon the form already supplied for editing metadata. Default values and fields can be generated when loading the page of a data set. Those values should include all the information that is included in the dataset itself - i.e. the name of the dataset and its resources, including data type.

**Comment by christian-rli** [comment]
A metadata generator has been implemented for the csv upload wizard. Unfortunately it cannot really be used standalone. Changed the title of this issue accordingly.
