### ISSUE TITLE
Cannot modify scenario factsheet

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#519]
It is not possible to modify a scenario factsheet. 
Related to #400. 
Same message appears as in #400

**Comment by jh-RLI** [comment]
I looked at this and saw that an http 500 error (internal server error) is thrown. In my local oep environment, this error comes from the missing "License" field in the "Energyscenario" model. In modelview/views.py there is the if statement "if model.license: ......" which causes the error. @MGlauer do you see any problems when adding a license field to the model?
