### ISSUE TITLE
Glyphicons are not shown with Bootstrap 4

### ISSUE THREAD

**Issue by vliste-oeko** [OpenEnergyPlatform/oeplatform#522]
Wanted to upload a new Factsheet, but button for that feature is missing. However, adding an "/add" to the URL is working.

<img width="444" alt="Missing_add-button" src="https://user-images.githubusercontent.com/53172562/73267679-ce1df580-41d9-11ea-8559-d3dcd0935fca.png">

**Comment by MGlauer** [comment]
It seems this has been lost in translation due to the removal of glyph-icons from bootstrap4.

**Comment by johannwagner** [comment]
This should be fixed by https://github.com/OpenEnergyPlatform/oeplatform/pull/531
