### ISSUE TITLE
Problems with creating an account

### ISSUE THREAD

**Issue by vliste-oeko** [OpenEnergyPlatform/oeplatform#523]
- clicking "Login" (btw does is need a blank space?)-> "create a new account" -> submitting the first account information -> leaves me with no information about the next steps, only assumed that I would get an e-mail with further instruction and validation link

![Sign_up_Info](https://user-images.githubusercontent.com/53172562/73664148-3750ad80-469f-11ea-91c6-040be1be08e3.PNG)

- after clicking validation link in e-mail -> same page, as shown in screenshot above, opens up and no further instructions provided

- tried then instinctively to enter my registration info again: clicking on "Login" -> entering username and password -> received warning message (see screenshot below):

![Account locked2](https://user-images.githubusercontent.com/53172562/73664550-e4c3c100-469f-11ea-9a69-d6fba799385e.PNG)

- Who is the admin? And how could a user contact that person?

**Comment by MGlauer** [comment]
Huh, this seems to be a malfunction of the axes plugin. I experienced the same when setting up the platform locally. But back then it only occurred once. I will look into it.

**Comment by MGlauer** [comment]
That was hard to figure out and to be honest I did not completely understand it, yet. 
It seems that there is a weird combination of settings that only occurs: 
1. In production mode
2. If the `django.contrib.auth.backends.ModelBackend` is not activated

I found a configuration of parameters that works, but they are not production ready. I have to figure this out and, therefore, leave this ticket open. The test server should work now, tho.

**Comment by MGlauer** [comment]
> * after clicking validation link in e-mail -> same page, as shown in screenshot above, opens up and no further instructions provided

Adressed this in 3e76b5f

**Comment by vliste-oeko** [comment]
I can now successfully log in to my previously created account. 
However, creating a completely new account produce the following problem: 
- the link received in the confirmation e-mail did not work (see screenshots below)
![Conf_email](https://user-images.githubusercontent.com/53172562/74666855-8cfa7f00-51a2-11ea-82bf-5ad6c1afc5b3.PNG)

![URL_Error](https://user-images.githubusercontent.com/53172562/74666875-9683e700-51a2-11ea-89ae-b1eb8a568bdb.PNG)

**Comment by MGlauer** [comment]
This does not really look like a problem on the side of the platform. It looks like some HTTP proxy is in between you and the OEP blocking the connection. The IP (130.149.7.69) that refused the connection is part of the tu-berlin subnet. Maybe links from e-mails are blocked?

**Comment by vliste-oeko** [comment]
Sorry, my mistake! Tried it with a different e-mail address and it worked fine! :)

**Comment by christian-rli** [comment]
Has been merged.
