### ISSUE TITLE
Submitting Framework Factsheet works but did not find editing options afterwards (and issues with user-friendliness))

### ISSUE THREAD

**Issue by vliste-oeko** [OpenEnergyPlatform/oeplatform#527]
- interface for submitting a Framework Factsheet is not user friendly yet: different tabs/categories are not properly seperated and its not visible in which category the user is at when filling out the form (see screenshots below):

![Factsheet_Framework](https://user-images.githubusercontent.com/53172562/74668930-8241e900-51a6-11ea-9884-39b09b89574d.png)
![FS_Framework](https://user-images.githubusercontent.com/53172562/74668946-8837ca00-51a6-11ea-9631-0028dfb53566.PNG)

- further when submitting the factsheet it looks like this
![Result_FS](https://user-images.githubusercontent.com/53172562/74669232-05fbd580-51a7-11ea-8ad8-60fd96c06146.PNG)

- also in this interface no option or link to edit my Factsheet:
![FS_editing](https://user-images.githubusercontent.com/53172562/74669241-0a27f300-51a7-11ea-89a3-b1f6be9f17af.PNG)

**Comment by MGlauer** [comment]
This is due to the same issue (missing fonts in bootstrap 4) as in #522. Appending `/edit` should work as a workaround
