### ISSUE TITLE
There is no versionnumber visible on the oep website 

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#528]
For users and developers of the OEP it would be helpful to have the version number/release-id of the OEP displayed on the website. E.g. in the footer area.

**Comment by MGlauer** [comment]
I don't know whether this is a good idea. When it comes to [hardening of web servers](https://geekflare.com/apache-web-server-hardening-security/), it is generally discouraged to display the software version of the web server. I do not really see, why this should be different for the web service. 
As a compromise, we could show just the major version - maybe the minor version. But going down to patches seems like a security issue to me.

**Comment by jh-RLI** [comment]
That's right security should not suffer as a result. But the oep-code is publicly available anyway? The specification does not have to go beyond the major version. It's only about being able to refer to a version, to discuss improvements or bugs. Especially to show the difference between the oep-test (http://toep.iks.cs.ovgu.de/) environment and the production environment (https://openenergy-platform.org/).  Maybe it is enough if the version is only displayed in the test environment as additional debug information? @Ludee can provide more background about this request?

**Comment by Ludee** [comment]
Since this issue was not solved for the _version 0.7.0_ we can discuss this for the next one:

I would like like the version number to be displayed in the header (or footer) an all versions.
I don't really see a security thread, since it is all open anyway. Or do I miss a potential thread?

**Comment by MGlauer** [comment]
Yes, being open source does not change anything here. The apache webserver is open source, too. Still, they highly recommend hiding the version number (see link above).

There may be a mismatch between the live version and the most recent release - especially, if the code is hosted by multiple institutions. Publicizing the version number along with a change log from version X to version Y is basically a "How to hack this particular OEP-instance"
