### ISSUE TITLE
The Frontend for scenario-factsheets detail-view is still broken

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#530]
This error has been known for several weeks. But I could not associate an issue. 

The sfs detail-view is probably broken because of a css rule. In my case I need to zoom in to 200%. 
The same problem occurs in the current dev. branch. Is the problem already covered in a PR?

https://openenergy-platform.org/factsheets/scenarios/3/

**Comment by jh-RLI** [comment]
@Ludee I created this issue from your Redmine-ticket (http://redmine.iks.cs.ovgu.de/oe/issues/1870660628)

**Comment by MGlauer** [comment]
The error with the blue bar has been fixed during the redesign. The missing scenario factsheets were not an error because on our testserver there were no factsheets at this point in time.

**Comment by jh-RLI** [comment]
@MGlauer Okay, is the fix already merged?/ Is there a PR with which I can link this issue?

**Comment by MGlauer** [comment]
The redesign is still WIP in features/django3

**Comment by jh-RLI** [comment]
@MGlauer Is it okay if I create a PR for features/django3?

**Comment by jh-RLI** [comment]
Since the branch features/django3 is merged, this issue is resolve.
