### ISSUE TITLE
Table shows "no data" in dataview

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#538]
I need to link the following table: https://openenergy-platform.org/dataedit/view/supply/wind_turbine_library
and the data is not loaded.

I tested `SELECT * FROM supply.wind_turbine_library` and the data is in the oedb.

**Comment by MGlauer** [comment]
It looks fine for me

**Comment by Ludee** [comment]
Yes, seemed like some connection errors.
