### ISSUE TITLE
[Factsheets] SF - general information - tools

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#54]
There are two fields labelled as "tools". The second one seems to be meant as a "other" field and should only appear, when "other" is selected in the drop down menu of the first field. The options of the first field are still dummy data and seem to be supposed to include automatically the list of all models for which a fact sheet is available.

Do we want to allow the selection of more than one tool? See also Issue #55 .

**Comment by stap-m** [comment]
This is outdated.
