### ISSUE TITLE
Write an introduction for the ontology page

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/oeplatform#542]
## Open Energy Ontology

Here, the Open Energy Ontology OEO is being created as a domain ontology within the field of energy system modelling. The first release of the OEO is planned for summer 2020.

### Domain ontology: What is that?
An ontology is a formal collection of terms and relationships between those terms. An ontology can thus help to provide a clear understanding of a domain of discourse. On the Open Energy Platform this domain of discourse is energy system modelling and with the Open Energy Ontology (OEO) we aim to develop a language that works across disciplines.

### What is it good for?
There are several purposes and use cases for ontologies, which is why they are already used and developed in many scientific fields. Applications are
•	**Standardising terminology in a domain:** With an ontology a controlled vocabulary is provided, with clear definitions that indicate how terminology is to be used. It becomes possible to identify and diambiguate ambiguous vocabulary and a collection of synonyms is created to indicate the breadth of actual usage in the domain.
•	**Data annotation and integration:** Applying an ontology to data annotation in databases allows flexible, content-oriented data integration and aggregation. It adds the possibility of enhanced searching functions and logical querying across datasets.
•	**Templates for data capture:** The ontology can provide a structure which is used to make reporting more uniform and detailed.
•	**Visualisation:** Knowledge encoded in the ontology can be visualized in various ways to make it more comprehensible. 
•	**Text and Data mining:** The ontology can be used to automatically search across text and data resources to e.g. suggest associations (mentions) of ontology entities. Automatic assosiations of ontology entities to large corpora can be used to gain an overview of the literature or data across a domain. It can be used for discovery and for automated data or research synthesis and meta-analysis.

### Usage beyond the Open Energy Familiy tools
The OEO is developed within the scope of the Open Energy Family. Nevertheless, it is developed as an ontology for the whole energy system modelling area. We explicitly want it to be used in other contextes and use cases aswell. 

### Where and how can I contribute?
The OEO development was initiated in the project “SzenarienDB” and is augmented in the project “LOD_GEOSS”. The development is community based and takes place on GitHub: https://github.com/OpenEnergyPlatform/ontology

A OEO steering committee was created in autumn 2019.

**Comment by han-f** [comment]
How about adding/modifying at the beginning: 

An ontology is a formal collection of terms and relationships between those terms. An ontology can thus help to provide a clear understanding of a domain of discourse. On the Open Energy Platform this domain of discourse is energy system modelling and with the Open Energy Ontology (OEO) we aim to develop a language that works across disciplines.

**Comment by stap-m** [comment]
Thanks @han-f . 
I added your text. Maybe this is sufficient as introduction and we can leave the part "An ontology consists mainly of classes [...] which capture their exact meaning and applicable scope." aswell, at least for the moment?!

I also added a more detailed description for the use cases. It is based on the slides from the 4th OntoHack meeting (@jannahastings thank you!). Is it written in a way that ontology newbies can understand it?

I also mentioned the steering committee here. Is this the right place?

**Comment by MGlauer** [comment]
I created an ontology app that just links to this text. You can edit the text on branch [`features/what-is-ontology-542`](https://github.com/OpenEnergyPlatform/oeplatform/tree/features/what-is-ontology-542) in [`ontology/templates/about.html`](https://github.com/OpenEnergyPlatform/oeplatform/blob/features/what-is-ontology-542/ontology/templates/ontology/about.html).

As this site will probably be temporary and contain the OEO-functionalities, I would add a disclaimer regarding that.

**Comment by jannahastings** [comment]
Reads well! I committed just a few minor changes directly to the text on Martin's branch.

**Comment by han-f** [comment]
> I added your text. Maybe this is sufficient as introduction and we can leave the part "An ontology consists mainly of classes [...] which capture their exact meaning and applicable scope." aswell, at least for the moment?!
Yes I think it would be easier on the eye and if we think about this as a means to communicate the essence, then we may not need the details. I have edited the text above accordingly.

**Comment by stap-m** [comment]
> I have edited the text above accordingly.

Ok. I now comitted it directly to the branch.

**Comment by stap-m** [comment]
> As this site will probably be temporary and contain the OEO-functionalities later, I would add a disclaimer regarding that.

I think, later these explanations should somehow stay, as an addition to the OEO functionalities.

**Comment by MGlauer** [comment]
@stap-m Could you open a pull request when this is ready?
