### ISSUE TITLE
The text in imprint is not available in english

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#544]
http://toep.iks.cs.ovgu.de/legal/impressum/

**Comment by han-f** [comment]
@MGlauer: not sure who is best to update such a text with legal touch.

**Comment by MGlauer** [comment]
Same as #545: This has to be in german. We can add a courtesy translation, though. Unfortunately, we do not have any native speakers.

**Comment by han-f** [comment]
Another question: may the link also need to read "Impressum" instead of imprint?

**Comment by MGlauer** [comment]
I think so. I guess it was renamed during the redesign. Maybe @Ludee or @bmlancien can help here.

**Comment by bmlancien** [comment]
I didn't mention anything about this page url. 'Imprint' would make more sense, for sure.

**Comment by han-f** [comment]
Yes, I think in general, imprint makes more sense - but since the website is hosted in Germany there may be the legal need to have it in German. I can try to check.

**Comment by han-f** [comment]
Mein Vorschlag: _Impressum - Legal notice_
 Es scheint prinzipiell in Ordnung zu sein andere Begriffe zu verwenden, sofern klar ist, dass sich hinter dem Link das Impressum befindet. Imprint scheint die falsche englische Übersetzung zu sein, auch wenn oft verwendet und prinzipiell in Ordnung. 

Siehe z.B. 

- https://allcodesarebeautiful.com/impressum-auf-englisch-imprint-falsche-uebersetzung/#Zusammenfassung_fuer_Eilige_Imprint_nein_Legal_Notice_ja
- https://www.ihk-wiesbaden.de/recht/rechtsberatung/internetrecht-und-werbung/internetauftritt-rechtliche-anforderungen-und-pflichten-1255572: 
- https://allfacebook.de/policy/whitepaper-faq-zur-impressumspflicht-datenschutzerklaerung-und-disclaimer-bei-facebook
- https://www.it-recht-kanzlei.de/Thema/impressum-tmg.html?page=1#sect_1
