### ISSUE TITLE
The text under legal is not available in english

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#545]
http://toep.iks.cs.ovgu.de/legal/datasec/

**Comment by han-f** [comment]
@MGlauer: not sure who is best to update such a text with legal touch.

**Comment by MGlauer** [comment]
That is the problem. If we add a translation, we have to add a disclaimer that this is a courtesy tranlation. As we are hosted in Germany, we have to keep this text in German and the german version must be directly reachable from the front page.

That being said: I am not able to do this translation.

**Comment by han-f** [comment]
I see. The courtesy translation would basically be a 1:1 translation of what is being said in the text currently?
If yes, I could try to do that.
Alternatively, we could add an English disclaimer that the below information informs on XYZ and is there due to German law? 
This could also be done for the other pages I noted that they were only available in German?

**Comment by han-f** [comment]
Vorschlag für Den Linknamen: Data privacy statement

Die Datenschutzerklärung muss wohl auf Englisch vorhanden sein, da der Webseitenhinhalt Englisch ist und damit englischhsprachige Nutzer*innen als Zielgruppe hat, die die Datenschutzerklärung dann natürlich auch verstehen müssen. Siehe z.B.: 

- https://www.datenschutz.org/datenschutzerklaerung-mehrsprachig/ 
- https://easyrechtssicher.de/datenschutzerklaerung-englisch/

**Comment by han-f** [comment]
A courtesy translation seems also not sufficient (then also holds for #544, #546)

**Comment by christian-rli** [comment]
This page becomes obsolete with the new privacy policy that was created in #544 .
