### ISSUE TITLE
The text under terms of use is not available in english

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#546]
http://toep.iks.cs.ovgu.de/legal/tou/

**Comment by han-f** [comment]
@MGlauer: not sure who is best to update such a text with legal touch.

**Comment by MGlauer** [comment]
Same as #545, I would remove the legacy reference to open_eGo, tho.

**Comment by christian-rli** [comment]
I added a translation of the terms of use. English comes first, with a disclaimer that only the German version further down below is legally binding.

We recently received a new document outlining our new privacy policy. I would volunteer to integrate that text on the website (also with respect to #545 #544 and #157 ), but I am confused now as to what it will replace; the page behind legal? Maybe you know @han-f or @MGlauer ?
