### ISSUE TITLE
Text in email for password reset is missing information

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#550]
The text does not include what to do in case the password recovery request was not made by this email address. I am not sure this is needed. 
**Current text**
> You're receiving this email because you requested a password reset for your user account at toep.iks.cs.ovgu.de.
> Please go to the following page and choose a new password:
> https://toep.iks.cs.ovgu.de/user/reset/MjE/5er-e3ac7d281a278b187756/
> Your username, in case you've forgotten: Hannah
> Thanks for using our site!
> The toep.iks.cs.ovgu.de team

**Suggested improvement**
Hi
You are receiving this email because you requested a password reset for your user account on the Open Energy Platform (OEP)
Please follow this link to choose a new password: ###
And - just in case you forgot -  your username is  _###_
Thank you for working with the OEP.
Best regards,
the OEP team

**Comment by MGlauer** [comment]
The `toep.iks.cs.ovgu.de`-parts are intentional. If someone wants to self-host the OEP, they want their own URL in this place.

**Comment by han-f** [comment]
> The toep.iks.cs.ovgu.de-parts are intentional. If someone wants to self-host the OEP, they want their own URL in this place.
Sounds fine. I just added ### to not repeat the links. Main message is the suggestion to improve the text.

**Comment by han-f** [comment]
Would this then also hold for #548 ? In the first line there in the original text OpenEnergy Platform is spelled out.

**Comment by MGlauer** [comment]
Yes, for consistency, we should also change it there.

**Comment by han-f** [comment]
I adjusted the suggested text above accordingly (adding ###), and did so for #548 too.

**Comment by MGlauer** [comment]
I would like to use the same template for this and #548 and therefore replace

> Thank you for working with ###.

with

> If you have any questions, please do not hesitate to get in touch with us via the contact form ###
