### ISSUE TITLE
The Groups/Memberships sections lacks information

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#552]
There is a Membership section with which a user can interact. It lacks information. What is it for, what can a user do...
This shows when logged in:
![grafik](https://user-images.githubusercontent.com/36844029/76612305-4a676080-651c-11ea-95b6-88cfad04caaf.png)
When I click it I come to:
![grafik](https://user-images.githubusercontent.com/36844029/76612259-33287300-651c-11ea-830b-3152b0d119d5.png)
Then I can create a group, add members etc. But there is never any accompanying text.

**Comment by jh-RLI** [comment]
I enhanced the profile page a bit and added some text to provided more context about the Groups and how/where they are used currently.



![Image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/88209c60-60cc-4dd0-bf2e-c95e5fe15754)
