### ISSUE TITLE
Scenario Factsheets: not possible to select different Tools from dropdown

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#555]
When creating a new Factsheet, under the study section, it is not possible to select different toolsfrom the drop down menu, only this is available:
![grafik](https://user-images.githubusercontent.com/36844029/76735082-78d77c80-6764-11ea-8da9-71c97f8a372f.png)

Related to #527

**Comment by stap-m** [comment]
Outdated.
