### ISSUE TITLE
Scenario Factsheets: Tooltip is not in english

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#556]
When leaving a mandatory field empty and trying to submit the form, the tooltip reads in German: "Bitte füllen Sie dieses Feld aus". 

Suggested improvement: "please complete this mandatory field"

**Comment by johannwagner** [comment]
This is a language-agnostic tool tip, which is rendered from your browser in your system language. Actually, there is nothing I can do with little effort about this.

**Comment by han-f** [comment]
Maybe this should be implemented in the same manner as in Framework Factsheets? There such an error message looks like this, and makes it very obvious what the user should do.
Albeit, currently it lacks a button for working on completing the missing fields 

![grafik](https://user-images.githubusercontent.com/36844029/76749017-14c0b280-677c-11ea-8cf3-c932488e2546.png)
