### ISSUE TITLE
Scenario Factsheets: empty field not highlighted 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#557]
When trying to submit a factsheet with leaving mandatory fields empty, there is a tooltip (which still reads German, see #556), but the field itself or the area is not really highlighted in red or so. 

Also - when scrolling on the website the tooltip also scrolls, making it complicated to see which field was mandatory and the tooltip related to.

**Comment by johannwagner** [comment]
I think, bootstrap and django-form uses the browser-specific validation. So, I am not sure, if there is anything, we can do about this. This requires further investigation.

**Comment by stap-m** [comment]
Outdated?
