### ISSUE TITLE
Scenario Factsheets: no tooltip shown for questionmarks

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#558]
For several entries in scenario factsheets a question mark makes users expect they can interact (e.g. tooltip) - when hovering over the question mark or or clicking it, nothing happens. (javascript://)

**Comment by MGlauer** [comment]
True - seems like the bootstrap function for popovers has been removed and [use a third-party package now](https://getbootstrap.com/docs/4.0/components/popovers/).
