### ISSUE TITLE
Framework Factsheet: there is no button to complete missing fields

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#559]
The form informs about missing mandatory fields, but does not offer a button to edit them.
![grafik](https://user-images.githubusercontent.com/36844029/76749375-afb98c80-677c-11ea-8dac-13edb28262f8.png)

**Comment by MGlauer** [comment]
I do not understand. You have to click on the categories. Maybe the error panels should be displayed over the category tabs.

**Comment by han-f** [comment]
Yes, that maybe helpful.  Or if the category would be noted next to the field name to which the error applies.
