### ISSUE TITLE
All Factsheets: adding / editing buttons not at agood position

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#561]
For all factsheets, the Action buttons are in the sidebar, users may expect them under the headings at the top.

**Comment by johannwagner** [comment]
@christian-rli This needs to be discussed.

**Comment by jh-RLI** [comment]
As they are visible, I don't think this is relevant at the moment. We would need to carry out a comprehensive user test with multiple users to get a non-subjective opinion on this,
