### ISSUE TITLE
Framework Factsheets: License drop-down not complete and no freetext for 'other'

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#563]
The drop-down menu holds several licenses to choose from which is great. However, some of them have explicit version numbers attached. This makes having a steady and complete list complicated. 

When a user chooses 'Other', there is no possility to provide the name of this other license. 

![grafik](https://user-images.githubusercontent.com/36844029/76757512-0082b280-6788-11ea-85ac-cc018e0fc7f2.png)

**Comment by jh-RLI** [comment]
Other can now be used. When viewed, it is displayed in the wrong category. Closed as this issue has been resolved by providing a working Other + free text field.
