### ISSUE TITLE
Framework Factsheet: uploaded Logo does not show

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#565]
Uploading a logo (.png) seems to have worked, but when I view the factsheet information it is not rendered.
![grafik](https://user-images.githubusercontent.com/36844029/76758566-3b85e580-678a-11ea-86b1-95f44554b6cc.png)

**Comment by han-f** [comment]
I uploaded a .png - then tried editing the Factsheet again, uploading a .jpg - then got the error (see screenshot below). Tried .png again, error remained.

![grafik](https://user-images.githubusercontent.com/36844029/76758915-f1513400-678a-11ea-9bb0-b47fce14dc29.png)

**Comment by MGlauer** [comment]
Seems like this was a faulty configuration on the server-side and therefore not code-related.
