### ISSUE TITLE
Framework Factsheet: not all provided information shown in factsheet

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#566]
Several of the data that I provide in the input fields are not displayed as having been provided after saving the factsheet.
(too many to list or screenshot)

**Comment by MGlauer** [comment]
Does this happen when submitting a new factsheet or when editing an existing one?

**Comment by han-f** [comment]
I found it when editing an existing one (that I just submitted a second beforehand). I can try again when adding a new one.

**Comment by han-f** [comment]
I found it when editing an existing one (that I just submitted a second beforehand). I can try again when adding a new one.

**Comment by han-f** [comment]
I tried with some of the elements again, with a new factsheet and then they were displayed

**Comment by han-f** [comment]
This also happens for model factsheets - I assume it is the same issue ...

**Comment by MGlauer** [comment]
Ah, now I see. The information is stored, but just not displayed. Probably due to missing fields in the display forms.

**Comment by stap-m** [comment]
I think this can be closed
