### ISSUE TITLE
Development of "scenario bundles"

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#568]
Document and start development of the bundles.

**Comment by jh-RLI** [comment]
Result:
https://openenergy-platform.org/scenario-bundles/main

Documentation;
https://openenergyplatform.github.io/organisation/family_members/knowledge-representation/oekg/
https://openenergyplatform.github.io/organisation/family_members/templates-and-specification/scenario-bundles/
