### ISSUE TITLE
Dataview: can not edit permissions of table

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#571]
Contrary to the message below, I am not able to edit the permissions of the table (I am logged in). 
![grafik](https://user-images.githubusercontent.com/36844029/76830318-4b063c80-6825-11ea-9486-39d2439c08bf.png)

**Comment by MGlauer** [comment]
It seems the text-box is in the wrong place. As you are not owner of this dataset, it is intended behaviour that you cannot change the permissions. Probably the links should be disabled in this case.

**Comment by han-f** [comment]
Yes, it would be good to then disable the links.
