### ISSUE TITLE
Dataview: Add Graph / Map view not self-explanatory

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#573]
The menu that is displayed after clicking the above is not self-explanatory. My suggestion would be to add some explanatory paragraph (yes more text), or delete these interaction possibilities (for the moment). 
Map view:
![grafik](https://user-images.githubusercontent.com/36844029/76835223-ea7bfd00-682e-11ea-9325-a360e78157e5.png)
Graph view:
![grafik](https://user-images.githubusercontent.com/36844029/76835258-fb2c7300-682e-11ea-8219-5d429f7ddbda.png)

**Comment by MGlauer** [comment]
Do you know what these forms do? If so, cold you provide some explanatory text?

**Comment by han-f** [comment]
I could guess:one created a graph, the other a map. I could draft some explanatory text on what a user should in general do, but I think the drop down choices seem a bit complicated, too. If someone could provide me with some basic info to start from, I could try to draft tomorrow (today I only have time in between other tasks).

**Comment by MGlauer** [comment]
The forms have been split in cade9c95
