### ISSUE TITLE
Dataview: Added metadata is not validated?

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#574]
I am not sure whether this is an issue: I tried to add metadata to the example table. This worked. However, I always added the same to each element even if they require a certain input. There was no error thrown that I need to change what I input and the data is displayed on the sidebar, even if it does not make sense.

**Comment by jh-RLI** [comment]
I would divide this issue into two separate parts @han-f. 
1. parse and validate the metadata
2. presentation/placement of the metadata on the website

**Comment by jh-RLI** [comment]
@MGlauer This is about validating the metadata string. We could use this [package](https://github.com/Julian/jsonschema) to validate the individual fields.

**Comment by jh-RLI** [comment]
https://github.com/OpenEnergyPlatform/data-preprocessing/issues/50
