### ISSUE TITLE
Dataedit: This could be made more user-friendly

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#575]
When I enter the page the first thing I see is a heading "How to access the database".
For a new user this may be a bit overwhelming. How about: changing it to:
Heading: "How to access data"
Short text below heading: "There are two ways in which you can access data. In _Dataview_ you do so directly via navigating the website. Access via the _API_ is for those who like to code."

-> Like this I kind of know what to expect and what suits me better. A novice user may not know what the API is, click there and get lost.  Then the two tiles can come and their description below. I would make the tiles a bit smaller too. 

![grafik](https://user-images.githubusercontent.com/36844029/76931425-ead8ce80-68e8-11ea-8ecc-64254a03f7c0.png)

**Comment by christian-rli** [comment]
The frontpage changed to a more intuitive design.
