### ISSUE TITLE
Heading on database section could read easier for users.

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#576]
The menu item at the top left header menu reads "Databases", could it read "Data" instead?

**Comment by han-f** [comment]
The menu item at the top left header menu reads "Databases", could it read "Data" instead?

**Comment by MGlauer** [comment]
@Ludee The term "Database" was part of the Mock-Ups, I guess. What is your opinion on this?

**Comment by Ludee** [comment]
I prefer "Data" as @han-f suggested!

**Comment by jh-RLI** [comment]
It still reads Database. I think this is clear. Should we use "Data" instead?
