### ISSUE TITLE
Display of metadata needs revision

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#584]
I found some bugs in the representation of the metadata string:

- When an element is _null_ it is displayed as _<class 'NoneType'>_ on the OEP.

On the schema view the database name is used as title, please change to:

- **Title of the Table** (database_name)

**Comment by jh-RLI** [comment]
I can deal with it tomorrow. 

Additionally, I find the output window too narrow. We could use the space on the right for the metadata widget. Or at least fix the slider(scroll left/right) to the bottom of the screen, that would improve usability in my opinion. @Ludee @MGlauer

**Comment by johannwagner** [comment]
This was solved during the redesign. We moved it into the middle of the page.
