### ISSUE TITLE
Tags: list of tags in sidebar not "complete"

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#585]
The list of tags in the sidebar doen't seem to display the most-helpful tags anymore. 
It seems to list the first tags in alphabetical order. Clicking tags works, but using the filter field above to find and apply tags does not.

**Comment by han-f** [comment]
They seem to transform into most popular tags as the OEP is used.

**Comment by MGlauer** [comment]
This is caused by 
`{% get_tags None None 10 as all_tags %}` selelects only the top 10 tags.
@johannwagner Could you implement it in a way that one can display all tags?
(Calling get_tags with `None` instead of 10 returns all tags.)

**Comment by han-f** [comment]
What happens if we have a lot (!) of tags - would this clutter the sidebar, or would there be a _more_ link or something similar?

**Comment by johannwagner** [comment]
Right now, it would clutter the sidebar.

**Comment by MGlauer** [comment]
@johannwagner What about the "Show more" link @han-f proposed to hide less common tags by default?

**Comment by Ludee** [comment]
I think the tag functions on schema level need an improvement.
Easier selection and editing should be added.
@jh-RLI can you do that for the next release?

**Comment by Ludee** [comment]
The editing of tags doesn't work. This area needs attention, tags are an essential feature of the database.
