### ISSUE TITLE
Data: data table does not load

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#587]
The data tables simply do not load at all.
E.g.: https://openenergy-platform.org/dataedit/view/scenario/ksz2050_r2_ks95_fugitive_emissions

**Comment by han-f** [comment]
Firefox Quantum 68.6.0esr (64-Bit), Windows 10

**Comment by jh-RLI** [comment]
Using Google Chrome this works. 
![image](https://user-images.githubusercontent.com/38939526/77322930-c62f8d00-6d14-11ea-8695-dfab4212db52.png)

Unfortunately, I cannot test Firefox right now.

**Comment by han-f** [comment]
Its seems to have been a caching problem! It works for me too, thanks to @MGlauer pointing me to the cache issue.
