### ISSUE TITLE
Tags: naming is not uniform across sidebar

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#592]
Suggest to rename "Filters" heading  to "Tags" as this is what a user searches in the search bar.
Suggest to rename "Apply Filters" and "Reset Filters"  to "Apply Tags" and "Reset Tags".

**Comment by MGlauer** [comment]
I think this is because the buttons do not only apply to Tags but also to the search bar above.

**Comment by han-f** [comment]
How about renaming then? The search bar also searches for tags, no? So its heading could be _Tags_ instead ?
