### ISSUE TITLE
Factsheets: cannot delete factsheet

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#595]
There is no button to delete a factsheet - be it a study or a scenario.
By writing this, I wonder if it would be possible to delete scenario _Test test_ and _Test Scenario with Study_ 
This would improve the display of the list of Scenario Factsheets and limit it to factsheets that actually refer to real information. Many thanks.

**Comment by stap-m** [comment]
deletion should be discussed together with user permissions and access

**Comment by jh-RLI** [comment]
Related to #1299
