### ISSUE TITLE
Open Energy Family does not yet occur on the OEP webpage

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/oeplatform#596]
The concept of the Open Energy Family with all its members/tools should be described on the webpage. Did we already discuss this somewhere? Where is a good place?

**Comment by han-f** [comment]
Could we do this part on "About OEP" and part on a new page that is called "Open Energy Family"?
We could add one introductory paragraph that explains that the OEP is one member of the open energy family and then link to "Open Energy Family" where we explain the Members and link to github for each of them. 
I could try to draft such texts. On the "Open Energy Family"  page we could have the little icons representing the members next to the corresponding explanatory text, providing some visual guidance.

**Comment by han-f** [comment]
Should we have this as a topic for a Jour-Fixe before working on it?

**Comment by Ludee** [comment]
Merge this [GitHub Readme](https://github.com/OpenEnergyPlatform/organisation/blob/master/README.md) and the [About OEP](https://github.com/OpenEnergyPlatform/oeplatform/blob/master/base/templates/base/about.html)

**Comment by Ludee** [comment]
![OpenEnergyFamily_druck](https://user-images.githubusercontent.com/14353512/80697156-dd625700-8ad8-11ea-84c8-e710926d803b.png)

**Comment by stap-m** [comment]
Is the list of participating institutes complete?

**Comment by Ludee** [comment]
not yet, thanks for the hint.
