### ISSUE TITLE
Rework the page for the OEO and OEO-SC

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#598]
- [x] https://github.com/OpenEnergyPlatform/ontology/issues/313
- [x] https://github.com/OpenEnergyPlatform/oeplatform/issues/604

**Comment by christian-rli** [comment]
Arguments in favour of moving the page for the OEO-SC to the OEP:

- OEP looks good already, it's easy to add a subpage
- creating ye another wordpress page and paying for it is a nuisance for administration and organisation in general
- having everything at one place makes maintenance easier, logical sense and creates a tidy impression

**Comment by jh-RLI** [comment]
The subpage already exists if the content is available I can finish the work and prepare the release.

**Comment by Ludee** [comment]
Can be reviewed and included in next release!

**Comment by Ludee** [comment]
Add an **ontology** item to the header to enable navigating to the OEO pages (OEO & OEO-SC) from everywhere.

@MGlauer When is the next release?

**Comment by jh-RLI** [comment]
@Ludee YFI: The [release cycle ](https://github.com/OpenEnergyPlatform/oeplatform/blob/docs/deployment-pipeline/RELEASE_PROCEDURE.md)foresees that we publish a new release every first Monday of the month.

**Comment by Ludee** [comment]
@MGlauer Ping for including this commits for the OEP/OEO release.

**Comment by jh-RLI** [comment]
Created the PR and linked the issue and PR to the next release project.
