### ISSUE TITLE
Translation from python code to UML

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#60]
There should be a tool that translates existing python code to UML diagramms (especially class diagrams). The main issue is that python is not type secure but python 3.5 introduced [type hints](https://www.python.org/dev/peps/pep-0484/). These might be used to enhance the performance. Also, I do not know any tool that produces a valid xmi document according to recent standards. XMI is the standard exchange format for UML, though.

**Comment by EdithaK** [comment]
@MGlauer Can you colse?
