### ISSUE TITLE
GitHub releases are organised via "Projects" and "Milestones"

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#602]
We started with [Milestones](https://github.com/OpenEnergyPlatform/oeplatform/milestones) and moved to [Projects](https://github.com/OpenEnergyPlatform/oeplatform/projects).

Shall be delete the old milestones and create projects?

**Comment by MGlauer** [comment]
Yes, the usage of projects yields better functionalities than milestones do.

**Comment by christian-rli** [comment]
I deleted the old milestones.
