### ISSUE TITLE
Add OEO Steering Committee Subpage

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#604]
The OEO Steering Committee needs its own web page, which should be a sub page of the OEP. Please create such a sub page @jh-RLI . I think it makes sense to link it somewhere under ontology.

https://openenergy-platform.org/ontology/

The URL would then be 

https://openenergy-platform.org/ontology/oeo-steering-committee

Content for the page is here:

https://github.com/OpenEnergyPlatform/ontology/wiki/OEO-Steering-Committee

An issue to create an English translation is open here: https://github.com/OpenEnergyPlatform/ontology/issues/313

Creating the page and making it look simple, but decent enough are priorities. The final text and location can easily be changed later on. Contact me if you have any questions. 

Feel free to give feedback make changes to this issue @Ludee

**Comment by Ludee** [comment]
Add these two paragraphs:

- [ ] [What is the Open Energy Steering Committee (OEO-SC)?](https://github.com/OpenEnergyPlatform/ontology/wiki/OEO-Steering-Committee#what-is-the-open-energy-steering-committee-oeo-sc)
- [ ] [Who is involved with the OEO-SC?](https://github.com/OpenEnergyPlatform/ontology/wiki/OEO-Steering-Committee#who-is-involved-with-the-oeo-sc)
