### ISSUE TITLE
Tables with normal language titles do not work

### ISSUE THREAD

**Issue by l-emele** [OpenEnergyPlatform/oeplatform#607]
I've spotted that all entries in model draft, for which not only the name (with underscores) but also a title in normal language is shown lead to the error page.

Example: all of these
![grafik](https://user-images.githubusercontent.com/36884905/81577922-67989e00-93aa-11ea-91ca-70dc4fd673ee.png)

lead to:
![grafik](https://user-images.githubusercontent.com/36884905/81577995-85fe9980-93aa-11ea-94b2-f9c36f839c1d.png)

**Comment by MGlauer** [comment]
It seems this was cause by the fact that these tables still used version 0 (!) of the metadata format. It seems the last release dropped support for this format. I reintroduced it in f3f0e2a
