### ISSUE TITLE
Failed to add a new framework entry

### ISSUE THREAD

**Issue by CDerksen** [OpenEnergyPlatform/oeplatform#608]
Hi there,
I just tried to add a new framework to the Framework Factsheets, but I failed:
- Adding a logo file results to an error 
- I edited the section Mathematical Description, pressed 'Submit all' (to save the draft) and tried to edit the entries again. Unfortunately everything was gone ...

Is there a chance to register a framework and a model in a different way?

Best wishes,
C.

**Comment by Ludee** [comment]
Dear @CDerksen,

thanks for this bug report. 
Please try to edit the existing FFS [Test2](https://openenergy-platform.org/factsheets/frameworks/163/)
