### ISSUE TITLE
UML diagram validators

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#61]
We are looking for a tool that validates UML diagrams regarding correctness and conformance. This tool should be able to handle the XMI data format w.r.t. to recent standards. 

Linked to #60

**Comment by EdithaK** [comment]
closable?

**Comment by christian-rli** [comment]
There is documentation on printing UML here: https://openenergy-platform.org/tutorials/jupyter/UML_Workshop/
