### ISSUE TITLE
Wrong HTML in password reset e-mail

### ISSUE THREAD

**Issue by l-emele** [OpenEnergyPlatform/oeplatform#612]
I just reset my OEP password using the form on the website. I got the following e-mail:

> Hello<br>
> <br>
>
> You are receiving this email because you requested a password reset for your user account on openenergy-platform.org.
>
> Please follow this link to choose a new password:
>
> https://openenergy-platform.org/user/reset/MTIw/abcdefghijklmnopqrstuvwxyz/
> 
> And - just in case you forgot - your username is: ABCDEFGH
>
> <br>
> If you have any questions, please do not hesitate to get in touch with us via the contact form <br> <a href="https:///contact">https:///contact</a><br>
> <br>
>Best regards,<br>
> the  Team<br>

The `<br>` tags should not show up and the contact link is not valid.

**Comment by sashatankov** [comment]
Hey, I'd like to work on this one. What should the valid link be?

**Comment by MGlauer** [comment]
> Hey, I'd like to work on this one. What should the valid link be?

Oh, sorry! I did not see your post ^^' 

The problem was an inconsistency in the variables that have been used to pass the domain context to the templates. I.e.: The link was correct in the templates - just with the wrong variable.
