### ISSUE TITLE
Implement scenario fact sheets

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#618]
There has been an agreement regarding the structure of what has been described as scenario fact sheets. A more thorough analysis has shown that a single fact sheet is not sufficient and does not cover the use cases of the community. Therefore, an alternative scheme has been designed in which we distinguish between:

1. A scenario specification:
  * Defines constraints that make up a specific scenario
  * e.g. goals, assumptions etc.
2. A model calculation
  * The successful execution of a specific energy model
  * References input and output data
  * May conform to one or more scenario specifications
3. A bundle
  * Contains one or more model calculations
4. A study
  * A document in which results were published

Sub-issue of #368

**Comment by MGlauer** [comment]
We should use this issue to manage the work plan. The current plan is as follows:

A. We need to implement a SPARQL endpoint that allows us to query an RDF triple store that contains scenario factsheets as a graph.
B. Implement forms so that users may enter new data to the triple store. The terms used in queries should be based on our OEO.

@VenkateshDas is currently working on B. 

We still need a representation of the structures listed in the [original post](https://github.com/OpenEnergyPlatform/oeplatform/issues/618#issue-680088296) so that the queries can be properly formulated. @meisam-booshehri could you work on this part?

**Comment by meisam-booshehri** [comment]
@MGlauer Sure. I'm going to read a paper I got from Till today in order to figure out the next steps.

**Comment by jh-RLI** [comment]
This is implemented: We call it scenario bundles instead of scenario factsheets now. The OEKG is where we Store the Triples and we can query it using SPARQLWrapper and rdflib python libs. Additionally we will implement an GUI to query the OEKG.
