### ISSUE TITLE
Bug: Tables with a name starting with a capital letter can be uploaded

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#621]
@Richard-Schmitz  identified a possible bug which we (@han-f  and @wingechr ) previously experienced as well at one point.
Tables starting with a capital letter can be uploaded to the platform. They are displayed without content and the user who uploaded them cannot delete them. This should be fixed.

**Comment by MGlauer** [comment]
Could you specify, which API call has been used to create the table?

**Comment by han-f** [comment]
> Could you specify, which API call has been used to create the table?
@Richard-Schmitz: can you specify this please?

**Comment by Richard-Schmitz** [comment]
This is the command use in Python:

API_URL = 'https://openenergy-platform.org/api/v0'

**Comment by MGlauer** [comment]
> This is the command used in Python:
> 
> API_URL = 'https://openenergy-platform.org/api/v0'

Ah, so you are using the `oep-client` package. This helps, thanks!

**Comment by MGlauer** [comment]
I guess I figured it out and fixed it.

**Comment by Richard-Schmitz** [comment]
Thanks, I will try it out as soon as possible.

Could you please delete the following tables in the model_draft-section, so that their names can be re-used?
CountryValues1
CountryValues2
CountryValues3
CountryValues4
Fh_IEE_Trafo_FW_viel_dez_Biomasse_hohe_Sanierung_Emissionen
Fh_IEE_Trafo_FW_viel_dez_Biomasse_hohe_Sanierung_Endenergie
Fh_IEE_Trafo_FW_viel_dez_Biomasse_hohe_Sanierung_Speicher
Fh_IEE_Trafo_FW_viel_dez_Biomasse_hohe_Sanierung_Verkehr
fh_IEE_Trafo_FW_viel_dez_Biomasse_hohe_Sanierung_Speicher2

**Comment by MGlauer** [comment]
> Thanks, I will try it out as soon as possible.
> 
> Could you please delete the following tables in the model_draft-section, so that their names can be re-used?
> CountryValues1
> CountryValues2
> CountryValues3
> CountryValues4
> Fh_IEE_Trafo_FW_viel_dez_Biomasse_hohe_Sanierung_Emissionen
> Fh_IEE_Trafo_FW_viel_dez_Biomasse_hohe_Sanierung_Endenergie
> Fh_IEE_Trafo_FW_viel_dez_Biomasse_hohe_Sanierung_Speicher
> Fh_IEE_Trafo_FW_viel_dez_Biomasse_hohe_Sanierung_Verkehr
> fh_IEE_Trafo_FW_viel_dez_Biomasse_hohe_Sanierung_Speicher2

I can do that. I still have to update the live version of the server the next release is scheduled next Tuesday. I will close this ticket as soon as the release is done.

**Comment by Richard-Schmitz** [comment]
In the meantime, do I have to rename - for example - the table
"Fh_IEE_Trafo_FW_viel_dez_Biomasse_hohe_Sanierung_Emissionen"
into
"fh_iee_trafo_fw_viel_dez_biomasse_hohe_sanierung_emissionen"
or is it possible to upload with capital letters after the bugfix?

**Comment by han-f** [comment]
As far as I gathered you will rename them as the bugfix will be to prevent uploads with capital letters.

**Comment by Richard-Schmitz** [comment]
For your interest, the following two points caused errors when I was trying to upload my tables:

- The name of the table must not be longer than 63 characters, otherwise you will get an http error

- The headline of the coulmn "id" must be in lowercase letters, writing "ID" also causes an error

**Comment by MGlauer** [comment]
This should be fixed now
