### ISSUE TITLE
Display name of table and title from metadata

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#634]
Display name of table and title from metadata.

Some table work (old metadata version).
Check this table:
https://openenergy-platform.org/dataedit/view/model_draft/wn_abw_ego_demand_hv_largescaleconsumer

**Comment by jh-RLI** [comment]
This could be included in #600 .

**Comment by MGlauer** [comment]
This requires to reimplement the [read_label](https://github.com/OpenEnergyPlatform/oeplatform/blob/76974529847c39c6fa64f28a7b7d0ea0c3d9e272/dataedit/views.py#L303) function that maps a comment to a new table name (use OMI).

**Comment by MGlauer** [comment]
For this `load_metadata_from_db` has to be split into another function that translates the metadata to version 1.4.

**Comment by jh-RLI** [comment]
Overlap with #685 (keep 685 as UI discussion is more relevant) Metadata under v1.4 is no longer supported. Automatic conversion of an early OEM version to the latest is being considered and will be implemented.
