### ISSUE TITLE
Schema reference needs an updated description

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#635]
As long as we still have schemas, we may add "helper" tables in the "reference" schema. We need to update the description accordingly.

Suggestion:
Contains, sources, literature and helper tables which can assist with your work.

**Comment by han-f** [comment]
If possible I would also rename the display name of the schema to
'reference and help'   (and keep the url)

**Comment by Ludee** [comment]
Contains sources, literature and auxiliary/helper tables that can help you in your work.

**Comment by han-f** [comment]
So. let's implement for now: :
Contains sources, literature and auxiliary/helper tables that can help you with your work.
