### ISSUE TITLE
bug with mview

### ISSUE THREAD

**Issue by TuPhanRLI** [OpenEnergyPlatform/oeplatform#637]
Through the API tutorial, I created a table "bkg_vg250_2_lan_mview" in the "boundaries" schema (https://openenergy-platform.org/dataedit/view/boundaries/bkg_vg250_2_lan_mview) which wasn't
listed on the OEP website. But through the API I could still access the table and generate it. Is it supposed to be like that?

**Comment by christian-rli** [comment]
The table is listed in the boundary schema. I believe it wasn't displayed in you browser due to your caching of that page.
