### ISSUE TITLE
Several Display Flaws in Tutorial Area

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#638]
This appears to occur with all jupyter notebooks that were imported from github. 

The separating line between the tutorial and the sideline information is within the notebook. Therefore the side information overlaps the content. This may be connected to the issue that in the normal view there is a scroll bar at the bottom that allows to scroll just a tiny bit to the side. 

![Bildschirmfoto zu 2020-10-12 15-10-54](https://user-images.githubusercontent.com/42000429/95750725-d94c7f00-0c9d-11eb-8d72-d25ab1ceef43.png)

**Comment by TuPhanRLI** [comment]
The content at the tutorial by "OEP_API_tutorial_part1.html" doesn't display porperly and there are few ones which also doesn't show up @jh-RLI

**Comment by jh-RLI** [comment]
Already mentioned in #627. I will try to fix this.

**Comment by jh-RLI** [comment]
@johannwagner can you confirmed that this is fixed?

**Comment by johannwagner** [comment]
This is definitely fixed due to the redesign.
