### ISSUE TITLE
Clicking a tag in schema table leads to "edit tags"

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#639]
When I click a tag listed in a schema table, e.g. 'scenario', I assumed I would then obtain the list boiled down to entries with this tag. Instead, I am transported to the list of tags where I can edit them. Not sure if this is a bug, but definitely not what I as a user expect..

**Comment by jh-RLI** [comment]
The linked PR (on the right side) contains work that concerns the tags in dataedit, this will be included in the next release. I will include this in the PR.
