### ISSUE TITLE
section "review" should be removed from metadata editor

### ISSUE THREAD

**Issue by wingechr** [OpenEnergyPlatform/oeplatform#643]
users should not edit this information themselves

**Comment by christian-rli** [comment]
I agree. With a complete review process overhaul in the future we can think about a convenient functionality for reviewers to do this on the platform. However for now it should only be possible to upload the review info via the api.

**Comment by wingechr** [comment]
implemented in [feature/new_meta_editor](https://github.com/OpenEnergyPlatform/oeplatform/tree/feature/new_meta_editor) 
hide
* review
* metaMetadata
* resources.encoding
* resources.dialect
