### ISSUE TITLE
metadate editor: remove "If not applicable use (null)"

### ISSUE THREAD

**Issue by wingechr** [OpenEnergyPlatform/oeplatform#645]
users should not be asked to write "null" in each empty cell

**Comment by jh-RLI** [comment]
This could concern the ometadata itself. We require the user to use " null " in fields with an unknown or empty value.

**Comment by christian-rli** [comment]
Yes @TuPhanRLI the interface should automatically return null for an empty field. I think it's a logical convenience feature :) We require `null` in fields in the metadata string where there is an empty value. User on the platform need not care about the technical detail and just leave empty fields empty.

**Comment by christian-rli** [comment]
For completeness sake: "unknown" would be an information the user can enter. It differs from `null` in that there is the actual information that such information does exist, but it's unknown to the person working on this. In practice though, many users will likely leave the fields empty and that's also fine.

**Comment by wingechr** [comment]
implemented in [feature/new_meta_editor](https://github.com/OpenEnergyPlatform/oeplatform/tree/feature/new_meta_editor)
