### ISSUE TITLE
Internal Server Error 500 through Matlab 

### ISSUE THREAD

**Issue by TuPhanRLI** [OpenEnergyPlatform/oeplatform#654]
-through the advanced api i tried a post request with "joining tables and" calling the function "ST_AsText"
and "oder by" 
- previous mehods it did work with "forms" and "where" syntax

Some Side Information
url     = 'https://openenergy-platform.org//api/v0/advanced/search';

Options = weboptions('UserAgent','Mozilla/5.0','RequestMethod','post', 'MediaType','application/json');

{ "query":
             {"fields":

                     [
                         {"type": "function", "function": "ST_AsText", "operands":
                             [
                                 {
                                     "type": "column", "column": "point"
                                 }
                             ]
                          },
                         "name",
                         "description",
                         "standard_name",
                         "values",
                         "height",
                         "start",
                         "stop",
                         "segments"
                     ],

                 "from":
                  {"type": "join",
                           "left": {
                               "type": "table",
                               "table": "openfred_locations",
                               "schema":"climate",
                               "alias":"locations"

                           },
                           "right": {
                               "type": "join",
                                "left": {
                                    "type": "table",
                                    "table": "openfred_variables",
                                    "schema": "climate",
                                    "alias": "variables"
                                },
                                "right": {
                                    "type": "join",
                                    "left": {
                                        "type": "table",
                                        "table": "openfred_series",
                                        "schema": "climate",
                                        "alias": "series"
                                    },
                                    "right": {
                                        "type": "table",
                                        "table": "openfred_timespans",
                                        "schema": "climate",
                                        "alias": "time"
                                    },

                                    "on": {
                                        "operands": [
                                            {"type": "column", "column": "timespan_id", "table": "series"},
                                            {"type": "column", "column": "id", "table": "time"}
                                        ],
                                        "operator": "=",
                                        "type": "operator"
                                    }

                                },

                                "on": {
                                    "operands": [
                                        {"type": "column", "column": "id", "table": "variables"},
                                        {"type": "column", "column": "variable_id", "table": "series"}
                                    ],
                                    "operator": "=",
                                    "type": "operator"
                                }

                           },

                           "on":{
                               "operands": [
                                                {"type": "column", "column":"id", "table": "locations"},
                                                {"type": "column", "column":"location_id", "table": "series"}
                                             ],
                                                "operator": "=",
                                                "type": "operator"
                           }
                   },
              "where": [
                  {"operands": [{"type": "column", "column": "height"}, 400], "operator": "<=", "type": "operator"},
                  {"operands": [{"type": "column", "column": "height"}, 0], "operator": ">=", "type": "operator"},
                  {"operands": [{"type": "column", "column": "start"}, "2014-12-31T23:30:00"], "operator": "=", "type": "operator"},
                  
                  {"operands": [{"type": "column", "column": "point"}, "0101000020E61000000000004019F63340000000609EF44C40"], "operator": "=", "type": "operator"},
                  {"operands": [{"type": "column", "column": "name"}, "VABS_AV"], "operator": "=", "type": "operator"}

              ],
                "order_by": [{"type": "column", "column": "height", "ordering": "asc"}]
              }}

**Comment by KirannBhavaraju** [comment]
**Not reproducible**, on the platform in intitial testing via external sources (Postman). 

# Request Type
``` 
Request Type : POST
Request Url: https://openenergy-platform.org/api/v0/advanced/search/
Request Body Type : raw/JSON
```

# Request and Response Objects:
Please rename with a .json for json.
- Request Json as .txt: [request.txt](https://github.com/OpenEnergyPlatform/oeplatform/files/5643891/request.txt)
- Response Json as .txt: [response.txt](https://github.com/OpenEnergyPlatform/oeplatform/files/5643865/response.txt)

# Response Params: 
![image](https://user-images.githubusercontent.com/28805843/101186494-72bb6000-3653-11eb-86e0-3ed284e0fd84.png)

Can you please share more context as to your Matlab Script?

**Comment by KirannBhavaraju** [comment]
I am sharing the script i used in matlab to test your scenario with similar ` weboptions `, the same `schema`, `tables`, `joins`.  

![image](https://user-images.githubusercontent.com/28805843/101200883-30038300-3667-11eb-86b7-3e17fdaa24c9.png)

However, **have been unsucessful in reproducing your issue**.  @TuPhanRLI
