### ISSUE TITLE
Tutorials from markdown look different in preview then in final version

### ISSUE THREAD

**Issue by wingechr** [OpenEnergyPlatform/oeplatform#656]
Steps to reproduce:

* New tutorial:

```markdown
<a name="anchor">i am an anchor</a>
[i am a link to the anchor](#anchor)
```

* Preview (is ok)

![preview](https://user-images.githubusercontent.com/4265368/97320154-d04ad880-186d-11eb-9f02-8f51087d72bd.png)

* Submit (no raw html):

![rendered](https://user-images.githubusercontent.com/4265368/97320220-dc369a80-186d-11eb-82ef-227c041b8149.png)

**Comment by jh-RLI** [comment]
I have provided a hotfix to escape the html that fixes this bug. (see linked PR) 

Thereby I came across new bugs: 
Some markdown elements are not rendered as expected (elements like checkbox and code blocks). 

Why does it behave like this:
It seems that Markdown2 and the preview of the easymde Markdown Editor generate different results. 
Easymde does a better job rendering the markdown, but it does not generate html. 
 

## Markdown2 is generating (markdown to html) and saves to DB, the following is not generated as expected:
### checkbox:
"- [ ]" as :


### codeblocks:
"description:
    code

or
"``` code ```" as:

**Comment by jh-RLI** [comment]
I will have a look at how to set anchors in markdown or insert anchors as HTML. Are there any other HTML tags needed? @wingechr

**Comment by wingechr** [comment]
no, but we can also forgo the anchors, if it's too much hassel. it's more of a nice to have
