### ISSUE TITLE
Missing integration of review process in platform

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#658]
The review process is too complicated, especially if to attract volunteers. Significant parts of it can be automated. All of that should be integrated into the oep. If it's easy and maybe even fun to review, it'll make life easier for reviewers and maybe even attract volunteers.

**Comment by jh-RLI** [comment]
This new open peer review process is actively implemented in the platform.
![image](https://user-images.githubusercontent.com/38939526/236575877-98c5d401-0062-4eab-85ba-bffaa10ca331.png)

**Comment by jh-RLI** [comment]
The first version is well on its way. The review process is already implemented in the platform and is being actively further developed. See https://github.com/orgs/OpenEnergyPlatform/projects/15/views/1?layout=board
