### ISSUE TITLE
Not all tags are shown

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#660]
This is related to #659 
There are only a few tags shown that users can choose. Since the Filter search bar seems to only search for table names, there is no chance a user can find tables by tags other than the ones shown. 

It would be very helpful to include all tags in some way.

@MGlauer - this would also be very helpful to have fixed for the next release.

**Comment by han-f** [comment]
See also pull request https://github.com/OpenEnergyPlatform/oeplatform/pull/600

**Comment by MGlauer** [comment]
This PR has been already merged
