### ISSUE TITLE
Front page: explanatory text missing

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#661]
The front page has no mouse-over explanatory text that can guide the user. E.g. only a figure with "database"  may not be sufficient for a user to know this is where the data he/she is looking for is at.

Suggestion: provide mouse-overs or very short guidance that explains what to find where.

**Comment by MGlauer** [comment]
Related to #662

**Comment by meisam-booshehri** [comment]
I think this issue should be closed as this is related to issue #662, which is closed now. right?

**Comment by MGlauer** [comment]
Seems right
