### ISSUE TITLE
Front page does not sufficiently guide users

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#662]
The front page has no mouse-over explanatory text that can guide the user. E.g. only a figure with "database"  may not be sufficient for a user to know this is where the data he/she is looking for is at.

Suggestion: provide mouse-overs or very short guidance that explains what to find where.

**Comment by han-f** [comment]
Today we discussed that some texts will be implemented, not mouse-overs. Not sure when those texts should be made and by whom.
@bmlancien  let me know when it would be useful to write such texts, and whether I should have a go at them.

**Comment by bmlancien** [comment]
I think you could ask to write the texts right away. I just don't know who would implement this on the website after that. I was thinking of a solution like below. Quite simple: icon + heading + text + button inside a box for each section.

![OEP_HP_Desktop](https://user-images.githubusercontent.com/33999424/98255121-5b6a5380-1f7d-11eb-818a-ee7ad5aba4ae.png)

**Comment by han-f** [comment]
Looks great I think. 
@MGlauer @christian-rli @wingechr  @klarareder @stap-m @l-emele  here come some suggested texts for each of the boxes, feel free to adjust / implement once ready. 
**Database:** You are interested in data? Come, visit the database to explore. Every dataset available is published under an open license, so you can securely download and work with it. 
**Factsheets:** If you want to learn more about scenarios and models related to the data this is the right place to look. You contributed data and want to add context? Create your own factsheet here. 
**Ontology:** Come here to learn more about the Open Energy Ontology (OEO) which helps - for example - with data annotation and searches on the website.
**Tutorials:**  You would like to know how to contribute to the Open Energy Platform (OEP), or how to use the API to interact with the database, or something else? We provide many tutorials covering a wide range of ways on how to work with the OEP. You can also contribute your own.

**Comment by klarareder** [comment]
It is a nice and informative display. @bmlancien the icons are different from the icons you made with the open circle. E.g. Turorials are like a Screen and here pen and paper. Would it look good to use the same icons? Or even the icon with the open circle?

**Comment by han-f** [comment]
I think Bryan used the icons we already have on the front page: 

![grafik](https://user-images.githubusercontent.com/36844029/98342232-6ae6ac80-2010-11eb-81d0-d46f1b713cc3.png)

**Comment by klarareder** [comment]
Yes, but I still think we could consider using the other icons to be consistent.

**Comment by klarareder** [comment]
Some suggestions on the text:
**Database:** Are you interested in data? Visit the database to explore it. All contributors publish datasets under an open license, so you can securely download and work with it. Are you interested in sharing your own data? This is the place to upload it.
**Factsheets**: Do you want to learn more about scenarios and models related to the data this is the right place to look. You contributed data and want to add context? Create your own factsheet here.
**Ontology**: Come here to learn more about the Open Energy Ontology (OEO), which helps - for example - with data annotation and searches on the website.
**Tutorials**: Would you like to know, how to navigate on the Open Energy Platform (OEP), or how to contribute e.g by using the API, or something else? We provide many tutorials covering a wide range of ways on how to work with the OEP. You can also contribute your own tutorials.

**Comment by klarareder** [comment]
Is there an other wording for 'data annotation' (Ontology)? I think it is the correct term but (at least for me) not a term I can easily understand. I guess many non native speakers will be on the homepage, so I think it would be nice to have it very understandable.

**Comment by han-f** [comment]
> **Database:** Are you interested in data? Visit the database to explore it. All contributors publish datasets under an open license, so you can securely download and work with it. Are you interested in sharing your own data? This is the place to upload it.

Thanks for the suggestion @klarareder - I did not add information about "this is the place to upload" - since when a user goes to the database he/she sees the schemas, clicks a link and then sees a table. The interaction available is currently the download. Once the Wizard is there also the upload - but only with the wizard and not the API.  How about: 

> **Database:** Are you interested in data? Visit the database to explore it. All contributors publish datasets under an open license, so you can securely download and work with it. Are you interested in sharing your own data? This is the place to upload it via our Upload-Wizard.

What we still have missing then is the API. Maybe we could consider (new issue) to add not only the Wizard to the sidebar at the tables, but also a link to the API?

**Comment by klarareder** [comment]
Maybe we could have two buttons: 
1.) upload data easy  - [Info] without prior knowledge, recommended for a single table -> upload Wizard
2.) upload data convinient - [Info] programming skills required, recommended for multiple tables -> API

**Comment by bmlancien** [comment]
> the icons are different from the icons you made with the open circle. E.g. Turorials are like a Screen and here pen and paper. Would it look good to use the same icons? Or even the icon with the open circle?

@klarareder Yes, as @han-f mentioned, I only took the actual ones, but you're right that we should use the new icons to make it consistent with the rest. I don't think it is necessary to add the open circles, but it is also possible. But bear in mind that without circles they look like more icons, and with the circles, more like logos. An icon gives more the impression that we're talking about a feature whereas with a logo look we might think we're talking about a platform, a tool or another website. So it all depends on your purpose.

**Comment by klarareder** [comment]
> An icon gives more the impression that we're talking about a feature whereas with a logo look we might think we're talking about a platform, a tool or another website. So it all depends on your purpose.

Good point - than is without the circle more appropriate.

**Comment by stap-m** [comment]
> Factsheets: If you want to learn more about scenarios and models related to the data this is the right place to look. You contributed data and want to add context? Create your own factsheet here.

I'd extend it as follows: "[...] Create _and publish_ your own _factsheets_ here." 

> Ontology: Come here to learn more about the Open Energy Ontology (OEO) which helps - for example - with data annotation and searches on the website.

What about: "which helps - for example - with data annotation and _data search_." ?

**Comment by l-emele** [comment]
Does the ontology currently help with _data search_? I don't think that the OEO currently serves this purpose. So we should not mention this as it else awakens expectations that we currently cannot fulfill.

**Comment by han-f** [comment]
Text for ontology ( discussed with @MGlauer and @meisam-booshehri ): 

Ontology: Come here to learn more about the Open Energy Ontology (OEO), which with data annotation and management.

**Comment by KirannBhavaraju** [comment]
# Issue Status: 
First Preview Available.

# Changes/Additions:
- Some text for making it more clear, all the points mentioned above.
- Some text for "Documentation"
- Some positional/layout changes to follow with the theme of the application.

# Preview
Below are some previews of the changes in the `index.html`

## Fullscreen
![image](https://user-images.githubusercontent.com/28805843/102023030-047d4880-3d8b-11eb-802c-145b46f8e1f4.png)

## All further Window Resizing (Width Underflow)
![image](https://user-images.githubusercontent.com/28805843/102023106-79e91900-3d8b-11eb-9b4d-87960fb80695.png)

**Comment by stap-m** [comment]
Looks good. What else needs to be done here? This issue needs to be fixed an implemented before the Abschlussworkshop!

**Comment by han-f** [comment]
Decision from call on 2021-01-06: 

- substitute "Documentation" box by "Tutorials" (and its  text)
-  get rid of what currently is in "Documentation" box.

**Comment by KirannBhavaraju** [comment]
So the 4 main blocks would be Database, FactSheets, Ontology, and, Tutorials. 
The Documentation will then be where Tutorials is now, with no text and just a button..
Is this correct? @han-f

**Comment by han-f** [comment]
I understood that the Documentation could go altogether, since the link is included under the API link in the footer.

**Comment by KirannBhavaraju** [comment]
Oh okay, i was just confirming. Thanks for the clarification.

**Comment by KirannBhavaraju** [comment]
# Changes
- Removes Documentation
- Repositions Tutorials
- Scales accordingly

# Preview Desktop-Landscape
![image](https://user-images.githubusercontent.com/28805843/103897723-3f596e80-50f4-11eb-8e05-91a578bde587.png)

# Preview Handheld-Portrait
<img src="https://user-images.githubusercontent.com/28805843/103898398-28674c00-50f5-11eb-95c3-1292cb51fafe.png" width="50%" height="50%">

**Comment by klarareder** [comment]
It looks good! I noticed that you seem to work with an old verion of the layout, on the current OEP Website the section "Research Data Management" is called "API". Please make sure, that we keep the current status with API.
![grafik](https://user-images.githubusercontent.com/42575569/103985534-6746e180-5189-11eb-81ac-8471f8411a99.png)

**Comment by KirannBhavaraju** [comment]
The initial PR was createrd a month ago. Thanks for the heads up. 👍  

# Preview
![image](https://user-images.githubusercontent.com/28805843/104032557-9c295780-51ce-11eb-80df-2297e65fe050.png)

**Comment by stap-m** [comment]
@KirannBhavaraju I think there were more changes beside the renaming to "API" on the front page, espcially new links behind the diverse buttons. Can you also pls check if they match the current version? Thanks. The rest looks pretty.

**Comment by KirannBhavaraju** [comment]
yes @stap-m you are right. the links from the previous homepage have changed recently, but all the new html does is reorganize these blocks `Databases`, `Factsheets`, `Ontology`, `Tutorials`, and Removes the `Documentation` block. Everything else is the same with what is currently on develop. : ) So the links are the same.

**Comment by han-f** [comment]
I think the front page looks way better now. I overlooked in the previous screenshots  that it suddenly read "Databases" instead of "Database".

Could we fix this in a next release, or is "Databases" more precise @MGlauer ?
