### ISSUE TITLE
Tags: "Back to database link leads" to wrong page

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#668]
When I click the above mentioned link in /dataedit/tags/ I am not transported back to where I was before but to dataedit -> the page that should cease to exist anyway, see #664

**Comment by christian-rli** [comment]
Does this issue persist @han-f ? I cannot reproduce this. I am transported back to the schemas page. Either the page was still in your browser cache, or you tried this before the latest release.

**Comment by han-f** [comment]
No - it does not persist any longer - yay!
