### ISSUE TITLE
Search: seems to not include metadata

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#669]
To test the adjusted search:
I added some information to the metadata to this table on toep: http://toep.iks.cs.ovgu.de/dataedit/view/model_draft/szenarien_db_mmr

I added: 
Öko-Institut  under Description and 
Monitoring Mechanism Regulation under Title

Going back to schemas and entering those in the search bar and clicking "Apply Filters" leads to empty search results. 
This seems to me like metadata is not yet included in the search?

**Comment by MGlauer** [comment]
Ah, it does. But new metadata is not added to the search index, yet. I am working on it.

**Comment by han-f** [comment]
Has it been added in the current toep? I wanted to test adding new metadata and then searching for it, but received the "Forbidden" pop-up message (#677)

**Comment by MGlauer** [comment]
This seems like a bug with the metadata editor. Maybe @wingechr can help.

**Comment by wingechr** [comment]
@han-f it looks like you do not have permissions to set metadata via api. send me a private message what user you are using

**Comment by jh-RLI** [comment]
The metasearch is updated when metadata is api.posted to a table. I am closing this issue for now. Please open it if you find that updated metadata is still not included in search results.

**Comment by wingechr** [comment]
just as a note for later: I think after the implementation of the metadata jsonb field and once the metadata standard is stable, we should do a review of all the existing metadata and update them all as best as possible to the latest standard. 

By re-writing all the metadata, all the search fields and tags would be automatically updated as well
