### ISSUE TITLE
Delete views that do not make sense

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#670]
There are some views which do not make sense and whose titles are not helpful.
Can these be deleted?

E.g. for this table: https://openenergy-platform.org/dataedit/view/economy/destatis_gva_per_district 
There may be more scattered across tables.

**Comment by christian-rli** [comment]
I am wondering more generally if there are any views that were created and meant to be shared with others. I think this might be a usecase, but until the average user understands from the interface that this is an option plus when exactly a view is visible to others, the option should be removed. That's the quick solution. Afterwards we can think about how to enable and communicate a view sharing option.

**Comment by han-f** [comment]
I like your suggestion @christian-rli

**Comment by wingechr** [comment]
Maybe the feature to create views should be disabled until a decision can be made how they should be used. 

It only adds to the complexity of the platform and I am not sure is that useful.

**Comment by wingechr** [comment]
I am closing this issue. it's old and there was no consensus on the issue if the feature should be removed or not.

re-open if needed
