### ISSUE TITLE
toep: Upload Wizard placement doesn't look right

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#676]
See screenshot below. This is on Firefox and large Desktop monitor. 
When scaling the window smaller and all moves below the schema table the placement of the elements for the wizard remain the same, i.e. wizard icon next to the button and text off.

![grafik](https://user-images.githubusercontent.com/36844029/98637966-7d6f2780-2329-11eb-948e-a2c38031cf97.png)

**Comment by christian-rli** [comment]
This view was updated and the issue solved. Although I am missing the pretty hat :´)
