### ISSUE TITLE
toep: editing metadata pressing 'submit' throws error

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#677]
when editing metadata (worked before), clicking the submit button throws a pop-up message which states 'forbidden'.

Suggested improvement: the submit button may also be placed at the top. Now there is only one at the button and the form is really long.

**Comment by MGlauer** [comment]
@wingechr: I checked the permissions, and they do not seem to be an issue. Maybe the way the queries are sent is an issue. Do they pass the right credentials to the API?

**Comment by MGlauer** [comment]
PS: If `oeko_testtable` was used in this case.
