### ISSUE TITLE
toep: cannot edit / delete study

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#679]
http://toep.iks.cs.ovgu.de/factsheets/studies/1/edit/
Same happens on the live OEP. It would be good to be able to edit/delete scenarios and studies. 
This may involve adding a 'delete' button somewhere. Not sure whether this exists already.

**Comment by Ludee** [comment]
This is quite important since the Scenario Factsheets are essential for SzenarienDB. Is this already fixed for the next release?

**Comment by christian-rli** [comment]
duplicate of #595
