### ISSUE TITLE
OEP: delete test factsheets

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#680]
There are several scenario factsheets that are obviously only there for testing purposes. They should be deleted. At the moment users cannot do this, since an error happens when trying to edit the study/scenario. No delete button can be found.
See also #679  and #595

https://openenergy-platform.org/factsheets/scenarios/

**Comment by Ludee** [comment]
I managed to edit the factsheets and reuse the _tests_.
Since there are several issues regarding the editing I will close this issue.

**Comment by KirannBhavaraju** [comment]
We can have a PR by the start of next week for a "Delete Factsheet" button in the Scenario factsheets, alongside, "Edit Scenario" and "Edit Study". The functionality wasnt supported by the api itself, but i have added it already. Yes, the EditStudy has many issues though. @Ludee @meisam-booshehri @MGlauer

**Comment by meisam-booshehri** [comment]
@MGlauer I believe you took over deleting the test factsheets in our meeting on Wednesday. Am I right or mistaken?
