### ISSUE TITLE
toep: Clicking a tag in schema table still leads to 'edit tags'

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#681]
Clicking a tag in the list with tables in a schema still leads to 'edit tags' rather than to displaying only those tables that have the tag attached. 

see e.g.: http://toep.iks.cs.ovgu.de/dataedit/view/model_draft 
see also #639  - which seems to have been addressed and closed already

**Comment by jh-RLI** [comment]
That's right, as I [mentioned in the PR,](https://github.com/OpenEnergyPlatform/oeplatform/pull/600#issuecomment-719773975) this is not fixed yet. I will create a new PR and link it here.

**Comment by han-f** [comment]
Clicking a tag in the newest release reduces the schema view to the tables that include the tag, but when clicking the table name to open the corresponding schema no tables are shown at all.

Also - when in a schema and selecting a tag, nothing is shown even if there are plenty tables with this tag 
See example below for scenario schema. There are actually 10 tables tagged KS95.

This was working in the previous release. 

![grafik](https://user-images.githubusercontent.com/36844029/104721044-93d09f80-572d-11eb-9b29-0bdbd138edf9.png)

**Comment by han-f** [comment]
Not sure whether this is the correct issue though.

**Comment by MGlauer** [comment]
It seems this happens if and only if the search bar is empty. This messes with the url parser.

**Comment by han-f** [comment]
With me it happens also with searchbar filled:
![grafik](https://user-images.githubusercontent.com/36844029/104724457-fe370f00-5730-11eb-8008-dd3bd25c52b9.png)

**Comment by han-f** [comment]
This F5 functionality confuses me. I clicked F5 many times before, now it seems to work again.  Is there a general rule how many times one needs to hit F5 before things show up as they should?
