### ISSUE TITLE
Search/Filter function not intuitive

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/oeplatform#693]
The  filter page is not intuitive:
1.) Apply and Reset filters 
    a) are to far at the bottom -> need to be at the top
    b) look very much like the tags themselves. Need to have a different color/form.
2.) Find data resources need to be at the very top, above the filter funcion.

![grafik](https://user-images.githubusercontent.com/42575569/100329326-cda6e480-2fcd-11eb-99db-d2a2c78a46ec.png)

**Comment by han-f** [comment]
Some changes are now visible. Many thanks. The only thing that seems left is that the buttons still look similar to the tags below them.

**Comment by jh-RLI** [comment]
This was reworked in the latest release v0.10.1.
