### ISSUE TITLE
[Factsheets] Bug when editing a framework factsheet

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#697]
#### What is the Issue about?
A user edits a framework factsheet and unchecks a checkbox, for example. Then the input is confirmed with "submit all". Up to this point everything runs as expected. If now the same framework factsheet is edited again because another value is to be changed, then a cached page is provided by the browser. The problem is, that the values of the state before the first editing are displayed. If you empty your browser cache and reload the page the updated values are displayed.  

#### Solution:
- Quick fix: use Strg+F5 to reload the page.
- Long term fix: Caching should be disabled for the factsheets pages.

**Comment by Ludee** [comment]
The same is observed on the model and scenario factsheet.
While this is a minor bug it has a huge impact on the usability.

Is the proposed solution to disable caching a valid solution? 
How can this be implemented in Django?

**Comment by jh-RLI** [comment]
@johannwagner can you advise on the best way to tackle the issue? Is my suggested solution for such problems (disable cacheing) applicable? Or do you see another reason for the problem. If you don't know how something like this happens either, I'll do some research.

**Comment by maurerle** [comment]
This is a quite annoying bug - as showing an outdated view gives the user the impression that the update did not work.
F5 works good, but is a quite technical workaround.

One can tell the browser that a document should be updated, by serving a different ETag of the file:
https://docs.djangoproject.com/en/4.2/topics/conditional-view-processing/#the-condition-decorator

Maybe this helpes to reduce the caching issues?

**Comment by jh-RLI** [comment]
Thanks for this tip did not know about the ETag. I will try it out and implement, as long as not too many follow-up problems occur :)

**Comment by jh-RLI** [comment]
Well i decided to use the [never_cache](https://docs.djangoproject.com/en/3.2/topics/http/decorators/#django.views.decorators.cache.never_cache) decorator as it seems to be more predictable. We will install the fix on our test-oep instance soon and check if it solves the issue.
