### ISSUE TITLE
[Factsheets] smoother editing of fact sheets

### ISSUE THREAD

**Issue by tillmo** [OpenEnergyPlatform/oeplatform#70]
Implement a smoother editing of fact sheets. When I am in a tab of a fact sheet, there should be an edit button. When pressing the edit button, the editor should open incrementally, that is, only my current tab is changed by turning all fields into editable fields. After pressing "submit", the updated tab should be displayed incrementally, that is, the rest of the page still stays as it is.
See e.g. https://github.com/django-inplaceedit/django-inplaceedit

**Comment by tillmo** [comment]
see also #27

**Comment by stap-m** [comment]
This is outdated.
