### ISSUE TITLE
change nameing of metadata file when downloading data

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/oeplatform#704]
When a data set is downloaded from the OEP, the metadata file is named "datapackage.json". This is contraintuitive.
It should be called smth like "_tablename_ _metadata.json"

**Comment by wingechr** [comment]
This is not a bug. 

The zip file is following the datapackage specifications (https://specs.frictionlessdata.io/data-package/), and the metadata must be named "datapackage.json"
