### ISSUE TITLE
merge breaks JSON Download

### ISSUE THREAD

**Issue by wingechr** [OpenEnergyPlatform/oeplatform#709]
* merge 72c5c98eba076e2b4822bc82ab43a568b9f34434 breaks the "Download JSON" button in the data view, resulting in javascritp error `Uncaught ReferenceError: downloadMetadata is not defined`, because this function was removed from the code.

* The Upload section also has vanished

# Reason
Those lines are deleted in the merge 72c5c98eba076e2b4822bc82ab43a568b9f34434  in file dataedit/templates/dataedit/dataview.html

**Comment by MGlauer** [comment]
Weird... I am pretty sure I tested both download buttons before merging... I will look into it.

**Comment by MGlauer** [comment]
Ok, The functionalities should be back now. @wingechr could you test it, please?

**Comment by wingechr** [comment]
yep, seems fine again, thanks! 👍
