### ISSUE TITLE
Datapackage download link has disappeared 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#711]
Previously we were able to download the csv of a table and a data package.
Now the possibility to download the data package has disappeared. We would like to demonstrate this functionality on January 20th, so it would be very good to get it back. 

Not sure who is the best to assign - please adjust accordingly.

**Comment by jh-RLI** [comment]
It seems that the "permissions" button has been confused with the "download datapackage" button. In the linked PR I have fixed this again.

**Comment by han-f** [comment]
@jh-RLI: many thanks, this is good news!
