### ISSUE TITLE
"no description found" under heading oeo 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#713]
On: https://openenergy-platform.org/ontology/oeo/ 
under the first heading called "oeo" it states "no description found".

We should add a description or remove the text.

**Comment by han-f** [comment]
In todays meeting it seems all were ok with this not being of priority for the 20th.

**Comment by christian-rli** [comment]
There is a description now. The modules still lack descriptions, but are called for in another issue already (#671 ).
