### ISSUE TITLE
Hide box which interacts with table

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#715]
Please hide this box behind some dropdown and add a short text above that introduces what users can do with the box.

![grafik](https://user-images.githubusercontent.com/36844029/103748400-5751c500-5004-11eb-9c3d-24999f18fde1.png)

Text suggestion: 
You can use this box below to interact with the data table

@stap-m @klarareder : Do you think this short text suffices?

**Comment by stap-m** [comment]
What about: "Here you can group data or add rules for your view." ?

**Comment by han-f** [comment]
Thanks @stap-m , this reads better than my suggestion I think.

**Comment by klarareder** [comment]
Sounds good!

**Comment by KirannBhavaraju** [comment]
Cool. but, I have a 2 questions @han-f . 
1. Should we hide this entire box behind a dropdown? I assume user interaction with the text opens this dialogue somehow: Am i mistaken?
![image](https://user-images.githubusercontent.com/28805843/104033660-1c03f180-51d0-11eb-9b35-05ebd9aaaa18.png)
2. Everytime the user exits the "dropdown thingie" the entire selection has to be made again, wouldnt that make the user experience a little cumbersome?

**Comment by MGlauer** [comment]
This has already been 366019a89

**Comment by han-f** [comment]
Thanks @MGlauer - and apologies for not having the right terms e.g. "collapsible" at hand.

**Comment by christian-rli** [comment]
Has been implemented, as mentioned above.
