### ISSUE TITLE
Model factsheet - Minor Bugs

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#717]
I am testing and updating the factsheets and I found some minor bugs and problems in the model fact sheet that needs to be fixed:

- **Software** | External optimizer

When checkbox is _yes_ a text field is displayed. The text is not displayed in the factsheet after submission.
Bug is in _add=model.external_optimizer_yes_text_?
-> Allow multiple entries in form

- **Basic Information** | Link to User Documentation

The URL is broken with an internal URL and {}.
see: https://openenergy-platform.org/factsheets/models/32/
Bug in _code_documentation_ or url check function in _model_snipped.html_ ?

- **Basic Information** vs **General Information**

It's _basic_ in the factsheet but _general_ in the edit.
Please change to **General Information**

- Order of cards

Factsheet: ~~Basic~~ General; Openness; Software; **References**; Coverage; Math; Integration
Edit: General Information; Openness; Software; Coverage; Math; Integration; **References**; Tags

Please harmonise to:
General Information; Openness; Software; Coverage; Math; Integration; References; Tags
-> Move references in models.html to the end

- Expand first card General Information when factsheet is opened

- Cards in edit mode

There are no gaps/ spaces between the cards in edit mode.
Please add spaces to improve readability.

**Comment by jh-RLI** [comment]
Added padding and border to the section headings:
![image](https://user-images.githubusercontent.com/38939526/103946879-8452c480-5137-11eb-8d98-be22d43da9df.png)

Do you think the frame is good or should I just add spacing in between (padding)?

**Comment by jh-RLI** [comment]
See the PR above^

**Comment by jh-RLI** [comment]
Fixed all except the Software | External optimizer and Basic Information | Link to User Documentation. Will work on it in the next few days.

**Comment by han-f** [comment]
Just came across this and think padding would be nice. Also the border seems black which quite jumps at you - have it more in the dark blue theme instead?

**Comment by jh-RLI** [comment]
I have removed the border again, because this does not look good on the different screen sizes (responsive). But I have added a little more padding so that the distance between the words is larger.

**Comment by jh-RLI** [comment]
I have noticed that some fields are not displayed in the framework factsheets view. The fields are only visible when you are in edit mode. I have added the fields again. 

Fields added to openness:
- user_documentation
- installation_guide
- link_to_code_documentation
- skills_basic
- skills_advanced

**Comment by jh-RLI** [comment]
Fixed the issue in "Software | External optimizer" and "Basic Information | Link to User Documentation". This issue is solved with the next release.
