### ISSUE TITLE
Tag colours do not match

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#719]
As already documented, the tag colours have a bug. Not all tags are displayed #692

In addition, in the schema view the colours are changing!

![grafik](https://user-images.githubusercontent.com/14353512/103893985-7fb5ee00-50ee-11eb-86da-aba5fd1057b3.png)

![grafik](https://user-images.githubusercontent.com/14353512/103894049-9fe5ad00-50ee-11eb-8f1e-0c66d24a3c3c.png)

Since the colours are used to show "categories" this needs to be fixed #390

**Comment by han-f** [comment]
I can confirm this, see for example https://openenergy-platform.org/dataedit/view/scenario?query=&tags=185 
And: In schema view, most of the times only a certain number of tags is showing (in our case mostly 8), but on occasions it is more than that.

![grafik](https://user-images.githubusercontent.com/36844029/104000126-142b5980-519e-11eb-9aea-b4c049041132.png)

**Comment by han-f** [comment]
#691

**Comment by han-f** [comment]
I found a weird behaviour with the tags (maybe this should become a new issue):
When I use the search via tags functionality (example given: _SzenarienDB_) - the schemas view is reduced correctly and when I click the schema I want to visit the tables with the tag are shown (e.g. schema climate) BUT it seems the search only shows those tables in the schema that have this tag also displayed in the overview table. When a table has the tag, but the tag is not shown in the individual schema view, the table is not returned as a search result. See screenshots below. 

Correct result in schema climate: 
![grafik](https://user-images.githubusercontent.com/36844029/104007668-9a4c9d80-51a8-11eb-8544-c91b69f183d0.png)
In schema scenario only one result, while there are many more tables with the ag:
![grafik](https://user-images.githubusercontent.com/36844029/104007774-be0fe380-51a8-11eb-9fed-a7c8cb13c6c3.png)
Example table with tag _SzenarienDB_ in schema scenario:
![grafik](https://user-images.githubusercontent.com/36844029/104007851-e0a1fc80-51a8-11eb-9a29-1bff2d065905.png)

**Comment by Ludee** [comment]
Will be fixed with #876
