### ISSUE TITLE
Use new Open Energy Family and OEP logos

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/oeplatform#722]
The new OEF logo shoulde included into the "is about" page and the new OEP logo (No 5) should be used in the header.

**Comment by Ludee** [comment]
I'm sorting and licensing the logos right now. 
I will push them to the oeplatform repo and link it in the organisation repo https://github.com/OpenEnergyPlatform/organisation/issues/37.
Then we can use them!

**Comment by Ludee** [comment]
Since all logos in SVG and PNG are big (10 MB) I will not push them to the oeplatform but add them to the [organisation repo](https://github.com/OpenEnergyPlatform/organisation).
We decided to grant a CC0 license to all icons to allow unlimited use and adaption.

**Comment by Ludee** [comment]
I also updated the icons on the welcome page.

**Comment by Ludee** [comment]
The tutorial icon is missing. I will create a branch and PR.

**Comment by jh-RLI** [comment]
@Ludee to me it looks like this can be closed?
