### ISSUE TITLE
SSL verification error / max retries

### ISSUE THREAD

**Issue by tbanze** [OpenEnergyPlatform/oeplatform#729]
@MGlauer 
Since a pair of days I get failures when requesting any data via API (Python). The following errors appears during a request: 

**SSLCertVerificationError:** [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

**MaxRetryError:** HTTPSConnectionPool(host='openenergy-platform.org', port=443): Max retries exceeded with url: /api/v0/schema/boundaries/tables/ffe_osm_nuts3/rows/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

**SSLError:** HTTPSConnectionPool(host='openenergy-platform.org', port=443): Max retries exceeded with url: /api/v0/schema/boundaries/tables/ffe_osm_nuts3/rows/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

**Comment by tbanze** [comment]
**Update:** Today (after ca. three days) the problems are gone and it works fine.

**Comment by MGlauer** [comment]
It seems to work again, now. As far as I can tell this was not a failure of the OEP, but of a server within the certification chain. This is something I actually never heard of happening - and am positive optimistic that it will not happen again.

Sorry for any inconvenience that was caused by this issue.

**Comment by tbanze** [comment]
Okay great. Thanks for your fast support.
