### ISSUE TITLE
There is no "back to tutorials" button

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#736]
When I am viewing a specific tutorial there is no "back to tutorials" button or similar. I think this would be helpful to have.

**Comment by jh-RLI** [comment]
That is not quite right. I introduced such buttons with the last release. The implementation is just not quite flawless yet. So far, the buttons only appear when you are logged in and only for tutorials that are created via the editor. In addition, the button is not very visible. I will improve this in the near future.

![image](https://user-images.githubusercontent.com/38939526/110256726-b4cda800-7f9a-11eb-8791-7add1d65f3ca.png)
