### ISSUE TITLE
[Factsheets] make links in fact sheets clickable

### ISSUE THREAD

**Issue by tillmo** [OpenEnergyPlatform/oeplatform#74]

**Comment by EdithaK** [comment]
@MGlauer: Still a ToDo. Do you have a student for this?

**Comment by MGlauer** [comment]
No, but we should include this for our next release.

**Comment by EdithaK** [comment]
@pkassing this have to be done by hand. Please go to every given fact sheet and make it a link.
@MGlauer how does it work? with html command? 
<link href="style.css" rel="stylesheet"> ?

**Comment by EdithaK** [comment]
"<link href="style.css" rel="stylesheet">"

**Comment by EdithaK** [comment]
link href="style.css" rel="stylesheet"
