### ISSUE TITLE
Contact form failing

### ISSUE THREAD

**Issue by SachaHq** [OpenEnergyPlatform/oeplatform#742]
Dear OEP developers,

I had a question regarding factsheets and when trying to send the contact form, I got the error message :

*Sorry, something went wrong!*

*It looks as though we have unexpectedly broken something on our system, while processing your request.
An e-mail has already been sent to the admin, thus the admin will be informed about this incident. The admin will fix this problem as soon as possible.*

*In the meantime, you are welcome to ask further questions here: contact form.*
*Thanks a lot for your feedback!*

Yet I have filled in all the fields and done the captcha. Do you have any idea of what happened ?

Thank you,

Sacha

**Comment by MGlauer** [comment]
Looks like this is a bug in the mail backend and apparently not related to the OEP itself. I will check whether the mail server is functioning.

**Comment by SachaHq** [comment]
Dear OEP developers,

After retrying today, it now seems to work properly.

Kind regards,

Sacha

**Comment by jh-RLI** [comment]
I assume this is fixed? @MGlauer

**Comment by MGlauer** [comment]
Yes, should be fixed
