### ISSUE TITLE
Explanatory text under 'Schemas' is missing

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#746]
I received feedback from a potential user of the OEP that it would be helpful to have a short text under 'Schemas' for explanation as otherwise this title is not self-explanatory for "Quantitists" and "Qualitists".  
![grafik](https://user-images.githubusercontent.com/36844029/117811058-6c638c80-b260-11eb-9d00-c50e91bd8f9e.png)

Suggestion: _Schemas organise the available data according to specific topics. The topics are shown and described in the table below._

**Comment by jh-RLI** [comment]
I would vote to leave out "Schemas" and use something like "Data Catalog", but adding a description as you suggested is definitely good to have.

**Comment by han-f** [comment]
> I would vote to leave out "Schemas" and use something like "Data Catalog", but adding a description as you suggested is definitely good to have.

Yes that would even be better, I somehow thought the heading was fix :-)

**Comment by han-f** [comment]
New suggestion:
Heading: _Data Catalogue_
Explanation: _Data on the Open Energy Platform are organised according to specific topics. The topics are shown and described in the table below._

**Comment by jh-RLI** [comment]
Schemas got renamed to topics that could be self-explanatory? If not, open a new one.
