### ISSUE TITLE
[Factsheets] MF/FF: Contact

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#75]
Contact-Mail:
Please, do not force people to fill in a mail address, but allow links to contact web forms, mailing lists, GitHub etc..

**Comment by EvaWie** [comment]
Suggestion:
Make separated fields for family name, first name, institution, contact e.g. email

Consider also to make these fields for all (other) authors (without asking for the email address).

**Comment by ludee** [comment]
Author(s) (institution, working field, active time period)
see: http://193.175.187.164/factsheets/frameworks/5/
There are 9 authors and only one contact (person). No "working field" and no "active time period".
All in seperate fields:
Author(s) (first name, name, contact, institution, working field, active time period)

**Comment by EvaWie** [comment]
"working field" and no "active time period" are not mandatory.
We should keep the limitation to contact (person).

**Comment by stap-m** [comment]
This is also outdated, I guess
