### ISSUE TITLE
add title as headline for study factsheets

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/oeplatform#751]
At the study factsheet [overview page](https://openenergy-platform.org/factsheets/rdf/study/) I can see a list with study name to click on.
When entering a study factsheet page, the headline is "Factsheet:" but the name of the study is shown nowhere.
E.g. [here](https://openenergy-platform.org/factsheets/rdf/study/TrafoFW_study/)

ToDo: include study name into the headline of the study factsheet page

**Comment by jh-RLI** [comment]
Good Catch! I will fix this soon.

**Comment by jh-RLI** [comment]
This will take a bit more time than expected as I have to improve my dev setup to test this properly.

**Comment by Anne-Oeko** [comment]
Additionally it would be good to better sort the factsheets. Alphabetically, according to date or other issues, but the current listing seems a bit arbitrary, e.g. https://openenergy-platform.org/factsheets/scenarios/

**Comment by stap-m** [comment]
I close now, it seems to be fixed. For the comment of @Anne-Oeko I created a separate issue #1295
