### ISSUE TITLE
Update API documentation on readthedocs?

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#753]
The documentation on readthedocs does not provide an indication on whether it is up to date and when it was last updated, the copyright states 2016 which may lead users to think it is outdated.
![grafik](https://user-images.githubusercontent.com/36844029/119968462-c88f1600-bfad-11eb-9291-e12b85d41012.png) 

Thus I think it would be useful to add such an indicator as the main OEP page links prominently and directly to the API documentation on readthedocs: https://oep-data-interface.readthedocs.io/en/latest/api/how_to.html

As a follow-up I wonder: 
* Does this API documentation - and possibly also the rest on readthedocs -  need an update? How does its API part relate to the API tutorials? Do we replicate content and effort? 

cc: @stap-m @wingechr

**Comment by wingechr** [comment]
I think the readthedocs should be removed

* It's incosistent with the tutorials on the platform / github
* It's out of date

**Comment by han-f** [comment]
> I think the readthedocs should be removed

    It's incosistent with the tutorials on the platform / github
    It's out of date
I would be in favor of this, but how can we best make that decision - discuss it at a general jour-fixe @stap-m ?

**Comment by christian-rli** [comment]
MG: This is meant as a developer documentation and very much out of date. 
This needs to be discussed in a developer meeting.

**Comment by han-f** [comment]
Another helpful remark came:
if we keep some part of readthedocs: there is no license information available right now - add suitable open license information

cc @l-emele @stap-m

**Comment by wingechr** [comment]
As discussed in the last meeting:

* I am going to move tutorial like parts abuot the advanced API into a github tutorial 
* we remove link from the platform website
* we keep the page, but only for actual development docs

**Comment by christian-rli** [comment]
Also see #303

**Comment by jh-RLI** [comment]
There was a newish decision in the developer meeting. We want to keep the developer documentation as it also includes some tests, and still helpful source of information.
I created a new Project ["oeplatform"](https://oeplatform.readthedocs.io/en/latest/?badge=latest) on ReadTheDocs to be able to build the documentation. But we would have to restructure it and then provide at least some headlines that can be filled with content over time and is required to be updated for all new developments.

**Comment by jh-RLI** [comment]
@han-f I can update the year and the project name (or just rename it to oeplatform) in the footer (see your screenshot above).

**Comment by jh-RLI** [comment]
Continues in #1206
