### ISSUE TITLE
Displaying Jupyter Notebook Subsection Links

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#755]
Have a look at this tutorial: https://openenergy-platform.org/tutorials/jupyter/tutorial_open-data-licenses/ 

Having all those ¶ symbols doesn't look nice. As @stap-m has pointed out in OpenEnergyPlatform/tutorial#140 they should be replaced, ideally with this symbol 🔗.

**Comment by johannwagner** [comment]
This is fixed in since v0.9.3, I guess. It is not deployed on `openenergy-platform.org` but will be in the near future.
