### ISSUE TITLE
Better structure Tutorials page

### ISSUE THREAD

**Issue by Anne-Oeko** [OpenEnergyPlatform/oeplatform#762]
I think it is really hard to get an overview about tutorials here: https://openenergy-platform.org/tutorials/. It would be much better to cluster the tutorials, e.g. according to user group or topic and add short descriptions on each tutorial.

**Comment by han-f** [comment]
I agree and I think this is related to #462 and #738

**Comment by jh-RLI** [comment]
The issue describes an idea that I wanted to discuss anyway.  Unfortunately, my time has been very limited in recent months.
I think we should implement this and group the tutorials further into categories or levels (according to new tutorial [metadata](https://github.com/OpenEnergyPlatform/tutorial/issues/135#issuecomment-826691597). You would then first see an overview page with the grouping names (category or level). When you click on a category or level, you will see a reduced list of tutorials. We could also add a new field to the tutorial metadata called "description" but I think the title describes the content already.

@johannwagner Maybe we should include this in the next iteration for the tutorials app development or do you think this fits well in https://github.com/OpenEnergyPlatform/oeplatform/pull/738

**Comment by johannwagner** [comment]
@jh-RLI I think, we want to do this in two steps. The PR is quite big and should be merged soon.

**Comment by han-f** [comment]
> We could also add a new field to the tutorial metadata called "description" but I think the title describes the content already.

From a user perspective I like the idea to have a small excerpt that lets you get a feel for what is inside the tutorial. So I would be in favor of having a description field with a (very) short summary of what can be expected.  
I think this is helpful for all users that are not your traditional "APInists", and for those such a short summary won't hurt either I assume, since you can also simply ignore it.

**Comment by Anne-Oeko** [comment]
Dear all - I agree that descriptions would be very helpful for many people and for those who don't need them, they won't harm. I would not know where to start when accessing the tutorials' page at the moment and I think the idea is to spread the OEP further.

**Comment by wingechr** [comment]
I am closing this because of the complete overhaul of the tutorial page
