### ISSUE TITLE
[Framework (Factsheets,  Model, Scenario)] Various bugs in Factsheet app 

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#764]
There are several bugs regarding the OEP Factsheets. The code can be found in the (django)"modelview" app. I added an Excel file to this issue where you can find more detailed information. Unfortunately, it's written in German (get back to me if this is a problem).  The Excel does not cover all existing factsheets but reviews some of them. It also just covers bugs within the Framework Factsheet. But we might need to fix similar bugs in the other Factsheet types (Scenario, Model).
-> My hope is that this is enough to fix most of the bugs.
[21-06-08_OEP_Review.xlsx](https://github.com/OpenEnergyPlatform/oeplatform/files/6677786/21-06-08_OEP_Review.xlsx)

The majority of bugs relate to input or output fields in the factsheet creation form or factsheet detail-view. In many cases, inputs are not visible when viewing a factsheet and sometimes there are outputs that cannot be edited. It would be good if all inputs have an output and all outputs can be edited. Another bug related to URL fields, if one edit an URL field the URL gets wrapped in [] and is not clickable anymore. We can discuss this further in the comments.

There are several other bugs already documented in multiple Issue (most of them contain "Factsheet" in the title) in this repo. . I would like to start fixing them all. This issue is a good starting point for this.

**Comment by jh-RLI** [comment]
@Adel-Memariani This is the issue we talked about in the oep-dev meeting.

**Comment by johannwagner** [comment]
I already fixed some "old" bugs in this PR: https://github.com/OpenEnergyPlatform/oeplatform/pull/767

They also have tickets in this repository, you may want to skip those in the sheet.

**Comment by jh-RLI** [comment]
@Adel-Mem could you give me an update on the current status of this issue? Is there any progress or a pull request?

**Comment by jh-RLI** [comment]
There is also this major bug when editing factsheets: https://github.com/OpenEnergyPlatform/oeplatform/issues/697
Any help is appreciated :)

**Comment by jh-RLI** [comment]
@adelmemariani are there any updates on this issue? Would appreciate your feedback, as this problem should have been solved by now.

**Comment by adelmemariani** [comment]
I am working on the issues. macOS configuration took some time :)

**Comment by jh-RLI** [comment]
Sounds good, thanks for the feedback :)

**Comment by jh-RLI** [comment]
Outdated
