### ISSUE TITLE
[Factsheets] Decission on "framework" - FS - integration 

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#77]
Fact Sheet overview page ... with all Fact Sheets of all kind.

**Comment by EvaWie** [comment]
Add the Acronyms of the models / frameworks / Scenarios to the lists, please.

**Comment by EdithaK** [comment]
@beritRLI We have only one framework-FS (oemof). We should either integrate the wrongly sorted frameworks from "models" to "frameworks" OR delete the category "framework".
On my opinion the framework-section is confusing for the most users. It hinders them to fill out the sheet!

If we do non of the explained options we should integrate a Fact Sheet overview page.

Can we make a decission on this?
