### ISSUE TITLE
Ontology page: Better navigation for potential contributers

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#774]
I think we can improve guiding new users to how they can access and contribute to the OEO.

Currently the text under _Where and how can I contribute?_ reads:
_The OEO development was initiated in the project “SzenarienDB” and is augmented in the project “LOD_GEOSS”. The development is community based and takes place on GitHub.
A OEO steering committee was created in autumn 2019._

I think this includes information that does not really fit the heading. 
Suggested change:

**_Where and how can I contribute?_**
_Anyone is invited to contribute to OEO development as this is a community-driven process. 
OEO development takes place on [GitHub](https://github.com/OpenEnergyPlatform/ontology). 
We have some [helpful guidelines](https://github.com/OpenEnergyPlatform/ontology/blob/dev/CONTRIBUTING.md) on the workflow. 
If you have questions, please reach out via the OEP [contact form](https://openenergy-platform.org/contact/). We can then facilitate someone who can follow up on your question._ 

**_Further information_**
_OEO development was initiated in the project “[SzenarienDB](https://www.enargus.de/pub/bscw.cgi/?op=enargus.eps2&q=%2201180818/1%22)” and is currently continued in the projects “[LOD_GEOSS](https://www.enargus.de/pub/bscw.cgi/?op=enargus.eps2&q=%2201186899/1%22)” and "[SIROP](https://www.enargus.de/pub/bscw.cgi/?op=enargus.eps2&q=%2201227101/1%22)". 
[The OEO steering committee](https://openenergy-platform.org/ontology/oeo-steering-committee/) was created in autumn 2019._

Note: may be helpful to combine work on this with working on #750

cc @Anne-Oeko, @l-emele, @stap-m

**Comment by l-emele** [comment]
Suggestion, mention also the wiki: _We have some [helpful guidelines](https://github.com/OpenEnergyPlatform/ontology/blob/dev/CONTRIBUTING.md) on the workflow and a [wiki](https://github.com/OpenEnergyPlatform/ontology/wiki) providing detailed information._

**Comment by han-f** [comment]
Add-on suggestion: also link directly to the how to participate entry in the wiki: 
_We have some [helpful guidelines ](https://github.com/OpenEnergyPlatform/ontology/blob/dev/CONTRIBUTING.md) on the workflow and a [wiki ](https://github.com/OpenEnergyPlatform/ontology/wiki) providing detailed information.
That said: [Welcome! We invite you to participate ](https://github.com/OpenEnergyPlatform/ontology/wiki/Welcome!-How-to-participate)_

**Comment by han-f** [comment]
Based on all that was discussed, I think the current, complete suggestion would be as follows:


**_Where and how can I contribute?_**
_Anyone is invited to contribute to OEO development as this is a community-driven process. 
OEO development takes place on [GitHub](https://github.com/OpenEnergyPlatform/ontology). 
_We have some [helpful guidelines ](https://github.com/OpenEnergyPlatform/ontology/blob/dev/CONTRIBUTING.md) on the workflow and a [wiki ](https://github.com/OpenEnergyPlatform/ontology/wiki) providing detailed information.
That said: [Welcome! We invite you to participate ](https://github.com/OpenEnergyPlatform/ontology/wiki/Welcome!-How-to-participate)._
If you have questions, please reach out via the OEP [contact form](https://openenergy-platform.org/contact/). We can then facilitate someone who can follow up on your question._ 


**_Further information_**
_OEO development was initiated in the project “[SzenarienDB](https://www.enargus.de/pub/bscw.cgi/?op=enargus.eps2&q=%2201180818/1%22)” and is currently continued in the projects “[LOD_GEOSS](https://www.enargus.de/pub/bscw.cgi/?op=enargus.eps2&q=%2201186899/1%22)” and "[SIROP](https://www.enargus.de/pub/bscw.cgi/?op=enargus.eps2&q=%2201227101/1%22)". 
[The OEO steering committee](https://openenergy-platform.org/ontology/oeo-steering-committee/) was created in autumn 2019._

**Comment by stap-m** [comment]
The OEO is also described in a peer reviewed paper, published in Energy & AI, see: [https://doi.org/10.1016/j.egyai.2021.100074]()

**Comment by christian-rli** [comment]
closed with #795
