### ISSUE TITLE
Sections in tutorials can not be linked to

### ISSUE THREAD

**Issue by wingechr** [OpenEnergyPlatform/oeplatform#778]
## problem

* it would be really helpful for the tutorials to be able to link to anchors in the text
* but, related to #657:  we cannot/will not allow raw html in markdown for security reasons

## proposed solution

after the markdown -> html parser has finished, add code that creates automatic textanchors for all headers so that tehy can be linked to

@han-f, @Anne-Oeko

**Comment by johannwagner** [comment]
I actually fixed this in some of the tutorial rework branches. There is a permalink link next to each heading, that can be linked.

**Comment by wingechr** [comment]
That's great, I did not realize that, my bad.

**Comment by wingechr** [comment]
Sorry, i closed this too early.

The permalinks only work for the tutorials coming from github jupyter notebooks, not from the markdown tutorials.
Also, maybe fix #777 in the process

**Comment by han-f** [comment]
As we are progressing with WP3 it would be great to hear about how this is coming along?

**Comment by han-f** [comment]
Get in touch with @han-f
