### ISSUE TITLE
The factsheet overview text is out of date

### ISSUE THREAD

**Issue by sfluegel05** [OpenEnergyPlatform/oeplatform#784]
The last paragraph on the page https://openenergy-platform.org/factsheets/overview/ says:
> The release of Dec. 2017 will include functions to filter the Fact Sheets and to compare them regarding specified characteristics. In 2018 we will broaden the view of energy system models and provide the possibility to specify health, social and other aspects.

This should be updated.

**Comment by han-f** [comment]
This is a good idea. While doing so, maybe we can update the whole text on this page to read easier and guide users better. I can give the textual update a try and post it here, if someone can then implement on the OEP once we have a publishable version that would be great. 

cc @stap-m, @l-emele

**Comment by Ludee** [comment]
This has been fixed with #983
