### ISSUE TITLE
Put abbreviations used in the database into the glossary

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#80]
automated or manual workflow?

**Comment by EvaWie** [comment]
Is this the wrong place to post it?

**Comment by beritRLI** [comment]
I have no idea how that should work automated... We should check the wording in the database and add the missing words to the glossary manually => Martin, could you comment, if that's the way you see it, too?

**Comment by EdithaK** [comment]
@MGlauer There is no automated way, true?
If that is true:
@KilianZimmerer please copy and explain abbreviations used in the database into the glossary.
Find glossary here: [https://wiki.openmod-initiative.org/wiki/Category:Glossary](url)
If the glossary-FAQ leaves questiones, please ask Ludee and add the information to the glossary.

**Comment by christian-rli** [comment]
This task is no longer relevant. The OEO is preferred over the glossary. Help texts should be reworked when refactoring factsheets.
