### ISSUE TITLE
Update text on factsheet page (Overview)

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#801]
I suggest to update the text on the factsheet overview page to make it easier to understand and have a more neutral language (example to adjust: _to avoid repeated and long explications of the used tools as well as senseless printing_).

I can draft a new text for this. 
But before doing this it would be good to have answers to the following questions:

1. will the study factsheets (alpha) make the scenario factsheet element in the drop-down obsolete, or will both continue to exist?
2. If both continue to exist, how do they relate to each other, i.e. what do the scenario factsheets cover that is not included in the study factsheets (alpha)?
3. can we add, on each individual factsheet page, a very short description what these kind of factsheets are about? I think this would be helpful for users. If yes, I can draft texts for these short introductions too (would open separate tickets). 

cc @stap-m, @l-emele

**Comment by christian-rli** [comment]
Also solves #784

**Comment by jh-RLI** [comment]
I am also interested in how the framework, scenario and model factsheets will be proceeded with. I am not sure to what extent the study factsheets will replace the other factsheets? Should work continue to be invested there or will they be obsolete in the near future? @han-f @Ludee @adelmemariani @wingechr

**Comment by han-f** [comment]
From SIROP Jour Fixe 2022-05-18: I will start drafting a new overview text now based on our current status and share it here for review. 

@Ludee - when would you need this to be done to be included not in the upcoming but the release thereafter?

cc @stap-m, @l-emele

**Comment by han-f** [comment]
related also to #853

**Comment by han-f** [comment]
Here is a suggested updated text for the overview page. Also I support the suggestion from #853 to rename the link in the drop-down to: _About Factsheets_

Please note: when this text is put online, the current Study Factsheet alpha link in the drop-down should already have been removed. 

Text draft for overview page:

The Open Energy Platform hosts a series of factsheets – currently we offer [model factsheets](https://openenergy-platform.org/factsheets/models/), [framework factsheets](https://openenergy-platform.org/factsheets/frameworks/) and [scenario factsheets](https://openenergy-platform.org/factsheets/scenarios/) that help to learn more about the context of the data you can find in the [database](https://openenergy-platform.org/dataedit/schemas). 

For example, you may want to know more about the background of some of the data you found than the metadata attached directly to it can provide. Then factsheets are a helpful place to visit. 

Specifically, our current [scenario factsheets](https://openenergy-platform.org/factsheets/scenarios/) provide some dedicated information about specific scenarios for which [projection data](https://openenergy-platform.org/dataedit/view/scenario/) is available on the Open Energy Platform. Please note, however, that their format was developed some time ago and they will undergo substantial updates. 

In the future, these scenario factsheets will also be succeeded by study factsheets that will hold more functionality. 
These study factsheets will help you also learn more about scenario contexts but also to explore scenario bundles. Scenario bundles tie together various information about a scenario available on the Open Energy Platform. This includes information on the projection data available, the framework(s) and model(s) applied, and the study context. The study factsheets will make these relations explicitly visible, as they are currently already there but not explicitly visible. 

And not only that: the study factsheets will be based on the concepts available in the Open Energy Ontology. We cannot say for sure when they will be live, but we are working hard to make this happen. We thus suggest you come back and check from time to time whether they are available. In case they are – also this text will be updated.

cc @stap-m, @l-emele

**Comment by stap-m** [comment]
Reads good!

**Comment by l-emele** [comment]
Reads already good. Some suggestion for improvement, as from an outside view it is not clear whether _their format_ means the format of the scenario factsheets or the projection data.

Specifically, our current [scenario factsheets](https://openenergy-platform.org/factsheets/scenarios/) provide some dedicated information about specific scenarios for which [projection data](https://openenergy-platform.org/dataedit/view/scenario/) is available on the Open Energy Platform. Please note, however, that the~ir~ format **of the scenario factsheet* was developed some time ago and they will undergo substantial updates.

Further, if I remember correctly, we wanted to include a link to the alpha factsheets. Something like:
_A not yet fully functionally feature preview of the future study factsheets can be accesses [here](https://openenergy-platform.org/factsheets/rdf/study/)._

**Comment by han-f** [comment]
Thanks for the feedback @l-emele. I ilke your adjustment wrt to the format.

The updated text could thus read:

The Open Energy Platform hosts a series of factsheets – currently we offer [model factsheets](https://openenergy-platform.org/factsheets/models/), [framework factsheets](https://openenergy-platform.org/factsheets/frameworks/) and [scenario factsheets](https://openenergy-platform.org/factsheets/scenarios/) that help to learn more about the context of the data you can find in the [database](https://openenergy-platform.org/dataedit/schemas).

For example, you may want to know more about the background of some of the data you found than the metadata attached directly to it can provide. Then factsheets are a helpful place to visit.

Specifically, our current [scenario factsheets](https://openenergy-platform.org/factsheets/scenarios/) provide some dedicated information about specific scenarios for which [projection data](https://openenergy-platform.org/dataedit/view/scenario/) is available on the Open Energy Platform. Please note, however, that the format of the scenario factsheet  was developed some time ago and they will undergo substantial updates.

In the future, these scenario factsheets will also be succeeded by study factsheets that will hold more functionality.
These study factsheets will help you also learn more about scenario contexts but also to explore scenario bundles. Scenario bundles tie together various information about a scenario available on the Open Energy Platform. This includes information on the projection data available, the framework(s) and model(s) applied, and the study context. The study factsheets will make these relations explicitly visible, as they are currently already there but not explicitly visible.

And not only that: the study factsheets will be based on the concepts available in the Open Energy Ontology. We cannot say for sure when they will be live, but we are working hard to make this happen. We thus suggest you come back and check from time to time whether they are available. In case they are – also this text will be updated. A not yet fully functionally feature preview of the future study factsheets can be accesses [here](https://openenergy-platform.org/factsheets/rdf/study/).

**Comment by Ludee** [comment]
While grouping it in paragraphs I did some editing to the text.
Thanks for the great work @han-f 
This is a great improvement to the page!
