### ISSUE TITLE
Implement filter functionality for tutorials

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#805]
I recall that we talked (@christian-rli  and @johannwagner) about filtering the tutorial list according to preferences of users to only see a subset of tutorials (helpful when the list has grown further). I can't find or recall the issue that was made for it and was surprised the new release came live without this functionality. 
Thus, I would strongly suggest to add this feature in the next release. 
Here are the notes I found in the oeo-developer meeting pad (scroll to 2021-06-28): 

    filter nach kategorie, medium, level einbauen
    Dazu: jeweils in Pfeil nach unten in der blauen zeile neben category, medium und level
    Nach klicken des Pfeils geht ein Menü auf, aus dem man sich die Dinge auswählt, nach denen gefiltert werden soll
    Danach reduziert sich die Tabelle auf die Einträge, die der Auwahl im Filter entsprechen

Maybe this can be addressed together with part of #762:

> From a user perspective I like the idea to have a small excerpt that lets you get a feel for what is inside the tutorial. So I would be in favor of having a description field with a (very) short summary of what can be expected.
> I think this is helpful for all users that are not your traditional "APInists", and for those such a short summary won't hurt either I assume, since you can also simply ignore it.

cc @Anne-Oeko

**Comment by han-f** [comment]
As we are progressing with WP3 it would be great to hear about how this is coming along?

**Comment by han-f** [comment]
Get in touch with @han-f

**Comment by wingechr** [comment]
i think this is resolved with the new tutorial page, especially the search
