### ISSUE TITLE
Put terms used in the Fact Sheets into the glossary

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#81]
automated or manual workflow?

**Comment by ludee** [comment]
terms could be automated, but then we still need the definitions.
first we need to know if and how the connection between the factsheets and the glossary works

**Comment by EdithaK** [comment]
@MGlauer I guess there is no automated link between the Glossary and the Factsheets. Right? Could it be a practical way to link the buzzwords from FS to Glossary?
If that is true:
@KilianZimmerer please copy and explain abbreviations used in the factsheets into the glossary. Please set Links from FS-words to the explanation in the Glossary, if helpful for the user.

Find glossary here: https://wiki.openmod-initiative.org/wiki/Category:Glossary
If the glossary-FAQ leaves questiones, please ask Ludee and add the information to the glossary.

**Comment by christian-rli** [comment]
This task is no longer relevant. The OEO is preferred over the glossary. Help texts should be reworked when refactoring factsheets.
