### ISSUE TITLE
Connect keywords/tags in OEM with OEP tags

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#813]
This should be solved in another project.

**Comment by jh-RLI** [comment]
https://github.com/OpenEnergyPlatform/oeplatform/issues/740

**Comment by wingechr** [comment]
* [] identify tables in django
* [] identify entry points for changing tags and metadata

**Comment by jh-RLI** [comment]
Currently known definitions of tag related tables in the dataedit app:
[models.py](https://github.com/OpenEnergyPlatform/oeplatform/blob/2662689752cb3a1c00a8c585220b895c4c5da545/dataedit/models.py#L30-L43)
[structures.py](https://github.com/OpenEnergyPlatform/oeplatform/blob/2662689752cb3a1c00a8c585220b895c4c5da545/dataedit/structures.py#L21-L42)

**Comment by wingechr** [comment]
> Currently known definitions of tag related tables in the dataedit app: (verify, which is used on DB) [models.py](https://github.com/OpenEnergyPlatform/oeplatform/blob/2662689752cb3a1c00a8c585220b895c4c5da545/dataedit/models.py#L30-L43)
> 
> THIS SHOULD BE THE TABLE ON DB. lookup in "public" schema [structures.py](https://github.com/OpenEnergyPlatform/oeplatform/blob/2662689752cb3a1c00a8c585220b895c4c5da545/dataedit/structures.py#L21-L42)

I checked on the database side, the tags are stored in the oedb, not the django database

* table `public.tags` has the tags and usage stats
* table `public.table_tags` has the n-n-relation between tags and tables

**Comment by jh-RLI** [comment]
Dublicated tags: https://github.com/OpenEnergyPlatform/oeplatform/issues/876

**Comment by jh-RLI** [comment]
This[ function](https://github.com/OpenEnergyPlatform/oeplatform/blob/2662689752cb3a1c00a8c585220b895c4c5da545/dataedit/views.py#L37) can be used to read the metadata.

In general, here are some helpful functions: [/dataedit/metadata/__init__.py](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/dataedit/metadata/__init__.py)

**Comment by jh-RLI** [comment]
In case we transfer tags from the database to the metadata "keywords". How do we store the ID and the color value? There are no fields for this in the metadata.

**Comment by Ludee** [comment]
Option 1: Delete in the backend (LH)
    remove entries from table_tags
    remove from tags table

    Option 2: Prevent new errors (CH)
    write as alembic scripts
    new unique name as addition constraint
    preventing new double entry

**Comment by wingechr** [comment]
furthermore: remove feature to rename tag

**Comment by wingechr** [comment]
i set up branch [feature/improve-tags-813](https://github.com/OpenEnergyPlatform/oeplatform/tree/feature/improve-tags-813)

**Comment by wingechr** [comment]
@Ludee I commited a migration script for the tags. the sql query to remove duplicates is a little long, definitely requires a second look & backups in production :-)

```
# add new column name_normalized (allow nullable at first)
    op.add_column(
        table_name="tags",
        column=sa.Column("name_normalized", sa.String(length=40), nullable=True),
        schema="public",
    )               

    # create normalized names
    op.execute(
        """        
        -- create normalized names
        UPDATE public.tags
        SET name_normalized = TRIM(BOTH '_' FROM REGEXP_REPLACE(LOWER(name), '[^a-z0-9]+', '_'))
        ;
        -- create temporary column id_normalized
        ALTER TABLE public.tags ADD id_normalized BIGINT
        ;
        UPDATE public.tags t
        SET id_normalized = n.id_normalized
        FROM (
            SELECT name_normalized, MIN(id) AS id_normalized
            FROM public.tags
            GROUP BY name_normalized
        ) n
        WHERE n.name_normalized = t.name_normalized
        ;
        -- change tag usage
        -- !! changing ids could lead to duplicates which will cause an error
        -- so this is why the query is a little more complicated
        UPDATE public.table_tags tt
        SET tag = t.id_normalized
        FROM (
            SELECT
            tt.schema_name, tt.table_name, MIN(tt.tag) as tag, t.id_normalized
            FROM public.table_tags tt
            JOIN public.tags t
            ON tt.tag = t.id
            --> these three must be unique after the change
            GROUP BY tt.schema_name, tt.table_name, t.id_normalized
            HAVING MIN(t.id) != t.id_normalized
        ) t
        WHERE t.schema_name = tt.schema_name
        AND t.table_name = tt.table_name
        AND t.tag = tt.tag
        ;
        -- delete duplicates
        DELETE FROM public.table_tags tt
        WHERE tag IN
        (
            SELECT id 
            FROM public.tags
            WHERE id != id_normalized
            OR COALESCE(name_normalized, '') = ''
        )
        ;
        DELETE FROM public.tags
        WHERE id != id_normalized
        OR COALESCE(name_normalized, '') = ''
        ;
        -- drop temporary table
        ALTER TABLE public.tags DROP COLUMN id_normalized
        ;
        """
    )

    # change column to unique not null
    op.alter_column(
        table_name="tags",
        column_name="name_normalized",
        nullable=False,        
        schema="public",
    )
    op.create_unique_constraint(
        constraint_name="uq_name_normalized",
        table_name="tags",
        columns=["name_normalized"],        
        schema="public"
    )
```

**Comment by jh-RLI** [comment]
@wingechr I added the functionality to add oemetadata keywords to 1. new Tags 2. Tabletags and add current TableTags to metadata. Please test this :) . I will test the migration script next.

**Comment by jh-RLI** [comment]
@wingechr I reviewed the result of your migration script with the actual OEP tags data. I had to clean the data from an additional column called "category" (correct me if the column name is wrong, @Ludee), which was manually created (via SQL) directly in the database backend some time ago. This column is not managed by django or alembic. As I learned, this column should be used to group tags and improve the display of tags on the OEP. 

The result is good, but there are still minor errors.  For example, tags with a name with more than 1 space or - are not normalized. Only the first occurrence is correctly converted to a _ .

**Example:**

![image](https://user-images.githubusercontent.com/38939526/155229116-61a61d6e-0cbd-4705-bb11-90981d16cf9a.png)

![image](https://user-images.githubusercontent.com/38939526/155229064-cf4972c2-7875-4156-b0c2-5273a1a35a21.png)

**Comment by jh-RLI** [comment]
The migration script now works as intended 👍 @wingechr

**Comment by jh-RLI** [comment]
@wingechr @Ludee As I noted yesterday, I thought that in case the metadata as comment on table is empty, metadata must be appended. Now, I noticed that the function load_metadata_from_db() automatically appends version 1.4.0 to the table if the metadata is empty.  Unfortunately, this does not explain why in some cases the metadata is left empty and tags are not added to the keywords. So I can't reproduce the error at the moment.

**Comment by wingechr** [comment]
The `TEMPLATE_V1_4` in https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/dataedit/metadata/v1_4.py
is not correct.

I am also suprised that omi apparently does not use the json schema files at all.
