### ISSUE TITLE
Missing implementation of oemetadata 1.5 

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#815]
Check if the following things work with the new version and make the necessary updates, if not:

- [x] display of all (new) keys. make references to the oeo link to their definition on the oep
- [x] wizard allows creating metadata in new standard
- [ ] update tutorials

**Comment by jh-RLI** [comment]
https://github.com/OpenEnergyPlatform/oeplatform/issues/880

**Comment by jh-RLI** [comment]
[First we need to finish updating omi with the new dialect for oem v1.5.0.](https://github.com/OpenEnergyPlatform/omi/pull/45)

Since we have changed the structure of the metadata, we need to figure out how to maintain the OMI functionality with which older versions of the metadata are processed.

**Comment by jh-RLI** [comment]
The metadata widget now shows the new timeseries list:
![image](https://user-images.githubusercontent.com/38939526/171858549-577b26da-90c8-4807-8c46-b49d71bb68ba.png)

It can also show the is_about and value_reference as well as "@context" "@id" fields at the very bottom of the widget:
![image](https://user-images.githubusercontent.com/38939526/171858834-d048658f-d9b7-4cea-8922-12c5e8369e4f.png)


![image](https://user-images.githubusercontent.com/38939526/171858745-173572c0-2f26-4fff-9929-88cd6863df42.png)

**Comment by jh-RLI** [comment]
@Ludee are you okay with the widget as it is now? If you want any changes let me now here I will try to implement them. Regarding the order of the keys, I will not be able to change this within this release.

**Comment by jh-RLI** [comment]
I move the update tutorials issue to the tutorials repo.
