### ISSUE TITLE
[Factsheets] SF Ask for contact information

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#82]
@ludee Do we want to ask for contact information in the Scenario Fact Sheet?

**Comment by ludee** [comment]
It is not needed, if every scenario is connected to a model. I could not find that connection, but it was planned to have it?!

**Comment by EvaWie** [comment]
Scenarios can be made by people, that are not part of the model developing group.

**Comment by ludee** [comment]
That is a point. Then add contact info (Email) to the study

**Comment by Ludee** [comment]
Please add
**Contact (e-mail)**
to **Study** in SFS
