### ISSUE TITLE
IRIs in RDF-Factsheets are not displayed

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#820]
One example would be [this factsheet](https://openenergy-platform.org/factsheets/rdf/study/KSz_2050/). The field 
`Model Calculations` -> `Inputs` -> `URL` is displaying "undefined". It should instead display a clickable link to the data table that is refered.

**Comment by jh-RLI** [comment]
We removed the RDF factsheets (old study factsheets).
