### ISSUE TITLE
Factsheet links at data table views

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#821]
From 2021-10-27

To link factsheets to data the following would be needed:

- Introduce (make visible) button in study factsheets to be able to work with them
- Introduce functionality to add link to data in the form and make that link clickable
- Introduce info alongside data tables which factsheets include the data

**Comment by christian-rli** [comment]
When working on this issue, also consider the comments in #138

**Comment by stap-m** [comment]
This will be adressed in [project 25](https://github.com/orgs/OpenEnergyPlatform/projects/25/). Especially the last topic should be kept in mind, therefore I change the title.

**Comment by han-f** [comment]
closed as discussed in SIROP project meeting. Last bullet as new issue #1305 1305
