### ISSUE TITLE
[Factsheets] MF - Coverage - final / end energy

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#84]
Taking the fact,  that "electricity, heating, mobility and oil" are not really sectors (see openmod wiki fact sheet) as a starting point we defined "Modeled demand sectors" (Households, Industry, Commercial sector, Transport) and "Modeled energy sectors (final energy)" (Electricity, Heat, Liquid fuels, Gas, Others) as well as "Modeled energy carriers (primary energy carriers)" (Gas, Liquids, Solid, Renewables with options each). Furthermore, there is "Modeled technologies: components for generation or conversion" (Renewables, Conventional with options each).
See: http://193.175.187.164/factsheets/models/add/

That seems to be to much.
1. Please, make the option at the third level to voluntary options, that appear when the second level is selected.
2. @ludee: How do we re-organise the questions above? Can we just leave out "Modeled energy carriers (primary energy carriers)" and add the options "Geothermal heat" (RE), "Hydrogen" (Conv. + RE), "Biofuels" (RE) to Modeled technologies: components for generation or conversion"?

**Comment by ludee** [comment]
You are totally right that the given options doesn't fit "sectors". The distinction between the three main sectors (electricity, heat, mobility) should be at the beginning. Perhaps combined with "demand sectors". Then leave out the "energy carriers" and add more technologies (distinct between electrical and thermal).

**Comment by EvaWie** [comment]
Conclusion:

1. Modeled energy sectors (final energy): delete the options "Liquid fuels", "Gas"
2. Modeled demand sectors: unchanged, maybe we should make a text field here to let the user specify, if she/he wants to
3. Modeled energy carriers (primary energy carriers): delete whole question
4. Modeled technologies: components for **POWER** generation or conversion: add power in the title of the question, add Geothermal heat" (to RE), make one collective option "biomass, biogas, biofuels", distinguish coal: lignite and hard coal

Thank you.

**Comment by EdithaK** [comment]
@Ludee Still a to do! Pls assing MG if you cant do it.
