### ISSUE TITLE
Mismatching top bar and Main page elements "documentation"

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#844]
The Top bar links to the documentation on readthedocs. That element is not found among the Main page elements. That's inconsistent as well as confusing. The readthedocs page needs an update, but more crucially, test users have clicked there when what they were lookng for is something like the tutorials. Turn readthedocs into a developers documentation and remove it from the front page.

**Comment by jh-RLI** [comment]
The documentation was renamed to "Developer Documentation" and is in an option of "About". We also updated the readthedocs project to a new project name "openenergyplatform" and rebuild the latest  state, so it should be a bit more readable to the developer. In general there is still a lot of documentation missing.
