### ISSUE TITLE
Finding tutorials s difficult

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#845]
Test users had a hard time figuring out what was behind some of the tutorials. That was prior to the redesign and the names were made more descriptive. There is probably still some room for improvement there, but a filter function in the current view might be very helpful already.

**Comment by han-f** [comment]
I think at one point we suggested to add small excerpts to the tutorials, and still think these will come in handy, as a heading can only provide so much information without getting to long.
Suggestion see: #762
