### ISSUE TITLE
Tagging is too much scroll work

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#858]
As described in #857 the current display of tags is frustrating. That issue focusses reworking the filter/search functionality. Similar things are true for tagging a table. There is a lot of scrolling up and down going on and finding the apply button. Rework the concept, ideally in sync with #857 so the solutions match

**Comment by Ludee** [comment]
My idea is to group the tags by categories. This has been already partly integrated in the backend.
The tags can be shown separately for each group as known from CKAN systems. 
Then the colours can also be taken by the group as default.

I will add a list of the categories here:

**Comment by wingechr** [comment]
Grouping is good, by i think it does not solve the problem if there is hundreds of tags. 
What about a textbox/dropdown with autosuggest? (like https://jqueryui.com/autocomplete/#default)

**Comment by jh-RLI** [comment]
I also think that categories do not completely fix the problem. +1 for @wingechr suggestion, because a search is much more intuitive and can for instance already deliver results if only a part of the tag name is given.

**Comment by jh-RLI** [comment]
This was not closed by the linked PR (the PR was linked because it implements related code). The table tagging will be improved with the next release

**Comment by Ludee** [comment]
I tested the new feature and it is a great improvement! Thanks for the brilliant idea and implementation.
Now it would be cool to use the colors/grouping with this. Is it possible?

**Comment by wingechr** [comment]
groups should be easy: https://developer.snapappointments.com/bootstrap-select/examples/

![grafik](https://user-images.githubusercontent.com/4265368/173426431-3d83e2ae-edfa-4aab-a69e-f2b1d0a0e65d.png)

colors are a bit more tricky:

* you can't really but colored boxes inside an<option>tag
* using styles to color the entire background/text looks very ugly and confusing (but MAYBE can be done with one color for a group?)

**Comment by jh-RLI** [comment]
Regarding the colors, we can try to simply display a dot or another small indicator with the color next to the text.

**Comment by jh-RLI** [comment]
@wingechr I just found out about the Custom Content option. 
``` html
<select class="selectpicker">
  <option data-content="<span class='badge badge-success'>Relish</span>">Relish</option>
</select> 
```

https://developer.snapappointments.com/bootstrap-select/examples/#customize-options

**Comment by jh-RLI** [comment]
The solution I described above seems to work very well. Please test this with more tags. I linked the PR.
![image](https://user-images.githubusercontent.com/38939526/174095092-777ae97c-5bda-4f00-a615-220aac997a9e.png)

**Comment by jh-RLI** [comment]
@Ludee 
The tag color feature is now implemented along with some other improvements. We should now add the grouping.
Do we already have a complete list of categorized tags? Or at least a list of categories? 
We will need to create another migration script that adds the categories to the current tags. And we need to add the category column to the table model and to the tag creation/editing form.
