### ISSUE TITLE
[Factsheets] Grid models do not fit in the Model Fact Sheet

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#86]
Grid models like SciGRID do not fit in the Model Fact Sheet. Find a solution to make it fit e.g. special questions for grid models.
Maybe there could be a selection: energy system model, gas model, grid model and accordingly relevant tabs with relevant questions will be appear.

**Comment by EvaWie** [comment]
Maybe even for transportation models..

**Comment by ludee** [comment]
The focus was and is on energy system models. We don't want to addapt all questions to all different types of models like the one you quoted.
Add a dropdown with possible "energy" model types (energy system, grid, transportation, markets). The idea to link tabs to that is good. But not possible in our project this year. leave it open to the next one!

**Comment by EvaWie** [comment]
Does this additional drop down menu make sense at the current state - without the activation of questions and tabs the question seems to be a classifying question and should be defined having issue #78 in mind.

**Comment by christian-rli** [comment]
#78 was solved. Refactoring of the factsheets is done via terms of the ontology. This issue doesn't seem relevant anymore. Do feel free to reopen, in case it is.
