### ISSUE TITLE
Some tags are duplicates

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#876]
At least one tag with the same name exists twice: 

parameters:
https://openenergy-platform.org/dataedit/tags/178
https://openenergy-platform.org/dataedit/tags/180
Can these please be merged into one tag?

Maybe a good idea to also check for other potential duplicates that may be merged?

**Comment by Ludee** [comment]
I downloaded the list of all tags from the database and found some more issues:

- tag with no name (230)
- assumptions (179 / 181)
- Electrical / Electricity (199 / 136)
- emission projection (239 / 272)
- FlexMex (285 / 173)
- Gas (138 / 253)
- input data (237 / 219)
- MODEX-EnSAVes (284 / 287)
- Netzentwicklungsplan / NEP (276 / 277)
- notation-keys ( 269 / 290)
- parameters (178 / 180)

**Comment by jh-RLI** [comment]
I´m not sure what the numbers are indicating? Is this the tag id? @Ludee

**Comment by Ludee** [comment]
Yes, the numbers are the ids.
