### ISSUE TITLE
Outdated links: openmod forum URL on landing page

### ISSUE THREAD

**Issue by robbiemorrison** [OpenEnergyPlatform/oeplatform#896]
The openmod forum URL should really be updated.  Old version:
- https://forum.openmod-initiative.org

And new version:
- https://forum.openmod.org

Not urgent, but still worth fixing, I believe.

**Comment by Ludee** [comment]
I will update the links on the landing page (index.html) and update the documentation.

**Comment by robbiemorrison** [comment]
thanks team!
