### ISSUE TITLE
Navigation bar needs to be updated

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#898]
The navigation bar needs some updates:

- [x] Create documentation
- [x] Add "Tutorials" section
- [x] Add "OEO-Viewer"
- [x] Move "Documentation" under "About OEP"
- [x] Move "FAQ" under "About OEP"

Structure:

| Database | Factsheets | Ontology | Tutorials | About |
| -------- | -------- | -------- | -------- | -------- |
|  | Overview | Overview | | Overview |
|  | Framework Factsheet | OEO Modules | | Developer Documentation |
|  | Model Factsheet | OEO Viewer | | FAQ |
|  | Scenario Factsheet | OEO SC | | |
|  | Study Factsheet (alpha) |  | | |

**Comment by Ludee** [comment]
The navigation bar is done in `base/templates/base`:
- `base.html`
- `base-wide.html`
Could not find any documentation.

**Comment by jh-RLI** [comment]
@Ludee  I agreed with your changes, I thought at first that maybe items like FAQ are a bit hidden, but I think this is the most organized way. As for the documentation, I can't say if it will be accepted by RTD exactly, but it looks good in general and definitely better than what was there before.
