### ISSUE TITLE
Tutorials: editing interface improvements

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#900]
The editing interface requires some information via drop-downs. I think there is room for improvement:

- **License drop-down**: only holds CC0, No, AGPL - but users need to choose something. So if my tutorial has a different type of license I have no possibility to choose the correct answer
- **Level**: I would allow for "any", too. Some tutorials may be easy to read for beginners but still relevant for other users too.
- **Language:** Currently only holds english, french, german and cannot be left empty. So with other language no possibility to choose correct answer
- **Youtube video url**: This seems prescriptive to youtube. Do we want that? Can it not simply be "video link"? What about users who may want to link videos on Vimeo etc?

Also: at least some of the information entered there (e.g. license, github handle) is not displayed anywhere after submitting.

**Comment by jh-RLI** [comment]
I agree with your suggestions. If we agree on a complete list for what should be included in the dropdowns, I can easily extend them. But I am not sure how fast I will get to it.

We are currently working through the issues that were bundled in the [GitHub projects](https://github.com/OpenEnergyPlatform/oeplatform/projects) by @christian-rli . We plan to complete most of the work for the Project named "v0.10.0 Tags + Metadata + Study-Factsheets" by the beginning of March. I don't see any project there that relates to the further development of the tutorial area. It would be good if we create another project and bundle all issues related to tutorial development there.

**Comment by han-f** [comment]
Thanks @jh-RLI - I know there is no bundle yet, but the improvements in the tutorial section are crucial for our capacity building modules to be developed. I gathered, that most of the changes are not very complicated - could these potentially be addressed by a minor release relatively shortly after the major one that is planned for March? @wingechr 

@jh-RLI if you let me know how to "bundle" these together, I can create a bundle and check whether there is anything to add. I could also prioritise the issues within the bundle as some may require a bit more effort?

**Comment by jh-RLI** [comment]
Hi @han-f , from my side you can create the project. That would be very helpful. As you can see in the other projects there is also always an end date given "Due in ...". We should discuss with @Ludee  when we can accommodate the Tutorials/capacity building modules in the schedule? The schedule until september 2022 seems very strict.

**Comment by han-f** [comment]
Thanks @jh-RLI. @wingechr  what is your impression? Are these improvements something that may be addressed in a minor update rather soon despite the workload planned already? 
These improvements are crucial to proceed with our capacity buildung workpackage and hopefully most of these are not so complicated to implement?

**Comment by han-f** [comment]
[Added a project](https://github.com/OpenEnergyPlatform/oeplatform/projects/16#card-78338659) and put the corresponding issues in there. There are some overlaps with another project, but I guess this won't matter:

**Comment by han-f** [comment]
@jh-RLI we discussed at the project meeting that there are some issues for WP 3 where it would be great if you could get in touch with me before starting implementation, so we can ensure the implementation follows without doubt along the exact line of thought of the initial issue. That way we can also avoid potential double work. I will flag this and the other such  issues with 
Get in touch with @han-f 

Maybe we can setup a trilateral on these issues also including @wingechr.

**Comment by han-f** [comment]
Hi @jh-RLI  - many thanks and I think lots is already on the way thanks to @wingechr that may be included in the May release. So we can work it out as we go along and as the implementation proceeds. Happy to see things are moving forward.

**Comment by jh-RLI** [comment]
Since we have added the academy and switched to the much better mkdos-based system as an editing interface, I will close this topic. Reopen if still relevant :)
