### ISSUE TITLE
Tutorials: Scaling browser window makes images in tutorial section overflow

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#904]
When I created a tutorial and added an image (800px) wide this looks OK a large resolution. When I scale the screen the image overflows and does not stay in the tutorial window, see screenshot below. 
Example: https://openenergy-platform.org/tutorials/18/

![grafik](https://user-images.githubusercontent.com/36844029/155689559-042dc18e-8107-41e6-b599-751b20ecc431.png)

**Comment by han-f** [comment]
Get in touch with @han-f

**Comment by wingechr** [comment]
should be fixed now with the new  tutorial markdown features
