### ISSUE TITLE
Partner logos update in about page

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oeplatform#912]
- [x] Add fortis logo @FlorianK13
- [x] Update logo HZG -> hereon
- [x] Fix project logo SIROP
- [x] Open Energy Family - Group Foto

**Comment by FlorianK13** [comment]
Should I add the fortiss logo to static/logos @Ludee?

**Comment by Ludee** [comment]
I just added it

**Comment by Ludee** [comment]
It's finally live @FlorianK13
