### ISSUE TITLE
Alembic up- and down grade do not match

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#916]
The latest changes to the alembic datamodel introduce some manual changes during upgrade, that are not reverted on downgrade. This will cause errors on repeated up- and downgrade.

**Comment by wingechr** [comment]
which step?

**Comment by wingechr** [comment]
in  `6b59560b879b_.py`

upgrade:
   * add column
   * add constraint

downgrade:
   * drop constraint
   * drop column

the execute part that removes the duplicate content is irreversible by necessity, but not structural.

**Comment by MGlauer** [comment]
Ok, as long as the execute statement is idempotent, this may not cause an error.

**Comment by wingechr** [comment]
it is (or should be :-) )
