### ISSUE TITLE
Delete table in OEP model draft fails using Wizard

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/oeplatform#918]
The deletion of tables using the Wizard on the OEP seems to fail.

Concerning [table](https://openenergy-platform.org/dataedit/view/model_draft/modex_openmodex_load)

Error screenshot:
![grafik](https://user-images.githubusercontent.com/54852694/156171955-7987cac3-461b-4c03-b527-f885e8e28404.png)

**Comment by jh-RLI** [comment]
@chrwm the table seems to be deleted. Did you delete it using the API? Otherwise, it may take some time before the deletion of the table with the wizzards is recognized by the OEP:

**Comment by pajot** [comment]
@jh-RLI I have a situation in which a table I deleted via API is still appearing in the `model_draft` schema, but when I click on it I get a 404.

This looks like a bug to me.

**Comment by chrwm** [comment]
@jh-RLI Thanks for the info. I just clicked the button.

**Comment by wingechr** [comment]
@chrwm: could you please enumerate steps to reproduce the problem? seems to work for me without a problem.

**Comment by wingechr** [comment]
awesome :-)

**Comment by pajot** [comment]
It looks like my e-mailed reply was not taken up by github.

My question: Did you test this with a bare repo, or on the production system?

**Comment by jh-RLI** [comment]
@wingechr can you say something about how you did it?

**Comment by wingechr** [comment]
I closed the ticket because for me, deletion of tables worked and the error could not be reproduced.

**Comment by pajot** [comment]
> I closed the ticket because for me, deletion of tables worked and the error could not be reproduced.

Thanks for the reply, but you still haven't really answered my question. Did you do this on the OEP in a bare repo, or on the production server?

**Comment by wingechr** [comment]
not the production server, i have no access to that

**Comment by pajot** [comment]
Did you test it on a bare clone of the OEP, or the production server?

Am 21. April 2022 14:39:49 MESZ schrieb wingechr ***@***.***>:
***@***.***: could you please enumerate steps to reproduce the problem? seems to work for me without a problem.
