### ISSUE TITLE
Filters "contains" and "doesn't contain" do not work

### ISSUE THREAD

**Issue by l-emele** [OpenEnergyPlatform/oeplatform#944]
I just noticed that the filters "contains" and "doesn't contain" do not work.

In the table https://openenergy-platform.org/dataedit/view/climate/szenariendb_gwp I tried to filter entries that contain the word "methane":
![grafik](https://user-images.githubusercontent.com/36884905/162134733-b5682d9d-c4d9-44b6-9e60-1d2907d2f1be.png)

But the filter does not do anything, the whole original table is shown:
![grafik](https://user-images.githubusercontent.com/36884905/162134804-656dbd67-c38c-4bc4-9ab6-2e4fdc70bd89.png)

The same happens if I select "doesn't contain". Other filters, e.g. "equal" do work.

**Comment by jh-RLI** [comment]
This might be solved by #818 @wingechr do you agree?

**Comment by wingechr** [comment]
yes
