### ISSUE TITLE
[Factsheets] MF - Openess - Cooperative programming

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#95]
@ludee 

Cooperative or collaborative programming?

How do we define cooperative / collaborative programming? Chance to join the developer group (as in the info text)? Chance to make pull request on GitHub or other platforms?

There is a tick box (yes / no). Should we allow the comment, that the collaboration will be possible soon? Another tick box?

**Comment by ludee** [comment]
Change to "collaborative".
The rest is OK. No additional box needed.
