### ISSUE TITLE
Improve usability of tags when using the data filters

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#965]
- Show the currently selected Tags (regarding data filters):
I think it would be useful to show the currently selected tags in addition to the checkmark that is shown in the "big" tag list:
![image](https://user-images.githubusercontent.com/38939526/165496694-61e5da76-eae5-4bf5-9659-e93077c2d14b.png)

- We should consider changing the presentation of tags. 
  - @Ludee suggested introducing categories which include a subset of tags. This would be useful, but there are still too many tags IMO. 
  - There are several technical/functional solution we could take advantage from. For Example, we could introduce a dropdown for all tags or tag category that provides a search bar at the top. This would also fix the first point, as the presentation of tags changes.
  For example, there are these jQuery plugins for bootstrap 4: [bootstrap-select](https://developer.snapappointments.com/bootstrap-select/examples/#live-search_1) , [select2](https://select2.org/getting-started/basic-usage)

**Comment by wingechr** [comment]
* I agree. even with categories, it does not scale well with many tags.
* dropdowns are the way to go. i have some experience with bootstrap-select and can recommend it. especially because it has a simple but powerful builtin search box.
