### ISSUE TITLE
[Factsheets] in general - indicate successful upload

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#98]
Message, green colour...

**Comment by ludee** [comment]
upload of the factsheet?

**Comment by EvaWie** [comment]
Yes, up to now the user does not get any feedback.

**Comment by christian-rli** [comment]
After a successful change the old page is also still in the browser cache (at least for me), leading the user to think that the update didn't work. So when implementing, make sure there is a green success info and something like a forced cache refresh.

**Comment by stap-m** [comment]
is part of PR #1221
