### ISSUE TITLE
[Factsheets] MF Ranking

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#99]
The Fact Sheets are meant to be a tool to enhance transparency and reproducibility of model results.
There are mandatory fields in the fact sheets, but the extent to which the fact sheets are filled out (level of detail) is up to the user. Can we increase the motivation to fill out the fact sheets by ranking (e.g. filled out completely; important information missing; etc.)? Is that realisable, automatable or would that require a human rating?

**Comment by stap-m** [comment]
I am closing this issue since it id outdated.
